
				<div class="col-sm-9 padding-right">
					<div class="product-details"><!--product-details-->
						<div class="col-sm-5">
							<div class="view-product">
								<img src="images/product/perfumy_65.jpg" alt="" />
								
							</div>
							

						</div>
						<div class="col-sm-7">
							<div class="product-information"><!--/product-information-->
								<img src="images/product-details/new.jpg" class="newarrival" alt="" /> 
								<h2>DÁMSKE PARFÉMY #61</h2><p>pivónia
|
lotos
|
citrusy </p>
								<p>Symbol: 101061</p>
								<p>Francúzske vonné oleje: 20%</p>
								<!-- <span>
									<span>US $59</span>
									<label>Quantity:</label>
									<input type="text" value="3" />
									<button type="button" class="btn btn-fefault cart">
										<i class="fa fa-shopping-cart"></i>
										Add to cart
									</button>
								</span> -->
								<p><b>50 ml</b> In Stock</p>

								
							</div><!--/product-information-->

						</div>
						<div><br><br>
						<h2>Prečo ju budete milovať:</h2>
						pre mrazivú krásu kveti novej kompozície. Je to 
chladná a elegantná vôňa ako parfémy Snehovej 
kráľovnej a zároveň - vďaka čerstvým tónom 
pivónie a lotosu - jemná a veľmi ženská.  
<br> <br>
<h4>Z ktorej rodiny pochádza: <i>kvetinovo-ovocnej</i></h4> 
<h4>Ako je vnímaná: <i>kvetinový, sviežy</i></h4>
<h4>Akú má projekciu: <i>miernu</i></h4>



						</div>
					</div><!--/product-details-->
	
				</div>
