
				<div class="col-sm-9 padding-right">
					<div class="product-details"><!--product-details-->
						<div class="col-sm-5">
							<div class="view-product">
								<img src="images/product/perfumy_42.jpg" alt="" />
								
							</div>
							

						</div>
						<div class="col-sm-7">
							<div class="product-information"><!--/product-information-->
								<!-- <img src="images/product-details/new.jpg" class="newarrival" alt="" /> -->
								<h2>PÁNSKE PARFÉMY #44</h2><p>bergamot
|
kadidlo
|
zázvor</p>
								<p>Symbol: 101044</p>
								<p>Francúzske vonné oleje: 20%</p>
								<!-- <span>
									<span>US $59</span>
									<label>Quantity:</label>
									<input type="text" value="3" />
									<button type="button" class="btn btn-fefault cart">
										<i class="fa fa-shopping-cart"></i>
										Add to cart
									</button>
								</span> -->
								<p><b>50 ml</b> In Stock</p>

								
							</div><!--/product-information-->

						</div>
						<div><br><br>
						<h2>Čo Vás v ňom zvedie:</h2>
						vlna osvieženia. Táto výrazná, viacrozmerná 
vôňa bola vytvorená pre súčasného muža 
- sebavedomého, túžiaceho po slobode 
a výzvach. Je to sti mulujúci pocit príjemnej 
sviežosti  zabalenej do aróma kadidla priťahujúcej 
pozornosť.
<br> <br>
<h4>Z ktorej rodiny pochádza: <i>drevito-korenistej</i></h4> 
<h4>Ako je vnímaná: <i>sviežy, zelený</i></h4>
<h4>Akú má projekciu: <i>miernu</i></h4>



						</div>
					</div><!--/product-details-->
	
				</div>
