
				<div class="col-sm-9 padding-right">
					<div class="product-details"><!--product-details-->
						<div class="col-sm-5">
							<div class="view-product">
								<img src="images/product/perfumy_51.jpg" alt="" />
								
							</div>
							

						</div>
						<div class="col-sm-7">
							<div class="product-information"><!--/product-information-->
								<!-- <img src="images/product-details/new.jpg" class="newarrival" alt="" /> --> 
								<h2>Perfumy Damskie #51</h2><p>konwalia – czarna porzeczka – wanilia</p>
								<p>Numer produktu: 101051</p>
								<p>Zaperfumowanie: 20%</p>
								<!-- <span>
									<span>US $59</span>
									<label>Quantity:</label>
									<input type="text" value="3" />
									<button type="button" class="btn btn-fefault cart">
										<i class="fa fa-shopping-cart"></i>
										Add to cart
									</button>
								</span> -->
								<p><b>50 ml</b> </p>

								
							</div><!--/product-information-->

						</div>
						<div><br><br>
						<h2>Za co go pokochasz:</h2>
za wyraﬁnowanie. Słodki aromat owoców czarnej porzeczki, jaśminu i konwalii, pogłębiony zmysłowymi nutami cedru, sandałowca i piżma jest elegancki i tajemniczy.  
<br> <br>
<h4>Z jakiej rodziny pochodzi: <i>orientalno-kwiatowej</i></h4> 
<h4>Jak jest odbierany: <i>słodki, głęboki</i></h4> 
<h4>Jaką ma projekcję: <i>mocną</i></h4> 
<h4>Z jakiej jest kategorii: <i>glamour</i></h4>
<h4>Architektura zapachu: 
<br><i>Nuta głowy: czarna porzeczka, bergamotka</i>
<br><i>Nuta serca: jaśmin, konwalia</i>
<br><i>Nuta głębi: cedr, drzewo sandałowe, piżmo, wanilia</i></h4>


						</div>
					</div><!--/product-details-->

				</div>
