
				<div class="col-sm-9 padding-right">
					<div class="product-details"><!--product-details-->
						<div class="col-sm-5">
							<div class="view-product">
								<img src="images/product/perfumy_26.jpg" alt="" />
								
							</div>
							

						</div>
						<div class="col-sm-7">
							<div class="product-information"><!--/product-information-->
								<!-- <img src="images/product-details/new.jpg" class="newarrival" alt="" /> -->
								<h2>PÁNSKE PARFÉMY #26</h2><p>agar
|
palisander
|
vanilka</p>
								<p>Symbol: 101026</p>
								<p>Francúzske vonné oleje: 20%</p>
								<!-- <span>
									<span>US $59</span>
									<label>Quantity:</label>
									<input type="text" value="3" />
									<button type="button" class="btn btn-fefault cart">
										<i class="fa fa-shopping-cart"></i>
										Add to cart
									</button>
								</span> -->
								<p><b>50 ml</b> In Stock</p>

								
							</div><!--/product-information-->

						</div>
						<div><br><br>
						<h2>Čo Vás v ňom zvedie:</h2>
						hĺbka odu. Ušľachti lá, zmyselná kompozícia 
s drahocenným agarovým drevom v hlavnej 
úlohe. Elegantné pozadie vône je naplnená 
palisandrom, vanilkou a santalovým drevom.
<br> <br>
<h4>Z ktorej rodiny pochádza: <i>orientálno-drevovej</i></h4> 
<h4>Ako je vnímaná: <i>teplá, agarová</i></h4>
<h4>Akú má projekciu: <i>silnú</i></h4>



						</div>
					</div><!--/product-details-->

				</div>
