
				<div class="col-sm-9 padding-right">
					<div class="product-details"><!--product-details-->
						<div class="col-sm-5">
							<div class="view-product">
								<img src="images/product/GEL_1000x1000_2.png" alt="" />
								
							</div>
							

						</div>
						<div class="col-sm-7">
							<div class="product-information"><!--/product-information-->
								<!-- <img src="images/product-details/new.jpg" class="newarrival" alt="" /> -->
								<h2>HYDRATAČNÝ GÉL NA UMÝVANIE TELA</h2>
								<p>ID: 201001</p>
								
								<!-- <span>
									<span>US $59</span>
									<label>Quantity:</label>
									<input type="text" value="3" />
									<button type="button" class="btn btn-fefault cart">
										<i class="fa fa-shopping-cart"></i>
										Add to cart
									</button>
								</span> -->
								<p><b>250 ml</b> In Stock</p>

								
							</div><!--/product-information-->

						</div>
						<div><br><br>
						<h2>Poznáte spôsob na dobrý deň?</h2>
						Ranná sprcha oživí a stimuluje k činnosti a večerný kúpeľ zlepšuje náladu a zmierňuje únavu po dlhom 
dni. Smyšlienkou o tejto výnimočnej chvíli sme vytvorili ktorý Vám poskytne dennú dávku čistého potešenia. 
Obsahuje jedinečnú rastlinnú zložku Xeradin™, 
ktorá je prirodzeným zdrojom 24-hodinovej hydratácie. Jeho jedinečná olejovitá konzistencia vytvára 
jemnú penu, ktorá dokonale umyje a ošetrí pokožku a necháva ju sviežu. Krásna vôňa originálnych 
francúzskych olejov Vás tiež dodatočne uvoľní a zrelaxuje, prenesie Vás do sveta zmyslov.
<h3>Čo je naším tajomstvom:</h3>botanický komplex z výťažkov piati ch rias 
bohatých na minerálne soli, vápnik, fosfor, jód 
a vitamíny, ktoré prirodzene obnovujú vitalitu 
a zlepšujú vzhľad pokožky. 
<h3>Prečo ho budete milovať:</h3>za nádherne voňavú, jemné a zamatovú 
na dotyk pokožku, hydratovanú dlhú dobu
<h3> Ako sa používa:</h3>vezmite malé množstvo gélu, naneste 
na mokrú pokožku, jemne votrite, až kým 
sa nevytvorí zamatová pena, potom 
opláchnite vodou.
<h3>Čo tak krásne vonia:</h3>čierna ríbezľa, bergamot, ruža, konvalinka, 
mach, pižmo a cédrové drevo vytvárajú vonnú 
kompozíciu, po ktorej obidvaja radi siahnete.


						</div>
					</div><!--/product-details-->
					
					
					
					
					
				</div>
