
				
				<div class="col-sm-9 padding-right">
					<div class="product-details"><!--product-details-->
						<div class="col-sm-5">
							<div class="view-product">
								<img src="images/product/202001.jpg" alt="" />
								
							</div>
							

						</div>
						<div class="col-sm-7">
							<div class="product-information"><!--/product-information-->
								<!-- <img src="images/product-details/new.jpg" class="newarrival" alt="" /> -->
								<h2>HYDARATAČNÝ TELOVÝ PEELING</h2>
								<p>ID: 202001</p>
								
								<!-- <span>
									<span>US $59</span>
									<label>Quantity:</label>
									<input type="text" value="3" />
									<button type="button" class="btn btn-fefault cart">
										<i class="fa fa-shopping-cart"></i>
										Add to cart
									</button>
								</span> -->
								<p><b>250 ml</b> In Stock</p>

								
							</div><!--/product-information-->

						</div>
						<div><br><br>
						<h2>Poznáte tajomstvo zamatovej pokožky?</h2>
						Aby si pleť udržala hladkosť a mladistvý vzhľad, potrebuje intenzívne čistenie. Systematické 
odstraňovanie odumretej pokožky počas relaxačnej masáže v sprche alebo pri kúpaní je skvelým 
spôsobom, ako ju spevniť a zosilniť. S myšlienkou o tomto zákroku zostal vytvorený
ktorý dokonale čistí a ošetruje pokožku. Telový peeling obsahuje na jemno pomleté marhuľové kôstky, 
ktoré stimulujú mikrocirkuláciu a zaisťujú dokonalú hladkosť pokožky a rastlinných komplexov, ktoré 
pomáhajú udržiavať jej správnu hydratáciu. Vďaka použitiu originálnych francúzskych olejčekov má 
krásnu zmyselnú vôňu, ktorá Vám na chvíľu umožní odtrhnúť sa od reality. 

<h3>Čo je naším tajomstvom:</h3>botanický komplex extraktov z piati ch 
morských rias, bohatých na minerály, 
polysacharidy a aminokyseliny, ktoré pomáhajú 
udržiavať správnu úroveň hydratácie, obnovujú 
vitalitu a zlepšujú vzhľad pokožky.  
<h3>Prečo ho budete milovať:</h3>za neuveriteľne hladkú, jemnú a spevnenú 
pleť dokonale pripravenú na príjem cenných 
aktí vnych zložiek obsiahnutých v iných 
kozmeti ckých prípravkoch.
<h3> Ako sa používa:</h3>malé množstvo peelingu naneste na vlhkú 
pokožku a vmasírujte krúživým pohybom, 
potom opláchnite vodou. Používajte 2-3 
krát týždenne. Pred použití m nezabudnite 
pretrepať.
<h3>Čo tak krásne vonia:</h3>čierne ríbezle, bergamot, ruže, konvalinka, 
mach, pižmo a cédrové drevo vytvárajú vonnú 
kompozíciu, po ktorú radi obaja siahnete.


						</div>
					</div><!--/product-details-->
					
					
					
					
					
				</div>
