
				
				<div class="col-sm-9 padding-right">
					<div class="product-details"><!--product-details-->
						<div class="col-sm-5">
							<div class="view-product">
								<img src="images/product/203001.png" alt="" />
								
							</div>
							

						</div>
						<div class="col-sm-7">
							<div class="product-information"><!--/product-information-->
								<!-- <img src="images/product-details/new.jpg" class="newarrival" alt="" /> -->
								<h2>HYDRATAČNÝ TELOVÝ BALZAM</h2>
								<p>ID: 202001</p>
								
								<!-- <span>
									<span>US $59</span>
									<label>Quantity:</label>
									<input type="text" value="3" />
									<button type="button" class="btn btn-fefault cart">
										<i class="fa fa-shopping-cart"></i>
										Add to cart
									</button>
								</span> -->
								<p><b>250 ml</b> In Stock</p>

								
							</div><!--/product-information-->

						</div>
						<div><br><br>
						<h2>Poznáte tajomstvo krásnej pokožky?</h2>
						Tkvie to v každodennej starostlivosti, ktorá je založená na správnej hydratácii. To je najjednoduchší 
spôsob, ako sa cítiť sebavedome a pohodlne vo svojej vlastnej koži. Mysleli sme na to vytvorením 
ľahkého  ktorý vďaka účinným zložkám ju účinne hydratuje a vyživuje, chráni pred presušením. Má okamžitý 
a dlhodobý účinok, pretože obsahuje jedinečnú rastlinnú zložku XeradinTM, ktorá výrazne zlepšuje 
funkcie kože a znižuje stratu vody. Balzam je perfektne absorbovaný, takže pokožka je vláčna, 
extrémne jemná a hodvábna na dotyk.<br>A jeho krásna, relaxačná vôňa zostane s Vami celý deň.

<h3>Čo je naším tajomstvom:</h3>
komplex výťažkov z piati ch rias bohatých 
na minerály, polysacharidy a aminokyseliny, 
ktoré prirodzene obnovujú vitalitu a zlepšujú 
vzhľad pokožky a pomáhajú udržiavať správnu 
úroveň hydratácie.
  
<h3>Prečo ho budete milovať:</h3>
pre dlhotrvajúcu hydratáciu, príjemný pocit 
pohodlia a zamatové vyhladenie pokožky.

<h3> Ako sa používa:</h3>
naneste malé množstvo balzamu na pokožku 
a jemne votrite, až kým sa neabsorbuje. 
Použite na každodennú hydratáciu po kúpaní 

<h3>Čo tak krásne vonia:</h3>
čierna ríbezľa, bergamot, ruža, konvalinka, 
mach a cédrové drevo vytvárajú vonnú 
kompozíciu, po ktorej obidvaja radi siahnete.


						</div>
					</div><!--/product-details-->
					
					
					
					
					
				</div>
