
				
				<div class="col-sm-9 padding-right">
					<div class="product-details"><!--product-details-->
						<div class="col-sm-5">
							<div class="view-product">
								<img src="images/product/204001.jpg" alt="" />
								
							</div>
							

						</div>
						<div class="col-sm-7">
							<div class="product-information"><!--/product-information-->
								<!-- <img src="images/product-details/new.jpg" class="newarrival" alt="" /> -->
								<h2>HYDRATAČNÝ KRÉM NA RUKY</h2>
								<p>ID: 206001</p>
								
								<!-- <span>
									<span>US $59</span>
									<label>Quantity:</label>
									<input type="text" value="3" />
									<button type="button" class="btn btn-fefault cart">
										<i class="fa fa-shopping-cart"></i>
										Add to cart
									</button>
								</span> -->
								<p><b>50 ml</b> In Stock</p>

								
							</div><!--/product-information-->

						</div>
						<div><br><br>
						<h2>Ako funguje neviditeľná rukavica?</h2>
						Vyťahujeme ich na privítanie a dotýkame nimi blízkych. Niet divu, že chceme, aby naše dlane 
vyzerali krásne a vyzerali boli ošetrované. Aby boli vždy príjemné na dotyk a zamatovo hladké, 
vyvinuli sme
DAILY MOISTURISING 
HAND CREAM
ktorého aktívne zložky pôsobia ako „neviditeľná rukavica“, obaľujú pokožku a chránia ju pred 
presušením. Krém necháva na pokožke jemný fi lm posilňujúci ochranný plášť pokožky.

<h3>Za čo ho budete milovať:</h3>
jeho aktí vne zložky vytvárajú na dlani 
„neviditeľnú rukavicu“, ktorá chráni 
pokožku pred stratou vody. Vďaka tomu je 
pokožka dlane lepšie hydratovaná, hladšia, 
dobre napätá.  
  
<h3> Čo je naším tajomstvom:</h3>
kombinácia komplexu piati ch rias 
s extraktom z fi govej opuncie a olejom 
Canola.

<h3> Čo Vás v ňom poteší:</h3>
jeho účinok budete cíti ť už po prvom
použití.  

<h3>  Prečo ho nevymeníte 
za žiadnu inú? </h3>
na vlastnej koži sa presvedčíte, ako 
účinkuje množstvo jeho zložiek, ktoré 
nielen hydratujú pokožku, ale ti ež jej 
poskytnú regeneráciu.

<h3>Na čo sme ešte hrdí?</h3>
vytvorili sme krém bohatý na hydratačné 
zložky, s neobyčajne ľahkou, nemastnou 
konzistenciou. To je pre nás dôležité, 
pretože sa nám nepáči, keď sú naše ruky 
vlhké alebo mastné.

<h3> Čo tak krásne vonia:</h3>
čierne ríbezle, ruža, konvalinka, mach, 
pižmo a cédrové drevo. 


						</div>
					</div><!--/product-details-->
					
					
					
					
					
				</div>
