
				
				<div class="col-sm-9 padding-right">
					<div class="product-details"><!--product-details-->
						<div class="col-sm-5">
							<div class="view-product">
								<img src="images/product/205002.jpg" alt="" />
								
							</div>
							

						</div>
						<div class="col-sm-7">
							<div class="product-information"><!--/product-information-->
								<!-- <img src="images/product-details/new.jpg" class="newarrival" alt="" /> -->
								<h2>VLASOVÝ KONDICIONÉR REKONŠTRUKCIA & OCHRANA  </h2>
								<p>ID: 205002</p>
								
								<!-- <span>
									<span>US $59</span>
									<label>Quantity:</label>
									<input type="text" value="3" />
									<button type="button" class="btn btn-fefault cart">
										<i class="fa fa-shopping-cart"></i>
										Add to cart
									</button>
								</span> -->
								<p><b>250 ml</b> In Stock</p>

								
							</div><!--/product-information-->

						</div>
						<div><br><br>
						<h2>Ako sa starať pre svoje vlasy?  </h2>
						Zdravé a lesklé vlasy nás robia atraktívnymi. Preto sa oplatí používať kondicionér, ktorý spôsobí, 
že každý deň sa budeme tešiť dokonalým vzhľadom. Pre normálne, suché a poškodené vlasy obsahuje vybrané zložky, ktoré intenzívne regenerujú 
a obnovujú poškodené vlasy. Keratín ™, získaná účinná látka z artičoku, chráni vlasy pred negatívnym 
vplyvom vonkajších faktorov, vrátane slnečného žiarenia. Výrazne zlepšuje ich stav a vitalitu a stará 
sa o ich lesk. Extrakt z bambusových listov chráni vlasy pred škodlivými účinkami voľných radikálov 
a morská voda z hlbín Zeme ich remineralizuje a posilňuje.

<h3>Čo je naším tajomstvom:</h3>
komplex 7 rastlinných olejov, bohatých na 
mastné kyseliny a vitamíny A, D a E, ktorý 
efektí vne hydratuje a regeneruje vlasy. 
  
<h3>Prečo ho budete milovať:</h3>
za ľahkú receptúru, ktorá nezaťažuje Vaše 
vlasy a za silné, zdravé a lesklé vlasy, ktoré sú 
odolnejšie voči pôsobeniu vonkajších faktorov, 
menej citlivé na elektrizovanie a ľahšie sa 
rozčesávajú. 

<h3> Ako sa používa:</h3>
naneste malé množstvo na vlhké vlasy a jemne 
vmasírujte. Po chvíli opláchnite teplou vodou. 
Používajte spolu s vlasovým šampónom 
Rekonštrukcia & Ochrana. 

<h3>Čo tak krásne vonia:</h3>
čierne ríbezle, bergamot, ruže, konvalinka, 
mach, pižmo a cédrové drevo vytvárajú vonnú 
kompozíciu, po ktorú radi obaja siahnete.


						</div>
					</div><!--/product-details-->
					
					
					
					
					
				</div>
