
				<div class="col-sm-9 padding-right">
					<div class="product-details"><!--product-details-->
						<div class="col-sm-5">
							<div class="view-product">
								<img src="images/product/205001.jpg" alt="" />
								
							</div>
							

						</div>
						<div class="col-sm-7">
							<div class="product-information"><!--/product-information-->
								<!-- <img src="images/product-details/new.jpg" class="newarrival" alt="" /> -->
								<h2>VLASOVÝ ŠAMPÓN REKONŠTRUKCIA & OCHRANA </h2>
								<p>ID: 205001</p>
								
								<!-- <span>
									<span>US $59</span>
									<label>Quantity:</label>
									<input type="text" value="3" />
									<button type="button" class="btn btn-fefault cart">
										<i class="fa fa-shopping-cart"></i>
										Add to cart
									</button>
								</span> -->
								<p><b>250 ml</b> In Stock</p>

								
							</div><!--/product-information-->

						</div>
						<div><br><br>
						<h2>Ako mať zdravé a krásne vlasy? </h2>
						Silné a dobre upravené vlasy sú našou vizitkou. Stavte na efektívnu starostlivosť, vďaka ktorej budú 
zdravé a lesklé. Nášpre každodenné použitie, kombinovaný pre normálne, suché a poškodené vlasy, spája v sebe šetrné 
umývacie vlastnosti s intenzívnou rekonštrukciou a ochranou. Obsahuje extrakt z bambusových listov, 
ktorý zabraňuje podráždeniu a chráni vlasy pred škodlivými účinkami voľných radikálov a botanický 
komplex s 5 morskými riasami, ktorý pomáha udržiavať správnu úroveň hydratácie. Pridali sme do 
neho morskú vodu bohatú na minerály z hlbín zeme s posilňujúcim a mineralizujúcim účinkom.

<h3>Čo je naším tajomstvom:</h3>
Keracyn™ – aktí vna zložka, ktorá zreteľným 
spôsobom zlepšuje stav vlasov, posilňuje ich 
a chráni pred vonkajšími poškodeniami, 
čo vedie k uchovaniu lesku typickému pre 
zdravé vlasy.
  
<h3>Prečo ho budete milovať:</h3>
pre výrazné zlepšenie stavu vlasov, ktoré 
sú odolnejšie, lesklejšie, lepšie sa ukladajú 
a nekučeravia sa. Sú ti ež viac odolné voči 
poškodeniam spôsobeným vonkajšími faktormi 
vrátane slnečného žiarenia.

<h3> Ako sa používa:</h3>
naneste šampón na mokré vlasy, jemne 
vmasírujte a opláchnite. V prípade 
potreby postup zopakujte. Používajte 
ho spolu s kondicionérom na vlasy 
Rekonštrukcia & Ochrana. 

<h3>Čo tak krásne vonia:</h3>
čierne ríbezle, bergamot, ruže, konvalinka, 
mach, pižmo a cédrové drevo vytvárajú vonnú 
kompozíciu, po ktorú radi obaja siahnete.


						</div>
					</div><!--/product-details-->
					
					
					
					
					
				</div>
