
				<div class="col-sm-9 padding-right">
					<div class="product-details"><!--product-details-->
						<div class="col-sm-5">
							<div class="view-product">
								<img src="images/product/206001.jpg" alt="" />
								
							</div>
							

						</div>
						<div class="col-sm-7">
							<div class="product-information"><!--/product-information-->
								<!-- <img src="images/product-details/new.jpg" class="newarrival" alt="" /> -->
								<h2>HYDRATAČNÝ KRÉM NA NOHY  </h2>
								<p>ID: 206001</p>
								
								<!-- <span>
									<span>US $59</span>
									<label>Quantity:</label>
									<input type="text" value="3" />
									<button type="button" class="btn btn-fefault cart">
										<i class="fa fa-shopping-cart"></i>
										Add to cart
									</button>
								</span> -->
								<p><b>75 ml</b> In Stock</p>

								
							</div><!--/product-information-->

						</div>
						<div><br><br>
						<h2>Ako sa starať o svoje nohy?</h2>
						Zvyčajne venujeme starostlivosti o chodidlá menej času a pozornosti ako iným častiam tela. 
A predsa nemali by len esteticky vyzerať, ale mali by byť tiež v dobrej kondícii, aby nás nosili životom 
bez nepohodlia. Preto, aby boli elegantné a krásne počas celého roka, vytvorili sme extrémne DAILY MOISTURISING 
FOOT CREAM. Vďaka bohatstvu účinných látok sa rýchlo obnovuje ich zdravý vzhľad a dokonalá hladkosť .

<h3>Prečo si ho zamilujete:</h3>
pre veľkolepý efekt. Krém funguje 
efektí vne a rýchlo a poskytuje viditeľné 
zlepšenie stavu pokožky a vzhľadu nôh 
od prvej aplikácie. Hydratuje a regeneruje 
pokožku, znižuje jej drsnosť a zabraňuje 
vysušeniu a popraskaniu päty. 
  
<h3> Čo je naším tajomstvom:</h3>
špeciálne vyvinutá receptúra bohatá 
na účinné látky. Botanický komplex 
s 5 morskými riasami, močovinou 
a kyselinou mliečnou zaisťuje správnu 
úroveň hydratácie pokožky, zati aľ čo vosk 
z ryžových otrúb a bambucké maslo robia 
chodidlá zamatovo hebkými a príjemnými 
na dotyk.  

<h3>  Prečo ho nevymeníte za žiaden iný: </h3>
náš krém obsahuje prírodný neutralizačná 
látka zápachov, ktorý Vám poskytne 
jedinečný pocit pohodlia a sviežosti . 

<h3>Čo tak krásne vonia:</h3>
svieža zelená vôňa s nádychom čiernych 
ríbezlí, ruže, konvalinky, machu, pižma 
a cédrového dreva.


						</div>
					</div><!--/product-details-->
					
					
					
					
					
				</div>
