
				<div class="col-sm-9 padding-right">
					<div class="product-details"><!--product-details-->
						<div class="col-sm-5">
							<div class="view-product">
								<img src="images/product/304006.jpg" alt="" />
								
							</div>
							

						</div>
						<div class="col-sm-7">
							<div class="product-information"><!--/product-information-->
								<!-- <img src="images/product-details/new.jpg" class="newarrival" alt="" /> -->
								<h2>PRÍRODNÝ  BALZAM NA PERY</h2>
								<p>Symbol: 304006</p>
								
								<!-- <span>
									<span>US $59</span>
									<label>Quantity:</label>
									<input type="text" value="3" />
									<button type="button" class="btn btn-fefault cart">
										<i class="fa fa-shopping-cart"></i>
										Add to cart
									</button>
								</span> -->
								<p><b>4 g</b> In Stock</p>

								
							</div><!--/product-information-->

						</div>
						<div><br><br>
						<h2>Ako mať krásne pery každý deň?</h2>
						Hladké, mäkké a zvlhčené, vyzerajú skvele, ale pokožka pier je jemná a tenká, takže na udržanie 
ich zdravého vzhľadu je potrebné sa o ne zvlášť starať. Náš 
NATURAL LIP BALM 
pôsobí komplexne - stará sa o ne, chráni ich a zlepšuje ich stav v každom ročnom období . 

<h3>Prečo si ho zamilujete:</h3>
účinná starostlivosť a ochrana. Balzam 
obsahuje melónový olej, ricínový olej, kukui 
a jojobu, sójový vosk a Candelilla a bambucké 
maslo. Toto zloženie prírodných zložiek 
pomáha obnoviť zdravý vzhľad pier a poskytuje 
ochranu pred škodlivými účinkami vonkajších 
faktorov, ako sú slnko, vietor, mráz, znečistenie 
alebo klimatizácia. 
  
<h3>Čo ešte o tom treba vedieť:</h3>
balzam je mimoriadne jemný, ideálny na 
starostlivosť o suché, citlivé a podráždené 
pery. Je vhodný pre ženy, mužov aj deti  
od 3 rokov.  

<h3>   Čo spôsobí, že ho 
nenahradíte žiadnym iným:</h3>
príjemná konzistencia, vďaka ktorej sa ľahko 
roztopí a rozoti era. Zostáva na perách dlhú 
dobu a nezanecháva lepivú vrstvu. A k tomu 
príjemne vonia osviežujúcim melónom. 




						</div>
					</div><!--/product-details-->

				</div>
