
				<div class="col-sm-9 padding-right">
					<div class="product-details"><!--product-details-->
						<div class="col-sm-5">
							<div class="view-product">
								<img src="images/product/305001.jpg" alt="" />
								
							</div>
							

						</div>
						<div class="col-sm-7">
							<div class="product-information"><!--/product-information-->
								<!-- <img src="images/product-details/new.jpg" class="newarrival" alt="" /> -->
								<h2>MICELÁRNA VODA 3 V 1</h2>
								<p>Symbol: 305001</p>
								
								<!-- <span>
									<span>US $59</span>
									<label>Quantity:</label>
									<input type="text" value="3" />
									<button type="button" class="btn btn-fefault cart">
										<i class="fa fa-shopping-cart"></i>
										Add to cart
									</button>
								</span> -->
								<p><b>200 ml</b> In Stock</p>

								
							</div><!--/product-information-->

						</div>
						<div><br><br>
						<h2>Ako efektívne a rýchlo urobiť odlíčenie a vyčistiť tvár?</h2>
						Odlíčenie, očistenie a tonizácia sú tri nevyhnutné stupne starostlivosti pre svieži a atraktívny 
vzhľad pleti počas každého dňa. Ranné očistenie tváre a večerné odstraňovanie make-upu je 
však časovo náročné a unavujúce. Preto sme vytvorili 
MICELLAR LIQUID 3 IN 1 
– multifunkčná, neobyčajne jemná micelárna voda, ktorá sa komplexne postará o Vašu pleť. 
Každodenný ranný rituál očistenia pokožky a večerné odstraňovanie make-upu nebol nikdy 
taký jednoduchý a príjemný! MICELÁRNA VODA 3 V 1 neobyčajne účinne a rýchlo odstraňuje 
make-up, vrátane vodotesnej riasenky, odstraňuje mazu a nečistoty z povrchu pokožky 
a obnovuje jej správne pH - bez oplachovania! Odporúčaná na tvár ako aj na krk a výstrih.

<h3>Prečo si ju zamiluješ:</h3>
za bohatstvo účinných látok, ktoré sa 
postarajú o dokonalú kondíciu Vašej 
pleti. MICELÁRNA KVAPALINA 3 V 1 obsahuje komplex zložiek zaručujúci 
udržanie v rovnováhe mikrobioty 
pokožky, čo spôsobuje, že pokožka znovu 
získa správne pH a krásny vzhľad. Extrakt 
z bobúľ goji dodáva pokožke vitalitu a soľ 
kyseliny hyalurónovej dokonale hydratuje, 
zabezpečuje jej pevnosť a pružnosť  
  
<h3>Čo Vás v ňom poteší:</h3>
účinnosť a rýchlosť, s akou odstraňuje 
dokonca aj vodotesný make-up a úžasný 
efekt do hĺbky očistenej a tónovanej 
pokožku bez pocitu sti ahnuti a. 
Dokonale pripravuje pokožku na 
aplikáciu krému alebo séra.  

<h3> Na čo sme ešte hrdí:</h3>
92 % respondentov potvrdilo, že 
kozmeti ka dôkladne a rýchlo odstráni 
maskaru na oči (dokonca aj vode 
odolnú!) a nezanecháva neesteti cké 
„šmuhy“ pod očami. 23 z 25 ľudí uznalo, 
že kozmeti cký výrobok je nenahraditeľný 
počas rannej starostlivosti  o tvár 
a večerného odstraňovania líčidla.* 
<br>* Na základe nezávislých aplikačných a užívateľských testov vykonaných na skupine 25 osôb.<br>
 
<h3>Čo Vám poskytne dodatočnú bezpečnosť: </h3>
MICELÁRNA VODA 3 V 1 bola 
testovaná pod dohľadom oft almológa 
a odporúča sa aj pre ľudí s citlivými 
očami a nosiacimi kontaktné šošovky. 
Jemná receptúra je vhodná pre každý 
druh pleti, ti ež citlivej.


						</div>
					</div><!--/product-details-->

				</div>
