
				<div class="col-sm-9 padding-right">
					<div class="product-details"><!--product-details-->
						<div class="col-sm-5">
							<div class="view-product">
								<img src="images/product/501001.jpg" alt="" />
								
							</div>
							

						</div>
						<div class="col-sm-7">
							<div class="product-information"><!--/product-information-->
								<!-- <img src="images/product-details/new.jpg" class="newarrival" alt="" /> -->
								<h2>PENA NEUTRALIZUJÚCA NEPRÍJEMNÉ VÔNE</h2>
								<p>Symbol: 501001</p>
								
								<!-- <span>
									<span>US $59</span>
									<label>Quantity:</label>
									<input type="text" value="3" />
									<button type="button" class="btn btn-fefault cart">
										<i class="fa fa-shopping-cart"></i>
										Add to cart
									</button>
								</span> -->
								<p><b>250 ml</b> In Stock</p>

								
							</div><!--/product-information-->

						</div>
						<div><br><br>
						<h2>Ako odstrániť zápach cesnaku z Vašich rúk?</h2>
						Tu je magická pena 
ANTI-ODOUR HAND WASH, 
vďaka ktorej ako mávnutím čarovného prútika z našich dlaní miznú nepríjemné zápachy: 
cesnaku, cibule, rýb, starej zeleniny. Zakaždým, keď ponárame dlane do hustej, krémovej peny, 
oslobodzujeme sa od pretrvávajúcich zápachov, aby sme mohli bez problémov vychutnať 
vône lahodných jedál.

<h4>Prečo si ju zamiluješ:</h4>
za okamžité uvoľnenie Vašich dlaní od 
nepríjemného zápachu.  
  
<h4>Čo spôsobuje, že sa tak dokonale stará o dlane: </h4>
používame jemné čisti ace prostriedky. Staráme 
sa o správnu hydratáciu a hladkosť Vašich 
rúk. Špeciálna formula starostlivosti  o ruky, 
ktorú sme vyvinuli, spája výťažok z bavlny 
a polysacharidy z peruánskej rastliny tary 
(Caesalpinia spinosa). 

<h4>Čo Vám poskytne dodatočnú bezpečnosť:</h4>
predtým, ako sa táto penu dostane do Vašich 
rúk, prešla množstvom podrobných výskumov 
vrátane dermatologického testu, ktoré 
potvrdzujú toleranciu voči pokožke. Vonné 
oleje, ktoré používame, nemajú žiadne alergény 
v súlade s normami IFRA (Internati onal 
Fragrance Associati on). <br>
 
<h4>Čo Vás v nej milo prekvapí:</h4>
pena ti ež účinne odstraňuje zafarbenie od 
zeleniny a ovocia (červená repa, mrkva, 
čučoriedky).

<h4>Čo tak krásne vonia:</h4>
čerstvé zelené noty, biele kvety a šťavnaté 
citrusy. 

						</div>
					</div><!--/product-details-->

				</div>
