
				<div class="col-sm-9 padding-right">
					<div class="product-details"><!--product-details-->
						<div class="col-sm-5">
							<div class="view-product">
								<img src="images/product/501001.jpg" alt="" />
								
							</div>
							

						</div>
						<div class="col-sm-7">
							<div class="product-information"><!--/product-information-->
								<!-- <img src="images/product-details/new.jpg" class="newarrival" alt="" /> -->
								<h2>ODMASŤOVAČ</h2>
								<p>Symbol: 501001</p>
								
								<!-- <span>
									<span>US $59</span>
									<label>Quantity:</label>
									<input type="text" value="3" />
									<button type="button" class="btn btn-fefault cart">
										<i class="fa fa-shopping-cart"></i>
										Add to cart
									</button>
								</span> -->
								<p><b>500 ml</b> In Stock</p>

								
							</div><!--/product-information-->

						</div>
						<div><br><br>
						<h2>Ako odstrániť prischnutý tuk z rúry na pečenie?</h2>
						tu je naša tajná zbraň: 
GREASE BUSTER 
Spálený alebo prischnutý tuk, sadze, lepkavá špina alebo zaschnuté škvrny z omáčok na ňom 
nerobia ani najmenší dojem. Octová esencia a prírodné rozpúšťadlá mu umožňujú rýchlo 
odstrániť dokonca aj staré nečistoty, ale sú bezpečné pre čistené povrchy.

<h4>Prečo si ju zamiluješ:</h4>
za lesknúcu sa čistotu bez nutnosti drhnutia.  
  
<h4>Čo Vás v ňom uchváti:</h4>
účinne funguje aj v tvrdej a studenej vode.

<h4>Čo Vám poskytne dodatočnú bezpečnosť: </h4>
schválenie PZH (Národný Hygienický Ústav).<br>
 
<h4>Čo ním vyčistíte:</h4>
dosky, kuchynské skrinky a police, kachličky, 
drezy, digestory, odsávače, plynové 
a elektrické sporáky, chladničky, rúry, grile, 
rošty, fritézy a ďalšie kuchynské spotrebiče.

<h4>Čo tak krásne vonia:</h4>
lipový kvet, šťavnaté, čerstvé ovocie 
a ušľachtilý céder.

<h4>POZRITE, AKÝ JEDNODUCHÝ JE V POUŽITÍ: </h4>
postriekajte čistený povrch, 
počkajte chvíľku a potom 
opláchnite čistou vodou 
a utrite do sucha. Hotovo!
						</div>
					</div><!--/product-details-->

				</div>
