
				<div class="col-sm-9 padding-right">
					<div class="product-details"><!--product-details-->
						<div class="col-sm-5">
							<div class="view-product">
								<img src="images/product/501004.jpg" alt="" />
								
							</div>
							

						</div>
						<div class="col-sm-7">
							<div class="product-information"><!--/product-information-->
								<!-- <img src="images/product-details/new.jpg" class="newarrival" alt="" /> -->
								<h2>GÉL NA UMÝVANIE RIADU</h2>
								<p>Symbol: 501004</p>
								
								<!-- <span>
									<span>US $59</span>
									<label>Quantity:</label>
									<input type="text" value="3" />
									<button type="button" class="btn btn-fefault cart">
										<i class="fa fa-shopping-cart"></i>
										Add to cart
									</button>
								</span> -->
								<p><b>500 ml</b> In Stock</p>

								
							</div><!--/product-information-->

						</div>
						<div><br><br>
						<h2>Kto dnes umýva riad?</h2>
						Varenie spolu s priateľmi alebo rodinou je úžasnou radosťou. Len škoda, že po každom, 
dokonca aj najúžasnejšom jedle v umývadle na Vás čakajú špinavé riady. Nestrácajte svoju 
chuť do jedla, pretože už jedna kvapka hustého 
WASHING-UP GEL 
ľahko odstráni tuky, zvyšky jedla a iné nečistoty. Je mimoriadne účinný, výkonný a bezpečný 
aj pre najjemnejší porcelán.

<h4>Prečo ho budete milovať:</h4>
za jemnosť pre dlane. Nemusíte umývať 
v rukaviciach, pretože náš gél má vynikajúce 
hydratačné zložky. 
  
<h4>Čo spôsobuje, že sa dokonale stará o dlane: </h4>
keď umývate riad, my premýšľame 
o starostlivosti  o Vaše dlane. V našom géli 
používame iba jemné umývacie prostriedky. 
Aby sme zaisti li Vašim dlaniam vhodnú 
hydratáciu, jeho zloženie sme obohati li 
o ryžový olej, bylinný komplex z rebríčka 
obyčajného, nechtí ka, pagaštanu konského, 
hamamelu, ľubovníka, slezu, harmančeka 
a mäty piepornej a polysacharidy z peruánskej 
rastliny Tara 
(Caesalpinia spinosa). 

<h4>Čo Vám poskytne dodatočnú bezpečnosť:</h4>
predtým, ako sa tento gél dostal do Vašej 
kuchyne, podstúpil rad podrobných 
testov vrátane dermatologického testu 
potvrdzujúceho toleranciu pokožky. Vonné 
oleje, ktoré používame, nemajú žiadne alergény 
v súlade s normami IFRA (Internati onal 
Fragrance Associati on). Gél má aj schválenie 
PZH (Národný Hygienický Ústav). Postarali 
sme sa o to všetko, pretože Vaša spokojnosť je 
pre nás veľmi dôležitá.<br>
 
<h4> Čo tak krásne vonia:</h4>
čerstvá mäta, borovicové ihličie, sladká ruža, 
levanduľa a zmyselné santalové drevo.

<h4>Čo hovoria užívatelia?</h4>
Presne 100 % respondentov * uviedlo, 
že gél na umývanie riadu je nielen 
jednoducho odstraňuje tuky, zvyšky 
potravín a iné nečistoty, ale aj jemný pre 
pokožku dlaní a dokonale umýva riady 
dokonca aj v studenej vode.

<br>* Nezávislý spotrebiteľský prieskum uskutočnený na skupine 25 ľudí.

<h4>POZRITE, AKÝ JEDNODUCHÝ JE V POUŽITÍ:</h4>
naneste malé množstvo 
gélu na špongiu na 
umývanie riadu, a umytý 
riad dôkladne opláchnite 
vodou, utrite ho do 
sucha alebo len nechajte 
na odtokovej doske.

<h4>Sady s dizajnovou pumpičkou: <i>symbol: 591204</i></h4>
						</div>
					</div><!--/product-details-->

				</div>
