
				<div class="col-sm-9 padding-right">
					<div class="product-details"><!--product-details-->
						<div class="col-sm-5">
							<div class="view-product">
								<img src="images/product/501003.jpg" alt="" />
								
							</div>
							

						</div>
						<div class="col-sm-7">
							<div class="product-information"><!--/product-information-->
								<!-- <img src="images/product-details/new.jpg" class="newarrival" alt="" /> -->
								<h2>PENA NEUTRALIZUJÚCA NEPRÍJEMNÉ VÔNE</h2>
								<p>Symbol: 501003</p>
								
								<!-- <span>
									<span>US $59</span>
									<label>Quantity:</label>
									<input type="text" value="3" />
									<button type="button" class="btn btn-fefault cart">
										<i class="fa fa-shopping-cart"></i>
										Add to cart
									</button>
								</span> -->
								<p><b>500 ml</b> In Stock</p>

								
							</div><!--/product-information-->

						</div>
						<div><br><br>
						<h2>Ako rýchlo upratať kuchyňu?</h2>
						Predstavte si, že len postriekate a utierate a kuchyňa sa leskne. Náš 
KITCHEN SMART SPRAY 
pracuje takýmto šikovným spôsobom. Môžete ním bleskovo umyť prakticky všetko: stolové 
dosky, skrine, kuchynské spotrebiče, okenné parapety, odpadkové nádoby alebo sklokeramickú 
varnú doska. Je všestranný: čistí, jemne leští, odmasťuje a neutralizuje pretrvávajúce zápachy.

<h4>Prečo ho budete milovať:</h4>
pre rýchlosť účinku. Striekate a uti erate. 
Je to rýchlejšie ako posielanie SMS.  
  
<h4>Na aké povrchy ho môžete použiť:</h4>
a drevené parapety, z MDF dosiek, 
laminovaných, plastových a dokonca 
aj mramorových. 

<h4>Čo Vám poskytne dodatočnú bezpečnosť:</h4>
schválenie PZH (Národný Hygienický Ústav). 
Môžete ho používať na povrchy, ktoré sú 
v styku s jedlom.<br>
 
<h4>Čo tak krásne vonia:</h4>
exotické ylang-ylang a santalové drevo 
sprevádzané čerstvými notami z pelargónie 
a bergamotu.

<h4>POZRITE, AKÝ JEDNODUCHÝ JE V POUŽITÍ:</h4>
postriekajte čistený povrch 
a potom utrite vlhkou 
handričkou alebo opláchnite 
čistou vodou a utrite do 
sucha. Hotovo!

						</div>
					</div><!--/product-details-->

				</div>
