
				<div class="col-sm-9 padding-right">
					<div class="product-details"><!--product-details-->
						<div class="col-sm-5">
							<div class="view-product">
								<img src="images/product/502001.jpg" alt="" />
								
							</div>
							

						</div>
						<div class="col-sm-7">
							<div class="product-information"><!--/product-information-->
								<!-- <img src="images/product-details/new.jpg" class="newarrival" alt="" /> -->
								<h2>SPREJ NA UMÝVANIE A NA STAROSTLIVOSŤ O KÚPEĽŇU</h2>
								<p>Symbol: 502001</p>
								
								<!-- <span>
									<span>US $59</span>
									<label>Quantity:</label>
									<input type="text" value="3" />
									<button type="button" class="btn btn-fefault cart">
										<i class="fa fa-shopping-cart"></i>
										Add to cart
									</button>
								</span> -->
								<p><b>500 ml</b> In Stock</p>

								
							</div><!--/product-information-->

						</div>
						<div><br><br>
						<h2>Ako upratať kúpeľňu za 5 minút?</h2>
						Máte dojem, že Vaša kúpeľňa stále potrebuje upratať? Dokonale Vás chápeme, preto sme vytvorili 
tento univerzálny 
BATHROOM SMART SPRAY, 
vďaka ktorému upratovanie v kúpeľni bude trvať najviac päť minút. V jeho zložení nájdete dirt 
stop complex. Vďaka nemu každé nasledujúce použitie chráni čistený povrch, čím zabraňuje 
opätovnému usadzovaniu nečistôt. Preto, aby sme Vám vytvorili podmienky rovnako ako 
v najluxusnejších kúpeľoch, vonné oleje použité v spreji sme doviezli priamo z Francúzska.

<h4>Prečo ju budete milovať:</h4>
odteraz ak zmiznete v kúpeľni viac ako 
10 minút, znamená to len jednu vec – že máte 
chuť na dlhší kúpeľ.  
  
<h4>Čo Vás v ňom poteší:</h4>
inteligentná formula tekuti ny spôsobí, že menej 
času budete venovať na upratovanie a efekt 
je dlhodobý. Toto bude teraz naše tajomstvo. 
Je na vás, či ho budete zdieľať s inými členmi 
domácnosti .

<h4>Čo ním môžete umyť:</h4>
prakti cky všetko. Vane, umývadlo, záchod, 
toaletnú misu, kohúti ky a dokonca aj veľké 
podlahové a stenové povrchy.<br>
 
<h4>Čo tak krásne vonia:</h4>
čerstvé granátové jablko, chutné slivky, mandle 
a višňový kvet.

<h4>Čo hovoria užívatelia?</h4>
Presne 100 % respondentov* potvrdilo, že 
sprej dáva dlhodobý efekt čistoty, 
chráni čistený povrch pred opätovným 
usadzovaním nečistôt, dáva lesk čisteným 
povrchom a dokonale sa hodí ako výrobok 
na umývanie veľkých podlahových alebo 
stenových povrchov.

<br>* Nezávislý spotrebiteľský prieskum uskutočnený na skupine 25 ľudí.

<h4>POZRITE, AKÝ JEDNODUCHÝ JE V POUŽITÍ:</h4>
tento prípravok prakti cky 
pracuje za Vás. Postriekajte 
ním umývadlo, vaňu alebo 
batériu, chvíľku počkajte. 
Utrite vlhkou hubkou alebo 
handričkou a dôkladne 
opláchnite vodou.

<h4>Sady s dizajnovou pumpičkou: <i>symbol: 592101</i></h4>
						</div>
					</div><!--/product-details-->

				</div>
