
				<div class="col-sm-9 padding-right">
					<div class="product-details"><!--product-details-->
						<div class="col-sm-5">
							<div class="view-product">
								<img src="images/product/502003.jpg" alt="" />
								
							</div>
							

						</div>
						<div class="col-sm-7">
							<div class="product-information"><!--/product-information-->
								<!-- <img src="images/product-details/new.jpg" class="newarrival" alt="" /> -->
								<h2>ČISTIČ</h2>
								<p>Symbol: 502003</p>
								
								<!-- <span>
									<span>US $59</span>
									<label>Quantity:</label>
									<input type="text" value="3" />
									<button type="button" class="btn btn-fefault cart">
										<i class="fa fa-shopping-cart"></i>
										Add to cart
									</button>
								</span> -->
								<p><b>500 ml</b> In Stock</p>

								
							</div><!--/product-information-->

						</div>
						<div><br><br>
						<h2>Ako samostatne vyčistiť upchaté umývadlo?</h2>
						Ak nechcete zavolať inštalatéra zakaždým, dôrazne odporúčame náš 
SINK & DRAIN UNBLOCKER. 
Hustý gél Vám pomôže dokonca aj v prípade veľmi vážneho upchania. Precízne vyčistí 
odtok pôsobením stojacej vody. Pomáha taktiež zbaviť sa nepríjemného zápachu spojeného 
s upchaním. Jednoducho nalejte gél do odtoku, urobte si šálku kávy a zavolajte svojim 
známym a po 20 minútach opláchnite veľkým množstvom vody.

<h4>Prečo ho budete milovať:</h4>
má bleskový účinok a je lacnejší ako inštalatér. 
Používaný pravidelne raz mesačne Vám umožní 
raz a navždy zabudnúť na upchatý drez.  
  
<h4> O čo sme sa ešte postarali:</h4>
gél nespôsobuje koróziu oceľových rúr a gumy.

<h4>Na čo ho môžete použiť:</h4>
na drezy, sifóny, toalety, sprchové vaničky, 
vane, odtokové potrubia v kuchyni a kúpeľni.<br>
 
<h4>Aké zápchy Vám pomôže odstrániť:</h4>
upchania spôsobené tukom, kávovými 
a čajovými usadeninami, jedlom, vlasmi, 
papierom alebo vatou.

<h4>Prečo je bez vône:</h4>
aby Vás nelákalo, aby ste ho voňali.

<h4>POZRITE, AKÝ JEDNODUCHÝ JE V POUŽITÍ:</h4>
nalejte 100 ml prípravku 
do umývadla alebo 
toalety, ponechajte 20 
minút a opláchnite veľkým 
množstvo vody. 

<h4>ČO JE OBZVLÁŠŤ DÔLEŽITÉ PRE ŽENY: </h4>
môžete zabudnúť na 
inštalatéra a krtkovače. 
Gél má automati cký účinok 
a je veľmi hygienický pri 
používaní. Sami môžete 
poradiť so zapchaným 
potrubím a nemusíte nič 
pretláčať.

						</div>
					</div><!--/product-details-->

				</div>
