
				<div class="col-sm-9 padding-right">
					<div class="product-details"><!--product-details-->
						<div class="col-sm-5">
							<div class="view-product">
								<img src="images/product/502005.jpg" alt="" />
								
							</div>
							

						</div>
						<div class="col-sm-7">
							<div class="product-information"><!--/product-information-->
								<!-- <img src="images/product-details/new.jpg" class="newarrival" alt="" /> -->
								<h2>GÉL NA ODSTRÁNENIE KAMEŇA A HRDZE</h2>
								<p>Symbol: 502005</p>
								
								<!-- <span>
									<span>US $59</span>
									<label>Quantity:</label>
									<input type="text" value="3" />
									<button type="button" class="btn btn-fefault cart">
										<i class="fa fa-shopping-cart"></i>
										Add to cart
									</button>
								</span> -->
								<p><b>500 ml</b> In Stock</p>

								
							</div><!--/product-information-->

						</div>
						<div><br><br>
						<h2>Ako odstrániť hrdzavé škvrny?</h2>
						Ak už máte dosť matných povrchov a hrdzavých škvŕn, siahnite po našom osvedčenom 
prostriedku: hustý aktívny gél
RUST & LIMESCALE BUSTER
Tesne pokrýva čistený povrch, obnovuje jeho lesk a chráni pred novými usadeninami . 
Bleskovo odstraňuje usadeniny z kameňa, vody a mydla, hrdzavé škvrny . Vďaka nemu Vaša 
sanitárna armatúra sa bude opäť lesknúť od čistoty .

<h4>Prečo ho nenahradíte žiadnym iným: </h4>
keď mu zveríte svoj domov, kameň Vám 
spadne navždy zo srdca.   
  
<h4>Na čo ho môžete použiť:</h4>
na vane, umývadlá, kohúti ky, sprchy a toaletné 
misy, ako aj veľké povrchy (podlahy, dlaždice).

<h4>O čo sme sa ešte postarali:</h4>
o bezpečný uzáver.<br>
 
<h4>Čo tak krásne vonia:</h4>
sladké ovocné noty s čerstvosťou dúhovky 
a ibištekových kvetov. 

<h4>POZRITE, AKÝ JEDNODUCHÝ JE V POUŽITÍ:</h4>
naneste gél na znečistený 
povrch, nechajte niekoľko 
minút, potom pretrite 
kefk  ou alebo špongiou. 
Dôkladne opláchnite vodou 
alebo pretrite vlhkou 
handričkou.  



						</div>
					</div><!--/product-details-->

				</div>
