
				<div class="col-sm-9 padding-right">
					<div class="product-details"><!--product-details-->
						<div class="col-sm-5">
							<div class="view-product">
								<img src="images/product/502004.jpg" alt="" />
								
							</div>
							

						</div>
						<div class="col-sm-7">
							<div class="product-information"><!--/product-information-->
								<!-- <img src="images/product-details/new.jpg" class="newarrival" alt="" /> -->
								<h2>GÉL NA ČISTENIE TOALIET</h2>
								<p>Symbol: 502004</p>
								
								<!-- <span>
									<span>US $59</span>
									<label>Quantity:</label>
									<input type="text" value="3" />
									<button type="button" class="btn btn-fefault cart">
										<i class="fa fa-shopping-cart"></i>
										Add to cart
									</button>
								</span> -->
								<p><b>750 ml</b> In Stock</p>

								
							</div><!--/product-information-->

						</div>
						<div><br><br>
						<h2>Bezstresový spôsob na čistenie toaliet</h2>
						Čistenie toalety nepatrí medzi naše obľúbené činnosti. Rovnako sa nám nepáči zápach chlóru. 
Preto sme vyvinuli efektívne riešenie, ktoré nám pomáha robiť to veľmi rýchlo a v celej kúpeľni 
krásne vonia: 
TOILET EXPERT 
Jeho gélová formula quick clean si bleskovo poradí s najťažšími nečistotami. Založená na 
moderných silikónoch a prírodnej kyseline mliečnej zaručuje sanitárnym povrchom dokonalú 
čistotu a krásny lesk a originálna kompozícia založená na francúzskych olejčekoch má 
nádhernú a sviežu vôňu. 

<h4>Prečo ho nenahradíte žiadnym iným:</h4>
nemusíte si vybrať, či Vaša toaleta bude 
hygienicky čistá alebo pekne voňavá.  
  
<h4>Na čo ho môžete použiť:</h4>
na záchodové misy, bidetové misy, umývadlá 
a keramické sprchové vaničky.

<h4>Čo tak krásne vonia:</h4>
šťavnaté ovocie, sladká vanilka a kokos.<br>
 
<h4>Čo je naším tajomstvom:</h4>
účinná gélová formula, ktorá funguje rovnako 
v teplej aj studenej vode. Hustý gél nesteká 
ihneď z čisteného povrchu, ale robí na 
ňom povlak a umožňuje aktí vnym zložkám 
pracovať. Gél má skvelý účinok takti ež pod 
hladinou vody. A čo je dôležité, neobsahuje 
ani kvapku chlóru.

<h4>POZRITE, AKÝ JEDNODUCHÝ JE V POUŽITÍ:</h4>
polejte čistený povrch 
gélom a nechajte na 
niekoľko minút. V prípade 
potreby predrhnite kefou. 
Opláchnite dôkladne vodou. 



						</div>
					</div><!--/product-details-->

				</div>
