
				<div class="col-sm-9 padding-right">
					<div class="product-details"><!--product-details-->
						<div class="col-sm-5">
							<div class="view-product">
								<img src="images/product/502006.jpg" alt="" />
								
							</div>
							

						</div>
						<div class="col-sm-7">
							<div class="product-information"><!--/product-information-->
								<!-- <img src="images/product-details/new.jpg" class="newarrival" alt="" /> -->
								<h2>ANTIBAKTERIÁLNE PENOVÉ MYDLO</h2>
								<p>Symbol: 502006</p>
								
								<!-- <span>
									<span>US $59</span>
									<label>Quantity:</label>
									<input type="text" value="3" />
									<button type="button" class="btn btn-fefault cart">
										<i class="fa fa-shopping-cart"></i>
										Add to cart
									</button>
								</span> -->
								<p><b>250 ml</b> In Stock</p>

								
							</div><!--/product-information-->

						</div>
						<div><br><br>
						<h2>Ako sa postarať o hygienickú čistotu Vašich dlaní</h2>
						Najlepším spôsobom, ako sa zbaviť baktérií, je časté umývanie rúk. Preto sme vyvinuli krémovú 
penu s antibakteriálnymi vlastnosťami: 
ANTIBACTERIAL HAND FOAM. 
V hustej pene sme využili veľmi jemné čistiace prostriedky. Ochraňujú pokožku pred stratou 
lipidovej ochrannej bariéry, súčasne ju hydratujú a zmäkčujú. Táto voňavá kozmetika účinne 
čistí, chráni a ošetruje jemnú pokožku rúk a zanecháva ju hygienicky čistú. Spôsobuje, 
že umývanie rúk sa stáva príjemným každodenným rituálom. 

<h4>Prečo ju budete milovať:</h4>
pre anti bakteriálne vlastnosti a neobyčajne 
jemnú hypoalergénnu formulu vytvorenú pre 
každodennú starostlivosť o Vaše dlane.  
  
<h4>Čo spôsobuje, že tak dokonale sa stará o Vaše dlane:</h4>
v hustej pene sme využili veľmi jemné čisti ace 
prostriedky. Ochraňujú pokožku pred stratou 
lipidovej ochrannej bariéry, zati aľ čo ju 
navlhčujú a zmäkčujú. Formula 
clean & care založená na prírodných anti  bakteriálnych 
zložkách spája zlepšujúci sa vzhľad a znižujúci 
drsnosť pokožky komplex 
WHITESENSE™ 
(s jemnými, bielymi kvetmi, stolistovej ruže, 
jazmínu a sedmokrásky) s výťažkom zo 
stolistovej ruže (Rosa Centi folia), ktorý má anti oxidančný účinok a účinok proti  starnuti u 

<h4>Čo Vám poskytne dodatočnú bezpečnosť: </h4>
predtým, ako táto penová látka dostala do 
Vašich rúk, prešla niekoľkými podrobnými 
testami vrátane dermatologického testu 
potvrdzujúceho toleranciu pokožky. 
Hypoalergénna formula sa stará o ruky, 
nespôsobuje precitlivenosť a alergie.<br>
 
<h4>Čo Vás v nej milo prekvapí:</h4>
pena má neutrálny PH pre pokožku, vďaka 
tomu pomáha znížiť vysušenie pokožky.

<h4>Čo tak krásne vonia:</h4>
šťavnaté jablko a hruška, jemná ľalia a čerstvé 
bambusové noty. 



						</div>
					</div><!--/product-details-->

				</div>
