
				<div class="col-sm-9 padding-right">
					<div class="product-details"><!--product-details-->
						<div class="col-sm-5">
							<div class="view-product">
								<img src="images/product/503005.jpg" alt="" />
								
							</div>
							

						</div>
						<div class="col-sm-7">
							<div class="product-information"><!--/product-information-->
								<!-- <img src="images/product-details/new.jpg" class="newarrival" alt="" /> -->
								<h2>GÉL NA PRANIE TMAVÝCH A ČIERNYCH TEXTÍLIÍ</h2>
								<p>Symbol: 503005</p>
								
								<!-- <span>
									<span>US $59</span>
									<label>Quantity:</label>
									<input type="text" value="3" />
									<button type="button" class="btn btn-fefault cart">
										<i class="fa fa-shopping-cart"></i>
										Add to cart
									</button>
								</span> -->
								<p><b>1000 ml</b> In Stock</p>

								
							</div><!--/product-information-->

						</div>
						<div><br><br>
						<h2>Ako nosiť čiernu s triedou?</h2>
						Krásna, hlboká čierna funguje ako magnet. Priťahuje pohľady plné obdivu, ale aj všetky častice 
prachu. Prach usadzujúci sa na vláknach a kameň z tvrdej vody spôsobujú, že čierne farby 
strácajú svoju hĺbku a tmavé tkaniny vyblednú a vyhasnú. V boji proti týmto nepriaznivým 
účinkom sme vytvorili 
DARKS GEL, 
ktorý zabraňuje opätovnému usadzovaniu nečistôt z vodného kameňa na vláknach. Chráni 
textílie pred stratou farby, nezanecháva neestetické svetlé šmuhy a škvrny. Perfektne sa stará 
o hĺbku a intenzitu čiernej a tmavých farieb.

<h4>Prečo ho budete milovať:</h4>
za istotu, že Vaše čierne šaty vyzerajú sviežo 
a elegantne a Vy priťahujete pohľady.  
  
<h4>Čo Vás v ňom poteší:</h4>
jeho gélová koncentrovaná formula. Vďaka 
tomu funguje efektí vne a nezaberá veľa miesta 
na poličke a stačí na veľmi dlhú dobu.    

<h4>Čo Vám poskytne dodatočnú bezpečnosť: </h4>
formula black protect.<br>
 
<h4>Ako vonia čierna:</h4>
radi sa hráme s vôňami, a preto sme požiadali 
tvorcov, ktorí s nami spolupracujú, aby vytvorili 
kompozíciu inšpirovanú eleganciou čiernej 
farby. Očarili nás zmyselnou hrou, spájajúc 
klasické noty ruží a konvalinky s teplými 
dôrazmi pižma.

<h4>ČO EŠTE MÔŽETE UROBIŤ PRE VAŠE ČIERNE OBLEČENIE: </h4>
na pláchanie použite 
náš parfumovaný gél 
na zmäkčovanie tkanín 
s vynikajúcimi anti stati ckými 
vlastnosťami.
						</div>
					</div><!--/product-details-->

				</div>
