
				<div class="col-sm-9 padding-right">
					<div class="product-details"><!--product-details-->
						<div class="col-sm-5">
							<div class="view-product">
								<img src="images/product/503006.jpg" alt="" />
								
							</div>
							

						</div>
						<div class="col-sm-7">
							<div class="product-information"><!--/product-information-->
								<!-- <img src="images/product-details/new.jpg" class="newarrival" alt="" /> -->
								<h2>GÉL NA PRANIE FAREBNÝCH TEXTÍLIÍ</h2>
								<p>Symbol: 503006</p>
								
								<!-- <span>
									<span>US $59</span>
									<label>Quantity:</label>
									<input type="text" value="3" />
									<button type="button" class="btn btn-fefault cart">
										<i class="fa fa-shopping-cart"></i>
										Add to cart
									</button>
								</span> -->
								<p><b>1000 ml</b> In Stock</p>

								
							</div><!--/product-information-->

						</div>
						<div><br><br>
						<h2>Ako prať farby dohromady?</h2>
						Kombinácia farieb môže spôsobovať ťažkosti, najmä ak po ďalšom praní je odtieň malinového 
svetra stále viac mliečny a oranžové nohavice stratili svoj lesk. Ak chcete, aby Vaše oblečenie 
vždy urobilo skvelý dojem, navrhli sme 
COLOUR GEL, 
ktorý dokonale chráni farby pred účinkami prania. Zabraňuje prenosu pigmentov medzi 
tkaninami, vďaka čomu ešte lepšie chráni farby tkanín. Odteraz sa postaráme o intenzívne farby 
Vášho oblečenia a Vy o úspešné viacfarebné štylizácie.

<h4>Prečo ho budete milovať:</h4>
za to, že Vaše farebné oblečenie má živé 
a intenzívne farby a Vy vyzeráte skvele.  
  
<h4>Čo je naším tajomstvom:</h4>
formula s aktí vnymi enzýmami spôsobuje, že 
gél má vynikajúci účinok už v nízkych teplotách 
(od 20°C). A ako dobre viete, pranie v nižších 
teplotách je prospešné nielen pre Vaše 
oblečenie, ale aj pre Vaše fi nancie.   

<h4>Čo Vám poskytne dodatočnú bezpečnosť:  </h4>
prísada, ktorá zabraňuje prenosu pigmentov 
medzi tkaninami. <br>
 
<h4>Ako voňajú farby:</h4>
radi sa hráme s vôňami, a preto sme požiadali 
tvorcov, ktorí s nami spolupracujú, aby vytvorili 
kompozíciu odrážajúcu bohatstvo sveta farieb. 
Ako náhle sme pocíti li vibrujúce noty marhule 
a pulzovanie korenistých prísad, vedeli sme, že 
žiadna iná vôňa by to nevyjadrila lepšie. 

<h4>ČO JE OBZVLÁŠŤ DÔLEŽITÉ PRE MUŽOV</h4>
chápeme, že môžete 
nerozlišovať všetky farby. 
Ak neviete, či môžete 
prať svoje smaragdové 
nohavice so svetlozeleným 
tričkom, náš gél Vám dáva 
zelené svetlo. Vďaka zložke 
zabraňujúcej prenosu 
pigmentov môžete všetky 
farby prať spolu (pokiaľ 
výrobca odevov neuvedie 
na ští tku inak). 
						</div>
					</div><!--/product-details-->

				</div>
