
				<div class="col-sm-9 padding-right">
					<div class="product-details"><!--product-details-->
						<div class="col-sm-5">
							<div class="view-product">
								<img src="images/product/503004.jpg" alt="" />
								
							</div>
							

						</div>
						<div class="col-sm-7">
							<div class="product-information"><!--/product-information-->
								<!-- <img src="images/product-details/new.jpg" class="newarrival" alt="" /> -->
								<h2>GÉL NA PRANIE BIELYCH TEXTÍLIÍ</h2>
								<p>Symbol: 503004</p>
								
								<!-- <span>
									<span>US $59</span>
									<label>Quantity:</label>
									<input type="text" value="3" />
									<button type="button" class="btn btn-fefault cart">
										<i class="fa fa-shopping-cart"></i>
										Add to cart
									</button>
								</span> -->
								<p><b>1000 ml</b> In Stock</p>

								
							</div><!--/product-information-->

						</div>
						<div><br><br>
						<h2>Ako dobre vyzerať v bielej?</h2>
						Snehová biela bavlny, krémová biela čipiek, perleťová biela atlasu, mliečna biela hodvábu... 
Každý malý odtieň, každá refrakcia svetla je dôležitá. Dokonale vidíme rozdiel medzi snehovou 
bielou košeľou a alabastrovou bielou tafty sukne. Preto formula nášho gélu na pranie 
WHITES GEL 
bola vypracovaná tak, aby chránila všetky odtiene bielej, nielen tie snehové. Udržuje ich 
v bezchybnej čistote, zabraňuje šednutiu a nezanecháva šmuhy. Dokonale oživuje svetlé farby 
a ponecháva vyprané prádlo čerstvé a nádherne voňavé.

<h4>Prečo ho budete milovať:</h4>
za istotu, že Vaše svetlé a biele šaty sú 
dokonale čisté a Vy vyzeráte skvele.  
  
<h4>Čo Vás v ňom poteší:</h4>
jeho gélová koncentrovaná formula. Vďaka 
tomu funguje efektí vne a nezaberá veľa miesta 
na poličke a stačí na veľmi dlhú dobu.    

<h4>Čo Vám poskytne dodatočnú bezpečnosť: </h4>
formula whites sensor. Gél neobsahuje opti cké 
bielidlá, preto je bezpečný pre všetky odti ene 
bielej a nespôsobuje šednuti e jemných textílií.<br>
 
<h4>Ako vonia biela:</h4>
radi sa hráme s vôňami, a preto sme požiadali 
tvorcov, ktorí s nami spolupracujú, aby 
vytvorili kompozíciu inšpirovanú bielou 
farbou. Majestátne spojili silu bielych kvetov 
s jemnosťou bavlny a chladným prízvukom 
snehových vločiek.


						</div>
					</div><!--/product-details-->

				</div>
