
				<div class="col-sm-9 padding-right">
					<div class="product-details"><!--product-details-->
						<div class="col-sm-5">
							<div class="view-product">
								<img src="images/product/503003.jpg" alt="" />
								
							</div>
							

						</div>
						<div class="col-sm-7">
							<div class="product-information"><!--/product-information-->
								<!-- <img src="images/product-details/new.jpg" class="newarrival" alt="" /> -->
								<h2>PARFÉMOVANÝ GÉL NA ZMÄKČOVANIE TKANÍN</h2>
								<p>Symbol: 503003</p>
								
								<!-- <span>
									<span>US $59</span>
									<label>Quantity:</label>
									<input type="text" value="3" />
									<button type="button" class="btn btn-fefault cart">
										<i class="fa fa-shopping-cart"></i>
										Add to cart
									</button>
								</span> -->
								<p><b>1000 ml</b> In Stock</p>

								
							</div><!--/product-information-->

						</div>
						<div><br><br>
						<h2>Ako ušetriť čas pri žehlení?</h2>
						viete, že správne zmäkčovanie tkanín umožňuje ich rýchlejšie vyžehlenie a pri žehlení 
zriedkavejšie vznikajú neestetické „vrásky“? Náš gél zmäkčovanie tkanín 
PERFUMED 
FABRIC SOFTENER GEL 
dokonale zmäkčuje textílie, spôsobujúc, že žehlička sa takmer sama kĺže na žehlenom 
povrchu. A tkaniny sú neuveriteľne ľahké, mäkké a nadýchané.

<h4>Prečo ho budete milovať:</h4>
pre mäkkosť, s ktorou tkaniny zabalia 
Vašu pokožku. Spoznáte novú dimenzia 
nachýnanosti bez elektrizácie. A večný 
problém toho, kto zavesí bielizeň, prejde 
do histórie.  
  
<h4>Čo Vás v ňom poteší:</h4>
vďaka perfektnému zmäkčeniu tkanín ušetríte 
veľa času pri žehlení.   

<h4>Čo tak krásne vonia:</h4>
zmyselná a obklopujúca gélová vôňa je 
návratom k najlepším tradíciám francúzskeho 
parfumérstva. Bohatá kveti nová kyti ca bola 
prehĺbená balzamickou vôňou santalového 
dreva a teplým nádychom pižma. Za svoju 
sviežosť a ľahkosť vďačí vibrujúcim notám 
sicílskej mandarínky. Jednoducho krása v čistej 
forme.<br>
 
<h4>Čo Vám poskytne dodatočnú bezpečnosť: </h4>
kondicionér a gél prešli 
sériou podrobných testov, 
vrátane dermatologického 
vyšetrenia, potvrdzujúcich 
toleranciu kože.

<h4>POZRITE, AKÝ JEDNODUCHÝ JE V POUŽITÍ:</h4>
stačí pridať správne 
množstvo gélu do 
posledného plákania. 
Môžete ho použiť aj počas 
prania v práčke ako aj 
ručného prania.
						</div>
					</div><!--/product-details-->

				</div>
