
				<div class="col-sm-9 padding-right">
					<div class="product-details"><!--product-details-->
						<div class="col-sm-5">
							<div class="view-product">
								<img src="images/product/503001.jpg" alt="" />
								
							</div>
							

						</div>
						<div class="col-sm-7">
							<div class="product-information"><!--/product-information-->
								<!-- <img src="images/product-details/new.jpg" class="newarrival" alt="" /> -->
								<h2>GÉL NA ODSTRAŇOVANIE ŠKVŔN</h2>
								<p>Symbol: 503001</p>
								
								<!-- <span>
									<span>US $59</span>
									<label>Quantity:</label>
									<input type="text" value="3" />
									<button type="button" class="btn btn-fefault cart">
										<i class="fa fa-shopping-cart"></i>
										Add to cart
									</button>
								</span> -->
								<p><b>500 ml</b> In Stock</p>

								
							</div><!--/product-information-->

						</div>
						<div><br><br>
						<h2>Ako odstrániť 15 najčastejších škvŕn za 10 minút?</h2>
						Spýtali sme sa našich známych, aké škvrny sa im stávajú najčastejšie. Z odpovedí, ktoré 
sme získali, sme vytvorili zoznam pätnástich výziev pre náš odstraňovač škvŕn 
STAIN BUSTER. 
Za púhych 10 minút sme odstránili škvrny od kávy, čaju, krvi, coca-coly, oleja, červeného 
vína, pomarančového džúsu, trávy, zeme, fl uidu, omáčky, paradajkovej polievky, 
mandarínky, zubnej pastu a jablčno-višňovej šťavy. A bez trenia. Sme na neho hrdí!

<h4>Prečo tak dobre účinkuje:</h4>
tajomstvom účinnosti  nášho odstraňovača škvŕn je oxysystém, 
založený na aktí vnom kyslíku a enzýmoch. Pracuje dokonale 
aj pri nízkych teplotách (od 20° C). Hustý gél sa 
ľahko rozvádza na texti le a preniká do škvŕn, 
má precízny bodový účinok a je mimoriadne 
účinný.  
  
<h4>Prečo ho budete milovať:</h4>
pre bezohľadnosť voči škvrnám a jemnosť pre 
tkaniny.    

<h4>Čo Vás v ňom milo prekvapí:</h4>
je jemný pre farby. Dokonca aj po 
mnohonásobnom použití  zachovávajú svoj 
prirodzený odti eň.<br>
 
<h4>Na čo ho môžete použiť:</h4>
pre všetky druhy látok, dokonca aj na ti e 
najjemnejšie, pre biele a farebné oblečenie, 
pretože neobsahuje chlór.

<h4>Prečo je bez vône:</h4>
odstraňovač škvŕn je bez vône, aby sa dal 
použiť takti ež na detské oblečenie. Ak chcete, 
aby Vaše oblečenie krásne voňalo, pridajte 
do prania náš parfumovaný kondicionér alebo 
gél na pláchanie.

<h4>POZRITE, AKÝ JEDNODUCHÝ JE V POUŽITÍ</h4>
gél môžete priamo na škvrnu 
(bodovo) alebo ho pridajte 
do prania.
						</div>
					</div><!--/product-details-->

				</div>
