
				<div class="col-sm-9 padding-right">
					<div class="product-details"><!--product-details-->
						<div class="col-sm-5">
							<div class="view-product">
								<img src="images/product/503008.jpg" alt="" />
								
							</div>
							

						</div>
						<div class="col-sm-7">
							<div class="product-information"><!--/product-information-->
								<!-- <img src="images/product-details/new.jpg" class="newarrival" alt="" /> -->
								<h2>INTENZÍVNE PARFUMOVANÝ KONDICIONÉR NA PLÁCHANIE TKANÍN</h2>
								<p>Symbol: 503008</p>
								
								<!-- <span>
									<span>US $59</span>
									<label>Quantity:</label>
									<input type="text" value="3" />
									<button type="button" class="btn btn-fefault cart">
										<i class="fa fa-shopping-cart"></i>
										Add to cart
									</button>
								</span> -->
								<p><b>1000 ml</b> In Stock</p>

								
							</div><!--/product-information-->

						</div>
						<div><br><br>
						<h2>Ako sa starať o oblečenie pri praní?</h2>
						Veľa informácií o sebe poskytujeme prostredníctvom svojho odevu a elegantné a voňavé 
oblečenie ovplyvňuje nielen to, ako sme vnímaní, ale aj našu náladu. Preto, ak chcete, aby 
vyzeralo ako nové a voňalo krásne po dlhú dobu, používajte 
LONG-LASTING PERFUMED 
LAUNDRY CONDITIONER, 
ktorý sa stará o vlákna a robí tkaniny extrémne mäkkými, ľahkými, pružnými a nadýchanými. 
Pšeničné proteíny v ňom obsiahnuté účinne chránia farby pred vyblednutím a biele pred 
zošednutím.

<h4>Prečo si ju zamiluješ:</h4>
pre receptúru stay new, ktorá aktí vne chráni 
vlákna počas prania a sušenia, zabraňuje 
ich poškodeniu, deformácii a žmolkovaniu, 
a takti ež praskaniu potlače na tričkách. Látky 
vyzerajú, že boli často prané o polovicu menej.  
  
<h4>Čo Vás v ňom uchváti:</h4>
vôňa, ktorá vydrží ešte dlhšie – dokonca 
až 24 týždňov! Vonné oleje sme uzavreli 
v špeciálnych mikrokapsuliach HD Acti ve Life, 
ktoré uvoľňujú úžasnú arómu - dokonca bez 
toho, aby sa materiál natieral.  

<h4>Čo tak krásne vonia:</h4>
kompozícia kveti nového dreva vytvorená 
z francúzskych vonných olejov, v ktorej 
sme kombinovali jemné jazmínové, tropické 
ylang-ylang a exoti cké aróma kokosovej vody 
so zmyselným pižmom, aloe, ružovým drevom 
a korenistými tónmi santalového dreva.<br>
 
<h4>O čo sme sa ešte postarali:</h4>
kondicionér prešiel 
množstvom podrobných 
testov, vrátane 
dermatologického testu, 
ktorý potvrdzuje kožnú 
znášanlivosť.

<h4>POZRITE, AKÝ JEDNODUCHÝ JE V POUŽITÍ: </h4>
jednoducho pridajte 
správne množstvo 
kondicionéra do 
posledného plákania. 
Môžete ho použiť v práčke, 
tak aj počas ručného prania, 
na všetky druhy tkanín a na 
všetky druhy farieb.
						</div>
					</div><!--/product-details-->

				</div>
