
				<div class="col-sm-9 padding-right">
					<div class="product-details"><!--product-details-->
						<div class="col-sm-5">
							<div class="view-product">
								<img src="images/product/503007.jpg" alt="" />
								
							</div>
							

						</div>
						<div class="col-sm-7">
							<div class="product-information"><!--/product-information-->
								<!-- <img src="images/product-details/new.jpg" class="newarrival" alt="" /> -->
								<h2>TEKUTÝ PRACÍ PRÁŠOK NA PRANIE ŠPORTOVÉHO OBLEČENIA</h2>
								<p>Symbol: 503007</p>
								
								<!-- <span>
									<span>US $59</span>
									<label>Quantity:</label>
									<input type="text" value="3" />
									<button type="button" class="btn btn-fefault cart">
										<i class="fa fa-shopping-cart"></i>
										Add to cart
									</button>
								</span> -->
								<p><b>500 ml</b> In Stock</p>

								
							</div><!--/product-information-->

						</div>
						<div><br><br>
						<h2>Ako sa starať o športové oblečenie?</h2>
						Ak pravidelne športujete a neviete si predstaviť týždeň bez tréningu, určite používate funkčné 
oblečenie . Vieme, že si vyžaduje špeciálne čistenie a starostlivosť, aby si dlho udržala svoje 
vlastnosti, a preto sme vytvorili 
SPORTSWEAR 
WASHING EXPERT 
Nielenže z oblečenia účinne odstraňuje nečistoty, ale tiež chráni štruktúru a farbu tkaniny . 
Použili sme v ňom inovatívne technológie, ktoré neutralizujú nepríjemné vône, ktoré Vám 
zaistia príjemnú sviežosť taktiež počas tréningu .

<h4>Prečo si ju zamiluješ:</h4>
nielen na dokonalé čistenie, ale aj na 
osvieženie športového oblečenia a ochranu 
jeho vlastností . Je bezpečný pre všetky typy 
funkčných tkanín. Dovoľuje zachovať ich 
priedušnosť.  
  
<h4>Čo Vás v ňom uchváti:</h4>
receptúra neutralizujúca zápach. Vďaka nej 
a voňavým olejom, uzavretým v špeciálnych 
kapsulách, je zápach potu účinne 
neutralizovaný nielen pri praní, ale aj pri nosení 
odevov, čo zaisťuje dlhodobý pocit sviežosti.   

<h4>Na čo ho môžete použiť:</h4>
na čistenie a starostlivosť o termoaktí vne 
odevy pre rôzne aplikácie - športové, 
membránové, vetruvzdorné, nepremokavé 
alebo bavlnené. Ak si odev, ktorý sa má 
vyčisti ť, vyžaduje impregnáciu, použite vhodný 
impregnačný prostriedok určený pre funkčný 
odev a nalejte ho do preplachovacej komory. 
Postupujte podľa pokynov výrobcu odevov. <br>
 
<h4> Čo tak krásne vonia:</h4>
kompozícia vytvorená z originálnych 
francúzskych vonných olejov s osviežujúcimi 
citrusovými tónmi, intenzívnou zelenou 
vôňou fi aliek, zrelej ruže a jemnej konvalinky. 
Dokonale ich dopĺňa balzamové cédrové 
drevo, tóny jantáru a zmyselného pižma.


						</div>
					</div><!--/product-details-->

				</div>
