
				<div class="col-sm-9 padding-right">
					<div class="product-details"><!--product-details-->
						<div class="col-sm-5">
							<div class="view-product">
								<img src="images/product/503002.jpg" alt="" />
								
							</div>
							

						</div>
						<div class="col-sm-7">
							<div class="product-information"><!--/product-information-->
								<!-- <img src="images/product-details/new.jpg" class="newarrival" alt="" /> -->
								<h2>PARFÉMOVANÝ KONDICIONÉR NA TEXTÍLIE</h2>
								<p>Symbol: 503002</p>
								
								<!-- <span>
									<span>US $59</span>
									<label>Quantity:</label>
									<input type="text" value="3" />
									<button type="button" class="btn btn-fefault cart">
										<i class="fa fa-shopping-cart"></i>
										Add to cart
									</button>
								</span> -->
								<p><b>1000 ml</b> In Stock</p>

								
							</div><!--/product-information-->

						</div>
						<div><br><br>
						<h2>Ako sa starať o športové oblečenie?</h2>
						Keď dávate novú vec do skrine, snívate o tom, že aby zostala krásna a príjemná na dotyk čo 
najdlhšie. Aby sa pekne ukladala, nekrčila sa a vždy vyzerala sviežo a elegantne. Splníme Vaše 
sny! Vďaka formule stay-new kondicionér 
PERFUMED LAUNDRY 
CONDITIONER  
účinne bojuje proti prvým známkam starnutia látok . Chráni pred deformáciami a chlpatením, 
znižuje mechanické poškodenie počas prania . Starostlivo dbá, aby farby Vášho oblečenia 
boli dlhšie živé a krásne. K tomu má fantastickú vôňu, vytvorenú v spolupráci s francúzskymi 
parfumérmi.

<h4>Prečo ho budete milovať:</h4>
vaše obľúbené oblečenie bude dlhšie vyzerať 
ako nové.
  
<h4>Čo Vás v nej uchváti:</h4>
dlhotrvajúca vôňa udržujúca sa až 8 
týždňov. Naše vonné oleje sú uzavreté 
v mikrokapsulách, ktoré pôsobia ako malé 
difúzory. Nerozpúšťajú sa vo vode a otvárajú 
sa len počas nosenia textí lií. Pri každom Vašom 
pohybe, kapsuly uvoľňujú olejčeky, obklopujúc 
Vás intenzívnou vôňou parfémov.   

<h4> Čo tak krásne vonia:</h4>
táto kompozícia je esenciou francúzskeho 
štýlu. Harmonicky spája klasické kveti nové 
noty so sladkosťou vanilkových a čokoládových 
praliniek. Celok jemne ozdobujú stredomorské 
akcenty, ktoré prinášajú príliv letnej, relaxačnej 
sviežosti. <br>
 
<h4>POZRITE, AKÝ JEDNODUCHÝ JE V POUŽITÍ: </h4>
stačí, že pridáte správne 
množstvo kondicionéra 
do posledného plákania. 
Môžete ho použiť aj počas 
prania v práčke ako aj 
ručného prania.


						</div>
					</div><!--/product-details-->

				</div>
