
				<div class="col-sm-9 padding-right">
					<div class="product-details"><!--product-details-->
						<div class="col-sm-5">
							<div class="view-product">
								<img src="images/product/504001.jpg" alt="" />
								
							</div>
							

						</div>
						<div class="col-sm-7">
							<div class="product-information"><!--/product-information-->
								<!-- <img src="images/product-details/new.jpg" class="newarrival" alt="" /> -->
								<h2>ZAMATOVÉ ČISTIACE MLIEKO</h2>
								<p>Symbol: 504001</p>
								
								<!-- <span>
									<span>US $59</span>
									<label>Quantity:</label>
									<input type="text" value="3" />
									<button type="button" class="btn btn-fefault cart">
										<i class="fa fa-shopping-cart"></i>
										Add to cart
									</button>
								</span> -->
								<p><b>500 ml</b> In Stock</p>

								
							</div><!--/product-information-->

						</div>
						<div><br><br>
						<h2>Ako sa správne starať o sanitárny porcelán?</h2>
						Viete, že niektoré domáce spotrebiče sú také jemné, že silné drhnutie môže poškodiť ich 
povrch? Preto sme vytvorili naše zamatové mlieko 
CREAM  
inšpirovali sme sa kozmetikou na odstraňovanie make-upu. Vďaka tomu nielen jemne čistí, 
ale ošetruje, dodáva lesk a chráni vyčistené povrchy.

<h4>Čo Vás v ňom poteší:</h4>
zamatová konzistencia ako v najjemnejšom 
kozmeti ckom výrobku so súčasnou rýchlosťou 
a účinnosťou pôsobenia. Obsahuje jemný 
olivový olej, ktorý krásne naleští  čistený 
povrch.  
  
<h4>Čo ním môžete čistiť:</h4>
sanitárny porcelán (umývadlá, drezy, vane), 
kuchynské spotrebiče, poniklované povrchy, 
keramický, smaltovaný, plastový záhradný 
nábytok, steny s kachličkami.   

<h4>Čo ľahko odstraňuje:</h4>
vodné a mydlové usadeniny, usadeniny 
kameňa, hrdzavé škvrny, pripáleniny a mastné 
usadeniny.<br>
 
<h4>Čo tak krásne vonia:</h4>
citrusy, čierne olivy, ľalia, hruškový kvet 
a santalové drevo.

<h4>Čo je naším tajomstvom:</h4>
jemná formula dovoľujúca čisti ť bez 
škrabancov.

<h4>POZRITE, AKÝ JEDNODUCHÝ JE V POUŽITÍ</h4>
naneste mlieko na čistený 
povrch. Ak je to potrebné, 
jemne pretrite. Potom 
jemne odstráňte zvyšok 
s vlhkou handričkou a hojne 
opláchnite vodou.
						</div>
					</div><!--/product-details-->

				</div>
