
				<div class="col-sm-9 padding-right">
					<div class="product-details"><!--product-details-->
						<div class="col-sm-5">
							<div class="view-product">
								<img src="images/product/504002.jpg" alt="" />
								
							</div>
							

						</div>
						<div class="col-sm-7">
							<div class="product-information"><!--/product-information-->
								<!-- <img src="images/product-details/new.jpg" class="newarrival" alt="" /> -->
								<h2>SPREJ NA UMÝVANIE OKIEN A ZRKADIEL S ANTIPAROVOU FUNKCIOU</h2>
								<p>Symbol: 504002</p>
								
								<!-- <span>
									<span>US $59</span>
									<label>Quantity:</label>
									<input type="text" value="3" />
									<button type="button" class="btn btn-fefault cart">
										<i class="fa fa-shopping-cart"></i>
										Add to cart
									</button>
								</span> -->
								<p><b>500 ml</b> In Stock</p>

								
							</div><!--/product-information-->

						</div>
						<div><br><br>
						<h2>Ako sa zbaviť šmúh z okien?</h2>
						Či Vaše okná boli kedykoľvek tak dokonale čisté, že sa stali prakticky neviditeľnými? 
Ak si myslíte, že je to nemožné, vyskúšajte náš multifunkčný 
GLASS & MIRROR EXPERT 
Uvidíte, že nielen perfektne čistí okná, ale aj zabraňuje ich zamlžovaniu a chráni ich pred 
opätovným znečistením. Vďaka obsahu alkoholu sa rýchlo vyparuje a nezanecháva šmuhy. 
Ľahko odstraňuje prach, prach, tuk, sadze a dokonca aj stopy po mastných rukách. Presvedčte 
sa, aký fantastický pocit to je, keď rozmýšľate, či máte pred sebou okennú tabuľu alebo len 
vzduch.

<h4>Prečo ho budete milovať:</h4>
dokonca aj počas slnečného dňa, na oknách 
neuvidíte šmuhy  
  
<h4>Na čo ho môžete použiť:</h4>
na okenné tabule a okenné rámy, na 
automobilové okná, okná v sprchovacích 
kabínach, na prístrešky, zrkadlá, kryštály, 
sklenené ti enidlá lámp. Na farebné, tónované 
a farebné sklenené tabule. Takti ež ho 
odporúčame na plast a plexisklo. Môže byť 
používaný na vnútorné a vonkajšie sklenené 
tabule.    

<h4>Čo tak krásne vonia:</h4>
šťavnaté citrusy, čerstvá mäta a osviežujúce 
morské noty.<br>
 
<h4>CENNÉ ODPORÚČANIE:</h4>
niekedy menej znamená 
viac. Ak sa chcete vyhnúť 
šmuhám, nepreháňajte 
to dávkovaním kvapaliny. 
Ušetríte drahocenný čas 
a peniaze. Nezabudnite, 
aby ste neumývali okná na 
priamom slnku - prípravok 
vtedy príliš rýchlo vyschne 
a znemožní Vám správne 
umyť okná.

<h4>POZRITE, AKÝ JEDNODUCHÝ JE V POUŽITÍ:</h4>
na čistený povrch naneste 
malé množstvo a utrite 
suchou handričkou. 
						</div>
					</div><!--/product-details-->

				</div>
