
				<div class="col-sm-9 padding-right">
					<div class="product-details"><!--product-details-->
						<div class="col-sm-5">
							<div class="view-product">
								<img src="images/product/504007.jpg" alt="" />
								
							</div>
							

						</div>
						<div class="col-sm-7">
							<div class="product-information"><!--/product-information-->
								<!-- <img src="images/product-details/new.jpg" class="newarrival" alt="" /> -->
								<h2>UNIVERZÁLNY GEL</h2>
								<p>Symbol: 504007</p>
								
								<!-- <span>
									<span>US $59</span>
									<label>Quantity:</label>
									<input type="text" value="3" />
									<button type="button" class="btn btn-fefault cart">
										<i class="fa fa-shopping-cart"></i>
										Add to cart
									</button>
								</span> -->
								<p><b>1000 ml</b> In Stock</p>

								
							</div><!--/product-information-->

						</div>
						<div><br><br>
						<h2>Ako ušetriť čas na upratovaní?</h2>
						Ak chcete ušetriť čas na upratovaní, potrebujete vynikajúce multifunkčné čistiace prostriedky . 
Napríklad náš koncentrovaný univerzálny gél. Keď máte vždy po ruke 
UNIVERSAL GEL, 
jedným ťahom ruky sa vyporiadate s prachom a škvrnami, dokonca aj tými zaschnutými, 
odmastíte umyté plochy a jemne ich naleštíte. A vďaka prekrásnym francúzskym aromatickým 
olejom vytvoríte relaxačnú domácu atmosféru. S takým fantastickým gélom môžete konečne 
sedieť a relaxovať.

<h4>Prečo ho budete milovať:</h4>
pre štvornásobný účinok. Účinne čistí , 
odmasťuje, jemne leští  a jemne parfumuje 
umyté povrchy.   
  
<h4>Čo je naším tajomstvom:</h4>
vysoko koncentrovaná gélová formula = šetrí 
priestor, čas a peniaze.    

<h4>Na čo ho môžete použiť:</h4>
pre všetky umývateľné, kovové, MDF, 
vrstvené, plastové, keramické a linoleumové, 
terakotové a gresové povrchy. Oceníte to 
najmä pri umývaní veľkých plôch. <br>
 
<h4>Čo Vám poskytne dodatočnú bezpečnosť: </h4>
schválenie PZH (Národný Hygienický Ústav)

<h4> Čo tak krásne vonia:</h4>
šťavnaté citrusy, francúzska levanduľa, jazmín 
a čerstvé ozónové noty.

<h4>O čo sme sa ešte postarali:</h4>
v mnohých domácnosti ach 
ktoré poznáme chýba 
priestor na uskladnenie 
čisti acich prostriedkov, 
preto sme sa pokúsili tento 
problém vyriešiť pomocou 
účinných koncentrátov 
s multi funkčnými 
receptúrami. Teraz máte 
v jednom účinnom výrobku 
až 4 rôzne účinky. Šikovne 
sme to vymysleli, však? 

<h4>POZRITE, AKÝ JEDNODUCHÝ JE V POUŽITÍ:</h4>
rozpusti te 35 ml gélu v 5 l 
teplej vody. Umyte povrch 
s dobre vyžmýkaným 
mopom alebo handričkou 
a nechajte ho jednoducho 
vyschnúť (zriedený gél 
nevyžaduje opláchnutie). 
						</div>
					</div><!--/product-details-->

				</div>
