
				<div class="col-sm-9 padding-right">
					<div class="product-details"><!--product-details-->
						<div class="col-sm-5">
							<div class="view-product">
								<img src="images/product/504011.jpg" alt="" />
								
							</div>
							

						</div>
						<div class="col-sm-7">
							<div class="product-information"><!--/product-information-->
								<!-- <img src="images/product-details/new.jpg" class="newarrival" alt="" /> -->
								<h2>SPREJ NA UMÝVANIE OKIEN A ZRKADIEL</h2>
								<p>Symbol: 504011</p>
								
								<!-- <span>
									<span>US $59</span>
									<label>Quantity:</label>
									<input type="text" value="3" />
									<button type="button" class="btn btn-fefault cart">
										<i class="fa fa-shopping-cart"></i>
										Add to cart
									</button>
								</span> -->
								<p><b>500 ml</b> In Stock</p>

								
							</div><!--/product-information-->

						</div>
						<div><br><br>
						<h2>Ako to urobiť, aby okná boli krištáľovo čisté?</h2>
						Snívate o tom, ako sa bleskovo, účinne a bez námahy zbaviť nečistôt z okien, zrkadiel a iných 
sklenených povrchov? Skončite s časovo náročným umývaním a leštením, zabudnite na 
nepríjemné šmuhy. Teraz vyčistenie dokonca aj takých problematických miest môže byť 
potešením. Náš GLASS AND MIRROR SPRAY 
ľahko sa rozotiera po povrchu a bezpečným spôsobom odstraňuje všetky nečistoty, 
okrem iného mastnotu, prach, sadze a prach. Vďaka obsahu alkoholu sa rýchlo vyparuje, 
nezanecháva šmuhy a škvrny. Presvedčte sa, ako ľahko sa môžete starať o sklené povrchy 
vo Vašom dome a užite si ich dokonalú čistotu.

<h4>Prečo ho budete milovať:</h4>
pre krištáľovo čisté okná a zrkadlá, bez 
akejkoľvek šmuhy.   
  
<h4>Čo je naším tajomstvom:</h4>
sprej obsahuje prísady, ktoré dobre navlhčia 
čistený povrch a spájajú v sebe časti ce nečistôt 
čím spôsobia, že do niekoľkých sekúnd 
odstránite všetky nečistoty z okien a zrkadiel, 
vrátane nepríjemných stôp mastných rúk. 
Vďaka obsahu alkoholu sa veľmi rýchlo sa 
vyparuje z povrchu, nezanecháva šmuhy.   

<h4>Na čo ho môžete použiť:</h4>
na sklenené okenné tabule a zárubne, sklá 
automobilov, sklenené tabule v sprchovacích 
kabínach, prístrešky, zrkadlá, kryštály, sklenené 
ti enidlá. Na farebné sklo, tónované a farbené 
vrátane vitráží. Odporúčame ho takiež na 
plasty a plexisklo.<br>
 
<h4>O čo sme sa ešte postarali:</h4>
aby neobsahoval ani kvapku čpavku

<h4>Čo tak krásne vonia:</h4>
šťavnaté ovocie, kveti nové tóny a zmyselné 
pižmo.<br>

<h4>POZRITE, AKÝ JEDNODUCHÝ JE V POUŽITÍ:</h4>
na čistený povrch naneste 
malé množstvo (zo 
vzdialenosti  asi 15 cm) 
a utrite suchou handričkou.
Nikdy nenechávajte okennú 
tabuľu celkom vyschnúť.
						</div>
					</div><!--/product-details-->

				</div>
