
				<div class="col-sm-9 padding-right">
					<div class="product-details"><!--product-details-->
						<div class="col-sm-5">
							<div class="view-product">
								<img src="images/product/504009.jpg" alt="" />
								
							</div>
							

						</div>
						<div class="col-sm-7">
							<div class="product-information"><!--/product-information-->
								<!-- <img src="images/product-details/new.jpg" class="newarrival" alt="" /> -->
								<h2>SPREJ NA ČISTENIE OBRAZOVIEK A POVRCHOV Z OCELE INOX</h2>
								<p>Symbol: 504009</p>
								
								<!-- <span>
									<span>US $59</span>
									<label>Quantity:</label>
									<input type="text" value="3" />
									<button type="button" class="btn btn-fefault cart">
										<i class="fa fa-shopping-cart"></i>
										Add to cart
									</button>
								</span> -->
								<p><b>300 ml</b> In Stock</p>

								
							</div><!--/product-information-->

						</div>
						<div><br><br>
						<h2>Šmuhy a odtlačky prstov na obrazovkách?</h2>
						Šmuhy a odtlačky prstov na obrazovkách a zariadeniach vyrobených z nerezovej ocele nás 
môžu dráždiť nielen počas slnečného dňa . Objavujú sa náhle, už pri najmenšom dotyku. Kazia 
radosť zo sledovania fi lmov, sú chybou v čerstvo upratanom interiéri. Výnimočne nemáme 
radi, keď nám tieto maličkosti pokazia náladu, takže sme vytvorili ideálny 
SCREEN & INOX 
STEEL SMART SPRAY 
ktorý Vám tiež pomôže rýchlym a bezpečný spôsobom nielen vyčistiť, ale predovšetkým 
zabrániť opätovnému vzniku znečistení.

<h4>Prečo ho budete milovať:</h4>
nezanecháva stopy a šmuhy na čistených 
povrchoch.   
  
<h4>Na čo ho môžete použiť:</h4>
na počítačové monitory, tv obrazovky, plazmu, 
LCD, LED, displeje, vrátane ovládačov, 
mobilných telefónov a počítačových klávesníc. 
Tiež ho odporúčame pre čistenie zariadení 
vyrobený z ocele INOX. Môže byť použitý 
súčasne na matné a lesklé povrchy.   

<h4>Čo tak krásne vonia:</h4>
šťavnaté citrusy, jazmín, sladká vanilka, 
santalové drevo.<br>
 
<h4>Čo je naším tajomstvom:</h4>
sprej vytvára na vyčistenej ploche anti stati cký 
elektrostati cký povlak predchádzajúci 
opätovnému usadzovaniu sa prachu.


<h4>POZRITE, AKÝ JEDNODUCHÝ JE V POUŽITÍ:</h4>
naneste malé množstvo 
prípravku látkou 
mikrovlákna, potom 
prípravok rozveďte 
na čistenom povrchu. 
Nakoniec utrite do sucha 
a je to hotové.
						</div>
					</div><!--/product-details-->

				</div>
