
				<div class="col-sm-9 padding-right">
					<div class="product-details"><!--product-details-->
						<div class="col-sm-5">
							<div class="view-product">
								<img src="images/product/504005.jpg" alt="" />
								
							</div>
							

						</div>
						<div class="col-sm-7">
							<div class="product-information"><!--/product-information-->
								<!-- <img src="images/product-details/new.jpg" class="newarrival" alt="" /> -->
								<h2>GÉL NA ČISTENIE MEDZIER</h2>
								<p>Symbol: 504005</p>
								
								<!-- <span>
									<span>US $59</span>
									<label>Quantity:</label>
									<input type="text" value="3" />
									<button type="button" class="btn btn-fefault cart">
										<i class="fa fa-shopping-cart"></i>
										Add to cart
									</button>
								</span> -->
								<p><b>1000 ml</b> In Stock</p>

								
							</div><!--/product-information-->

						</div>
						<div><br><br>
						<h2>Ako vizuálne omladiť kúpeľňu?</h2>
						Vedeli ste, že starostlivé vyčistenie medzier môže omladiť interiér dokonca o niekoľko rokov? 
Takže ak máte rekonštrukciu svojho bytu v ďalších plánoch, začnite konať! Hustý gél 
GROUT CLEANER  
čistí, odmasťuje a krásne leští medzery, súčasne je jemný pre obkladačky, nie odfarbuje 
a nevyplachuje medzery. Po takomto osviežení obkladačky vyzerajú takmer ako novo 
položené.

<h4>Prečo ho budete milovať:</h4>
pre okázalý konečný výsledok.  
  
<h4>Na čo ho môžete použiť:</h4>
na biele spoje a farebné spoje pri glazúre, 
terakoty, gresy, mramor a mozaiky, na 
vonkajšie a vnútorné obkladačky na podlahe 
a na stene (vďaka hustej konzistencii gélu 
nesteká ihneď zo zvislých plôch).   

<h4>Postarali sme sa o to, že neobsahuje:</h4>
chlór a bielidlá.<br>
 
<h4>Čo tak krásne vonia:</h4>
kašmír, santalové drevo, ruža, kokosový 
a vanilkový krém.

<h4>POZRITE, AKÝ JEDNODUCHÝ JE V POUŽITÍ:</h4>
naneste gél rovnomerne 
na čistený povrch, počkajte 
niekoľko minút a utrite 
miesto špongiou alebo 
kefk  ou. Potom opláchnite 
vodou alebo pretrite vlhkou 
handričkou. 
						</div>
					</div><!--/product-details-->

				</div>
