
				<div class="col-sm-9 padding-right">
					<div class="product-details"><!--product-details-->
						<div class="col-sm-5">
							<div class="view-product">
								<img src="images/product/504006.jpg" alt="" />
								
							</div>
							

						</div>
						<div class="col-sm-7">
							<div class="product-information"><!--/product-information-->
								<!-- <img src="images/product-details/new.jpg" class="newarrival" alt="" /> -->
								<h2>GEL NA ČISTENIE GRILOV A RÚR NA PEČENIE</h2>
								<p>Symbol: 504006</p>
								
								<!-- <span>
									<span>US $59</span>
									<label>Quantity:</label>
									<input type="text" value="3" />
									<button type="button" class="btn btn-fefault cart">
										<i class="fa fa-shopping-cart"></i>
										Add to cart
									</button>
								</span> -->
								<p><b>500 ml</b> In Stock</p>

								
							</div><!--/product-information-->

						</div>
						<div><br><br>
						<h2>Ako zachrániť pripálenú panvicu?</h2>
						Spálená panvica? Pripálený hrniec? No, stáva sa to aj najlepším. To je dôvod, prečo máme tento 
mimoriadne efektívny 
GRILL & OVEN GEL 
Ľahko odstraňuje aj staré popáleniny a zadymenia, zaschnuté tuky a zvyšky jedál. Môžete ním 
bleskovo vyčistiť krbové sklo, grily, rošty a interiéry   rúr na pečenie.

<h4>Prečo ho budete milovať:</h4>
na zmenu defi nície pojmu „nečistota, ktorú 
nemožno odstrániť“. Odstraňuje dokonca to, 
čo sa zdalo byť neodstrániteľné.   
  
<h4>Čo Vás v ňom poteší:</h4>
hustá gélová konzistencia. Nesteká z čisteného 
povrchu, ale ju obklopuje a umožňuje 
účinkovať aktí vnym zložkám.    

<h4>Čo ním vyčistíte:</h4>
grily, rúry na pečenie, rošty, ražne, krbové sklo, 
vonkajšie povrchy panvíc a hrncov.<br>
 
<h4>Čo ním odstránite:</h4>
pripečený tuk, pripáleniny, odymenia, 
priškvareniny, sadze.

<h4>O čo sme sa ešte postarali:</h4>
o bezpečný uzáver.

<h4>Prečo je bez vône:</h4>
aby Vás nelákalo, aby ste ho voňali.

<h4>POZRITE, AKÝ JEDNODUCHÝ JE V POUŽITÍ:</h4>
aplikujte gél rovnomerne 
na čistený povrch, počkajte 
maximálne 15-20 minút 
a potom použite papierovú 
uti erku na zozbieranie 
nečistôt. Potom opláchnite 
čistou vodou a vytrite do 
sucha. 
						</div>
					</div><!--/product-details-->

				</div>
