
				<div class="col-sm-9 padding-right">
					<div class="product-details"><!--product-details-->
						<div class="col-sm-5">
							<div class="view-product">
								<img src="images/product/504008.jpg" alt="" />
								
							</div>
							

						</div>
						<div class="col-sm-7">
							<div class="product-information"><!--/product-information-->
								<!-- <img src="images/product-details/new.jpg" class="newarrival" alt="" /> -->
								<h2>PRÍPRAVOK NA SILNO ZNEČISTENÉ POVRCHY</h2>
								<p>Symbol: 504008</p>
								
								<!-- <span>
									<span>US $59</span>
									<label>Quantity:</label>
									<input type="text" value="3" />
									<button type="button" class="btn btn-fefault cart">
										<i class="fa fa-shopping-cart"></i>
										Add to cart
									</button>
								</span> -->
								<p><b>500 ml</b> In Stock</p>

								
							</div><!--/product-information-->

						</div>
						<div><br><br>
						<h2>Ako sa pripraviť na generálne upratovanie?</h2>
						Vďaka nášmu prípravku Vaše najbližšie okolie rýchlo poupratujete. 
DIRT BUSTER 
je to Vaša tajná zbraň so širokým použitím . Postaráte sa ním nielen o interiéry, ale aj 
o priestory okolo domu. Poupratujete altány, balkóny, garáže, vyčistíte fasády a upratujete 
domáce dielne. Postaráte sa o povrchový stav a odstránite všetky pretrvávajúce nečistoty.

<h4>Prečo ho budete milovať:</h4>
pre svoju silu a účinnosť. Odteraz, za chvíľu 
urobíte metamorfózu najbližšieho domáceho 
prostredia. Správnym dávkovaním prípravku 
prispôsobíte jeho výkon podľa svojich 
potrieb. Umývanie bude rýchlejšie a Vy bez 
námahy odstránite: mazivá, vosky, oleje, 
usadeniny, škvrny a nečistoty zo všetkých silne 
znečistených povrchov.   
  
<h4>O čo sme sa ešte postarali:</h4>
o ďalšie zložky znižujúce rýchlosť postupu 
korózie.   

<h4>Čo ním môžete umyť:</h4>
prakti cky všetko, nechránené a tvrdé povrchy: 
dlažobné kocky, terakotu, linoleum, dlaždice, 
strešné kryti ny, balkóny, terasy, kovové 
povrchy. Okrem toho ho môžete použiť na 
umývanie špinavého oblečenia a čalúnenia.<br>
 
<h4>Čo Vás v ňom poteší:</h4>
účinne odstraňuje nečistoty, dokonca 
aj v studenej vode.

<h4>Čo je naším tajomstvom:</h4>
formula 
extremely effective
spájajúca vlastnosti  umývania 
a odmasťovania. Prípravok môžete 
používať bez obáv na tvrdých 
povrchoch a odolných voči účinku 
alkalických činidiel.

<h4>POZRITE, AKÝ JEDNODUCHÝ JE V POUŽITÍ:</h4>
zrieďte správne množstvo 
prípravku vo vode (podľa 
pokynov na obale). Umyte 
povrch a nechajte ho 
vysušiť. Prípravok môžete 
použiť na umývanie povrchu 
alebo na ručné pranie.
						</div>
					</div><!--/product-details-->

				</div>
