
				<div class="col-sm-9 padding-right">
					<div class="product-details"><!--product-details-->
						<div class="col-sm-5">
							<div class="view-product">
								<img src="images/product/504003.jpg" alt="" />
								
							</div>
							

						</div>
						<div class="col-sm-7">
							<div class="product-information"><!--/product-information-->
								<!-- <img src="images/product-details/new.jpg" class="newarrival" alt="" /> -->
								<h2>PRÍPRAVOK NA UMÝVANIE DREVENÝCH PODLÁH A LAMINOVANÝCH PANELOV</h2>
								<p>Symbol: 504003</p>
								
								<!-- <span>
									<span>US $59</span>
									<label>Quantity:</label>
									<input type="text" value="3" />
									<button type="button" class="btn btn-fefault cart">
										<i class="fa fa-shopping-cart"></i>
										Add to cart
									</button>
								</span> -->
								<p><b>1000 ml</b> In Stock</p>

								
							</div><!--/product-information-->

						</div>
						<div><br><br>
						<h2>Je možné umyť drevenú podlahu prípravkom na panely?</h2>
						Naším prípravkom áno! Vytvorili sme jemný prípravok na umývanie 
HARDWOOD & LAMINATE 
FLOOR EXPERT 
na báze prírodného karnaubského vosku, ktorý je vhodný pre drevené podlahy a laminátové 
panely. Dokonale leští a chráni pred vlhkosťou. Silikónová emulzia utesňuje podlahu v spojoch 
a na malých medzerách, čím zabraňuje prieniku nečistôt a prachu. Vytvára neviditeľný povlak 
s protišmykovým efektom a chráni prirodzené farby vyčistených povrchov.

<h4>Prečo ho budete milovať:</h4>
pre dokonalú čistotu bez šmúh. Prípravok 
nielen umýva, ale aj chráni povrch pred ďalšími 
nečistotami. A nemusíte už nič zametať pod 
koberec.  
  
<h4>Čo Vás v ňom poteší:</h4>
univerzálnosť. Už nemusíte rozmýšľať, ktoré 
podlahy ním môžete umývať. Je ideálny 
súčasne pre lakované drevo, ako aj pre 
laminátové panely.   

<h4>Čo Vám poskytne dodatočnú bezpečnosť: </h4>
proti šmykový efekt. Doceníte ho ešte viac, 
ak sú vo Vašej domácnosti  malé deti , starší 
ľudia alebo ľudia s problémami s pohyblivosťou.<br>
 
<h4>Na čo ho môžete použiť:</h4>
na podlahy a povrchy z lakovaného dreva, 
obklady sti en, parkety, drevené schodiská 
a zábradlia, podlahové a stenové panely, 
povrchy podobné drevu. Ideálny pre všetky 
druhy dreva, aj pre exoti cké drevo. Môžete ho 
takti ež použiť aj na lakovaný korok.

<h4>Čo tak krásne vonia:</h4>
čerstvé kvety, sladká vanilka a zmyselná pačuli. 

<h4>POZRITE, AKÝ JEDNODUCHÝ JE V POUŽITÍ:</h4>
dobre povysávajte alebo 
pozametajte čistený povrch. 
35 ml kvapaliny rozpusti te 
v 5 litroch teplej vody 
a podlahu umyte dobre 
vyžmýkanou handričkou 
alebo odstredivým mopom. 
Vytrite do sucha alebo 
ponechajte vyschnúť. 
						</div>
					</div><!--/product-details-->

				</div>
