
				<div class="col-sm-9 padding-right">
					<div class="product-details"><!--product-details-->
						<div class="col-sm-5">
							<div class="view-product">
								<img src="images/product/504010.jpg" alt="" />
								
							</div>
							

						</div>
						<div class="col-sm-7">
							<div class="product-information"><!--/product-information-->
								<!-- <img src="images/product-details/new.jpg" class="newarrival" alt="" /> -->
								<h2>KRÉMOVÝ SPREJ PRE STAROSTLIVOSŤ O NÁBYTOK</h2>
								<p>Symbol: 504010</p>
								
								<!-- <span>
									<span>US $59</span>
									<label>Quantity:</label>
									<input type="text" value="3" />
									<button type="button" class="btn btn-fefault cart">
										<i class="fa fa-shopping-cart"></i>
										Add to cart
									</button>
								</span> -->
								<p><b>300 ml</b> In Stock</p>

								
							</div><!--/product-information-->

						</div>
						<div><br><br>
						<h2>Ako urobiť, aby nábytok absolvoval test bielej rukavice?</h2>
						Myslíte si, že prach na Vašom nábytku sa objaví takmer okamžite po upratovaní? To je možné, 
pretože drevené a laminované povrchy priťahujú prachové častice. Aby sme vyriešili tento 
problém raz a navždy, vytvorili sme 
FURNITURE CREAM SPRAY 
ktorý dokonale čistí a stará sa o čistené povrchy, chráni ich pred vlhkosťou a má antistatický 
účinok, čím zabraňuje opätovnému usadzovaniu prachu . Obsah avokádových a ryžových 
olejov, rovnako aj karnaubského vosku, zaručí Vášmu nábytku starostlivosť a dáva mu jemný 
lesk. A výnimočná kompozícia spôsobuje, že domov má príjemnú arómu ihličnatého lesa.

<h4>Prečo ho budete milovať:</h4>
za to, že spája výhody jemnej, krémovej 
emulzie a spreju pohodlného v používaní. Stačí 
len postriekať a utrieť povrch suchou, jemnou 
handričkou.  
  
<h4>Čo Vás v ňom poteší:</h4>
– pridanie prírodného karnaubského vosku 
a emulzie s avokádovým olejom a ryžovým 
olejom spôsobí, že Váš nábytok sa bude jemne 
lesknúť a jeho farba je obnovená. Zabudnite 
na šmuhy a škvrny!   

<h4>Čo ním vyčistíte:</h4>
drevený lakovaný nábytok, nábytok 
zabezpečený: starožitné, dyhované, 
voskované, olejované a vyrobené z drevu 
podobných materiálov (lamináty a dyha).<br>
 
<h4> Čo tak krásne vonia:</h4>
čerstvé ihličie sibírskych borovíc, zelený mach, 
ružové korenie a zmyselné pižmo.



						</div>
					</div><!--/product-details-->

				</div>
