
				<div class="col-sm-9 padding-right">
					<div class="product-details"><!--product-details-->
						<div class="col-sm-5">
							<div class="view-product">
								<img src="images/product/504004.jpg" alt="" />
								
							</div>
							

						</div>
						<div class="col-sm-7">
							<div class="product-information"><!--/product-information-->
								<!-- <img src="images/product-details/new.jpg" class="newarrival" alt="" /> -->
								<h2>ŠAMPÓN NA KOBERCE</h2>
								<p>Symbol: 504004</p>
								
								<!-- <span>
									<span>US $59</span>
									<label>Quantity:</label>
									<input type="text" value="3" />
									<button type="button" class="btn btn-fefault cart">
										<i class="fa fa-shopping-cart"></i>
										Add to cart
									</button>
								</span> -->
								<p><b>1000 ml</b> In Stock</p>

								
							</div><!--/product-information-->

						</div>
						<div><br><br>
						<h2>Ako dobre vyprať koberec?</h2>
						Ak chcete, aby Vaše koberce udržali čo najdlhšiu farbu a textúru, pravidelné vysávanie 
a pravidelné pranie nestačí. To je dôvod, prečo sme vytvorili unikátny 
CARPET SHAMPOO, 
 ktorý spája účinnosť pracieho tekutého prášku s kozmetikou pre starostlivosť o najjemnejšie 
štetiny. Hrubá, aktívna penová hmota preniká hlboko do vlákien a presne odstraňuje dokonca 
aj staré nečistoty. Obnovuje sviežosť, jemnosť a nadýchanosť kobercov. A doplnkovo chráni 
vlákna pred novou nečistotou.

<h4>Prečo ho budete milovať:</h4>
dobre vypratý koberec urobí Váš domov nielen 
pekným a útulným, ale vo vzduchu bude menej 
prachu a lepšie sa bude dýchať.  
  
<h4>Čo Vám poskytne dodatočnú bezpečnosť: </h4>
vonné oleje bez alergénov v súlade s normami 
IFRA (Internati onal Fragrance Associati on), 
čo je mimoriadne dôležité, keď sú vo Vašej 
domácnosti  malé deti  alebo domáce zvieratá.   

<h4>Na čo ho môžete použiť:</h4>
koberce z prírodných a synteti ckých vlákien, 
podlahové, nástenné a kúpeľňové koberce, 
podlahové kryti ny z prírodných a umelých 
vlákien, čalúnenie (takti ež v aute). Šampón je 
určený na ručné pranie.<br>
 
<h4>Čo tak krásne vonia:</h4>
šťavnaté citrusy, fi alkové listy, zmyselná vanilka 
a dubový mach.

<h4>POZRITE, AKÝ JEDNODUCHÝ JE V POUŽITÍ:</h4>
najprv starostlivo 
povysávajte koberec alebo 
čalúnenie. Rozpusti te 
150 ml (3 mierky) tekuti ny 
v 1 litri vody. Ponorte 
hubu do roztoku a vytlačte 
niekoľkokrát, aby ste 
vytvorili hustú penu. 
Rovnomerne naneste penu 
po povysávanom povrchu, 
a dávajte pozor, aby sa 
nebol príliš mokrý. Koberec 
ponechajte vyschnúť. 
Po vysušení sa šampón 
premení na prášok, ktorý je 
potrebné povysávať. 
						</div>
					</div><!--/product-details-->

				</div>
