
				
				<div class="col-sm-9 padding-right">
					<div class="features_items"><!--features_items-->
						<h2 class="title text-center">Parfémy Pánske</h2>
						<div class="col-sm-4">
							<div class="product-image-wrapper">
								<div class="single-products">
									<div class="productinfo text-center">
										<img src="images/product/perfumy_02.jpg" alt="" />
										<h2>#02</h2>
										<p>zelené jablko | škorica | olivovník</p>
										<a href="perfumy_101002_xsk.html" class="btn btn-default add-to-cart"><i class="fa fa-shopping-cart"></i>More Info</a>
									</div>
									<!-- <div class="product-overlay">
										<div class="overlay-content">
											<h2>$56</h2>
											<p>Easy Polo Black Edition</p>
											<a href="#" class="btn btn-default add-to-cart"><i class="fa fa-shopping-cart"></i>Add to cart</a>
										</div>
									</div> -->
								</div>
							</div>
						</div>
						
						<div class="col-sm-4">
							<div class="product-image-wrapper">
								<div class="single-products">
									<div class="productinfo text-center">
										<img src="images/product/perfumy_04.jpg" alt="" />
										<h2>#04</h2>
										<p>grapefruit | káva | čierne korenie</p>
										<a href="perfumy_101004_xsk.html" class="btn btn-default add-to-cart"><i class="fa fa-shopping-cart"></i>More Info</a>
									</div>
									<!-- <div class="product-overlay">
										<div class="overlay-content">
											<h2>$56</h2>
											<p>Easy Polo Black Edition</p>
											<a href="#" class="btn btn-default add-to-cart"><i class="fa fa-shopping-cart"></i>Add to cart</a>
										</div>
									</div> -->
								</div>
							</div>
						</div>
						
						<div class="col-sm-4">
							<div class="product-image-wrapper">
								<div class="single-products">
									<div class="productinfo text-center">
										<img src="images/product/perfumy_06.jpg" alt="" />
										<h2>#06</h2>
										<p>citrus | kumkvat | jalovec</p>
										<a href="perfumy_101006_xsk.html" class="btn btn-default add-to-cart"><i class="fa fa-shopping-cart"></i>More Info</a>
									</div>
									<!-- <div class="product-overlay">
										<div class="overlay-content">
											<h2>$56</h2>
											<p>Easy Polo Black Edition</p>
											<a href="#" class="btn btn-default add-to-cart"><i class="fa fa-shopping-cart"></i>Add to cart</a>
										</div>
									</div> -->
								</div>
							</div>
						</div>
						
						<div class="col-sm-4">
							<div class="product-image-wrapper">
								<div class="single-products">
									<div class="productinfo text-center">
										<img src="images/product/perfumy_08.jpg" alt="" />
										<h2>#08</h2>
										<p>morské noty | limeta | rezeda</p>
										<a href="perfumy_101008_xsk.html" class="btn btn-default add-to-cart"><i class="fa fa-shopping-cart"></i>More Info</a>
									</div>
									<!-- <div class="product-overlay">
										<div class="overlay-content">
											<h2>$56</h2>
											<p>Easy Polo Black Edition</p>
											<a href="#" class="btn btn-default add-to-cart"><i class="fa fa-shopping-cart"></i>Add to cart</a>
										</div>
									</div> -->
								</div>
							</div>
						</div>
						
						<div class="col-sm-4">
							<div class="product-image-wrapper">
								<div class="single-products">
									<div class="productinfo text-center">
										<img src="images/product/perfumy_10.jpg" alt="" />
										<h2>#10</h2>
										<p>mandarínka | zázvor | levanduľa</p>
										<a href="perfumy_101010_xsk.html" class="btn btn-default add-to-cart"><i class="fa fa-shopping-cart"></i>More Info</a>
									</div>
									<!-- <div class="product-overlay">
										<div class="overlay-content">
											<h2>$56</h2>
											<p>Easy Polo Black Edition</p>
											<a href="#" class="btn btn-default add-to-cart"><i class="fa fa-shopping-cart"></i>Add to cart</a>
										</div>
									</div> -->
								</div>
							</div>
						</div>
						

						
						<div class="col-sm-4">
							<div class="product-image-wrapper">
								<div class="single-products">
									<div class="productinfo text-center">
										<img src="images/product/perfumy_14.jpg" alt="" />
										<h2>#14</h2>
										<p>morské noty | pomaranč | céder</p>
										<a href="perfumy_101014_xsk.html" class="btn btn-default add-to-cart"><i class="fa fa-shopping-cart"></i>More Info</a>
									</div>
									<!-- <div class="product-overlay">
										<div class="overlay-content">
											<h2>$56</h2>
											<p>Easy Polo Black Edition</p>
											<a href="#" class="btn btn-default add-to-cart"><i class="fa fa-shopping-cart"></i>Add to cart</a>
										</div>
									</div> -->
								</div>
							</div>
						</div>
						
						<div class="col-sm-4">
							<div class="product-image-wrapper">
								<div class="single-products">
									<div class="productinfo text-center">
										<img src="images/product/perfumy_16.jpg" alt="" />
										<h2>#16</h2>
										<p>hruška | mäta | bazalka</p>
										<a href="perfumy_101016_xsk.html" class="btn btn-default add-to-cart"><i class="fa fa-shopping-cart"></i>More Info</a>
									</div>
									<!-- <div class="product-overlay">
										<div class="overlay-content">
											<h2>$56</h2>
											<p>Easy Polo Black Edition</p>
											<a href="#" class="btn btn-default add-to-cart"><i class="fa fa-shopping-cart"></i>Add to cart</a>
										</div>
									</div> -->
								</div>
							</div>
						</div>
						
						<div class="col-sm-4">
							<div class="product-image-wrapper">
								<div class="single-products">
									<div class="productinfo text-center">
										<img src="images/product/perfumy_18.jpg" alt="" />
										<h2>#18</h2>
										<p>káva | ružové korenie | tonkový bôb</p>
										<a href="perfumy_101018_xsk.html" class="btn btn-default add-to-cart"><i class="fa fa-shopping-cart"></i>More Info</a>
									</div>
									<!-- <div class="product-overlay">
										<div class="overlay-content">
											<h2>$56</h2>
											<p>Easy Polo Black Edition</p>
											<a href="#" class="btn btn-default add-to-cart"><i class="fa fa-shopping-cart"></i>Add to cart</a>
										</div>
									</div> -->
								</div>
							</div>
						</div>
						
						<div class="col-sm-4">
							<div class="product-image-wrapper">
								<div class="single-products">
									<div class="productinfo text-center">
										<img src="images/product/perfumy_20.jpg" alt="" />
										<h2>#20</h2>
										<p>škorica | ruža | noty kože</p>
										<a href="perfumy_101020_xsk.html" class="btn btn-default add-to-cart"><i class="fa fa-shopping-cart"></i>More Info</a>
									</div>
									<!-- <div class="product-overlay">
										<div class="overlay-content">
											<h2>$56</h2>
											<p>Easy Polo Black Edition</p>
											<a href="#" class="btn btn-default add-to-cart"><i class="fa fa-shopping-cart"></i>Add to cart</a>
										</div>
									</div> -->
								</div>
							</div>
						</div>
						<div class="col-sm-4">
							<div class="product-image-wrapper">
								<div class="single-products">
									<div class="productinfo text-center">
										<img src="images/product/perfumy_22.jpg" alt="" />
										<h2>#22</h2>
										<p>citrón | noty kože | jantár</p>
										<a href="perfumy_101022_xsk.html" class="btn btn-default add-to-cart"><i class="fa fa-shopping-cart"></i>More Info</a>
									</div>
									<!-- <div class="product-overlay">
										<div class="overlay-content">
											<h2>$56</h2>
											<p>Easy Polo Black Edition</p>
											<a href="#" class="btn btn-default add-to-cart"><i class="fa fa-shopping-cart"></i>Add to cart</a>
										</div>
									</div> -->
								</div>
							</div>
						</div>
						
						<div class="col-sm-4">
							<div class="product-image-wrapper">
								<div class="single-products">
									<div class="productinfo text-center">
										<img src="images/product/perfumy_26.jpg" alt="" />
										<h2>#26</h2>
										<p>agar | palisander | vanilka</p>
										<a href="perfumy_101026_xsk.html" class="btn btn-default add-to-cart"><i class="fa fa-shopping-cart"></i>More Info</a>
									</div>
									<!-- <div class="product-overlay">
										<div class="overlay-content">
											<h2>$56</h2>
											<p>Easy Polo Black Edition</p>
											<a href="#" class="btn btn-default add-to-cart"><i class="fa fa-shopping-cart"></i>Add to cart</a>
										</div>
									</div> -->
								</div>
							</div>
						</div>
						
						<div class="col-sm-4">
							<div class="product-image-wrapper">
								<div class="single-products">
									<div class="productinfo text-center">
										<img src="images/product/perfumy_28.jpg" alt="" />
										<h2>#28</h2>
										<p>bergamot | papája | muškátový oriešok</p>
										<a href="perfumy_101028_xsk.html" class="btn btn-default add-to-cart"><i class="fa fa-shopping-cart"></i>More Info</a>
									</div>
									<!-- <div class="product-overlay">
										<div class="overlay-content">
											<h2>$56</h2>
											<p>Easy Polo Black Edition</p>
											<a href="#" class="btn btn-default add-to-cart"><i class="fa fa-shopping-cart"></i>Add to cart</a>
										</div>
									</div> -->
								</div>
							</div>
						</div>
						
						<div class="col-sm-4">
							<div class="product-image-wrapper">
								<div class="single-products">
									<div class="productinfo text-center">
										<img src="images/product/perfumy_30.jpg" alt="" />
										<h2>#30</h2>
										<p>zelené jablko | škorica | olivovník</p>
										<a href="perfumy_101030_xsk.html" class="btn btn-default add-to-cart"><i class="fa fa-shopping-cart"></i>More Info</a>
									</div>
									<!-- <div class="product-overlay">
										<div class="overlay-content">
											<h2>$56</h2>
											<p>Easy Polo Black Edition</p>
											<a href="#" class="btn btn-default add-to-cart"><i class="fa fa-shopping-cart"></i>Add to cart</a>
										</div>
									</div> -->
								</div>
							</div>
						</div>
						
						<div class="col-sm-4">
							<div class="product-image-wrapper">
								<div class="single-products">
									<div class="productinfo text-center">
										<img src="images/product/perfumy_32.jpg" alt="" />
										<h2>#32</h2>
										<p>grapefruit | fi alka | noty kože</p>
										<a href="perfumy_101032_xsk.html" class="btn btn-default add-to-cart"><i class="fa fa-shopping-cart"></i>More Info</a>
									</div>
									<!-- <div class="product-overlay">
										<div class="overlay-content">
											<h2>$56</h2>
											<p>Easy Polo Black Edition</p>
											<a href="#" class="btn btn-default add-to-cart"><i class="fa fa-shopping-cart"></i>Add to cart</a>
										</div>
									</div> -->
								</div>
							</div>
						</div>
						
						<div class="col-sm-4">
							<div class="product-image-wrapper">
								<div class="single-products">
									<div class="productinfo text-center">
										<img src="images/product/perfumy_34.jpg" alt="" />
										<h2>#34</h2>
										<p>morská voda | bobkový list | mandarínka</p>
										<a href="perfumy_101034_xsk.html" class="btn btn-default add-to-cart"><i class="fa fa-shopping-cart"></i>More Info</a>
									</div>
									<!-- <div class="product-overlay">
										<div class="overlay-content">
											<h2>$56</h2>
											<p>Easy Polo Black Edition</p>
											<a href="#" class="btn btn-default add-to-cart"><i class="fa fa-shopping-cart"></i>Add to cart</a>
										</div>
									</div> -->
								</div>
							</div>
						</div>
						
						<div class="col-sm-4">
							<div class="product-image-wrapper">
								<div class="single-products">
									<div class="productinfo text-center">
										<img src="images/product/perfumy_36.jpg" alt="" />
										<h2>#36</h2>
										<p>zelené jablko | škorica | olivovník</p>
										<a href="perfumy_101036_xsk.html" class="btn btn-default add-to-cart"><i class="fa fa-shopping-cart"></i>More Info</a>
									</div>
									<!-- <div class="product-overlay">
										<div class="overlay-content">
											<h2>$56</h2>
											<p>Easy Polo Black Edition</p>
											<a href="#" class="btn btn-default add-to-cart"><i class="fa fa-shopping-cart"></i>Add to cart</a>
										</div>
									</div> -->
								</div>
							</div>
						</div>
						
						<div class="col-sm-4">
							<div class="product-image-wrapper">
								<div class="single-products">
									<div class="productinfo text-center">
										<img src="images/product/perfume_38.jpg" alt="" />
										<h2>#38</h2>
										<p>morská voda | bobkový list | mandarínka</p>
										<a href="perfumy_101038_xsk.html" class="btn btn-default add-to-cart"><i class="fa fa-shopping-cart"></i>More Info</a>
									</div>
									<!-- <div class="product-overlay">
										<div class="overlay-content">
											<h2>$56</h2>
											<p>Easy Polo Black Edition</p>
											<a href="#" class="btn btn-default add-to-cart"><i class="fa fa-shopping-cart"></i>Add to cart</a>
										</div>
									</div> -->
								</div>
							</div>
						</div>
						
						<div class="col-sm-4">
							<div class="product-image-wrapper">
								<div class="single-products">
									<div class="productinfo text-center">
										<img src="images/product/perfumy_40.jpg" alt="" />
										<h2>#40</h2>
										<p>pomaranč | vetiver | benzoín</p>
										<a href="perfumy_101040_xsk.html" class="btn btn-default add-to-cart"><i class="fa fa-shopping-cart"></i>More Info</a>
									</div>
									<!-- <div class="product-overlay">
										<div class="overlay-content">
											<h2>$56</h2>
											<p>Easy Polo Black Edition</p>
											<a href="#" class="btn btn-default add-to-cart"><i class="fa fa-shopping-cart"></i>Add to cart</a>
										</div>
									</div> -->
								</div>
							</div>
						</div>
						
						<div class="col-sm-4">
							<div class="product-image-wrapper">
								<div class="single-products">
									<div class="productinfo text-center">
										<img src="images/product/perfumy_42.jpg" alt="" />
										<h2>#42</h2>
										<p>bergamot | kadidlo | zázvor</p>
										<a href="perfumy_101042_xsk.html" class="btn btn-default add-to-cart"><i class="fa fa-shopping-cart"></i>More Info</a>
									</div>
									<!-- <div class="product-overlay">
										<div class="overlay-content">
											<h2>$56</h2>
											<p>Easy Polo Black Edition</p>
											<a href="#" class="btn btn-default add-to-cart"><i class="fa fa-shopping-cart"></i>Add to cart</a>
										</div>
									</div> -->
								</div>
							</div>
						</div>
						
						<div class="col-sm-4">
							<div class="product-image-wrapper">
								<div class="single-products">
									<div class="productinfo text-center">
										<img src="images/product/perfumy_44.jpg" alt="" />
										<h2>#44</h2>
										<p>čierne korenie | pačuli | ndrevité tóny</p>
										<a href="perfumy_1010044_xsk.html" class="btn btn-default add-to-cart"><i class="fa fa-shopping-cart"></i>More Info</a>
									</div>
									<!-- <div class="product-overlay">
										<div class="overlay-content">
											<h2>$56</h2>
											<p>Easy Polo Black Edition</p>
											<a href="#" class="btn btn-default add-to-cart"><i class="fa fa-shopping-cart"></i>Add to cart</a>
										</div>
									</div> -->
								</div>
							</div>
						</div>
						

						




						
						
<!--						<ul class="pagination">
							<li class="active"><a href="">1</a></li>
							<li><a href="">2</a></li>
							<li><a href="">3</a></li>
							<li><a href="">&raquo;</a></li>
						</ul> -->
					</div><!--features_items-->
							<ul class="pagination">
							<li class="active"><a href="">1</a></li>
							<li><a href="">2</a></li>
							<li><a href="">3</a></li>
							<li><a href="">&raquo;</a></li>
						</ul>
				</div>
