
				
				<div class="col-sm-9 padding-right">
					<div class="features_items"><!--features_items-->
						<h2 class="title text-center">Parfémy Dámske</h2>
						<div class="col-sm-4">
							<div class="product-image-wrapper">
								<div class="single-products">
									<div class="productinfo text-center">
										<img src="images/product/perfume_01.jpg" alt="" />
										<h2>#01</h2>
										<p>zelené jablko | magnólia | uhorky</p>
										<a href="perfumy_101001_xsk.html" class="btn btn-default add-to-cart"><i class="fa fa-shopping-cart"></i>More Info</a>
									</div>
									<!-- <div class="product-overlay">
										<div class="overlay-content">
											<h2>$56</h2>
											<p>Easy Polo Black Edition</p>
											<a href="#" class="btn btn-default add-to-cart"><i class="fa fa-shopping-cart"></i>Add to cart</a>
										</div>
									</div> -->
								</div>
							</div>
						</div>
						
						<div class="col-sm-4">
							<div class="product-image-wrapper">
								<div class="single-products">
									<div class="productinfo text-center">
										<img src="images/product/perfume_03.jpg" alt="" />
										<h2>#03</h2>
										<p>ruža | pomaranč | pačula</p>
										<a href="perfumy_101003_xsk.html" class="btn btn-default add-to-cart"><i class="fa fa-shopping-cart"></i>More Info</a>
									</div>
									<!-- <div class="product-overlay">
										<div class="overlay-content">
											<h2>$56</h2>
											<p>Easy Polo Black Edition</p>
											<a href="#" class="btn btn-default add-to-cart"><i class="fa fa-shopping-cart"></i>Add to cart</a>
										</div>
									</div> -->
								</div>
							</div>
						</div>
						
						<div class="col-sm-4">
							<div class="product-image-wrapper">
								<div class="single-products">
									<div class="productinfo text-center">
										<img src="images/product/perfume_05.jpg" alt="" />
										<h2>#05</h2>
										<p>vanilková | kosatec | pižmo</p>
										<a href="perfumy_101005_xsk.html" class="btn btn-default add-to-cart"><i class="fa fa-shopping-cart"></i>More Info</a>
									</div>
									<!-- <div class="product-overlay">
										<div class="overlay-content">
											<h2>$56</h2>
											<p>Easy Polo Black Edition</p>
											<a href="#" class="btn btn-default add-to-cart"><i class="fa fa-shopping-cart"></i>Add to cart</a>
										</div>
									</div> -->
								</div>
							</div>
						</div>
						
						<div class="col-sm-4">
							<div class="product-image-wrapper">
								<div class="single-products">
									<div class="productinfo text-center">
										<img src="images/product/perfume_07.jpg" alt="" />
										<h2>#07</h2>
										<p>vanilka | hruška | čokoládky</p>
										<a href="perfumy_101007_xsk.html" class="btn btn-default add-to-cart"><i class="fa fa-shopping-cart"></i>More Info</a>
									</div>
									<!-- <div class="product-overlay">
										<div class="overlay-content">
											<h2>$56</h2>
											<p>Easy Polo Black Edition</p>
											<a href="#" class="btn btn-default add-to-cart"><i class="fa fa-shopping-cart"></i>Add to cart</a>
										</div>
									</div> -->
								</div>
							</div>
						</div>
						
						<div class="col-sm-4">
							<div class="product-image-wrapper">
								<div class="single-products">
									<div class="productinfo text-center">
										<img src="images/product/perfumy_09.jpg" alt="" />
										<h2>#9</h2>
										<p>karamel | melón | cukrová vata</p>
										<a href="perfumy_101009_xsk.html" class="btn btn-default add-to-cart"><i class="fa fa-shopping-cart"></i>More Info</a>
									</div>
									<!-- <div class="product-overlay">
										<div class="overlay-content">
											<h2>$56</h2>
											<p>Easy Polo Black Edition</p>
											<a href="#" class="btn btn-default add-to-cart"><i class="fa fa-shopping-cart"></i>Add to cart</a>
										</div>
									</div> -->
								</div>
							</div>
						</div>
						
						<div class="col-sm-4">
							<div class="product-image-wrapper">
								<div class="single-products">
									<div class="productinfo text-center">
										<img src="images/product/perfume_11.jpg" alt="" />
										<h2>#11</h2>
										<p>orchidea | čajové listy | bergamot</p>
										<a href="perfumy_101011_xsk.html" class="btn btn-default add-to-cart"><i class="fa fa-shopping-cart"></i>More Info</a>
									</div>
									<!-- <div class="product-overlay">
										<div class="overlay-content">
											<h2>$56</h2>
											<p>Easy Polo Black Edition</p>
											<a href="#" class="btn btn-default add-to-cart"><i class="fa fa-shopping-cart"></i>Add to cart</a>
										</div>
									</div> -->
								</div>
							</div>
						</div>
						
						<div class="col-sm-4">
							<div class="product-image-wrapper">
								<div class="single-products">
									<div class="productinfo text-center">
										<img src="images/product/perfumy_13.jpg" alt="" />
										<h2>#13</h2>
										<p>horký pomaranč | med | zázvor</p>
										<a href="perfumy_101013_xsk.html" class="btn btn-default add-to-cart"><i class="fa fa-shopping-cart"></i>More Info</a>
									</div>
									<!-- <div class="product-overlay">
										<div class="overlay-content">
											<h2>$56</h2>
											<p>Easy Polo Black Edition</p>
											<a href="#" class="btn btn-default add-to-cart"><i class="fa fa-shopping-cart"></i>Add to cart</a>
										</div>
									</div> -->
								</div>
							</div>
						</div>
						
						<div class="col-sm-4">
							<div class="product-image-wrapper">
								<div class="single-products">
									<div class="productinfo text-center">
										<img src="images/product/perfumy_15.jpg" alt="" />
										<h2>#15</h2>
										<p>jahoda | višňa | karamel</p>
										<a href="perfumy_101015_xsk.html" class="btn btn-default add-to-cart"><i class="fa fa-shopping-cart"></i>More Info</a>
									</div>
									<!-- <div class="product-overlay">
										<div class="overlay-content">
											<h2>$56</h2>
											<p>Easy Polo Black Edition</p>
											<a href="#" class="btn btn-default add-to-cart"><i class="fa fa-shopping-cart"></i>Add to cart</a>
										</div>
									</div> -->
								</div>
							</div>
						</div>
						
						<div class="col-sm-4">
							<div class="product-image-wrapper">
								<div class="single-products">
									<div class="productinfo text-center">
										<img src="images/product/perfumy_17.jpg" alt="" />
										<h2>#17</h2>
										<p>malina | jazmín | med</p>
										<a href="perfumy_101017_xsk.html" class="btn btn-default add-to-cart"><i class="fa fa-shopping-cart"></i>More Info</a>
									</div>
									<!-- <div class="product-overlay">
										<div class="overlay-content">
											<h2>$56</h2>
											<p>Easy Polo Black Edition</p>
											<a href="#" class="btn btn-default add-to-cart"><i class="fa fa-shopping-cart"></i>Add to cart</a>
										</div>
									</div> -->
								</div>
							</div>
						</div>
						
						<div class="col-sm-4">
							<div class="product-image-wrapper">
								<div class="single-products">
									<div class="productinfo text-center">
										<img src="images/product/perfumy_19.jpg" alt="" />
										<h2>#19</h2>
										<p>jazmín | céder | melón</p>
										<a href="perfumy_101019_xsk.html" class="btn btn-default add-to-cart"><i class="fa fa-shopping-cart"></i>More Info</a>
									</div>
									<!-- <div class="product-overlay">
										<div class="overlay-content">
											<h2>$56</h2>
											<p>Easy Polo Black Edition</p>
											<a href="#" class="btn btn-default add-to-cart"><i class="fa fa-shopping-cart"></i>Add to cart</a>
										</div>
									</div> -->
								</div>
							</div>
						</div>
						<div class="col-sm-4">
							<div class="product-image-wrapper">
								<div class="single-products">
									<div class="productinfo text-center">
										<img src="images/product/perfumy_21.jpg" alt="" />
										<h2>#21</h2>
										<p>pomarančový kvet | santalový strom | pižmo</p>
										<a href="perfumy_101021_xsk.html" class="btn btn-default add-to-cart"><i class="fa fa-shopping-cart"></i>More Info</a>
									</div>
									<!-- <div class="product-overlay">
										<div class="overlay-content">
											<h2>$56</h2>
											<p>Easy Polo Black Edition</p>
											<a href="#" class="btn btn-default add-to-cart"><i class="fa fa-shopping-cart"></i>Add to cart</a>
										</div>
									</div> -->
								</div>
							</div>
						</div>
						
						<div class="col-sm-4">
							<div class="product-image-wrapper">
								<div class="single-products">
									<div class="productinfo text-center">
										<img src="images/product/perfumy_23.jpg" alt="" />
										<h2>#23</h2>
										<p>ruža | pačula | ambrózia</p>
										<a href="perfumy_101023_xsk.html" class="btn btn-default add-to-cart"><i class="fa fa-shopping-cart"></i>More Info</a>
									</div>
									<!-- <div class="product-overlay">
										<div class="overlay-content">
											<h2>$56</h2>
											<p>Easy Polo Black Edition</p>
											<a href="#" class="btn btn-default add-to-cart"><i class="fa fa-shopping-cart"></i>Add to cart</a>
										</div>
									</div> -->
								</div>
							</div>
						</div>
						
						<div class="col-sm-4">
							<div class="product-image-wrapper">
								<div class="single-products">
									<div class="productinfo text-center">
										<img src="images/product/perfumy_25.jpg" alt="" />
										<h2>#25</h2>
										<p>zelené jablko | škorica | olivovník</p>
										<a href="perfumy_101025_xsk.html" class="btn btn-default add-to-cart"><i class="fa fa-shopping-cart"></i>More Info</a>
									</div>
									<!-- <div class="product-overlay">
										<div class="overlay-content">
											<h2>$56</h2>
											<p>Easy Polo Black Edition</p>
											<a href="#" class="btn btn-default add-to-cart"><i class="fa fa-shopping-cart"></i>Add to cart</a>
										</div>
									</div> -->
								</div>
							</div>
						</div>
						
						<div class="col-sm-4">
							<div class="product-image-wrapper">
								<div class="single-products">
									<div class="productinfo text-center">
										<img src="images/product/perfumy_27.jpg" alt="" />
										<h2>#27</h2>
										<p>malina | jazmín | med</p>
										<a href="perfumy_101027_xsk.html" class="btn btn-default add-to-cart"><i class="fa fa-shopping-cart"></i>More Info</a>
									</div>
									<!-- <div class="product-overlay">
										<div class="overlay-content">
											<h2>$56</h2>
											<p>Easy Polo Black Edition</p>
											<a href="#" class="btn btn-default add-to-cart"><i class="fa fa-shopping-cart"></i>Add to cart</a>
										</div>
									</div> -->
								</div>
							</div>
						</div>
						
						<div class="col-sm-4">
							<div class="product-image-wrapper">
								<div class="single-products">
									<div class="productinfo text-center">
										<img src="images/product/perfumy_29.jpg" alt="" />
										<h2>#29</h2>
										<p>liči | broskyňa | pižmo</p>
										<a href="perfumy_101029_xsk.html" class="btn btn-default add-to-cart"><i class="fa fa-shopping-cart"></i>More Info</a>
									</div>
									<!-- <div class="product-overlay">
										<div class="overlay-content">
											<h2>$56</h2>
											<p>Easy Polo Black Edition</p>
											<a href="#" class="btn btn-default add-to-cart"><i class="fa fa-shopping-cart"></i>Add to cart</a>
										</div>
									</div> -->
								</div>
							</div>
						</div>
						
						<div class="col-sm-4">
							<div class="product-image-wrapper">
								<div class="single-products">
									<div class="productinfo text-center">
										<img src="images/product/perfumy_31.jpg" alt="" />
										<h2>#31</h2>
										<p>pivonia | ruža | ružové korenie</p>
										<a href="perfumy_101031_xsk.html" class="btn btn-default add-to-cart"><i class="fa fa-shopping-cart"></i>More Info</a>
									</div>
									<!-- <div class="product-overlay">
										<div class="overlay-content">
											<h2>$56</h2>
											<p>Easy Polo Black Edition</p>
											<a href="#" class="btn btn-default add-to-cart"><i class="fa fa-shopping-cart"></i>Add to cart</a>
										</div>
									</div> -->
								</div>
							</div>
						</div>
						
						<div class="col-sm-4">
							<div class="product-image-wrapper">
								<div class="single-products">
									<div class="productinfo text-center">
										<img src="images/product/perfumy_33.jpg" alt="" />
										<h2>#33</h2>
										<p>frézia | ruža | pačula</p>
										<a href="perfumy_101033_xsk.html" class="btn btn-default add-to-cart"><i class="fa fa-shopping-cart"></i>More Info</a>
									</div>
									<!-- <div class="product-overlay">
										<div class="overlay-content">
											<h2>$56</h2>
											<p>Easy Polo Black Edition</p>
											<a href="#" class="btn btn-default add-to-cart"><i class="fa fa-shopping-cart"></i>Add to cart</a>
										</div>
									</div> -->
								</div>
							</div>
						</div>
						
						<div class="col-sm-4">
							<div class="product-image-wrapper">
								<div class="single-products">
									<div class="productinfo text-center">
										<img src="images/product/perfumy_35.jpg" alt="" />
										<h2>#35</h2>
										<p>fréza | santalového dreva</p>
										<a href="perfumy_101035_xsk.html" class="btn btn-default add-to-cart"><i class="fa fa-shopping-cart"></i>More Info</a>
									</div>
									<!-- <div class="product-overlay">
										<div class="overlay-content">
											<h2>$56</h2>
											<p>Easy Polo Black Edition</p>
											<a href="#" class="btn btn-default add-to-cart"><i class="fa fa-shopping-cart"></i>Add to cart</a>
										</div>
									</div> -->
								</div>
							</div>
						</div>
						
						<div class="col-sm-4">
							<div class="product-image-wrapper">
								<div class="single-products">
									<div class="productinfo text-center">
										<img src="images/product/perfumy_37.jpg" alt="" />
										<h2>#37</h2>
										<p>granátové jablko | orchidea | mahagón</p>
										<a href="perfumy_101037_xsk.html" class="btn btn-default add-to-cart"><i class="fa fa-shopping-cart"></i>More Info</a>
									</div>
									<!-- <div class="product-overlay">
										<div class="overlay-content">
											<h2>$56</h2>
											<p>Easy Polo Black Edition</p>
											<a href="#" class="btn btn-default add-to-cart"><i class="fa fa-shopping-cart"></i>Add to cart</a>
										</div>
									</div> -->
								</div>
							</div>
						</div>
						
						<div class="col-sm-4">
							<div class="product-image-wrapper">
								<div class="single-products">
									<div class="productinfo text-center">
										<img src="images/product/perfumy_39.jpg" alt="" />
										<h2>#39</h2>
										<p>citrón | zelené jablko | bambus</p>
										<a href="perfumy_101039_xsk.html" class="btn btn-default add-to-cart"><i class="fa fa-shopping-cart"></i>More Info</a>
									</div>
									<!-- <div class="product-overlay">
										<div class="overlay-content">
											<h2>$56</h2>
											<p>Easy Polo Black Edition</p>
											<a href="#" class="btn btn-default add-to-cart"><i class="fa fa-shopping-cart"></i>Add to cart</a>
										</div>
									</div> -->
								</div>
							</div>
						</div>
						
						<div class="col-sm-4">
							<div class="product-image-wrapper">
								<div class="single-products">
									<div class="productinfo text-center">
										<img src="images/product/perfumy_41.jpg" alt="" />
										<h2>#41</h2>
										<p>zelený čaj | citrón | dubový mach</p>
										<a href="perfumy_101041_xsk.html" class="btn btn-default add-to-cart"><i class="fa fa-shopping-cart"></i>More Info</a>
									</div>
									<!-- <div class="product-overlay">
										<div class="overlay-content">
											<h2>$56</h2>
											<p>Easy Polo Black Edition</p>
											<a href="#" class="btn btn-default add-to-cart"><i class="fa fa-shopping-cart"></i>Add to cart</a>
										</div>
									</div> -->
								</div>
							</div>
						</div>
						
						
						<div class="col-sm-4">
							<div class="product-image-wrapper">
								<div class="single-products">
									<div class="productinfo text-center">
										<img src="images/product/perfumy_45.jpg" alt="" />
										<h2>#45</h2>
										<p>broskyňa | ruža | frézia</p>
										<a href="perfumy_101045_xsk.html" class="btn btn-default add-to-cart"><i class="fa fa-shopping-cart"></i>More Info</a>
									</div>
									<!-- <div class="product-overlay">
										<div class="overlay-content">
											<h2>$56</h2>
											<p>Easy Polo Black Edition</p>
											<a href="#" class="btn btn-default add-to-cart"><i class="fa fa-shopping-cart"></i>Add to cart</a>
										</div>
									</div> -->
								</div>
							</div>
						</div>
						

						
						<div class="col-sm-4">
							<div class="product-image-wrapper">
								<div class="single-products">
									<div class="productinfo text-center">
										<img src="images/product/perfumy_49.jpg" alt="" />
										<h2>#49</h2>
										<p>zelené jablko | škorica | olivovník</p>
										<a href="perfumy_101049_xsk.html" class="btn btn-default add-to-cart"><i class="fa fa-shopping-cart"></i>More Info</a>
									</div>
									<!-- <div class="product-overlay">
										<div class="overlay-content">
											<h2>$56</h2>
											<p>Easy Polo Black Edition</p>
											<a href="#" class="btn btn-default add-to-cart"><i class="fa fa-shopping-cart"></i>Add to cart</a>
										</div>
									</div> -->
								</div>
							</div>
						</div>



						
						
<!--						<ul class="pagination">
							<li class="active"><a href="">1</a></li>
							<li><a href="">2</a></li>
							<li><a href="">3</a></li>
							<li><a href="">&raquo;</a></li>
						</ul> -->
					</div><!--features_items-->
							<ul class="pagination">
							<li class="active"><a href="">1</a></li>
							<li><a href="">2</a></li>
							<li><a href="">3</a></li>
							<li><a href="">&raquo;</a></li>
						</ul>
				</div>
