
				<div class="col-sm-9 padding-right">
					<div class="product-details"><!--product-details-->
						<div class="col-sm-5">
							<div class="view-product">
								<img src="images/product/perfume_11.jpg" alt="" />
								
							</div>
							

						</div>
						<div class="col-sm-7">
							<div class="product-information"><!--/product-information-->
								<!-- <img src="images/product-details/new.jpg" class="newarrival" alt="" /> -->
								<h2>Perfume Woman #11</h2><p>orchid - tea leaves - bergamot</p>
								<p>Product code: 101011</p>
								<p>Fragrance concetration: 20%</p>
								<!-- <span>
									<span>US $59</span>
									<label>Quantity:</label>
									<input type="text" value="3" />
									<button type="button" class="btn btn-fefault cart">
										<i class="fa fa-shopping-cart"></i>
										Add to cart
									</button>
								</span> -->
								<p><b>50 ml</b> In Stock</p>

								
							</div><!--/product-information-->

						</div>
						<div><br><br>
						<h2>Why you’ll love it:</h2>
						for the sweet-tea infatuation. This perfume is unaffected and natural, yet you cannot stop thinking about it...
<br> <br>
<h4>Family: <i>oriental floral</i></h4> 
<h4>Perception: <i>tea, sweet</i></h4>
<h4>Projection: <i>moderate</i></h4>
<h4>Category: <i>business</i></h4> 
<h4>Fragrance architecture:
<br><i>Head note: bergamot, osmanthus, tea leaves</i>
<br><i>Heart note: Provence rose, freesia, orchid, jasmine</i>
<br><i>Base note: musk, patchouli</i></h4>



						</div>
					</div><!--/product-details-->
					
					
					
					
					
				</div>
