			<div class="col-sm-9 padding-right">
					<div class="product-details"><!--product-details-->
						<div class="col-sm-5">
							<div class="view-product">
								<img src="images/product/perfumy_65.jpg" alt="" />
								
							</div>
							

						</div>
						<div class="col-sm-7">
							<div class="product-information"><!--/product-information-->
								<img src="images/product-details/new.jpg" class="newarrival" alt="" /> 
								<h2>Perfume Woman #65</h2><p>bergamot, citrus, cedar</p>
								<p>Product code: 101065</p>
								<p>Fragrance concetration: 20%</p>
								<!-- <span>
									<span>US $59</span>
									<label>Quantity:</label>
									<input type="text" value="3" />
									<button type="button" class="btn btn-fefault cart">
										<i class="fa fa-shopping-cart"></i>
										Add to cart
									</button>
								</span> -->
								<p><b>50 ml</b> In Stock</p>

								
							</div><!--/product-information-->

						</div>
						<div><br><br>
<h2>Why you’ll love it:</h2>
for an immediate surge of energy. Perfectly balanced, citrus fragrance with expressive notes of olive tree and cedar will make you feel like you're on a Greek island.
<br> <br>
<h4>Family: <i>wood-floral</i></h4> 
<h4>Perception: <i>citrus, woody</i></h4>
<h4>Projection: <i>moderate</i></h4>
<h4>Category: <i>casual</i></h4> 
<h4>Fragrance architecture:
<br><i>Head note: bergamot, fig, green tangerine, citrus, pear</i>
<br><i>Heart note: lily, jasmine, cardamom, narcissus</i>
<br><i>Base note: sandalwood, cedar, olive tree, musk</i></h4>



						</div>
					</div><!--/product-details-->

				</div>
