
				<div class="col-sm-9 padding-right">
					<div class="product-details"><!--product-details-->
						<div class="col-sm-5">
							<div class="view-product">
								<img src="images/product/perfumy_44.jpg" alt="" />
								
							</div>
							

						</div>
						<div class="col-sm-7">
							<div class="product-information"><!--/product-information-->
								<!-- <img src="images/product-details/new.jpg" class="newarrival" alt="" /> --> 
								<h2>Perfume Man #44</h2><p>seaweed - orange - cotton blossom</p>
								<p>Product code: 101044</p>
								<p>Fragrance concetration: 20%</p>
								<!-- <span>
									<span>US $59</span>
									<label>Quantity:</label>
									<input type="text" value="3" />
									<button type="button" class="btn btn-fefault cart">
										<i class="fa fa-shopping-cart"></i>
										Add to cart
									</button>
								</span> -->
								<p><b>50 ml</b> In Stock</p>

								
							</div><!--/product-information-->

						</div>
						<div><br><br>
<h2>What will seduce you:</h2>
a wave of refreshment. This expressive, multidimensional fragrance has been created for a modern man who is confident and desires freedom and challenge. It is a stimulating feeling of pleasant freshness wrapped in an intriguing aroma of incense.
<br> <br>
<h4>Family: <i>wood-spice</i></h4> 
<h4>Perception: <i>fresh, green</i></h4>
<h4>Projection: <i>moderate</i></h4>
<h4>Category: <i>sport</i></h4> 
<h4>Fragrance architecture:
<br><i>Head note: bergamot, incense</i>
<br><i>Heart note: violet, lavender, ginger</i>
<br><i>Base note: cedar</i></h4>



						</div>
					</div><!--/product-details-->

				</div>
