
				<div class="col-sm-9 padding-right">
					<div class="product-details"><!--product-details-->
						<div class="col-sm-5">
							<div class="view-product">
								<img src="images/product/perfumy_59.jpg" alt="" />
								
							</div>
							

						</div>
						<div class="col-sm-7">
							<div class="product-information"><!--/product-information-->
								<!-- <img src="images/product-details/new.jpg" class="newarrival" alt="" /> --> 
								<h2>Perfume Woman #59</h2><p>orange - vanilla - blackcurrant</p>
								<p>Product code: 101059</p>
								<p>Fragrance concetration: 20%</p>
								<!-- <span>
									<span>US $59</span>
									<label>Quantity:</label>
									<input type="text" value="3" />
									<button type="button" class="btn btn-fefault cart">
										<i class="fa fa-shopping-cart"></i>
										Add to cart
									</button>
								</span> -->
								<p><b>50 ml</b> In Stock</p>

								
							</div><!--/product-information-->

						</div>
						<div><br><br>
<h2>Why you’ll love it:</h2>
for its natural seductiveness. Be careful, it’s a true love potion. Rose, apricot, vanilla and fresh citrus fruit will steal both your heart and his.
<br> <br>
<h4>Family: <i>floral and fruity</i></h4> 
<h4>Perception: <i>citrus, spicy</i></h4>
<h4>Projection: <i>moderate</i></h4>
<h4>Category: <i>romance</i></h4> 
<h4>Fragrance architecture:
<br><i>Head note: black currant, orang, tangerine</i>
<br><i>Heart note: apricot, rose, lily of the valley</i>
<br><i>Base note: ambergris, cedar, vanilla</i></h4>



						</div>
					</div><!--/product-details-->
	
				</div>
