
				<div class="col-sm-9 padding-right">
					<div class="product-details"><!--product-details-->
						<div class="col-sm-5">
							<div class="view-product">
								<img src="images/product/perfumy_31.jpg" alt="" />
								
							</div>
							

						</div>
						<div class="col-sm-7">
							<div class="product-information"><!--/product-information-->
								<!-- <img src="images/product-details/new.jpg" class="newarrival" alt="" /> --> 
								<h2>Perfume Woman #31</h2><p>peony - rose - pink pepper </p>
								<p>Product code: 101031</p>
								<p>Fragrance concetration: 20%</p>
								<!-- <span>
									<span>US $59</span>
									<label>Quantity:</label>
									<input type="text" value="3" />
									<button type="button" class="btn btn-fefault cart">
										<i class="fa fa-shopping-cart"></i>
										Add to cart
									</button>
								</span> -->
								<p><b>50 ml</b> In Stock</p>

								
							</div><!--/product-information-->

						</div>
						<div><br><br>
<h2>Why you’ll love it:</h2>
for its subtlety and natural character. A fresh, pleasant scent, infused with the sweetness of roses and peonies, with a hint of spicy rosepepper.
<br> <br>
<h4>Family: <i>floral and fruity</i></h4> 
<h4>Perception: <i>fresh, rosy</i></h4>
<h4>Projection: <i>subtle</i></h4>
<h4>Category: <i>business</i></h4> 
<h4>Fragrance architecture:
<br><i>Head note: tangerine, peony</i>
<br><i>Heart note: rose, osmanthus</i>
<br><i>Base note: red pepper, sandalwood, patchouli</i></h4>



						</div>
					</div><!--/product-details-->

				</div>
