
				<div class="col-sm-9 padding-right">
					<div class="product-details"><!--product-details-->
						<div class="col-sm-5">
							<div class="view-product">
								<img src="images/product/perfumy_26.jpg" alt="" />
								
							</div>
							

						</div>
						<div class="col-sm-7">
							<div class="product-information"><!--/product-information-->
								<!-- <img src="images/product-details/new.jpg" class="newarrival" alt="" /> -->
								<h2>Perfume Man #26</h2><p>agar - rosewood - vanilla</p>
								<p>Product code: 101026</p>
								<p>Fragrance concetration: 20%</p>
								<!-- <span>
									<span>US $59</span>
									<label>Quantity:</label>
									<input type="text" value="3" />
									<button type="button" class="btn btn-fefault cart">
										<i class="fa fa-shopping-cart"></i>
										Add to cart
									</button>
								</span> -->
								<p><b>50 ml</b> In Stock</p>

								
							</div><!--/product-information-->

						</div>
						<div><br><br>
<h2>What will seduce you:</h2>
the depth of oud. Refined, sensual composition starring precious agar wood. The elegant background of the perfume is filled with rosewood, vanilla and sandalwood.
<br> <br>
<h4>Family: <i>oriental woody</i></h4> 
<h4>Perception: <i>warm, agar</i></h4>
<h4>Projection: <i>strong</i></h4>
<h4>Category: <i>prestige</i></h4> 
<h4>Fragrance architecture:
<br><i>Head note: agar, rosewood</i>
<br><i>Heart note: vanilla, cardamom, sandalwood</i>
<br><i>Base note: vetiver, tonka beans</i></h4>



						</div>
					</div><!--/product-details-->

				</div>
