
				<div class="col-sm-9 padding-right">
					<div class="product-details"><!--product-details-->
						<div class="col-sm-5">
							<div class="view-product">
								<img src="images/product/perfumy_40.jpg" alt="" />
								
							</div>
							

						</div>
						<div class="col-sm-7">
							<div class="product-information"><!--/product-information-->
								<!-- <img src="images/product-details/new.jpg" class="newarrival" alt="" /> --> 
								<h2>Perfume Man #40</h2><p>orange - vetiver - benzoin</p>
								<p>Product code: 101040</p>
								<p>Fragrance concetration: 20%</p>
								<!-- <span>
									<span>US $59</span>
									<label>Quantity:</label>
									<input type="text" value="3" />
									<button type="button" class="btn btn-fefault cart">
										<i class="fa fa-shopping-cart"></i>
										Add to cart
									</button>
								</span> -->
								<p><b>50 ml</b> In Stock</p>

								
							</div><!--/product-information-->

						</div>
						<div><br><br>
<h2>What will seduce you:</h2>
unconventionality. The original, smoky and citrus aroma is seductive, enchanting and tempting. A hint of black pepper adds piquancy.
<br> <br>
<h4>Family: <i>woody and spicy</i></h4> 
<h4>Perception: <i>cool, earthy</i></h4>
<h4>Projection: <i>strong</i></h4>
<h4>Category: <i>prestige</i></h4> 
<h4>Fragrance architecture:
<br><i>Head note: orange, grapefruit</i>
<br><i>Heart note: pepper, geranium</i>
<br><i>Base note: benzoin, vetiver, cedar</i></h4>



						</div>
					</div><!--/product-details-->

				</div>
