
				<div class="col-sm-9 padding-right">
					<div class="product-details"><!--product-details-->
						<div class="col-sm-5">
							<div class="view-product">
								<img src="images/product/perfumy_19.jpg" alt="" />
								
							</div>
							

						</div>
						<div class="col-sm-7">
							<div class="product-information"><!--/product-information-->
								<!-- <img src="images/product-details/new.jpg" class="newarrival" alt="" /> -->
								<h2>Perfume Woman #19</h2><p>jasmine - melon - cedar</p>
								<p>Product code: 101019</p>
								<p>Fragrance concetration: 20%</p>
								<!-- <span>
									<span>US $59</span>
									<label>Quantity:</label>
									<input type="text" value="3" />
									<button type="button" class="btn btn-fefault cart">
										<i class="fa fa-shopping-cart"></i>
										Add to cart
									</button>
								</span> -->
								<p><b>50 ml</b> In Stock</p>

								
							</div><!--/product-information-->

						</div>
						<div><br><br>
<h2>Why you’ll love it:</h2>
for its distinctive character. If you like to shine, this composition is for you! Sensual jasmine, orchid and appetizing notes of melon, pear and blackberry will ensure you get everyone’s attention.
<br> <br>
<h4>Family: <i>floral and fruity</i></h4> 
<h4>Perception: <i>floral, sensual</i></h4>
<h4>Projection: <i>strong</i></h4>
<h4>Category: <i>glamour</i></h4> 
<h4>Fragrance architecture:
<br><i>Head note: magnolia, melon, pear, bergamot</i>
<br><i>Heart note: plum, violet, orchid, lily of the valley</i>
<br><i>Base note: blackberry, vanilla, cedar</i></h4> 



						</div>
					</div><!--/product-details-->
					
					
					
					
					
				</div>
