
				<div class="col-sm-9 padding-right">
					<div class="product-details"><!--product-details-->
						<div class="col-sm-5">
							<div class="view-product">
								<img src="images/product/perfume_03.jpg" alt="" />
								
							</div>
							

						</div>
						<div class="col-sm-7">
							<div class="product-information"><!--/product-information-->
								<!-- <img src="images/product-details/new.jpg" class="newarrival" alt="" /> -->
								<h2>Perfume Woman #3</h2><p>rose - orange - patchouli</p>
								<p>Product code: 101003</p>
								<p>Fragrance concetration: 20%</p>
								<!-- <span>
									<span>US $59</span>
									<label>Quantity:</label>
									<input type="text" value="3" />
									<button type="button" class="btn btn-fefault cart">
										<i class="fa fa-shopping-cart"></i>
										Add to cart
									</button>
								</span> -->
								<p><b>50 ml</b> In Stock</p>

								
							</div><!--/product-information-->

						</div>
						<div><br><br>
						<h2>Why you’ll love it:</h2>
						for its subtle sensuality. It is a fragrance that will always make you feel feminine and elegant. Fresh citrus fruit, sensual flowers and the sweetness of vanilla will boost your self-confidence.
<br> <br>
<h4>Family: <i>oriental woody</i></h4> 
<h4>Perception: <i>sweet, balsamic</i></h4>
<h4>Projection: <i>strong</i></h4>
<h4>Category: <i>glamour</i></h4> 
<h4>Fragrance architecture:<br><i>Head note: tangerine, orange, orange blossom</i><br><i>Heart note: mimosa, rose, ylang-ylang</i><br><i>Base note: tonka beans, patchouli, vanilla</i></h4>



						</div>
					</div><!--/product-details-->
					
					
					
					
					
				</div>
