
				
				<div class="col-sm-9 padding-right">
					<div class="product-details"><!--product-details-->
						<div class="col-sm-5">
							<div class="view-product">
								<img src="images/product/perfume_07.jpg" alt="" />
								
							</div>
							

						</div>
						<div class="col-sm-7">
							<div class="product-information"><!--/product-information-->
								<!-- <img src="images/product-details/new.jpg" class="newarrival" alt="" /> -->
								<h2>Perfume Woman  #7</h2><p>vanilla - pear - chocolate pralines</p>
								<p>Product code: 101007</p>
								<p>Fragrance concetration: 20%</p>
								<!-- <span>
									<span>US $59</span>
									<label>Quantity:</label>
									<input type="text" value="3" />
									<button type="button" class="btn btn-fefault cart">
										<i class="fa fa-shopping-cart"></i>
										Add to cart
									</button>
								</span> -->
								<p><b>50 ml</b> In Stock</p>

								
							</div><!--/product-information-->

						</div>
						<div><br><br>
						<h2>Why you’ll love it:</h2>
						for the sweetness of vanilla. Imagine your perfect day.<br>

You feel excellent. You are enveloped by your favourite notes of chocolate pralines, vanilla, pear and jasmine. We can see you are smiling...
<br> <br>
<h4>Family: <i>floral gourmand</i></h4> 
<h4>Perception: <i>sweet, caramel</i></h4>
<h4>Projection: <i>strong</i></h4>
<h4>Category: <i>casual</i></h4> 
<h4>Fragrance architecture:<br><i>Head note: pear, black currant</i><br><i>Heart note: orange blossom, iris, jasmine</i><br><i>Base note: vanilla, chocolate pralines, tonka beans, patchouli</i></h4>



						</div>
					</div><!--/product-details-->
					
					
					
					
					
				</div>
