
				<div class="col-sm-9 padding-right">
					<div class="product-details"><!--product-details-->
						<div class="col-sm-5">
							<div class="view-product">
								<img src="images/product/perfumy_04.jpg" alt="" />
								
							</div>
							

						</div>
						<div class="col-sm-7">
							<div class="product-information"><!--/product-information-->
								<!-- <img src="images/product-details/new.jpg" class="newarrival" alt="" /> -->
								<h2>Perfume Man #04</h2><p>grapefruit - coffee - black pepper</p>
								<p>Product code: 101004</p>
								<p>Fragrance concetration: 20%</p>
								<!-- <span>
									<span>US $59</span>
									<label>Quantity:</label>
									<input type="text" value="3" />
									<button type="button" class="btn btn-fefault cart">
										<i class="fa fa-shopping-cart"></i>
										Add to cart
									</button>
								</span> -->
								<p><b>50 ml</b> In Stock</p>

								
							</div><!--/product-information-->

						</div>
						<div><br><br>
<h2>What will seduce you:</h2>
Its unbridled freshness. A refreshing scent, full of unbridled citrus joy. A hint of coffee and black pepper makes it always a good way to start a brand new day.
<br> <br>
<h4>Family: <i>citrus</i></h4> 
<h4>Perception: <i>fresh, citrus</i></h4>
<h4>Projection: <i>moderate</i></h4>
<h4>Category: <i>sport</i></h4> 
<h4>Fragrance architecture:
<br><i>Head note: grapefruit, bitter orange, tangerine, bergamot</i>
<br><i>Heart note: coffee, amyris, black pepper</i>
<br><i>Base note: vetiver, patchouli</i></h4>



						</div>
					</div><!--/product-details-->
					
					
					
					
					
				</div>
