
				<div class="col-sm-9 padding-right">
					<div class="product-details"><!--product-details-->
						<div class="col-sm-5">
							<div class="view-product">
								<img src="images/product/perfumy_36.jpg" alt="" />
								
							</div>
							

						</div>
						<div class="col-sm-7">
							<div class="product-information"><!--/product-information-->
								<!-- <img src="images/product-details/new.jpg" class="newarrival" alt="" /> --> 
								<h2>Perfume Man #36</h2><p>bergamot - tomato leaves - sandalwood </p>
								<p>Product code: 101036</p>
								<p>Fragrance concetration: 20%</p>
								<!-- <span>
									<span>US $59</span>
									<label>Quantity:</label>
									<input type="text" value="3" />
									<button type="button" class="btn btn-fefault cart">
										<i class="fa fa-shopping-cart"></i>
										Add to cart
									</button>
								</span> -->
								<p><b>50 ml</b> In Stock</p>

								
							</div><!--/product-information-->

						</div>
						<div><br><br>
<h2>What will seduce you:</h2>
freshness. The perfume owes its uniqueness to the combination of blackcurrant leaves and tomato leaves. Classic rose and warm sandalwood add charm and elegance.
<br> <br>
<h4>Family: <i>woody and fruity</i></h4> 
<h4>Perception: <i>fresh, green</i></h4>
<h4>Projection: <i>strong</i></h4>
<h4>Category: <i>business</i></h4> 
<h4>Fragrance architecture:
<br><i>Head note: tomato leaf, black currant leaf, bergamot</i>
<br><i>Heart note: rose, black pepper</i>
<br><i>Base note: sandalwood, patchouli</i></h4>



						</div>
					</div><!--/product-details-->

				</div>
