
				
				<div class="col-sm-9 padding-right">
					<div class="product-details"><!--product-details-->
						<div class="col-sm-5">
							<div class="view-product">
								<img src="images/product/perfumy_08.jpg" alt="" />
								
							</div>
							

						</div>
						<div class="col-sm-7">
							<div class="product-information"><!--/product-information-->
								<!-- <img src="images/product-details/new.jpg" class="newarrival" alt="" /> -->
								<h2>Perfume Man #08</h2><p>marine notes - lime - reseda </p>
								<p>Product code: 101008</p>
								<p>Fragrance concetration: 20%</p>
								<!-- <span>
									<span>US $59</span>
									<label>Quantity:</label>
									<input type="text" value="3" />
									<button type="button" class="btn btn-fefault cart">
										<i class="fa fa-shopping-cart"></i>
										Add to cart
									</button>
								</span> -->
								<p><b>50 ml</b> In Stock</p>

								
							</div><!--/product-information-->

						</div>
						<div><br><br>
<h2>What will seduce you:</h2>
powerful invigoration. Fresh sea breeze with invigorating notes of citrus fruit and sweet jasmine. Intoxicating notes of reseda and cyclamen make it hard to resist.
<br> <br>
<h4>Family: <i>citrus</i></h4> 
<h4>Perception: <i>fresh, marine</i></h4>
<h4>Projection: <i>moderate</i></h4>
<h4>Category: <i>sport</i></h4> 
<h4>Fragrance architecture:
<br><i>Head note: lime, bergamot, jasmine, lemon</i>
<br><i>Heart note: sea notes, reseda, rosemary, cyclamen</i>
<br><i>Base note: patchouli, vetiver, ambergris</i></h4>



						</div>
					</div><!--/product-details-->
					
					
					
					
					
				</div>
