
				<div class="col-sm-9 padding-right">
					<div class="product-details"><!--product-details-->
						<div class="col-sm-5">
							<div class="view-product">
								<img src="images/product/perfumy_28.jpg" alt="" />
								
							</div>
							

						</div>
						<div class="col-sm-7">
							<div class="product-information"><!--/product-information-->
								<!-- <img src="images/product-details/new.jpg" class="newarrival" alt="" /> -->
								<h2>Perfume Man #28</h2><p>bergamot - papaya - nutmeg </p>
								<p>Product code: 101028</p>
								<p>Fragrance concetration: 20%</p>
								<!-- <span>
									<span>US $59</span>
									<label>Quantity:</label>
									<input type="text" value="3" />
									<button type="button" class="btn btn-fefault cart">
										<i class="fa fa-shopping-cart"></i>
										Add to cart
									</button>
								</span> -->
								<p><b>50 ml</b> In Stock</p>

								
							</div><!--/product-information-->

						</div>
						<div><br><br>
<h2>What will seduce you:</h2>
its clarity and natural character. Exquisitely fresh, and yet very sensual perfume. Juicy pineapple combined with a pinch of nutmeg and musk make an incredible impression.
<br> <br>
<h4>Family: <i>citrus</i></h4> 
<h4>Perception: <i>fresh, green</i></h4>
<h4>Projection: <i>moderate</i></h4>
<h4>Category: <i>adventure</i></h4> 
<h4>Fragrance architecture:
<br><i>Head note: pineapple, papaya, bergamot, lemon</i>
<br><i>Heart note: lily of the valley, violet, nutmeg, rose</i>
<br><i>Base note: sandalwood, musk, ambergris</i></h4>



						</div>
					</div><!--/product-details-->

				</div>
