
				<div class="col-sm-9 padding-right">
					<div class="product-details"><!--product-details-->
						<div class="col-sm-5">
							<div class="view-product">
								<img src="images/product/perfumy_38.jpg" alt="" />
								
							</div>
							

						</div>
						<div class="col-sm-7">
							<div class="product-information"><!--/product-information-->
								<!-- <img src="images/product-details/new.jpg" class="newarrival" alt="" /> --> 
								<h2>Perfume Man #38</h2><p>seawater - laurel leaf - tangerine</p>
								<p>Product code: 101038</p>
								<p>Fragrance concetration: 20%</p>
								<!-- <span>
									<span>US $59</span>
									<label>Quantity:</label>
									<input type="text" value="3" />
									<button type="button" class="btn btn-fefault cart">
										<i class="fa fa-shopping-cart"></i>
										Add to cart
									</button>
								</span> -->
								<p><b>50 ml</b> In Stock</p>

								
							</div><!--/product-information-->

						</div>
						<div><br><br>
<h2>What will seduce you:</h2>
pleasant refreshment. Remember the moment you become immerse in pleasantly cool water. Feel the salt of the sea water, fresh citrus fruits and intoxicating sweetness of jasmine blossom on your skin.
<br> <br>
<h4>Family: <i>woody and fruity</i></h4> 
<h4>Perception: <i>fresh, green</i></h4>
<h4>Projection: <i>strong</i></h4>
<h4>Category: <i>sport</i></h4> 
<h4>Fragrance architecture:
<br><i>Head note: grapefruit, tangerine, sea water</i>
<br><i>Heart note: bay leaf, jasmine</i>
<br><i>Base note: guaiac wood, ambergris, oakmoss</i></h4>



						</div>
					</div><!--/product-details-->

				</div>
