
				<div class="col-sm-9 padding-right">
					<div class="product-details"><!--product-details-->
						<div class="col-sm-5">
							<div class="view-product">
								<img src="images/product/perfumy_25.jpg" alt="" />
								
							</div>
							

						</div>
						<div class="col-sm-7">
							<div class="product-information"><!--/product-information-->
								<!-- <img src="images/product-details/new.jpg" class="newarrival" alt="" /> -->
								<h2>Perfume Woman #25</h2><p>rose - sage - bergamot</p>
								<p>Product code: 101025</p>
								<p>Fragrance concetration: 20%</p>
								<!-- <span>
									<span>US $59</span>
									<label>Quantity:</label>
									<input type="text" value="3" />
									<button type="button" class="btn btn-fefault cart">
										<i class="fa fa-shopping-cart"></i>
										Add to cart
									</button>
								</span> -->
								<p><b>50 ml</b><font color="#ff0000">AVAILABLE WHILE STOCKS LAST</font><font color="#000000"></p>

								
							</div><!--/product-information-->

						</div>
						<div><br><br>
<h2>Why you’ll love it:</h2>
for its distinctive sensuality. The power of green herbs and fragrant spices, mixed with classic scents of rose and lily of the valley is a combination that will seduce you. 
<br> <br>
<h4>Family: <i>chypre floral</i></h4> 
<h4>Perception: <i>strong, fragrant</i></h4>
<h4>Projection: <i>strong</i></h4>
<h4>Category: <i>glamour</i></h4> 
<h4>Fragrance architecture:
<br><i>Head note: coriander, sage, ginger, bergamot, aldehydes</i>
<br><i>Heart note: rose, lilly of the valley, carnation</i>
<br><i>Base note: labdanum, benzoin, vanilla</i></h4> 



						</div>
					</div><!--/product-details-->

				</div>
