
				<div class="col-sm-9 padding-right">
					<div class="product-details"><!--product-details-->
						<div class="col-sm-5">
							<div class="view-product">
								<img src="images/product/perfumy_42.jpg" alt="" />
								
							</div>
							

						</div>
						<div class="col-sm-7">
							<div class="product-information"><!--/product-information-->
								<!-- <img src="images/product-details/new.jpg" class="newarrival" alt="" /> --> 
								<h2>Perfume Man #42</h2><p>black pepper, patchouli, wood notes</p>
								<p>Product code: 101042</p>
								<p>Fragrance concetration: 20%</p>
								<!-- <span>
									<span>US $59</span>
									<label>Quantity:</label>
									<input type="text" value="3" />
									<button type="button" class="btn btn-fefault cart">
										<i class="fa fa-shopping-cart"></i>
										Add to cart
									</button>
								</span> -->
								<p><b>50 ml</b> In Stock</p>

								
							</div><!--/product-information-->

						</div>
						<div><br><br>
<h2>What will seduce you:</h2>
an unprecedented character. It is a combination of fresh and slightly spicy aroma of black pepper with refreshing citrus and warm scent of wood notes, bringing a bit of exoticism. This bold composition fascinates and provides an extraordinary sensual experience.
<br> <br>
<h4>Family: <i>oriental-wood</i></h4> 
<h4>Perception: <i>aromatic, energizing</i></h4>
<h4>Projection: <i>strong</i></h4>
<h4>Category: <i>adventure</i></h4> 
<h4>Fragrance architecture:
<br><i>Head note: black pepper, citrus notes</i>
<br><i>Heart note: lavender, geranium, elemi</i>
<br><i>Base note: patchouli, vetiver, wood notes</i></h4>



						</div>
					</div><!--/product-details-->

				</div>
