
				<div class="col-sm-9 padding-right">
					<div class="product-details"><!--product-details-->
						<div class="col-sm-5">
							<div class="view-product">
								<img src="images/product/perfumy_57.jpg" alt="" />
								
							</div>
							

						</div>
						<div class="col-sm-7">
							<div class="product-information"><!--/product-information-->
								<img src="images/product-details/new.jpg" class="newarrival" alt="" /> 
								<h2>Perfume Woman #57</h2><p>tonka bean - cocoa - tuberose</p>
								<p>Product code: 101057</p>
								<p>Fragrance concetration: 20%</p>
								<!-- <span>
									<span>US $59</span>
									<label>Quantity:</label>
									<input type="text" value="3" />
									<button type="button" class="btn btn-fefault cart">
										<i class="fa fa-shopping-cart"></i>
										Add to cart
									</button>
								</span> -->
								<p><b>50 ml</b> In Stock</p>

								
							</div><!--/product-information-->

						</div>
						<div><br><br>
<h2>Why you’ll love it:</h2>
for its mischievousness and flirtatiousness.  A sweet and sensual fragrance of white flowers and freshly ground coffee beans. Seductive tonka beans will give it additional depth.
<br> <br>
<h4>Family: <i>oriental floral</i></h4> 
<h4>Perception: <i>sweet, sensual</i></h4>
<h4>Projection: <i>moderate</i></h4>
<h4>Category: <i>romance</i></h4> 
<h4>Fragrance architecture:
<br><i>Head note: almonds, coffee</i>
<br><i>Heart note: jasmine, tuberose</i>
<br><i>Base note: cocoa, tonka beans</i></h4>



						</div>
					</div><!--/product-details-->

				</div>
