
				<div class="col-sm-9 padding-right">
					<div class="product-details"><!--product-details-->
						<div class="col-sm-5">
							<div class="view-product">
								<img src="images/product/perfumy_23.jpg" alt="" />
								
							</div>
							

						</div>
						<div class="col-sm-7">
							<div class="product-information"><!--/product-information-->
								<!-- <img src="images/product-details/new.jpg" class="newarrival" alt="" /> -->
								<h2>Perfume Woman #23</h2><p>rose - patchouli - ambergris </p>
								<p>Product code: 101023</p>
								<p>Fragrance concetration: 20%</p>
								<!-- <span>
									<span>US $59</span>
									<label>Quantity:</label>
									<input type="text" value="3" />
									<button type="button" class="btn btn-fefault cart">
										<i class="fa fa-shopping-cart"></i>
										Add to cart
									</button>
								</span> -->
								<p><b>50 ml</b> In Stock</p>

								
							</div><!--/product-information-->

						</div>
						<div><br><br>
<h2>Why you’ll love it:</h2>
for its seductive aura. A classic, enveloping scent of sensual roses and balsamic ambergris, with a delicate hint of juicy citrus fruits and earthy herbal aroma of patchouli.
<br> <br>
<h4>Family: <i>chypre woody</i></h4> 
<h4>Perception: <i>spicy, warm</i></h4>
<h4>Projection: <i>strong</i></h4>
<h4>Category: <i>glamour</i></h4> 
<h4>Fragrance architecture:
<br><i>Head note: bergamot, tangerine</i>
<br><i>Heart note: rose</i>
<br><i>Base note: ambergris, patchouli</i></h4>



						</div>
					</div><!--/product-details-->

				</div>
