			
				<div class="col-sm-9 padding-right">
					<div class="product-details"><!--product-details-->
						<div class="col-sm-5">
							<div class="view-product">
								<img src="images/product/perfumy_18.jpg" alt="" />
								
							</div>
							

						</div>
						<div class="col-sm-7">
							<div class="product-information"><!--/product-information-->
								<!-- <img src="images/product-details/new.jpg" class="newarrival" alt="" /> -->
								<h2>Perfume Man #18</h2><p>coffee - rosepepper - tonka beans</p>
								<p>Product code: 101018</p>
								<p>Fragrance concetration: 20%</p>
								<!-- <span>
									<span>US $59</span>
									<label>Quantity:</label>
									<input type="text" value="3" />
									<button type="button" class="btn btn-fefault cart">
										<i class="fa fa-shopping-cart"></i>
										Add to cart
									</button>
								</span> -->
								<p><b>50 ml</b> In Stock</p>

								
							</div><!--/product-information-->

						</div>
						<div><br><br>
<h2>What will seduce you:</h2>
good style. This elegant scent is like a cup of aromatic espresso with a hint of orange peel and red pepper. Refreshing and classy.
<br> <br>
<h4>Family: <i>fougère</i></h4> 
<h4>Perception: <i>fragrant, coffee</i></h4>
<h4>Projection: <i>moderate</i></h4>
<h4>Category: <i>elegance</i></h4> 
<h4>Fragrance architecture:
<br><i>Head note: orange, bergamot</i>
<br><i>Heart note: coffee, pink pepper, amyris</i>
<br><i>Base note: tonka beans, vetiver, patchouli, musk</i></h4>



						</div>
					</div><!--/product-details-->
					
					
					
					
					
				</div>
