
				<div class="col-sm-9 padding-right">
					<div class="product-details"><!--product-details-->
						<div class="col-sm-5">
							<div class="view-product">
								<img src="images/product/perfumy_10.jpg" alt="" />
								
							</div>
							

						</div>
						<div class="col-sm-7">
							<div class="product-information"><!--/product-information-->
								<!-- <img src="images/product-details/new.jpg" class="newarrival" alt="" /> -->
								<h2>Perfume Man #10</h2><p>tangerine - ginger - lavender</p>
								<p>Product code: 101010</p>
								<p>Fragrance concetration: 20%</p>
								<!-- <span>
									<span>US $59</span>
									<label>Quantity:</label>
									<input type="text" value="3" />
									<button type="button" class="btn btn-fefault cart">
										<i class="fa fa-shopping-cart"></i>
										Add to cart
									</button>
								</span> -->
								<p><b>50 ml</b> In Stock</p>

								
							</div><!--/product-information-->

						</div>
						<div><br><br>
<h2>What will seduce you:</h2>
unexpected combinations. Freshly squeezed citrus fruits, a hint of ginger and original woody notes is a suggestion for those who value originality.
<br> <br>
<h4>Family: <i>citrus</i></h4> 
<h4>Perception: <i>cool, spicy</i></h4>
<h4>Projection: <i>strong</i></h4>
<h4>Category: <i>adventure</i></h4> 
<h4>Fragrance architecture:
<br><i>Head note: tangerine, lemon, bergamot</i>
<br><i>Heart note: lavender, violet leaves, ginger</i>
<br><i>Base note: ebony, teak wood</i></h4>



						</div>
					</div><!--/product-details-->
				</div>
