
				<div class="col-sm-9 padding-right">
					<div class="product-details"><!--product-details-->
						<div class="col-sm-5">
							<div class="view-product">
								<img src="images/product/perfumy_15.jpg" alt="" />
								
							</div>
							

						</div>
						<div class="col-sm-7">
							<div class="product-information"><!--/product-information-->
								<!-- <img src="images/product-details/new.jpg" class="newarrival" alt="" /> -->
								<h2>Perfume Woman #15</h2><p>strawberry - cherry - caramel</p>
								<p>Product code: 101015</p>
								<p>Fragrance concetration: 20%</p>
								<!-- <span>
									<span>US $59</span>
									<label>Quantity:</label>
									<input type="text" value="3" />
									<button type="button" class="btn btn-fefault cart">
										<i class="fa fa-shopping-cart"></i>
										Add to cart
									</button>
								</span> -->
								<p><b>50 ml</b> In Stock</p>

								
							</div><!--/product-information-->

						</div>
						<div><br><br>
<h2>Why you’ll love it:</h2>
for its sweet notes of high summer. Juicy summer fruits and bold gourmand notes make this composition tempting and appetizing.
<br> <br>
<h4>Family: <i>chypre floral</i></h4> 
<h4>Perception: <i>juicy, fruity</i></h4>
<h4>Projection: <i>moderate</i></h4>
<h4>Category: <i>romance</i></h4> 
<h4>Fragrance architecture:
<br><i>Head note: strawberry, cherry, pineapple, tangerine</i>
<br><i>Heart note: popcorn, caramel, violet</i>
<br><i>Base note: musk, ambergris, patchouli
</i></h4>



						</div>
					</div><!--/product-details-->
					
					
					
					
					
				</div>
