
				
				<div class="col-sm-9 padding-right">
					<div class="product-details"><!--product-details-->
						<div class="col-sm-5">
							<div class="view-product">
								<img src="images/product/perfumy_09.jpg" alt="" />
								
							</div>
							

						</div>
						<div class="col-sm-7">
							<div class="product-information"><!--/product-information-->
								<!-- <img src="images/product-details/new.jpg" class="newarrival" alt="" /> -->
								<h2>Perfume Woman #9</h2><p>caramel - melon - cotton candy</p>
								<p>Product code: 101009</p>
								<p>Fragrance concetration: 20%</p>
								<!-- <span>
									<span>US $59</span>
									<label>Quantity:</label>
									<input type="text" value="3" />
									<button type="button" class="btn btn-fefault cart">
										<i class="fa fa-shopping-cart"></i>
										Add to cart
									</button>
								</span> -->
								<p><b>50 ml</b> In Stock</p>

								
							</div><!--/product-information-->

						</div>
						<div><br><br>
<h2>Why you’ll love it:</h2>
for its otherworldly sweetness. Caramel, cotton candy, chocolate, melon and honey create a composition for women with irrepressible appetite for life.
<br> <br>
<h4>Family: <i>oriental spicy</i></h4> 
<h4>Perception: <i>sweet, vanilla</i></h4>
<h4>Projection: <i>strong</i></h4>
<h4>Category: <i>glamour</i></h4> 
<h4>Fragrance architecture:<br><i>Head note: melon, cotton candy, blackcurrant leaf</i><br><i>Heart note: honey, plum, peach</i><br><i>Base note: caramel, chocolate, vanilla, musk</i></h4>




						</div>
					</div><!--/product-details-->
					
					
					
					
					
				</div>
