			
				<div class="col-sm-9 padding-right">
					<div class="product-details"><!--product-details-->
						<div class="col-sm-5">
							<div class="view-product">
								<img src="images/product/perfume_05.jpg" alt="" />
								
							</div>
							

						</div>
						<div class="col-sm-7">
							<div class="product-information"><!--/product-information-->
								<!-- <img src="images/product-details/new.jpg" class="newarrival" alt="" /> -->
								<h2>Perfume Woman #5</h2><p>vanilla - iris - musk </p>
								<p>Product code: 101005</p>
								<p>FFragrance concetration: 20%</p>
								<!-- <span>
									<span>US $59</span>
									<label>Quantity:</label>
									<input type="text" value="3" />
									<button type="button" class="btn btn-fefault cart">
										<i class="fa fa-shopping-cart"></i>
										Add to cart
									</button>
								</span> -->
								<p><b>50 ml</b></p>

								
							</div><!--/product-information-->

						</div>
						<div><br><br>
						<h2>Why you’ll love it:</h2>
						for its cheerful lightness. Each time you reach for this powdery vanilla perfume, the corners of your mouth will lift of their own volition. You will feel light and fresh.
<br> <br>
<h4>Family: <i>chypre floral</i></h4> 
<h4>Perception: <i>powdery, vanilla</i></h4>
<h4>Projection: <i>moderate</i></h4>
<h4>Category: <i>casual</i></h4> 
<h4>Fragrance architecture:<br><i>Head note: jasmine, iris</i><br><i>Heart note: vanilla</i><br><i>Base note: white ambergris</i></h4>




						</div>
					</div><!--/product-details-->
					
					
					
					
					
				</div>
