
				<div class="col-sm-9 padding-right">
					<div class="product-details"><!--product-details-->
						<div class="col-sm-5">
							<div class="view-product">
								<img src="images/product/perfumy_53.jpg" alt="" />
								
							</div>
							

						</div>
						<div class="col-sm-7">
							<div class="product-information"><!--/product-information-->
								<img src="images/product-details/new.jpg" class="newarrival" alt="" /> 
								<h2>Perfume Woman #53</h2><p>coffee - pear - cashmeran</p>
								<p>Product code: 101053</p>
								<p>Fragrance concetration: 20%</p>
								<!-- <span>
									<span>US $59</span>
									<label>Quantity:</label>
									<input type="text" value="3" />
									<button type="button" class="btn btn-fefault cart">
										<i class="fa fa-shopping-cart"></i>
										Add to cart
									</button>
								</span> -->
								<p><b>50 ml</b> In Stock</p>

								
							</div><!--/product-information-->

						</div>
						<div><br><br>
<h2>Why you’ll love it:</h2>
for its powerful fragrance. Coffee, vanilla and almonds – it sounds delicious. But not to overdo sweetness, we also have a rich array of woody notes: from sandalwood to luxurious cashmere wood.
<br> <br>
<h4>Family: <i>oriental woody</i></h4> 
<h4>Perception: <i>sweet, coffee</i></h4>
<h4>Projection: <i>strong</i></h4>
<h4>Category: <i>glamour</i></h4> 
<h4>Fragrance architecture:
<br><i>Head note: pear, orange blossom, pink pepper</i>
<br><i>Heart note: almonds, coffee, jasmine</i>
<br><i>Base note: cashmere wood, sandalwood, cedar, vanilla</i></h4>



						</div>
					</div><!--/product-details-->

				</div>
