
				<div class="col-sm-9 padding-right">
					<div class="product-details"><!--product-details-->
						<div class="col-sm-5">
							<div class="view-product">
								<img src="images/product/perfumy_45.jpg" alt="" />
								
							</div>
							

						</div>
						<div class="col-sm-7">
							<div class="product-information"><!--/product-information-->
								<!-- <img src="images/product-details/new.jpg" class="newarrival" alt="" /> -->
								<h2>Perfume Woman #45</h2><p>peach - rose - freesia</p>
								<p>Product code: 101045</p>
								<p>Fragrance concetration: 20%</p>
								<!-- <span>
									<span>US $59</span>
									<label>Quantity:</label>
									<input type="text" value="3" />
									<button type="button" class="btn btn-fefault cart">
										<i class="fa fa-shopping-cart"></i>
										Add to cart
									</button>
								</span> -->
								<p><b>50 ml</b> In Stock</p>

								
							</div><!--/product-information-->

						</div>
						<div><br><br>
<h2>Why you’ll love it:</h2>
for its shimmer. If you devote a moment to this scent, you will discover how beautifully it pulses with the notes of sunny peach, sweet freesia and fresh coriander. It is strong and intense, but at the same time airy and delicate.
<br> <br>
<h4>Family: <i>chypre fruity</i></h4> 
<h4>Perception: <i>floral, intense</i></h4>
<h4>Projection: <i>strong</i></h4>
<h4>Category: <i>romance</i></h4> 
<h4>Fragrance architecture:
<br><i>Head note: freesia, peach, gardenia</i>
<br><i>Heart note: coriander, rose, jasmine</i>
<br><i>Base note: vanilla, patchouli, vetiver</i></h4>



						</div>
					</div><!--/product-details-->

				</div>
