
				<div class="col-sm-9 padding-right">
					<div class="product-details"><!--product-details-->
						<div class="col-sm-5">
							<div class="view-product">
								<img src="images/product/perfumy_32.jpg" alt="" />
								
							</div>
							

						</div>
						<div class="col-sm-7">
							<div class="product-information"><!--/product-information-->
								<!-- <img src="images/product-details/new.jpg" class="newarrival" alt="" /> --> 
								<h2>Perfume Man #32</h2><p>grapefruit - violet - leather notes</p>
								<p>Product code: 101032</p>
								<p>Fragrance concetration: 20%</p>
								<!-- <span>
									<span>US $59</span>
									<label>Quantity:</label>
									<input type="text" value="3" />
									<button type="button" class="btn btn-fefault cart">
										<i class="fa fa-shopping-cart"></i>
										Add to cart
									</button>
								</span> -->
								<p><b>50 ml</b> In Stock</p>

								
							</div><!--/product-information-->

						</div>
						<div><br><br>
<h2>What will seduce you:</h2>
unrestrained power. A robust shot of citrus, the sweetness of violet and sensual leather notes will increase the temperature by few degrees.
<br> <br>
<h4>Family: <i>woody and floral</i></h4> 
<h4>Perception: <i>fresh, leathery</i></h4>
<h4>Projection: <i>strong</i></h4>
<h4>Category: <i>elegance</i></h4> 
<h4>Fragrance architecture:
<br><i>Head note: grapefruit, tangerine</i>
<br><i>Heart note: violet, basil, mint</i>
<br><i>Base note: leather notes, vetiver</i></h4>



						</div>
					</div><!--/product-details-->

				</div>
