
				<div class="col-sm-9 padding-right">
					<div class="product-details"><!--product-details-->
						<div class="col-sm-5">
							<div class="view-product">
								<img src="images/product/perfumy_39.jpg" alt="" />
								
							</div>
							

						</div>
						<div class="col-sm-7">
							<div class="product-information"><!--/product-information-->
								<!-- <img src="images/product-details/new.jpg" class="newarrival" alt="" /> --> 
								<h2>Perfume Woman #39</h2><p>lemon - green apple - bamboo</p>
								<p>Product code: 101039</p>
								<p>Fragrance concetration: 20%</p>
								<!-- <span>
									<span>US $59</span>
									<label>Quantity:</label>
									<input type="text" value="3" />
									<button type="button" class="btn btn-fefault cart">
										<i class="fa fa-shopping-cart"></i>
										Add to cart
									</button>
								</span> -->
								<p><b>50 ml</b> In Stock</p>

								
							</div><!--/product-information-->

						</div>
						<div><br><br>
<h2>Why you’ll love it:</h2>
for its subtlety. Subtle and relaxing like a summer morning at the Adriatic. The sea breeze brings refreshing notes of green apple, rose, campanula and juicy lemon.
<br> <br>
<h4>Family: <i>citrus</i></h4> 
<h4>Perception: <i>fresh, relaxing</i></h4>
<h4>Projection: <i>moderate</i></h4>
<h4>Category: <i>glamour</i></h4> 
<h4>Fragrance architecture:
<br><i>Head note: green apple, bellflower, lemon</i>
<br><i>Heart note: white rose, bamboo, jasmine</i>
<br><i>Base note: cedar, ambergris , musk</i></h4>



						</div>
					</div><!--/product-details-->

				</div>
