
				<div class="col-sm-9 padding-right">
					<div class="product-details"><!--product-details-->
						<div class="col-sm-5">
							<div class="view-product">
								<img src="images/product/perfumy_21.jpg" alt="" />
								
							</div>
							

						</div>
						<div class="col-sm-7">
							<div class="product-information"><!--/product-information-->
								<!-- <img src="images/product-details/new.jpg" class="newarrival" alt="" /> -->
								<h2>Perfume Woman #21</h2><p>orange bloom - sandalwood - musk </p>
								<p>Product code: 101021</p>
								<p>Fragrance concetration: 20%</p>
								<!-- <span>
									<span>US $59</span>
									<label>Quantity:</label>
									<input type="text" value="3" />
									<button type="button" class="btn btn-fefault cart">
										<i class="fa fa-shopping-cart"></i>
										Add to cart
									</button>
								</span> -->
								<p><b>50 ml</b> In Stock</p>

								
							</div><!--/product-information-->

						</div>
						<div><br><br>
<h2>Why you’ll love it:</h2>
for its sensual elegance. Strong, feminine perfume with a dominant warm scent of musk, orange blossom and sandalwood.
<br> <br>
<h4>Family: <i>floral and woody</i></h4> 
<h4>Perception: <i>woody, musky</i></h4>
<h4>Projection: <i>strong</i></h4>
<h4>Category: <i>romance</i></h4> 
<h4>Fragrance architecture:
<br><i>Head note: bergamot, blackberry</i>
<br><i>Heart note: orange blossom, jasmine, musk</i>
<br><i>Base note: sandalwood, patchouli</i></h4>  

						</div>
					</div><!--/product-details-->

				</div>
