
				<div class="col-sm-9 padding-right">
					<div class="product-details"><!--product-details-->
						<div class="col-sm-5">
							<div class="view-product">
								<img src="images/product/perfumy_30.jpg" alt="" />
								
							</div>
							

						</div>
						<div class="col-sm-7">
							<div class="product-information"><!--/product-information-->
								<!-- <img src="images/product-details/new.jpg" class="newarrival" alt="" /> -->
								<h2>Perfume Man #30</h2><p>green apple - lavender - fir </p>
								<p>Product code: 101030</p>
								<p>Fragrance concetration: 20%</p>
								<!-- <span>
									<span>US $59</span>
									<label>Quantity:</label>
									<input type="text" value="3" />
									<button type="button" class="btn btn-fefault cart">
										<i class="fa fa-shopping-cart"></i>
										Add to cart
									</button>
								</span> -->
								<p><b>50 ml</b> In Stock</p>

								
							</div><!--/product-information-->

						</div>
						<div><br><br>
<h2>What will seduce you:</h2>
the promise of adventure. A strong, refreshing scent that will keep up with you every heated step of the way. The freshness of citrus fruits and green herbs will invigorate you.
<br> <br>
<h4>Family: <i>fougère</i></h4> 
<h4>Perception: <i>fresh, herbal</i></h4>
<h4>Projection: <i>strong</i></h4>
<h4>Category: <i>adventure</i></h4> 
<h4>Fragrance architecture:
<br><i>Head note: green apple, bergamot, lavender, basil, grapefruit</i>
<br><i>Heart note: carnation, geranium, sage</i>
<br><i>Base note: patchouli, cedar, fir</i></h4>



						</div>
					</div><!--/product-details-->

				</div>
