
				<div class="col-sm-9 padding-right">
					<div class="product-details"><!--product-details-->
						<div class="col-sm-5">
							<div class="view-product">
								<img src="images/product/perfumy_14.jpg" alt="" />
								
							</div>
							

						</div>
						<div class="col-sm-7">
							<div class="product-information"><!--/product-information-->
								<!-- <img src="images/product-details/new.jpg" class="newarrival" alt="" /> -->
								<h2>Perfume Man #14</h2><p>marine notes - orange - cedar</p>
								<p>Product code: 101014</p>
								<p>Fragrance concetration: 20%</p>
								<!-- <span>
									<span>US $59</span>
									<label>Quantity:</label>
									<input type="text" value="3" />
									<button type="button" class="btn btn-fefault cart">
										<i class="fa fa-shopping-cart"></i>
										Add to cart
									</button>
								</span> -->
								<p><b>50 ml</b> In Stock</p>

								
							</div><!--/product-information-->

						</div>
						<div><br><br>
<h2>What will seduce you:</h2>
its uncompromising nature. It is as refreshing as a gulp of fresh sea air. Before you know it, you will not be able to live without its citrus freshness, seasoned with spices and balsamic ambergris.
<br> <br>
<h4>Family: <i>woody and spicy</i></h4> 
<h4>Perception: <i>marine, spicy</i></h4>
<h4>Projection: <i>strong</i></h4>
<h4>Category: <i>sport</i></h4> 
<h4>Fragrance architecture:
<br><i>Head note: sea notes, aldehyde, orange</i>
<br><i>Heart note: neroli, cedar, black pepper</i>
<br><i>Base note: vanilla, ambergris, vetiver</i></h4>



						</div>
					</div><!--/product-details-->
					
					
					
					
					
				</div>
