
				<div class="col-sm-9 padding-right">
					<div class="product-details"><!--product-details-->
						<div class="col-sm-5">
							<div class="view-product">
								<img src="images/product/perfumy_17.jpg" alt="" />
								
							</div>
							

						</div>
						<div class="col-sm-7">
							<div class="product-information"><!--/product-information-->
								<!-- <img src="images/product-details/new.jpg" class="newarrival" alt="" /> -->
								<h2>Perfume Woman #17</h2><p>jasmine - passion fruit - vanilla</p>
								<p>Product code: 101017</p>
								<p>Fragrance concetration: 20%</p>
								<!-- <span>
									<span>US $59</span>
									<label>Quantity:</label>
									<input type="text" value="3" />
									<button type="button" class="btn btn-fefault cart">
										<i class="fa fa-shopping-cart"></i>
										Add to cart
									</button>
								</span> -->
								<p><b>50 ml</b> In Stock</p>

								
							</div><!--/product-information-->

						</div>
						<div><br><br>
<h2>Why you’ll love it:</h2>
for a hint of mystery. The oriental composition intoxicates with the sweetness of vanilla and jasmine, while sweet and exotic passion fruit adds unique charm to the mix.
<br> <br>
<h4>Family: <i>oriental spicy</i></h4> 
<h4>Perception: <i>vanilla, intoxicating</i></h4>
<h4>Projection: <i>strong</i></h4>
<h4>Category: <i>glamour</i></h4> 
<h4>Fragrance architecture:
<br><i>Head note: passion fruit</i>
<br><i>Heart note: jasmine, gardenia</i>
<br><i>Base note: vanilla, vetiver</i></h4> 



						</div>
					</div><!--/product-details-->
					
					
					
					
					
				</div>
