
				<div class="col-sm-9 padding-right">
					<div class="product-details"><!--product-details-->
						<div class="col-sm-5">
							<div class="view-product">
								<img src="images/product/perfumy_33.jpg" alt="" />
								
							</div>
							

						</div>
						<div class="col-sm-7">
							<div class="product-information"><!--/product-information-->
								<!-- <img src="images/product-details/new.jpg" class="newarrival" alt="" /> --> 
								<h2>Perfume Woman #33</h2><p>freesia - rose - patchouli </p>
								<p>Product code: 101033</p>
								<p>Fragrance concetration: 20%</p>
								<!-- <span>
									<span>US $59</span>
									<label>Quantity:</label>
									<input type="text" value="3" />
									<button type="button" class="btn btn-fefault cart">
										<i class="fa fa-shopping-cart"></i>
										Add to cart
									</button>
								</span> -->
								<p><b>50 ml</b> In Stock</p>

								
							</div><!--/product-information-->

						</div>
						<div><br><br>
<h2>Why you’ll love it:</h2>
for its subtlety and femininity. A sunny, delightful scent of sweet freesias, roses and vanilla, softened with patchouli and blackcurrant leaves.
<br> <br>
<h4>Family: <i>chypre floral</i></h4> 
<h4>Perception: <i>warm, sensual</i></h4>
<h4>Projection: <i>moderate</i></h4>
<h4>Category: <i>casual</i></h4> 
<h4>Fragrance architecture:
<br><i>Head note: black currant leaf</i>
<br><i>Heart note: freesia, rose</i>
<br><i>Base note: vanilla, patchouli, ambroxan</i></h4>



						</div>
					</div><!--/product-details-->
	
				</div>
