
				<div class="col-sm-9 padding-right">
					<div class="product-details"><!--product-details-->
						<div class="col-sm-5">
							<div class="view-product">
								<img src="images/product/perfumy_20.jpg" alt="" />
								
							</div>
							

						</div>
						<div class="col-sm-7">
							<div class="product-information"><!--/product-information-->
								<!-- <img src="images/product-details/new.jpg" class="newarrival" alt="" /> -->
								<h2>Perfume Man #20</h2><p>cinnamon - rose - leather notes </p>
								<p>Product code: 101020</p>
								<p>Fragrance concetration: 20%</p>
								<!-- <span>
									<span>US $59</span>
									<label>Quantity:</label>
									<input type="text" value="3" />
									<button type="button" class="btn btn-fefault cart">
										<i class="fa fa-shopping-cart"></i>
										Add to cart
									</button>
								</span> -->
								<p><b>50 ml</b> In Stock</p>

								
							</div><!--/product-information-->

						</div>
						<div><br><br>
<h2>What will seduce you:</h2>
perfect balance. Warm, spicy scent with a hint of balsamic ambergris and deep leather notes. It is expertly softened by the freshness of citrus fruits and mint.
<br> <br>
<h4>Family: <i>woody and spicy</i></h4> 
<h4>Perception: <i>warm, ambergris</i></h4>
<h4>Projection: <i>strong</i></h4>
<h4>Category: <i>business</i></h4> 
<h4>Fragrance architecture:
<br><i>Head note: grapefruit, tangerine, mint</i>
<br><i>Heart note: rose, spices, cinnamon</i>
<br><i>Base note: leather notes, cedar, ambergris</i></h4>



						</div>
					</div><!--/product-details-->

				</div>
