
				<div class="col-sm-9 padding-right">
					<div class="product-details"><!--product-details-->
						<div class="col-sm-5">
							<div class="view-product">
								<img src="images/product/perfumy_41.jpg" alt="" />
								
							</div>
							

						</div>
						<div class="col-sm-7">
							<div class="product-information"><!--/product-information-->
								<!-- <img src="images/product-details/new.jpg" class="newarrival" alt="" /> -->
								<h2>Perfume Woman #41</h2><p>greet tea - lemon - oakmoss</p>
								<p>Product code: 101041</p>
								<p>Fragrance concetration: 20%</p>
								<!-- <span>
									<span>US $59</span>
									<label>Quantity:</label>
									<input type="text" value="3" />
									<button type="button" class="btn btn-fefault cart">
										<i class="fa fa-shopping-cart"></i>
										Add to cart
									</button>
								</span> -->
								<p><b>50 ml</b> In Stock</p>

								
							</div><!--/product-information-->

						</div>
						<div><br><br>
<h2>Why you’ll love it:</h2>
for its freshness. It’s light and refreshing like a sip of ice tea on a scorching afternoon. Fresh citrus fruits, slightly tart rhubarb and a selection of strong spices.
<br> <br>
<h4>Family: <i>citrus</i></h4> 
<h4>Perception: <i>light, green</i></h4>
<h4>Projection: <i>subtle</i></h4>
<h4>Category: <i>casual</i></h4> 
<h4>Fragrance architecture:
<br><i>Head note: mint, green tea, lemon, orange, rhubarb</i>
<br><i>Heart note: carnation, fennel, jasmine, oakmoss</i>
<br><i>Base note: musk, cloves, ambergris, caraway</i></h4>



						</div>
					</div><!--/product-details-->
	
				</div>
