
				<div class="col-sm-9 padding-right">
					<div class="product-details"><!--product-details-->
						<div class="col-sm-5">
							<div class="view-product">
								<img src="images/product/perfumy_35.jpg" alt="" />
								
							</div>
							

						</div>
						<div class="col-sm-7">
							<div class="product-information"><!--/product-information-->
								<!-- <img src="images/product-details/new.jpg" class="newarrival" alt="" /> --> 
								<h2>Perfume Woman #35</h2><p>freesia - sandalwood - suede</p>
								<p>Product code: 101035</p>
								<p>Fragrance concetration: 20%</p>
								<!-- <span>
									<span>US $59</span>
									<label>Quantity:</label>
									<input type="text" value="3" />
									<button type="button" class="btn btn-fefault cart">
										<i class="fa fa-shopping-cart"></i>
										Add to cart
									</button>
								</span> -->
								<p><b>50 ml</b> In Stock</p>

								
							</div><!--/product-information-->

						</div>
						<div><br><br>
<h2>Why you’ll love it:</h2>
for its surprising combinations. Unmatched freshness of green apple, freesia and roses, completed by velvety tones of suede and sandalwood.
<br> <br>
<h4>Family: <i>floral and woody</i></h4> 
<h4>Perception: <i>fresh, invigorating</i></h4>
<h4>Projection: <i>moderate</i></h4>
<h4>Category: <i>sport</i></h4> 
<h4>Fragrance architecture:
<br><i>Head note: green apple, black pepper, freesia</i>
<br><i>Heart note: hibiscus, rose, heliotrope</i>
<br><i>Base note: suede, sandalwood</i></h4>



						</div>
					</div><!--/product-details-->

				</div>
