
				<div class="col-sm-9 padding-right">
					<div class="product-details"><!--product-details-->
						<div class="col-sm-5">
							<div class="view-product">
								<img src="images/product/perfumy_22.jpg" alt="" />
								
							</div>
							

						</div>
						<div class="col-sm-7">
							<div class="product-information"><!--/product-information-->
								<!-- <img src="images/product-details/new.jpg" class="newarrival" alt="" /> -->
								<h2>Perfume Man #22</h2><p>lemon - leather notes - ambergris </p>
								<p>Product code: 101022</p>
								<p>Fragrance concetration: 20%</p>
								<!-- <span>
									<span>US $59</span>
									<label>Quantity:</label>
									<input type="text" value="3" />
									<button type="button" class="btn btn-fefault cart">
										<i class="fa fa-shopping-cart"></i>
										Add to cart
									</button>
								</span> -->
								<p><b>50 ml</b> In Stock</p>

								
							</div><!--/product-information-->

						</div>
						<div><br><br>
<h2>What will seduce you:</h2>
everything. From strong, sensual leather notes to vibrant, slightly tart citrus and sweet violet notes. A composition for bold and confident men.
<br> <br>
<h4>Family: <i>oriental woody</i></h4> 
<h4>Perception: <i>strong, leathery</i></h4>
<h4>Projection: <i>strong</i></h4>
<h4>Category: <i>adventure</i></h4> 
<h4>Fragrance architecture:
<br><i>Head note: lemon, orange</i>
<br><i>Heart note: cedar, violet, coriander, leathery notes</i>
<br><i>Base note: ambergris, tonka beans, storax</i></h4>




						</div>
					</div><!--/product-details-->

				</div>
