
				<div class="col-sm-9 padding-right">
					<div class="product-details"><!--product-details-->
						<div class="col-sm-5">
							<div class="view-product">
								<img src="images/product/GEL_1000x1000_2.png" alt="" />
								
							</div>
							

						</div>
						<div class="col-sm-7">
							<div class="product-information"><!--/product-information-->
								<!-- <img src="images/product-details/new.jpg" class="newarrival" alt="" /> -->
								<h2>DAILY MOISTURISING BODY GEL</h2>
								<p>Product code: 201001</p>
								
								<!-- <span>
									<span>US $59</span>
									<label>Quantity:</label>
									<input type="text" value="3" />
									<button type="button" class="btn btn-fefault cart">
										<i class="fa fa-shopping-cart"></i>
										Add to cart
									</button>
								</span> -->
								<p><b>250 ml</b> In Stock</p>

								
							</div><!--/product-information-->

						</div>
						<div><br><br>
						<h2>Do you know how to have a Good morning?</h2>
The morning shower invigorates and spurs you into action, while the evening bath improves your 
mood and relieves fatigue after a long day. With this special moment in mind, we created a
DAILY MOISTURISING BODY GEL 
that will off er you a daily dose of pure pleasure. It contains Xeradin™, a unique, plant-based ingredient, 
which is a natural source of 24-hour hydration. Its special oil formula creates a delicate foam that 
perfectly cleans and conditions your skin, leaving it refreshed. And the marvellous scent of original 
French essential oils will help you relax and unwind even more, transporting you to the world of 
senses.

<h3>What our secret is:</h3>
The botanic complex of extracts from fi ve 
algae rich in mineral salts, calcium, phosphorus, 
iodine and vitamins, that naturally revitalise 
and improve the appearance of your skin.  

<h3>Why you’ll like it:</h3>
For the fantasti cally fragrant, soft and velvet-
smooth skin that stays moisturised for a long 
time.

<h3>How to use it:</h3>
Apply a small amount of wash on wet skin, 
massage delicately unti l velvety foam appears, 
then rinse.

<h3>What is that beautiful scent:</h3>
black currant, bergamot, rose, lily of the valley, 
moss, musk and cedar wood comprise a 
fragrant compositi on both of you will readily 
use.


						</div>
					</div><!--/product-details-->
					
					
					
					
					
				</div>
