
				
				<div class="col-sm-9 padding-right">
					<div class="product-details"><!--product-details-->
						<div class="col-sm-5">
							<div class="view-product">
								<img src="images/product/202001.jpg" alt="" />
								
							</div>
							

						</div>
						<div class="col-sm-7">
							<div class="product-information"><!--/product-information-->
								<!-- <img src="images/product-details/new.jpg" class="newarrival" alt="" /> -->
								<h2>DAILY MOISTURISING BODY SCRUB</h2>
								<p>Product code: 202001</p>
								
								<!-- <span>
									<span>US $59</span>
									<label>Quantity:</label>
									<input type="text" value="3" />
									<button type="button" class="btn btn-fefault cart">
										<i class="fa fa-shopping-cart"></i>
										Add to cart
									</button>
								</span> -->
								<p><b>250 ml</b> In Stock</p>

								
							</div><!--/product-information-->

						</div>
						<div><br><br>
						<h2>Do you know the secret to having velvety smooth skin?</h2>
For the skin to maintain its smooth and young appearance, it needs intensive cleansing. The systematic 
removal of dead skin cells during a relaxing massage in the shower or bath is a great way to make the 
skin more fi rm and to strengthen it. It is with this in mind, that the 
DAILY MOISTURISING BODY SCRUB 
was created, which perfectly cleanses and conditions the skin. The body scrub contains fi nely ground 
apricot kernels that stimulate microcirculation and ensure the skin is perfectly smooth, while the plant 
compounds help to keep the skin properly hydrated. Thanks to the content of original French essential 
oils, the scrub has a beautiful, sensual fragrance that will allow you to detach yourself from reality for 
a while.  

<h3>What our secret is:</h3>
a botanical compound of extracts from fi ve 
algae, rich in minerals, polysaccharides and 
amino acids, that help maintain the proper 
level of hydrati on, restore vitality and improve 
the appearance of the skin.   

<h3> What you will love about it:</h3>
the eff ect of incredibly smooth, soft  and toned 
skin, perfectly prepared to take in the precious 
acti ve ingredients contained in other body 
care products.

<h3>How to use it:</h3>
apply a small amount of the body scrub on 
wet skin and massage with circular moti ons, 
then rinse with water. Apply 2-3 ti mes a week. 
Remember to shake it well before each use.

<h3> What is that beautiful scent:</h3>
blackcurrant, bergamot, rose, lily-of-the-valley, 
moss, musk and cedar wood create a fragrance 
compositi on, that you will both use with 
pleasure.


						</div>
					</div><!--/product-details-->
					
					
					
					
					
				</div>
