
				
				<div class="col-sm-9 padding-right">
					<div class="product-details"><!--product-details-->
						<div class="col-sm-5">
							<div class="view-product">
								<img src="images/product/203001.png" alt="" />
								
							</div>
							

						</div>
						<div class="col-sm-7">
							<div class="product-information"><!--/product-information-->
								<!-- <img src="images/product-details/new.jpg" class="newarrival" alt="" /> -->
								<h2>DAILY MOISTURISING BODY BALM</h2>
								<p>Product code: 202001</p>
								
								<!-- <span>
									<span>US $59</span>
									<label>Quantity:</label>
									<input type="text" value="3" />
									<button type="button" class="btn btn-fefault cart">
										<i class="fa fa-shopping-cart"></i>
										Add to cart
									</button>
								</span> -->
								<p><b>250 ml</b> In Stock</p>

								
							</div><!--/product-information-->

						</div>
						<div><br><br>
						<h2>Do you know the secret of beautiful skin?</h2>
The secret to beautiful, smooth and soft skin lies in everyday care based on appropriate moisturisation . 
It’s the simplest way to feel confi dent and comfortable in your own skin. We thought about it when we 
created a light 
DAILY MOISTURISING BODY BALM 
that thanks to its benefi cial ingredients will eff ectively hydrate and nourish your skin, protecting it from 
dryness. It provides immediate and long-lasting eff ect, as it contains Xeradin™, a unique, plant-based 
ingredient that visibly improves the functioning of your skin, reducing the loss of moisture. The balm 
absorbs quickly, leaving the skin supple, incredibly soft and smooth to the touch. And its beautiful, 
relaxing fragrance will stay with you all day long.

<h3>What is our secret:</h3>
the complex of extracts from fi ve algae rich 
in minerals, polysaccharides and amino acids 
that naturally revitalise and improve the 
appearance of your skin, helping to maintain 
the right level of moisturiati on.
  
<h3>What you will love it for:</h3>
for the long-lasti ng moisturising eff ect, 
a pleasant feeling of comfort and velvet 
smoothness of your skin.

<h3>How to use it:</h3>
apply a small amount on your skin and 
delicately massage unti l absorbed. Use for 
everyday moisturisati on aft er a shower or 
a bath. 

<h3>What is that beautiful scent:</h3>
black currant, bergamot, rose, lily of the valley, 
moss, musk and cedar wood comprise a 
fragrant compositi on both of you will readily 
use.


						</div>
					</div><!--/product-details-->
					
					
					
					
					
				</div>
