
				
				<div class="col-sm-9 padding-right">
					<div class="product-details"><!--product-details-->
						<div class="col-sm-5">
							<div class="view-product">
								<img src="images/product/204001.jpg" alt="" />
								
							</div>
							

						</div>
						<div class="col-sm-7">
							<div class="product-information"><!--/product-information-->
								<!-- <img src="images/product-details/new.jpg" class="newarrival" alt="" /> -->
								<h2>DAILY MOISTURISING HAND CREAM</h2>
								<p>Product code: 206001</p>
								
								<!-- <span>
									<span>US $59</span>
									<label>Quantity:</label>
									<input type="text" value="3" />
									<button type="button" class="btn btn-fefault cart">
										<i class="fa fa-shopping-cart"></i>
										Add to cart
									</button>
								</span> -->
								<p><b>50 ml</b> In Stock</p>

								
							</div><!--/product-information-->

						</div>
						<div><br><br>
						<h2>How does the invisible glove work?</h2>
We pull them out to greet others and we touch our loved ones with them. No wonder we want 
our hands to look beautiful and well cared for. To make sure they’re always pleasant to the 
touch and velvety smooth, we have developed the 
DAILY MOISTURISING HAND 
CREAM 
whose active ingredients act as an „invisible glove”, wrapping the skin and protecting it from 
dryness. The cream leaves a subtle fi lm on the skin reinforcing the protective barrier of the skin. 

<h3>What you will love it for:</h3>
its acti ve ingredients form an „invisible 
glove” on the palm of your hand that 
protects the epidermis against water loss. 
Thanks to this, the skin of your hands is 
bett er moisturized, smoother, and firm.   
  
<h3>What is our secret:</h3>
the combinati on of a complex of fi ve algae 
with an extract from fi g prickly pear and 
Canola oil. 

<h3>What will delight you about it:</h3>
you will feel its eff ect aft er just one 
applicati on.   

<h3>What will make you not want to trade it for any other: </h3>
You will experience fi rst hand the 
eff ects of the rich compositi on, that 
not only moisturizes the skin, but also 
regenerates it.

<h3>What else are we proud of:</h3>
we have created a cream rich 
in moisturizing ingredients, but 
extraordinally light and non-greasy in 
texture. This is essenti al for us because 
we do not like having moist or greasy 
hands.

<h3>What is that beautiful scent: </h3>
blackcurrant, rose, lily of the valley, moss, 
musk and cedar wood. 


						</div>
					</div><!--/product-details-->
					
					
					
					
					
				</div>
