
				<div class="col-sm-9 padding-right">
					<div class="product-details"><!--product-details-->
						<div class="col-sm-5">
							<div class="view-product">
								<img src="images/product/205001.jpg" alt="" />
								
							</div>
							

						</div>
						<div class="col-sm-7">
							<div class="product-information"><!--/product-information-->
								<!-- <img src="images/product-details/new.jpg" class="newarrival" alt="" /> -->
								<h2>DAILY SHAMPOO REPAIR & PROTECT </h2>
								<p>Product code: 205001</p>
								
								<!-- <span>
									<span>US $59</span>
									<label>Quantity:</label>
									<input type="text" value="3" />
									<button type="button" class="btn btn-fefault cart">
										<i class="fa fa-shopping-cart"></i>
										Add to cart
									</button>
								</span> -->
								<p><b>250 ml</b> In Stock</p>

								
							</div><!--/product-information-->

						</div>
						<div><br><br>
						<h2>What does it take to have healthy and beautiful hair? </h2>
Strong and well-groomed hair is our pride . Choose eff ective care to keep them healthy and shiny. Our 
DAILY SHAMPOO REPAIR & PROTECT 
for everyday use, created for normal, dry and damaged hair, combines gentle washing properties with 
intensive rebuild and protection. It contains bamboo leaf extract, which prevents irritation and protects 
hair against free radicals, and botanical complex of 5 algae, which helps to maintain proper level of 
hydration. We added to it a mineral-rich sea water from the depths of the earth with a strengthening 
and mineralizing effect.

<h3>Which is our secret:</h3>
Keracyn™ – an acti ve ingredient that visibly 
improves the conditi on of hair, strengthens it 
and protects it from external damage, resulti ng 
in a shine typical of healthy hair.
  
<h3>Why will you love it:</h3>
for a signifi cant improvement in the conditi on 
of your hair, which is more durable, shiny, 
bett er arranged and does not puff . They are 
also more resistant to damage caused by 
external factors, including sunlight.

<h3>How to use it: </h3>
apply the shampoo to wet hair, gently rub it in 
and rinse. Repeat if necessary. Use it together 
with Hair Rebuilding & Protecti on Conditi oner. 

<h3>What smells so beautiful:</h3>
blackcurrant, bergamot, rose, lily of the valley, 
moss, musk and cedar wood create a fragrance 
compositi on, which both of you will love to 
reach for.


						</div>
					</div><!--/product-details-->

				</div>
