
				
				<div class="col-sm-9 padding-right">
					<div class="product-details"><!--product-details-->
						<div class="col-sm-5">
							<div class="view-product">
								<img src="images/product/205002.jpg" alt="" />
								
							</div>
							

						</div>
						<div class="col-sm-7">
							<div class="product-information"><!--/product-information-->
								<!-- <img src="images/product-details/new.jpg" class="newarrival" alt="" /> -->
								<h2>DAILY HAIR CONDITIONER REPAIR & PROTECT </h2>
								<p>Product code: 205002</p>
								
								<!-- <span>
									<span>US $59</span>
									<label>Quantity:</label>
									<input type="text" value="3" />
									<button type="button" class="btn btn-fefault cart">
										<i class="fa fa-shopping-cart"></i>
										Add to cart
									</button>
								</span> -->
								<p><b>250 ml</b> In Stock</p>

								
							</div><!--/product-information-->

						</div>
						<div><br><br>
						<h2>How to take care of your hair?</h2>
						Healthy and shiny hair makes us feel attractive . That’s why it’s worth using a conditioner that will make 
us enjoy their perfect look every day. 
DAILY HAIR CONDITIONER 
REPAIR & PROTECT 
for normal, dry and damaged hair contains selected ingredients that intensively regenerate and rebuild 
damaged hair. Keracyn™, an active ingredient derived from artichoke, protects them from the negative 
eff ects of external factors, including sunlight. Signifi cantly improves their condition and vitality and 
cares for their shine. Bamboo leaf extract protects hair from the harmful eff ects of free radicals, and sea 
water from the depths of the earth remineralizes and strengthens them.

<h3>What is our secret:</h3>
a complex of 7 vegetable oils, rich in fatt y acids 
and vitamins A, D and E, which eff ecti vely 
moisturizes and regenerates hair.  
  
<h3>Why will you love it:</h3>
a lightweight formula that doesn’t stress your 
hair and for strong, healthy and shiny hair that 
is more resistant to external factors, less prone 
to stati c and easier to comb.  

<h3> How to use it:</h3>
apply a small amount to wet hair and rub 
it gently. Aft er a while, rinse with warm 
water. Use together with Hair Shampoo 
Rebuilding & Protecti on. 

<h3>What smells so beautiful: </h3>
blackcurrant, bergamot, rose, lily of the valley, 
moss, musk and cedar wood create a fragrance 
compositi on, which both of you will love to 
reach for.


						</div>
					</div><!--/product-details-->
					
					
					
					
					
				</div>
