
				<div class="col-sm-9 padding-right">
					<div class="product-details"><!--product-details-->
						<div class="col-sm-5">
							<div class="view-product">
								<img src="images/product/305001.jpg" alt="" />
								
							</div>
							

						</div>
						<div class="col-sm-7">
							<div class="product-information"><!--/product-information-->
								<!-- <img src="images/product-details/new.jpg" class="newarrival" alt="" /> -->
								<h2>MICELLAR LIQUID 3 IN 1</h2>
								<p>Product code: 305001</p>
								
								<!-- <span>
									<span>US $59</span>
									<label>Quantity:</label>
									<input type="text" value="3" />
									<button type="button" class="btn btn-fefault cart">
										<i class="fa fa-shopping-cart"></i>
										Add to cart
									</button>
								</span> -->
								<p><b>200 ml</b> In Stock</p>

								
							</div><!--/product-information-->

						</div>
						<div><br><br>
						<h2>How to eff ectively and quickly remove makeup and cleanse the face?</h2>
Makeup removal, cleansing and toning are three essential steps in caring for a fresh and attractive 
skin appearance every day. However, morning facial cleansing and evening make-up removal can 
be time-consuming and tiring. That’s why we created 
MICELLAR LIQUID 3 IN 1 
– a multifunctional, extremely delicate micellar liquid that will take care of your skin in 
a comprehensive way. The daily ritual of morning skin cleansing and evening makeup removal 
has never been so simple and pleasant! 3 IN 1 MICELLAR LIQUID incredibly eff ectively and quickly 
removes make-up, including waterproof mascara, eliminates sebum and dirt from the skin 
surface and restores skin pH - without rinsing! Recommended for face, neck and neckline. 

<h3>What you will love it for:</h3>
for the richness of acti ve substances 
that will ensure the perfect conditi on 
of your skin. 3 IN 1 MICELLAR LIQUID 
contains a complex of ingredients 
ensuring the balance of skin microbiota, 
which makes the skin regain its proper 
pH and beauti ful appearance. The Goji 
berries extract adds vitality to the skin, 
and the salt of hyaluronic acid perfectly 
moisturizes the skin, ensuring its 
fi rmness and elasti city.  
  
<h3>What will delight you about it:</h3>
eff ecti veness and speed with which it 
removes even waterproof makeup and 
the incredible eff ect of deeply cleansed 
and toned skin without the feeling of 
ti ghtness. Perfectly prepares the skin for 
the applicati on of cream or serum.  

<h3>What will provide you with extra protection:</h3>
MICELLAR LIQUID 3 IN 1 has been tested 
under the supervision of an ophthalmologist 
and is also recommended for people with 
sensiti ve eyes and wearing contact lenses. 
The gentle formula is suitable for all skin 
types, including sensiti ve ones.
 
<h3>How to use it:</h3>
in order to thoroughly cleanse and tone 
the skin, apply a small amount of liquid 
to the pad and wipe the face, neck and 
neckline. To remove eye make-up, place 
the liquid-soaked pad on the closed 
eyelids and hold for a while. No fl ushing 
required.


						</div>
					</div><!--/product-details-->

				</div>
