
				<div class="col-sm-9 padding-right">
					<div class="product-details"><!--product-details-->
						<div class="col-sm-5">
							<div class="view-product">
								<img src="images/product/501001.jpg" alt="" />
								
							</div>
							

						</div>
						<div class="col-sm-7">
							<div class="product-information"><!--/product-information-->
								<!-- <img src="images/product-details/new.jpg" class="newarrival" alt="" /> -->
								<h2>ANTIODOUR HAND WASH</h2>
								<p>Product code: 501001</p>
								
								<!-- <span>
									<span>US $59</span>
									<label>Quantity:</label>
									<input type="text" value="3" />
									<button type="button" class="btn btn-fefault cart">
										<i class="fa fa-shopping-cart"></i>
										Add to cart
									</button>
								</span> -->
								<p><b>250 ml</b> In Stock</p>

								
							</div><!--/product-information-->

						</div>
						<div><br><br>
						<h2>How to remove the smell of garlic from your hands?</h2>
						Use the amazing 
ANTI-ODOUR HAND WASH 
As with a flick of the magic wand, it removes all the nasty smells from your palms: garlic, onion, 
fi sh, old vegetables. Every time you put your fi ngers in the thick, creamy foam, the stubborn 
odors go away. Now, you can enjoy the aroma of delicious dishes.

<h4>What you will love it for:</h4>
for instant delivery from an unpleasant smell 
on your hands.  
  
<h4>Why it’s so perfect for your hands:</h4>
Why it’s so perfect for your hands: we use 
delicate cleaning agents. Our soap moisturizes 
and smooths your skin. The hand care
 formula, developed especially for us, is based on cott on 
extract and polysaccharides from the Peruvian 
tara plant (Caesalpinia spinosa).  

<h4>What assures additional safety:</h4>
Before you could hold the foam in your 
hand, it went through a number of detailed 
tests, including dermatological tests. We use 
allergen-free fragrance oils compliant with 
IFRA standards (Internati onal Fragrance 
Associati on).  <br>
 
<h4>What you’ll love about it:</h4>
the foam successfully removes vegetable and 
fruit stains (beetroots, carrots, berries).

<h4>What is that beautiful scent:</h4>
fresh, green notes, white fl ours and juicy 
citrus. 

						</div>
					</div><!--/product-details-->

				</div>
