
				<div class="col-sm-9 padding-right">
					<div class="product-details"><!--product-details-->
						<div class="col-sm-5">
							<div class="view-product">
								<img src="images/product/501001.jpg" alt="" />
								
							</div>
							

						</div>
						<div class="col-sm-7">
							<div class="product-information"><!--/product-information-->
								<!-- <img src="images/product-details/new.jpg" class="newarrival" alt="" /> -->
								<h2>GREASE BUSTER</h2>
								<p>Product code: 501001</p>
								
								<!-- <span>
									<span>US $59</span>
									<label>Quantity:</label>
									<input type="text" value="3" />
									<button type="button" class="btn btn-fefault cart">
										<i class="fa fa-shopping-cart"></i>
										Add to cart
									</button>
								</span> -->
								<p><b>500 ml</b> In Stock</p>

								
							</div><!--/product-information-->

						</div>
						<div><br><br>
						<h2>How to remove dried grease from the stove?</h2>
This is our secret weapon: 
GREASE BUSTER 
Burned or dry fat, soot, sticky marks or dry juice stains do not stand a chance. Vinegar essence 
and natural solvents help immediately remove even old stains, while remaining safe for the 
cleaned surface.

<h4>What you will love it for:</h4>
surfaces become clean and shiny without 
scrubbing. 
  
<h4>What will delight you about it:</h4>
it is effi cient even in hard and cold water.

<h4>What assures additional safety:  </h4>
certi fi cate of the Polish Nati onal Insti tute 
of Hygiene.<br>
 
<h4>What you can clean with it:</h4>
table tops, kitchen cupboards and shelves, 
ti les, sinks, venti lati on hoods, extracti on 
fans, gas and electric cookers, fridges, ovens, 
grills, grates, deep fryers and other kitchen 
appliances.

<h4>What is that beautiful scent:</h4>
linden blossom, fresh, juicy fruit and noble 
cedar wood.

<h4>SEE HOW SIMPLE IT IS TO USE:</h4>
spray the surface to be 
cleaned, wait a while, then 
rinse with clean water and 
wipe dry. Finished!
						</div>
					</div><!--/product-details-->

				</div>
