
				<div class="col-sm-9 padding-right">
					<div class="product-details"><!--product-details-->
						<div class="col-sm-5">
							<div class="view-product">
								<img src="images/product/501004.jpg" alt="" />
								
							</div>
							

						</div>
						<div class="col-sm-7">
							<div class="product-information"><!--/product-information-->
								<!-- <img src="images/product-details/new.jpg" class="newarrival" alt="" /> -->
								<h2>WASHING-UP GEL</h2>
								<p>Product code: 501004</p>
								
								<!-- <span>
									<span>US $59</span>
									<label>Quantity:</label>
									<input type="text" value="3" />
									<button type="button" class="btn btn-fefault cart">
										<i class="fa fa-shopping-cart"></i>
										Add to cart
									</button>
								</span> -->
								<p><b>500 ml</b> In Stock</p>

								
							</div><!--/product-information-->

						</div>
						<div><br><br>
						<h2>Who will do the dishes to day?</h2>
						Cooking with your friends or family is such fun. What a shame that after every meal, even 
the most magnifi cent one, you need to face a pile of dirty dishes. Don’t lose your appetite! 
One drop of our 
WASHING-UP GEL 
will easily remove grease, rests of food and other stains. It is very effective, efficient, and safe 
even for the most delicate china.

<h4>What you will love it for:</h4>
it’s very gentle on your skin. You don’t need to 
wear gloves, because our gel contains fantasti c 
moisturizing agents. 
  
<h4>Why it’s so perfect for your hands:</h4>
when you’re doing the dishes, we’re taking 
care of your hands. Our gel contains only 
gentle cleaning agents. In order to protect 
your hands, we enriched the formula with 
rice oil, herbal complex containing yarrow, 
marigold, chestnut, witch-hazel, St John’s wort, 
hollyhock, camomile, mint and polysaccharides 
of the Peruvian tara plant 
(Caesalpinia spinosa).  

<h4>What assures additional safety:</h4>
before this gel made its way to your kitchen, 
it went through a number of detailed tests, 
including dermatological tests confi rming skin 
tolerance We use allergen-free fragrance oils 
compliant with IFRA standards (Internati onal 
Fragrance Associati on). The gel has received 
the certi fi cate of the Polish Nati onal Insti tute 
of Hygiene. We took care of everything, 
because your sati sfacti on is of essence to us.<br>
 
<h4>What is that beautiful scent:</h4>
fresh mint, pine needles, sweet rose, lavender 
and sensual sandalwood.

<h4>What do users say?</h4>
Exactly 100% of respondents* stated 
that the dishwashing gel not only easily 
removes grease, food left overs and other 
soiling, but it is also gentle on the skin and 
washes dishes perfectly even in cold water.

<br>* Independent consumer research conducted on a group of 25 people.

<h4>SEE HOW SIMPLE IT IS TO USE:</h4>
apply a small amount of 
the gel to a dishwashing 
sponge, and aft er washing, 
rinse the dishes thoroughly 
with water, wipe them dry 
or just leave on the drainer.

<h4>Price of the set with a designer pump: <i>Product code: 591204</i></h4>
						</div>
					</div><!--/product-details-->

				</div>
