
				<div class="col-sm-9 padding-right">
					<div class="product-details"><!--product-details-->
						<div class="col-sm-5">
							<div class="view-product">
								<img src="images/product/501003.jpg" alt="" />
								
							</div>
							

						</div>
						<div class="col-sm-7">
							<div class="product-information"><!--/product-information-->
								<!-- <img src="images/product-details/new.jpg" class="newarrival" alt="" /> -->
								<h2>KITCHEN SMART SPRAY</h2>
								<p>Product code: 501003</p>
								
								<!-- <span>
									<span>US $59</span>
									<label>Quantity:</label>
									<input type="text" value="3" />
									<button type="button" class="btn btn-fefault cart">
										<i class="fa fa-shopping-cart"></i>
										Add to cart
									</button>
								</span> -->
								<p><b>500 ml</b> In Stock</p>

								
							</div><!--/product-information-->

						</div>
						<div><br><br>
						<h2>How to clean your kitchen faster?</h2>
Imagine that you just spray and wipe, and the kitchen is spotlessly clean. 
This is the way our 
KITCHEN SMART SPRAY 
works. You will clean almost everything in no time at all: countertops, kitchen appliances, 
window sills, rubbish bins and ceramic cooktops. It’s versatile: it cleans, degreases, neutralizes 
unpleasant odours and leaves a glossy finish.

<h4>What you will love it for:</h4>
it acts really fast. Just spray and wipe clean. 
It’s quicker than texting.
  
<h4>Surfaces you can use it for:</h4>
all washable surfaces, wooden, MDF, 
laminated, plasti c and even marble worktops 
and window sills.  

<h4>What assures additional safety:</h4>
certi fi cate of the Polish Nati onal Insti tute of 
Hygiene. You can use it on surfaces that come 
into contact with food.<br>
 
<h4>What is that beautiful scent:</h4>
exoti c ylang-ylang and sandalwood, 
accompanied by fresh geranium and bergamot 
notes.

<h4>SEE HOW SIMPLE IT IS TO USE: </h4>
spray the surface to be 
cleaned and then wipe 
it with a damp cloth or rinse 
with clean water and wipe 
dry. Finished!

						</div>
					</div><!--/product-details-->

				</div>
