
				<div class="col-sm-9 padding-right">
					<div class="product-details"><!--product-details-->
						<div class="col-sm-5">
							<div class="view-product">
								<img src="images/product/502004.jpg" alt="" />
								
							</div>
							

						</div>
						<div class="col-sm-7">
							<div class="product-information"><!--/product-information-->
								<!-- <img src="images/product-details/new.jpg" class="newarrival" alt="" /> -->
								<h2>TOILET EXPERT</h2>
								<p>Product code: 502004</p>
								
								<!-- <span>
									<span>US $59</span>
									<label>Quantity:</label>
									<input type="text" value="3" />
									<button type="button" class="btn btn-fefault cart">
										<i class="fa fa-shopping-cart"></i>
										Add to cart
									</button>
								</span> -->
								<p><b>750 ml</b> In Stock</p>

								
							</div><!--/product-information-->

						</div>
						<div><br><br>
						<h2>A stress-free way to clean your toilet</h2>
						Cleaning a toilet is not our favourite thing to do. We don’t like the smell of chlorine, either. This is 
why we’ve developed an effi  cient solution to clean the toilet fast and make the entire bathroom 
smell lovely: 
TOILET EXPERT 
The gel quick clean formula instantly removes even the toughest stains. Based on modern 
silicones and natural lactic acid, Toilet Expert leaves the surface perfectly clean and shiny, and 
the original fragrance composition containing French oils gives off  a beautiful, fresh smell.

<h4>Why you won’t trade it for any other product:</h4>
you don’t need to choose between a 
hygienically clean toilet and a lovely scent.   
  
<h4>What you can use it for:</h4>
toilet bowls, bidets, sinks and ceramic shower 
bases.

<h4>What is that beautiful scent:</h4>
juicy fruits, sweet vanilla and coconut.<br>
 
<h4>What is our secret:</h4>
the effi  cient gel formula works well both 
in hot and cold water. The thick gel doesn’t 
trickle down the surface — it covers it up, 
allowing the acti ve ingredients to do their 
job. The gel also works below the water level. 
And the important thing is that it does not 
contain a drop of chlorine.

<h4>SEE HOW SIMPLE IT IS TO USE: </h4>
pour the gel on the surface 
to be cleaned and leave it 
on for a few minutes. Scrub 
with a brush if necessary. 
Rinse thoroughly with 
water. 

						</div>
					</div><!--/product-details-->

				</div>
