
				<div class="col-sm-9 padding-right">
					<div class="product-details"><!--product-details-->
						<div class="col-sm-5">
							<div class="view-product">
								<img src="images/product/502001.jpg" alt="" />
								
							</div>
							

						</div>
						<div class="col-sm-7">
							<div class="product-information"><!--/product-information-->
								<!-- <img src="images/product-details/new.jpg" class="newarrival" alt="" /> -->
								<h2>BATHROOM SMART SPRAY</h2>
								<p>Product code: 502001</p>
								
								<!-- <span>
									<span>US $59</span>
									<label>Quantity:</label>
									<input type="text" value="3" />
									<button type="button" class="btn btn-fefault cart">
										<i class="fa fa-shopping-cart"></i>
										Add to cart
									</button>
								</span> -->
								<p><b>500 ml</b> In Stock</p>

								
							</div><!--/product-information-->

						</div>
						<div><br><br>
						<h2>How to clean your bathroom in 5 minutes?</h2>
Do you have the impression that your bathroom needs cleaning all the time? 
We get this feeling completely so we created 
BATHROOM SMART SPRAY 
Now cleaning will take fi ve minutes at most. It contains our dirt stop complex. 
With every application, the cleaned surface becomes protected and dirt cannot 
build up again. And in order to make your bathroom feel as a most extravagant SPA, 
the fragrant oils used in the spray were sourced directly in France. 

<h4>What you will love it for:</h4>
from now on, when you disappear in the 
bathroom for longer than 10 minutes, it can 
mean only one thing — you want a long bath.  
  
<h4>What will delight you about it:</h4>
thanks to the smart formula the cleaning will 
take shorter, and the result will last longer. 
It will be our litt le secret. Whether you share 
it with your family or not — it’s your decision.

<h4>What you can clean with it:</h4>
practi cally everything. Bathtub, washbasin, 
bidet, toilet bowl, tap, and even bigger 
surfaces, such as the fl oor and walls.<br>
 
<h4>What is that beautiful scent:</h4>
fresh pomegranate, luscious plums, almonds 
and cherry blossom.

<h4>What do users say?</h4>
100% of respondents* confi rmed that 
the spray gives a long-lasti ng eff ect of 
cleanliness, protects the cleaned surface 
from redepositi ng of dirt, adds shine to 
cleaned surfaces and works great as a 
product for cleaning even large fl oor or 
wall surfaces.

<br>* Independent consumer research conducted on a group of 25 people.

<h4>SEE HOW SIMPLE IT IS TO USE: </h4>
this liquid practi cally does the 
work for you. Sprinkle it on 
the sink, bathtub or tap, wait 
a moment. Wipe with a damp 
sponge or cloth and rinse 
thoroughly with water.

<h4>Price of the set with a two-phase spray:  <i>Product code: 592101</i></h4>
						</div>
					</div><!--/product-details-->

				</div>
