
				<div class="col-sm-9 padding-right">
					<div class="product-details"><!--product-details-->
						<div class="col-sm-5">
							<div class="view-product">
								<img src="images/product/502006.jpg" alt="" />
								
							</div>
							

						</div>
						<div class="col-sm-7">
							<div class="product-information"><!--/product-information-->
								<!-- <img src="images/product-details/new.jpg" class="newarrival" alt="" /> -->
								<h2>ANTIBACTERIAL HAND FOAM</h2>
								<p>Product code: 502006</p>
								
								<!-- <span>
									<span>US $59</span>
									<label>Quantity:</label>
									<input type="text" value="3" />
									<button type="button" class="btn btn-fefault cart">
										<i class="fa fa-shopping-cart"></i>
										Add to cart
									</button>
								</span> -->
								<p><b>250 ml</b> In Stock</p>

								
							</div><!--/product-information-->

						</div>
						<div><br><br>
						<h2>How to keep your hands hygienically clean?</h2>
						The best way to get rid of germs is washing your hands often. This is why we developed 
a creamy antibacterial hand foam: 
ANTIBACTERIAL HAND FOAM 
To create this thick foam, we used very delicate cleaning agents. They prevent the skin from 
losing its protective lipid barrier, while moisturizing and softening it. This fragrant product 
effi  ciently washes, protects and cares for sensitive skin of your hands, leaving it hygienically 
clean. It makes washing your hands a pleasant daily ritual. 

<h4>Why you’ll like it:</h4>
it has anti bacterial properti es and an unusually 
delicate hypoallergenic formula created for 
everyday care of your hands.  
  
<h4>What protects your hands so perfectly:</h4>
to create this thick foam, we used very 
delicate cleaning agents. They prevent the skin 
from losing its protecti ve lipid barrier, while 
moisturizing and soft ening it. The 
clean & care 
formula based on natural anti bacterial 
ingredients combines the look-improving and 
roughness-reducing 
WHITESENSET 
 complex 
(from delicate white fl owers, centi folia rose, 
jasmine and daisy) with anti oxidizing and anti -
aging acti on of the centi folia rose extract 
(Rosa centi folia).  

<h4>What assures additional safety:</h4>
before you got the foam, it went through 
a range of detailed assessments, including 
dermatological testi ng, confi rming skin 
tolerance. The hypoallergenic formula cares 
for your hands without causing oversensiti vity 
or allergies.
 
<h4>What will pleasantly surprise you:</h4>
the foam’s pH is neutral for your skin, which 
helps to reduce skin dryness.

<h4>What is that beautiful scent:</h4>
juicy apple and pear, delicate lily and fresh 
bamboo notes.



						</div>
					</div><!--/product-details-->

				</div>
