
				<div class="col-sm-9 padding-right">
					<div class="product-details"><!--product-details-->
						<div class="col-sm-5">
							<div class="view-product">
								<img src="images/product/502005.jpg" alt="" />
								
							</div>
							

						</div>
						<div class="col-sm-7">
							<div class="product-information"><!--/product-information-->
								<!-- <img src="images/product-details/new.jpg" class="newarrival" alt="" /> -->
								<h2>RUST & LIMESCALE BUSTER</h2>
								<p>Product code: 502005</p>
								
								<!-- <span>
									<span>US $59</span>
									<label>Quantity:</label>
									<input type="text" value="3" />
									<button type="button" class="btn btn-fefault cart">
										<i class="fa fa-shopping-cart"></i>
										Add to cart
									</button>
								</span> -->
								<p><b>500 ml</b> In Stock</p>

								
							</div><!--/product-information-->

						</div>
						<div><br><br>
						<h2>How to remove rusty stains?</h2>
						If you are tired of matte surfaces and rusty stains, use our proven method: 
thick, active 
RUST & LIMESCALE BUSTER 
The gel covers the surface, brings back its shine and protects it against new residues. Instantly, 
it removes limescale, water and soap residue, rusty stains. Your bathroom fi xtures will be clean 
and shiny again.

<h4>  Why you won’t trade it for any other product:</h4>
once you use it, limescale will become history, 
forever.  
  
<h4>What you can use it for:</h4>
washtubs, washbasins, taps, showers, toilet 
bowls, and large surfaces (fl oors, walls).

<h4>Other things we took into account:</h4>
safe closing system.<br>
 
<h4>What is that beautiful scent:</h4>
sweet fruity notes with fresh orris and hibiscus 
notes. 

<h4>SEE HOW SIMPLE IT IS TO USE: </h4>
Apply the gel to the dirty 
surface, leave on for a few 
minutes, then wipe with 
a brush or sponge. Rinse 
thoroughly with water or 
wipe with a damp cloth. 

						</div>
					</div><!--/product-details-->

				</div>
