
				<div class="col-sm-9 padding-right">
					<div class="product-details"><!--product-details-->
						<div class="col-sm-5">
							<div class="view-product">
								<img src="images/product/502003.jpg" alt="" />
								
							</div>
							

						</div>
						<div class="col-sm-7">
							<div class="product-information"><!--/product-information-->
								<!-- <img src="images/product-details/new.jpg" class="newarrival" alt="" /> -->
								<h2>SINK & DRAIN UNBLOCKER</h2>
								<p>Product code: 502003</p>
								
								<!-- <span>
									<span>US $59</span>
									<label>Quantity:</label>
									<input type="text" value="3" />
									<button type="button" class="btn btn-fefault cart">
										<i class="fa fa-shopping-cart"></i>
										Add to cart
									</button>
								</span> -->
								<p><b>500 ml</b> In Stock</p>

								
							</div><!--/product-information-->

						</div>
						<div><br><br>
						<h2>How to unclog the sink yourself?</h2>
						If you do not want to call a plumber every time, we highly recommend our 
SINK & DRAIN UNBLOCKER 
This thick gel will help you out even if you’re dealing with a serious clog. It unclogs the drain 
precisely, acting in standing water. It also removes the unpleasant smell that occurs when pipes 
get blocked. You just pour the gel into the drain hole, make yourself a cup of coff ee and call 
your friends, and after 20 minutes you rinse with a lot of water.

<h4>What you will love it for:</h4>
it works instantly and is cheaper than a 
plumber. Apply it regularly once a month, and 
you can forget about clogged sinks forever.  
  
<h4>Other things we took into account:</h4>
the gel does not corrode steel pipes 
and rubber seals.

<h4>What you can use it for:</h4>
kitchen sink, siphon, toilet, shower base, 
bathtub, bathroom and kitchen drain pipes.<br>
 
<h4>What clogs it removes:</h4>
clogs made of built up grease, coff ee grounds 
and tea leaves, food rests, hair, paper or cott on 
wool.

<h4>Why it is unscented:</h4>
to dissuade you from smelling it.

<h4>SEE HOW SIMPLE IT IS TO USE: </h4>
pour 100 ml of the 
preparati on into the sink or 
toilet, leave for 20 minutes 
and rinse with a large 
amount of water. 

<h4>WHAT IS REALLY IMPORTANT FOR WOMEN</h4>
you can forget the 
plumber and the plunger. 
The gel acts on its own 
and it is very hygienic. 
You can handle a 
clogged drain on your 
own, and you don’t 
need to sweat with the 
plunger.

						</div>
					</div><!--/product-details-->

				</div>
