
				<div class="col-sm-9 padding-right">
					<div class="product-details"><!--product-details-->
						<div class="col-sm-5">
							<div class="view-product">
								<img src="images/product/502002.jpg" alt="" />
								
							</div>
							

						</div>
						<div class="col-sm-7">
							<div class="product-information"><!--/product-information-->
								<!-- <img src="images/product-details/new.jpg" class="newarrival" alt="" /> -->
								<h2>SHOWER EXPERT</h2>
								<p>Product code: 502002</p>
								
								<!-- <span>
									<span>US $59</span>
									<label>Quantity:</label>
									<input type="text" value="3" />
									<button type="button" class="btn btn-fefault cart">
										<i class="fa fa-shopping-cart"></i>
										Add to cart
									</button>
								</span> -->
								<p><b>500 ml</b> In Stock</p>

								
							</div><!--/product-information-->

						</div>
						<div><br><br>
						<h2>How to quickly clean your shower cabin?</h2>
						What do you usually do in the shower? Do you relax or do you think how to get rid of all the 
patches on the glass once and for all? We’re defi nitely more into relaxation and this is why we 
recommend our 
SHOWER EXPERT 
The proven formula based on lactic acid and alcohol removes soap and detergent residue, 
limescale and hard water stains. The cleaner leaves the glass spotlessly clean, without any 
smudges or patches, and it prevents fogging up. And in addition, it smells wonderfully.

<h4>What you will love it for:</h4>
once you two become friends, the ti me you 
spend in the shower will be a pleasure.  
  
<h4>What you’ll love about it:</h4>
the cleaner creates a protecti ve fi lm on the 
surface which prevents dirt and limescale from 
building up again. And this means less cleaning 
in the future.

<h4>What you can clean with it:</h4>
glass and acrylic shower enclosures, wall and 
fl oor ti les, shower bases, plasti c elements of 
shower cabins.<br>
 
<h4>What is that beautiful scent:</h4>
juicy raspberries, delicate aloe and very sweet 
toffee.

<h4>What do users say?</h4>
According to 92% of respondents* the 
spray leaves behind a beauti ful fragrance 
in the bathroom, and 80% claim that it 
perfectly removes everyday dirt (deposits 
from soap and cleaning products) and 
reduces the fogging of glass.

<br>* Independent consumer research conducted on a group of 25 people.

<h4>SEE HOW SIMPLE IT IS TO USE:</h4>
spray the enti re shower 
cubicle, wait a while and rinse 
thoroughly with water. In 
case of heavier soiling, you 
can scrub the most criti cal 
areas aft er spraying.

<h4>Price of the set with a two-phase spray: <i>Product code: 592101</i></h4>
						</div>
					</div><!--/product-details-->

				</div>
