
				<div class="col-sm-9 padding-right">
					<div class="product-details"><!--product-details-->
						<div class="col-sm-5">
							<div class="view-product">
								<img src="images/product/503005.jpg" alt="" />
								
							</div>
							

						</div>
						<div class="col-sm-7">
							<div class="product-information"><!--/product-information-->
								<!-- <img src="images/product-details/new.jpg" class="newarrival" alt="" /> -->
								<h2>DARKS GEL</h2>
								<p>Product code: 503005</p>
								
								<!-- <span>
									<span>US $59</span>
									<label>Quantity:</label>
									<input type="text" value="3" />
									<button type="button" class="btn btn-fefault cart">
										<i class="fa fa-shopping-cart"></i>
										Add to cart
									</button>
								</span> -->
								<p><b>1000 ml</b> In Stock</p>

								
							</div><!--/product-information-->

						</div>
						<div><br><br>
						<h2>How to wear black with class?</h2>
Beautiful, deep black colour has a magnetic power. It attracts admiring glances but also all pieces 
of fl uff  and specks of dust. The dust accumulating on the fi bres and the hard water residue make 
black hues lose their depth, and black fabrics grow pale and dull. To fi ght this unfl attering eff ect 
we’ve created our 
DARKS GEL 
which prevents dirt and hard water residue from building up again. It protects colours from 
washing out, it doesn’t leave bright, ugly smudges or patches and it perfectly enhances the depth 
and intensity of black colour and other dark hues.

<h4>What you will love it for:</h4>
you can be sure your black garments remain 
fresh and elegant and that you att ract the eyes 
of others.  
  
<h4>What will delight you about it:</h4>
the concentrated gel formula, which makes it 
efficient and compact. It doesn’t take much 
space on the shelf and goes a long way.    

<h4>What assures additional safety:</h4>
formula black protect.<br>
 
<h4>What black smells like:</h4>
we love playing with fragrances so we asked 
scent designers that work with us to create 
a compositi on inspired by the elegance 
of black. They conquered our hearts with 
a sensual nocturne which brings together 
classical rose and lily of the valley notes and 
warm musk accents.

<h4>WHAT ELSE YOU CAN DO FOR YOUR CLOTHES:</h4>
use our perfumed gel fabric 
soft ener, which has fantastic
anti-static  properties.  
						</div>
					</div><!--/product-details-->

				</div>
