
				<div class="col-sm-9 padding-right">
					<div class="product-details"><!--product-details-->
						<div class="col-sm-5">
							<div class="view-product">
								<img src="images/product/503001.jpg" alt="" />
								
							</div>
							

						</div>
						<div class="col-sm-7">
							<div class="product-information"><!--/product-information-->
								<!-- <img src="images/product-details/new.jpg" class="newarrival" alt="" /> -->
								<h2>STAIN BUSTER</h2>
								<p>Product code: 503001</p>
								
								<!-- <span>
									<span>US $59</span>
									<label>Quantity:</label>
									<input type="text" value="3" />
									<button type="button" class="btn btn-fefault cart">
										<i class="fa fa-shopping-cart"></i>
										Add to cart
									</button>
								</span> -->
								<p><b>500 ml</b> In Stock</p>

								
							</div><!--/product-information-->

						</div>
						<div><br><br>
						<h2>How to remove 15 most common stains in 10 minutes?</h2>
We asked our friends what type of stains they get most often. We used the answers we 
got to create a list of fi fteen challenges for our 
STAIN BUSTER 
In just 10 minutes it removed stains from coff ee, tea, blood, coca cola, oil, red wine, 
orange juice, grass, soil, foundation, gravy, tomato soup, tangerine, toothpaste, and apple 
and cherry juice. And it did it all without rubbing. We’re proud of it!

<h4>Why it works so well:</h4>
the secret of our stain remover? The 
oxysystem formula based on acti ve 
oxygen and enzymes. It works perfectly even in low 
temperature (from 20°C up). The thick gel is 
easy to spread on the fabric and it penetrates 
the stain, targeti ng just the right spot. It’s 
extremely efficient.  
  
<h4>What you will love it for:</h4>
it’s tough on the stains, but delicate on the 
fabric.    

<h4>What will pleasantly surprise you:</h4>
it is delicate for the colours. Even aft er several 
uses they will keep their natural hue.
 
<h4>What you can use it for:</h4>
all types of fabric, even the most delicate ones, 
whites and colours because it does not contain 
chlorine.

<h4>Why it is unscented:</h4>
the product is unscented so you can use it 
for children’s clothing, too. If you are keen 
on a beauti ful smell of your laundry, add our 
Perfumed Conditi oner or Gel Fabric Soft ener. 

<h4>SEE HOW SIMPLE IT IS TO USE:</h4>
You can apply the gel directly 
onto the stain (on the spot) 
or add it to the laundry.
						</div>
					</div><!--/product-details-->

				</div>
