
				<div class="col-sm-9 padding-right">
					<div class="product-details"><!--product-details-->
						<div class="col-sm-5">
							<div class="view-product">
								<img src="images/product/503004.jpg" alt="" />
								
							</div>
							

						</div>
						<div class="col-sm-7">
							<div class="product-information"><!--/product-information-->
								<!-- <img src="images/product-details/new.jpg" class="newarrival" alt="" /> -->
								<h2>WHITES GEL</h2>
								<p>Product code: 503004</p>
								
								<!-- <span>
									<span>US $59</span>
									<label>Quantity:</label>
									<input type="text" value="3" />
									<button type="button" class="btn btn-fefault cart">
										<i class="fa fa-shopping-cart"></i>
										Add to cart
									</button>
								</span> -->
								<p><b>1000 ml</b> In Stock</p>

								
							</div><!--/product-information-->

						</div>
						<div><br><br>
						<h2>How to look good in white?</h2>
Snow white cotton, cream white lace, pearl white satin, milky white silk... Every nuance, every 
refraction of light matters. We can clearly tell the diff erence between a snow-coloured shirt 
and an alabaster taff eta dress. This is why our 
WHITES GEL 
has been designed in a way that protects all shades of white, not only the brightest ones. 
It keeps them spotlessly clean, prevents the fabric from getting grey, does not leave smudges. 
It revives bright colours, leaving your clothes fresh and beautifully scented.

<h4>What you will love it for:</h4>
za istotu, že Vaše svetlé a biele šaty sú 
dokonale čisté a Vy vyzeráte skvele.  
  
<h4>What will delight you about it:</h4>
the concentrated gel formula, which makes 
it effi  cient and compact. It doesn’t take much 
space on the shelf and goes a long way.     

<h4>What assures additional 
safety:</h4>
whites sensor. The gel does not contain 
opti cal whiteners so it is safe for all shades 
of white and does not make delicate fabrics 
go grey.<br>
 
<h4>What white smells like:</h4>
we love playing with fragrances so we asked 
scent designers that work with us to create 
a compositi on inspired by the white colour. 
They have created a masterpiece, bringing 
together powerful white fl owers with subtle 
cott on, and a cool touch of snowfl akes.


						</div>
					</div><!--/product-details-->

				</div>
