
				<div class="col-sm-9 padding-right">
					<div class="product-details"><!--product-details-->
						<div class="col-sm-5">
							<div class="view-product">
								<img src="images/product/503002.jpg" alt="" />
								
							</div>
							

						</div>
						<div class="col-sm-7">
							<div class="product-information"><!--/product-information-->
								<!-- <img src="images/product-details/new.jpg" class="newarrival" alt="" /> -->
								<h2>PERFUMED LAUNDRY CONDITIONER</h2>
								<p>Product code: 503002</p>
								
								<!-- <span>
									<span>US $59</span>
									<label>Quantity:</label>
									<input type="text" value="3" />
									<button type="button" class="btn btn-fefault cart">
										<i class="fa fa-shopping-cart"></i>
										Add to cart
									</button>
								</span> -->
								<p><b>1000 ml</b> In Stock</p>

								
							</div><!--/product-information-->

						</div>
						<div><br><br>
						<h2>How to always look stylish?</h2>
						When you hang a new garment in your wardrobe you’d like it to remain beautiful and soft to the 
touch as long as possible. You want it to fi t perfectly, with no creasing, and always look fresh and 
smart. And we make your dreams come true! Thanks to the stay-new formula, 
PERFUMED LAUNDRY  
CONDITIONER 
effi ciently protects the fabric against the fi rst signs of wear. It prevents the clothes from becoming 
deformed and pilling. It makes sure the colours of your clothes remain bright and beautiful for 
longer. What is more, it has a lovely scent which we created with the help of French master 
perfumers.

<h4>What you will love it for:</h4>
your favourite garments will look brand new 
for longer.
  
<h4>What will delight you about it:</h4>
long-lasti ng scent, even up to 8 weeks. The 
fragrant oils are entrapped in microcapsules 
that work as ti ny diff users. They do not 
dissolve in water and open up only when you 
wear your clothes. With every movement, 
they’ll release the oils, enveloping you with an 
intense smell of perfume.  

<h4>What is that beautiful scent:</h4>
this compositi on is the essence of the French 
chic. It is a harmonious marriage of fl owery 
notes with sweet vanilla and chocolate 
pralines. Mediterranean accents round it out 
subtly with a hint of summery, relaxing breeze.<br>
 
<h4>SEE HOW SIMPLE IT IS TO USE:</h4>
just add the appriopriate 
amount of the conditi oner 
to the last rinse. You can 
use it both in the washing 
machine and for hand 
washing your clothes.


						</div>
					</div><!--/product-details-->

				</div>
