
				<div class="col-sm-9 padding-right">
					<div class="product-details"><!--product-details-->
						<div class="col-sm-5">
							<div class="view-product">
								<img src="images/product/503008.jpg" alt="" />
								
							</div>
							

						</div>
						<div class="col-sm-7">
							<div class="product-information"><!--/product-information-->
								<!-- <img src="images/product-details/new.jpg" class="newarrival" alt="" /> -->
								<h2>Long-lasting perfumed laundry conditioner</h2>
								<p>Product code: 503008</p>
								
								<!-- <span>
									<span>US $59</span>
									<label>Quantity:</label>
									<input type="text" value="3" />
									<button type="button" class="btn btn-fefault cart">
										<i class="fa fa-shopping-cart"></i>
										Add to cart
									</button>
								</span> -->
								<p><b>500 ml</b> In Stock</p>

								
							</div><!--/product-information-->

						</div>
						<div><br><br>
						<h2>How to take care of your clothes while washing?</h2>
We communicate a lot of information about ourselves with our outfits, and well maintained and fragrant clothes affect not only how we are perceived, but also our well-being. Therefore, if you want them to still look like new and smell beautiful for a long time to come, use an Intensive perfumed fabric conditioner that takes care of the fibers and makes the fabrics exceptionally soft, light, flexible and fluffy. The wheat proteins it contains effectively protect colors from fading and white from graying.

<h4>What will you love it for:</h4>
the stay new formula, which actively protects the fibers during washing and drying, prevents damage, deformation and mossing, as well as cracking of prints on T-shirts. Fabrics look as if they have been washed half as often. 
  
<h4>What will delight you in it:</h4>
a fragrance that lasts even longer - up to 24 weeks! The fragrance oils are encapsulated in special HD Active Life microcapsules that release a wonderful aroma - even without rubbing the material.   

<h4>What smells so beautiful:</h4>
a floral-wood composition made of French fragrance oils, in which we combined delicate jasmine, tropical ylang-ylang and the exotic aroma of coconut water with sensual musk, aloe vera, rosewood and resin-spicy tones of sandalwood.
 
<h4>See how easy it is to use:</h4>
all you have to do is add the right amount of conditioner to the last rinse. You can use it for both machine and hand washing, for all types of fabrics and all colors.

<h4>What will provide you with additional safety:</h4>
the conditioner has undergone a number of detailed tests, including a dermatological examination, confirming skin tolerance.
						</div>
					</div><!--/product-details-->

				</div>
