
				<div class="col-sm-9 padding-right">
					<div class="product-details"><!--product-details-->
						<div class="col-sm-5">
							<div class="view-product">
								<img src="images/product/503003.jpg" alt="" />
								
							</div>
							

						</div>
						<div class="col-sm-7">
							<div class="product-information"><!--/product-information-->
								<!-- <img src="images/product-details/new.jpg" class="newarrival" alt="" /> -->
								<h2>PERFUMED FABRIC SOFTENER GEL</h2>
								<p>Product code: 503003</p>
								
								<!-- <span>
									<span>US $59</span>
									<label>Quantity:</label>
									<input type="text" value="3" />
									<button type="button" class="btn btn-fefault cart">
										<i class="fa fa-shopping-cart"></i>
										Add to cart
									</button>
								</span> -->
								<p><b>1000 ml</b> In Stock</p>

								
							</div><!--/product-information-->

						</div>
						<div><br><br>
						<h2>How to save time when ironing?</h2>
						Do you know that appropriate fabric softening allows them to be ironed faster, 
and creates less wrinkles when ironing? Our 
PERFUMED FABRIC  
SOFTENER GEL 
softens them perfectly, causing the iron to run smoothly, almost as if on its own. 
And the fabrics are incredibly light, soft and fluffy.

<h4>What you will love it for:</h4>
for the soft ness with which the fabrics will 
envelop your skin. Experience the new level 
of fl uffi  ness with no stati c cling. And the old 
argument about who puts up the laundry will 
become history. 
  
<h4>What will delight you about it:</h4>
thanks to the perfect conditi oning eff ect, 
ironing will become so much faster.  

<h4>What is that beautiful scent:</h4>
the sensual and enveloping fragrance marks 
the return to the best traditi ons of the French 
perfume makers. The rich, fl owery bouquet 
is rounded out with balsamic touches of 
sandalwood and a warm hint of musk. 
The vibrati ng notes of Sicilian tangerine lend 
it freshness and lightness. Pure beauty.<br>
 
<h4>What assures additional safety:</h4>
both the conditi oner and 
the gel went through a 
number of detailed tests, 
including dermatological 
tests confi rming skin 
tolerance.

<h4>SEE HOW SIMPLE IT IS TO USE: </h4>
just add the appriopriate 
amount of the gel to the 
last rinse. You can use 
it both in the washing 
machine and for hand 
washing your clothes.
						</div>
					</div><!--/product-details-->

				</div>
