
				<div class="col-sm-9 padding-right">
					<div class="product-details"><!--product-details-->
						<div class="col-sm-5">
							<div class="view-product">
								<img src="images/product/503006.jpg" alt="" />
								
							</div>
							

						</div>
						<div class="col-sm-7">
							<div class="product-information"><!--/product-information-->
								<!-- <img src="images/product-details/new.jpg" class="newarrival" alt="" /> -->
								<h2>COLOUR GEL</h2>
								<p>Product code: 503006</p>
								
								<!-- <span>
									<span>US $59</span>
									<label>Quantity:</label>
									<input type="text" value="3" />
									<button type="button" class="btn btn-fefault cart">
										<i class="fa fa-shopping-cart"></i>
										Add to cart
									</button>
								</span> -->
								<p><b>1000 ml</b> In Stock</p>

								
							</div><!--/product-information-->

						</div>
						<div><br><br>
						<h2>How to wash colours together?</h2>
The art of matching colours can be tough, especially when after several washes your raspberry 
sweater grows paler and paler, and your orange trousers lost their vivid hue. To make your 
clothes look impressive at all times, we designed 
COLOUR GEL 
which protects colours from washing out. It prevents dyes from being transferred from one 
cloth to another, so it protects colours even better. From now on we will take care of the 
colours of your clothes, so all you need to worry about is pulling off  the right colourful look.

<h4>What you will love it for:</h4>
you can be sure the colours of your garments 
remain bright and vibrant and that you’ll look 
great.  
  
<h4>What is our secret:</h4>
thanks to the acti ve enzyme formula, the gel 
works perfectly even in low temperatures 
(from 20°C up). And as you know, washing 
clothes in colder water is bett er both for your 
garments, and your budget.  

<h4>What assures additional safety:</h4>
an ingredient preventi ng pigment transfer 
between fabrics. 
 
<h4>What the colour extravaganza smells like:</h4>
we love playing with fragrances so we asked 
scent designers that work with us to create a 
compositi on that will refl ect the great variety 
of colours. As soon as we smelled the vibrati ng 
apricot notes and the pulsati ng spices, we 
knew no other fragrance would be 
up for the task.  

<h4>WHAT IS REALLY IMPORTANT FOR MEN</h4>
we know you have 
problems telling one colour 
from another. If you’re not 
sure whether you can wash 
her emerald trousers with 
your lime T-shirt, our gel 
will give you a green light. 
Thanks to the dye transfer 
inhibitor you can wash all 
the colours together (unless 
the manufacturer’s label 
explicitly states otherwise).  
						</div>
					</div><!--/product-details-->

				</div>
