
				<div class="col-sm-9 padding-right">
					<div class="product-details"><!--product-details-->
						<div class="col-sm-5">
							<div class="view-product">
								<img src="images/product/504003.jpg" alt="" />
								
							</div>
							

						</div>
						<div class="col-sm-7">
							<div class="product-information"><!--/product-information-->
								<!-- <img src="images/product-details/new.jpg" class="newarrival" alt="" /> -->
								<h2>HARDWOOD & LAMINATE FLOOR EXPERT</h2>
								<p>Product code: 504003</p>
								
								<!-- <span>
									<span>US $59</span>
									<label>Quantity:</label>
									<input type="text" value="3" />
									<button type="button" class="btn btn-fefault cart">
										<i class="fa fa-shopping-cart"></i>
										Add to cart
									</button>
								</span> -->
								<p><b>1000 ml</b> In Stock</p>

								
							</div><!--/product-information-->

						</div>
						<div><br><br>
						<h2>Can you use the panel cleaner on a hardwood floor ??</h2>
With our cleaner – you can! We have created a delicate cleaning solution 
HARDWOOD & LAMINATE 
FLOOR EXPERT 
on the basis of natural carnauba wax, which is dedicated for both hardwood fl oors and 
laminated panels. It keeps your fl oors shiny and protects them against humidity. The silicone 
emulsion works as a sealant on joints and tiny cracks, preventing dirt and dust from building 
up in them. It creates an invisible anti-slip coat and protects the natural colour of the cleaned 
surface.

<h4>What you will love it for:</h4>
it cleans the fl oor perfectly, without smudges. 
The fl oor detergent not only cleans the 
surface, but also protects it against dirt. 
You won’t need to brush anything under the 
carpet anymore.  
  
<h4>What will delight you about it:</h4>
versati lity. You can stop wondering which 
fl oors you can clean with it. It is perfect both 
for varnished wood and laminated panels.   

<h4>What assures additional safety:</h4>
roti šmykový efekt. Doceníte ho ešte viac, 
ak sú vo Vašej domácnosti  malé deti , starší 
ľudia alebo ľudia s problémami s pohyblivosťou.<br>
 
<h4>What you can use it for:</h4>
floors and surfaces made of varnished wood, 
panelling, parquets, wooden stairs and 
banisters, laminate fl oors and wall panels, 
wood-like surfaces. It is perfect for all types of 
wood, including exoti c wood. You can also use 
it on varnished cork.

<h4>What is that beautiful scent:</h4>
fresh fl owers, sweet vanilla and sensual 
patchouli. 

<h4>SEE HOW SIMPLE IT IS TO USE: </h4>
carefully vacuum or sweep 
the surface to be cleaned. 
Dissolve 35 ml of liquid 
in 5 liters of warm water 
and wash the fl oor with 
a well wrung out cloth or 
a squeezed mop. Wipe dry 
or let it dry.
						</div>
					</div><!--/product-details-->

				</div>
