
				<div class="col-sm-9 padding-right">
					<div class="product-details"><!--product-details-->
						<div class="col-sm-5">
							<div class="view-product">
								<img src="images/product/504002.jpg" alt="" />
								
							</div>
							

						</div>
						<div class="col-sm-7">
							<div class="product-information"><!--/product-information-->
								<!-- <img src="images/product-details/new.jpg" class="newarrival" alt="" /> -->
								<h2>GLASS & MIRROR EXPERT</h2>
								<p>Product code: 504002</p>
								
								<!-- <span>
									<span>US $59</span>
									<label>Quantity:</label>
									<input type="text" value="3" />
									<button type="button" class="btn btn-fefault cart">
										<i class="fa fa-shopping-cart"></i>
										Add to cart
									</button>
								</span> -->
								<p><b>500 ml</b> In Stock</p>

								
							</div><!--/product-information-->

						</div>
						<div><br><br>
						<h2>How to get rid of smears on window panes?</h2>
Have your windows ever been so clean that they looked practically invisible? If you think this is 
impossible, try our versatile 
GLASS & MIRROR EXPERT 
You will see that not only does it clean the windows perfectly, but also prevents fogging and 
protects them from dirt building up again. As it contains alcohol, it evaporates fast and does not 
leave smudges. It easily removes dust, grease, soot, and even greasy hands marks. Discover this 
fantastic feeling when you need to think twice if there’s actually a pane of glass in front of you or 
just air.

<h4>What you will love it for:</h4>
even on a sunny day you won’t see a single 
smudge on your windows.  
  
<h4>What you can use it for:</h4>
window panes and frames, car windows, glass 
panes in shower cabins, shelters, mirrors, 
crystals, glass lampshades. Coloured, ti nted 
or stained glass. We also recommend it as 
a cleaner of plasti c and plexiglass panes. You 
can use it both inside and outside.   

<h4>What is that beautiful scent:</h4>
juicy citrus fruit, fresh mint and fresh marine 
notes.<br>
 
<h4>IMPORTANT TIP:</h4>
someti mes less is more. 
If you want to avoid 
smudges, go easy on the 
cleaner. You will save 
precious ti me and money. 
Remember not to clean 
your windows in direct 
sunlight — the liquid will dry 
too fast and you won’t be 
able to clean the windows 
correctly.

<h4>SEE HOW SIMPLE IT IS TO USE:</h4>
spray a small amount on the 
surface to be cleaned and 
wipe with a dry cloth.  
						</div>
					</div><!--/product-details-->

				</div>
