
				<div class="col-sm-9 padding-right">
					<div class="product-details"><!--product-details-->
						<div class="col-sm-5">
							<div class="view-product">
								<img src="images/product/504010.jpg" alt="" />
								
							</div>
							

						</div>
						<div class="col-sm-7">
							<div class="product-information"><!--/product-information-->
								<!-- <img src="images/product-details/new.jpg" class="newarrival" alt="" /> -->
								<h2>FURNITURE CREAM SPRAY</h2>
								<p>Product code: 504010</p>
								
								<!-- <span>
									<span>US $59</span>
									<label>Quantity:</label>
									<input type="text" value="3" />
									<button type="button" class="btn btn-fefault cart">
										<i class="fa fa-shopping-cart"></i>
										Add to cart
									</button>
								</span> -->
								<p><b>300 ml</b> In Stock</p>

								
							</div><!--/product-information-->

						</div>
						<div><br><br>
						<h2>How to make your furniture pass the white glove test?</h2>
Does dust on your furniture seem to appear immediately after you’ve cleaned it? It’s possible 
because wooden and laminated surfaces attract tiny specks of dirt. Searching for a be-all 
end-all solution, we created 
FURNITURE CREAM SPRAY 
which perfectly cleans and conditions the furniture surface, protecting it from moisture 
and leaving an antistatic coat to prevent dust from building up. Avocado and rice oil as 
well as carnauba wax take care of your furniture giving it a slight sheen. A unique aromatic 
composition consisting of Siberian pine, bergamot and patchouli will fi ll your house with 
a pleasant scent of evergreen forest.

<h4>What you will love it for:</h4>
it combines the qualiti es of a delicate, creamy 
emulsion with the convenience of a spray. Just 
spray the surface and wipe with a dry, soft  
clothą.
  
<h4>What will delight you about it:</h4>
natural carnauba wax and emulsion containing 
avocado and rice oils will give your furniture a 
subtle sheen and refresh their colour. You can 
forget about smudges and streaks!  

<h4>What you can clean with it:</h4>
wooden varnished furniture, furniture 
protected by various means: anti que, veneer, 
waxed, oiled, and made of wood-like materials 
(laminate and foil).<br>
 
<h4>What is that beautiful scent:</h4>
fresh Siberian pine needles, green moss, pink 
pepper and sensual musk.



						</div>
					</div><!--/product-details-->

				</div>
