
				<div class="col-sm-9 padding-right">
					<div class="product-details"><!--product-details-->
						<div class="col-sm-5">
							<div class="view-product">
								<img src="images/product/504005.jpg" alt="" />
								
							</div>
							

						</div>
						<div class="col-sm-7">
							<div class="product-information"><!--/product-information-->
								<!-- <img src="images/product-details/new.jpg" class="newarrival" alt="" /> -->
								<h2>GÉL NA ČISTENIE MEDZIER</h2>
								<p>Product code: 504005</p>
								
								<!-- <span>
									<span>US $59</span>
									<label>Quantity:</label>
									<input type="text" value="3" />
									<button type="button" class="btn btn-fefault cart">
										<i class="fa fa-shopping-cart"></i>
										Add to cart
									</button>
								</span> -->
								<p><b>1000 ml</b> In Stock</p>

								
							</div><!--/product-information-->

						</div>
						<div><br><br>
						<h2>How to make your bathroom look younger?</h2>
Do you know that cleaning your grout right can make your house look a few years younger? So 
if you’re not planning a renovation soon, you’d better get down to it! 
GROUT CLEANER 
cleans and degreases the grout, leaving a beautiful high-gloss finish. It is delicate for the tiles 
and it won’t stain or damage the grout. After such a treatment your tiles will look brand new.

<h4>What you will love it for:</h4>
pre okázalý konečný výsledok.  
  
<h4>What you can use it for:</h4>
white and coloured grout between glazed, 
terracott a, stoneware, marble and mosaic ti les, 
outdoors and indoors, it can be used on the 
fl oor and on the walls (thanks to its thick, gel 
texture it won’t trickle down a verti cal surface 
too soon).   

<h4>We’ve made sure the gel is free from: </h4>
chlorine and bleaches.<br>
 
<h4>What is that beautiful scent:</h4>
cashmere, sandal wood, rose, coconut and 
creamy vanilla.

<h4>SEE HOW SIMPLE IT IS TO USE: </h4>
apply the gel evenly to the 
surface to be cleaned, wait 
a few minutes and wipe 
the area with a sponge or 
a brush. Rinse with water or 
wipe with a damp cloth.
						</div>
					</div><!--/product-details-->

				</div>
