
				<div class="col-sm-9 padding-right">
					<div class="product-details"><!--product-details-->
						<div class="col-sm-5">
							<div class="view-product">
								<img src="images/product/504006.jpg" alt="" />
								
							</div>
							

						</div>
						<div class="col-sm-7">
							<div class="product-information"><!--/product-information-->
								<!-- <img src="images/product-details/new.jpg" class="newarrival" alt="" /> -->
								<h2>GRILL & OVEN GEL</h2>
								<p>Product code: 504006</p>
								
								<!-- <span>
									<span>US $59</span>
									<label>Quantity:</label>
									<input type="text" value="3" />
									<button type="button" class="btn btn-fefault cart">
										<i class="fa fa-shopping-cart"></i>
										Add to cart
									</button>
								</span> -->
								<p><b>500 ml</b> In Stock</p>

								
							</div><!--/product-information-->

						</div>
						<div><br><br>
						<h2>How to save a burnt frying pan?</h2>
						Burnt frying pan? Burnt pot? Well, it can happen to the best of us. 
This is why we have this incredibly eff ective 
GRILL & OVEN GEL 
It will easily remove even old burnt patches and smoke stains, dried grease and food rests. 
You can instantly clean your fi replace door, barbecue, grill and the inside of the oven.

<h4>What you will love it for:</h4>
it redefi nes the words “irremovable stains”. It 
will get rid of things that seemed impossible to 
remove.    
  
<h4>What will delight you about it:</h4>
thick gel texture. The thick gel doesn’t trickle 
down the surface — it covers it up, allowing 
the acti ve ingredients to do their job.    

<h4>What you can clean with it:</h4>
barbecue grills, ovens, grates, spits, fi replace 
glass, the outside of pans and pots.<br>
 
<h4>What you can remove with it:</h4>
burnt-on grease, burnt stains, smoke stains, 
carbon deposits, soot.

<h4>What else we took care of:</h4>
safe closing system.

<h4>Why it is unscented:</h4>
to dissuade you from smelling it. 

<h4>SEE HOW SIMPLE IT IS TO USE: </h4>
apply the gel evenly 
to the clean surface, wait 
a maximum of 15-20 minutes, 
and then collect the soiling 
with a paper towel. Rinse with 
clean water and wipe dry.
						</div>
					</div><!--/product-details-->

				</div>
