
				<div class="col-sm-9 padding-right">
					<div class="product-details"><!--product-details-->
						<div class="col-sm-5">
							<div class="view-product">
								<img src="images/product/504011.jpg" alt="" />
								
							</div>
							

						</div>
						<div class="col-sm-7">
							<div class="product-information"><!--/product-information-->
								<!-- <img src="images/product-details/new.jpg" class="newarrival" alt="" /> -->
								<h2>GLASS AND MIRROR SPRAY</h2>
								<p>Product code: 504011</p>
								
								<!-- <span>
									<span>US $59</span>
									<label>Quantity:</label>
									<input type="text" value="3" />
									<button type="button" class="btn btn-fefault cart">
										<i class="fa fa-shopping-cart"></i>
										Add to cart
									</button>
								</span> -->
								<p><b>500 ml</b> In Stock</p>

								
							</div><!--/product-information-->

						</div>
						<div><br><br>
						<h2>How to make the glass panels crystal clear?</h2>
Would you love to get rid of dirt from windows, mirrors and other glass surfaces quickly, 
effi  ciently and eff ortlessly? Forget time-consuming washing and polishing, and get rid of 
annoying streaks once and for all. From now on even such problematic surfaces can be 
a pleasure to clean. Our 
GLASS & MIRROR SPRAY 
Is easily distributed over the surface and safely removes all impurities, including grease, dust, 
soot and powder particles. The alcohol content makes it evaporate quickly, thus leaving no 
streaks or stains. See for yourself how easy it is to take care of the glass surfaces in your home 
and enjoy their pristine cleanliness. 

<h4>What you will love it for:</h4>
for crystal clear glass and mirror surfaces, 
completely streak-free.    
  
<h4>What is our secret:</h4>
the spray ingredients dampen the cleaned 
surface well and make the dirt parti cles attach 
to each other, allowing you to quickly remove 
dirt from windows and mirrors, including 
annoying greasy hand prints.   

<h4>What you can use it for:</h4>
cleaning windows and window frames, car 
windows, shower cubicles, gazebos, mirrors, 
crystals, glass lamp shades. For colored, tinted 
and stained glass, including stained glass 
windows. We also recommend using it on 
articles made of plastic and plexiglass.
 
<h4>Other things we took into account: </h4>
we made sure that it is completely ammonia-
free.

<h4>What is that beautiful scent:</h4>
juicy fruit, fl oral notes and sensual musk.<br>

<h4>SEE HOW SIMPLE IT IS TO USE: </h4>
spray a small amount on the 
surface to be cleaned (from 
a distance of about 15 cm) 
and wipe with a dry cloth. 
Never leave a glass surface 
to dry completely.
						</div>
					</div><!--/product-details-->

				</div>
