
				<div class="col-sm-9 padding-right">
					<div class="product-details"><!--product-details-->
						<div class="col-sm-5">
							<div class="view-product">
								<img src="images/product/504004.jpg" alt="" />
								
							</div>
							

						</div>
						<div class="col-sm-7">
							<div class="product-information"><!--/product-information-->
								<!-- <img src="images/product-details/new.jpg" class="newarrival" alt="" /> -->
								<h2>GROUT CLEANER</h2>
								<p>Product code: 504004</p>
								
								<!-- <span>
									<span>US $59</span>
									<label>Quantity:</label>
									<input type="text" value="3" />
									<button type="button" class="btn btn-fefault cart">
										<i class="fa fa-shopping-cart"></i>
										Add to cart
									</button>
								</span> -->
								<p><b>1000 ml</b> In Stock</p>

								
							</div><!--/product-information-->

						</div>
						<div><br><br>
						<h2>How to thoroughly clean your carpet?</h2>
If you want your carpets to keep their beautiful colour and texture as long as possible, 
regular vacuuming and washing is not enough. This is why we’ve created this unique 
CARPET SHAMPOO 
which brings together the effi  ciency of a washing liquid with cosmetics for grooming the 
fi nest hair. Thick, active foam penetrates the fi bres deeply and precisely removes even old 
stains. It restores freshness, softness and fl uffi  ness. And moreover, it protects the fi bres 
against new stains.

<h4>What you will love it for:</h4>
With a well washed carpet, not only will your 
home feel nice and cosy, but there will be less 
dust in the air, the atmosphere will improve 
and you’ll breathe more easily. 
  
<h4>What assures additional safety:</h4>
allergen-free fragrance oils compliant with 
IFRA standards (Internati onal Fragrance 
Associati on), which is especially important 
if you have small children or pets.   

<h4>What you can use it for:</h4>
carpets made of natural and syntheti c fi bres, 
fl oor rugs, wall rugs, bath mats, upholstery 
(including car upholstery). The shampoo 
is dedicated for hand washing.
 
<h4>What is that beautiful scent:</h4>
juicy citrus fruit, violet leaves, sensual vanilla 
and oakmoss.

<h4>SEE HOW SIMPLE IT IS TO USE: </h4>
first carefully vacuum 
the carpet or upholstery. 
Dissolve 150 ml 
(3 measures) of liquid in 
1 liter of water. Immerse 
a sponge in the soluti on 
and wring several ti mes to 
create a dense foam. Spread 
the foam evenly on the 
vacuumed surface, making 
sure that it does not get too 
wet. Leave the carpet to dry. 
Aft er drying the shampoo 
turns into a powder that 
needs to be collected with 
a vacuum cleaner. 
						</div>
					</div><!--/product-details-->

				</div>
