
				<div class="col-sm-9 padding-right">
					<div class="product-details"><!--product-details-->
						<div class="col-sm-5">
							<div class="view-product">
								<img src="images/product/504001.jpg" alt="" />
								
							</div>
							

						</div>
						<div class="col-sm-7">
							<div class="product-information"><!--/product-information-->
								<!-- <img src="images/product-details/new.jpg" class="newarrival" alt="" /> -->
								<h2>CREAM</h2>
								<p>Product code: 504001</p>
								
								<!-- <span>
									<span>US $59</span>
									<label>Quantity:</label>
									<input type="text" value="3" />
									<button type="button" class="btn btn-fefault cart">
										<i class="fa fa-shopping-cart"></i>
										Add to cart
									</button>
								</span> -->
								<p><b>500 ml</b> In Stock</p>

								
							</div><!--/product-information-->

						</div>
						<div><br><br>
						<h2>How to properly care for your bathroom porcelain?</h2>
Do you know that some items in your house are so fragile that scrubbing can damage their 
surface? This is why when designing our 
CREAM 
cleaner we drew inspiration from make up removing lotions. This is why our product not 
only gently cleans the surface, but also makes it gleam and protects it.

<h4>What will delight you about it:</h4>
its velvety texture, just like in delicate beauty 
products, and its speedy and effi  cient 
applicati on. It contains light olive oil which 
lends a beauti ful glossy fi nish to the cleaned 
surfaces. 
  
<h4>What you can clean with it:</h4>
sanitary fi xtures (sinks, washbasins, bathtubs), 
kitchen appliances, nickel plated, ceramic, and 
enamelled surfaces, plasti c garden furniture, 
wall ti les.  

<h4>It removes easily:</h4>
water and soap residue, limescale, rusty stains, 
burns and greasy residues.<br>
 
<h4>What is that beautiful scent:</h4>
citrus fruit, black olives, lilac, pear blossom 
and sandalwood.

<h4>What is our secret:</h4>
a delicate formula which cleans without 
damaging the surface.

<h4>SEE HOW SIMPLE IT IS TO USE: </h4>
apply the cream to the 
surface to be cleaned. 
If necessary, lightly rub. 
Then gently remove the 
residue with a slightly damp 
cloth and rinse thoroughly 
with water.
						</div>
					</div><!--/product-details-->

				</div>
