
				<div class="col-sm-9 padding-right">
					<div class="product-details"><!--product-details-->
						<div class="col-sm-5">
							<div class="view-product">
								<img src="images/product/504009.jpg" alt="" />
								
							</div>
							

						</div>
						<div class="col-sm-7">
							<div class="product-information"><!--/product-information-->
								<!-- <img src="images/product-details/new.jpg" class="newarrival" alt="" /> -->
								<h2>SCREEN & INOX STEEL SMART SPRAY</h2>
								<p>Product code: 504009</p>
								
								<!-- <span>
									<span>US $59</span>
									<label>Quantity:</label>
									<input type="text" value="3" />
									<button type="button" class="btn btn-fefault cart">
										<i class="fa fa-shopping-cart"></i>
										Add to cart
									</button>
								</span> -->
								<p><b>300 ml</b> In Stock</p>

								
							</div><!--/product-information-->

						</div>
						<div><br><br>
						<h2>Smudges and fi nger prints on screens?</h2>
Smudges and fi ngerprints left on screens and devices made of stainless steel can be annoying not 
only on a sunny day. They appear out of the blue, at the slightest touch. They make it hard to enjoy 
a fi lm, they are a fl aw in a freshly cleaned room. And we hate when such trifl es put as in a bad 
mood. That is why we designed the perfect 
SCREEN & INOX STEEL SMART SPRAY 
It will make cleaning fast and safe, but more importantly it will prevent new stains. 

<h4>What you will love it for:</h4>
it doesn’t leave traces and smudges on cleaned 
surfaces. 
  
<h4>What you can use it for:</h4>
computer screens, TV screens, plasma, LCD, 
LED and other displays, remote controls, 
mobile phones and computer keyboard. It is 
also recommended for cleaning devices made 
of INOX steel. You can use it for both matte 
and shiny surfaces.  

<h4>What is that beautiful scent:</h4>
juicy citrus fruit, jasmine, sweet vanilla, 
sandalwood.
 
<h4>What is our secret:</h4>
the spray forms an electrostati c coat on the 
surface, preventi ng dust from accumulati ng 
again.


<h4>SEE HOW SIMPLE IT IS TO USE: </h4>
spray a small amount of 
liquid on a microfi bre cloth 
and spread it on the surface 
you want to clean. Wipe it, 
and that’s it.
						</div>
					</div><!--/product-details-->

				</div>
