
				<div class="col-sm-9 padding-right">
					<div class="product-details"><!--product-details-->
						<div class="col-sm-5">
							<div class="view-product">
								<img src="images/product/504007.jpg" alt="" />
								
							</div>
							

						</div>
						<div class="col-sm-7">
							<div class="product-information"><!--/product-information-->
								<!-- <img src="images/product-details/new.jpg" class="newarrival" alt="" /> -->
								<h2>UNIVERSAL GEL</h2>
								<p>Product code: 504007</p>
								
								<!-- <span>
									<span>US $59</span>
									<label>Quantity:</label>
									<input type="text" value="3" />
									<button type="button" class="btn btn-fefault cart">
										<i class="fa fa-shopping-cart"></i>
										Add to cart
									</button>
								</span> -->
								<p><b>1000 ml</b> In Stock</p>

								
							</div><!--/product-information-->

						</div>
						<div><br><br>
						<h2>How to save time cleaning?</h2>
If you want to save time on cleaning, you need to get excellent, versatile detergents. 
Such as our universal gel concentrate. If you have 
UNIVERSAL GEL 
close by, in one go, you’ll get rid of dust and stains, even the persistent ones, degrease and 
gently polish the cleaned surfaces. And thanks to the lovely French fragrance oils, you’ll create 
a relaxing, cosy atmosphere. With such a fantastic gel, you can fi nally sit down and rest.

<h4>What you will love it for:</h4>
fourfold acti on. Thanks to the 
4 in 1 formula,ilt 
efficiently cleans, degreases, subtly polishes 
the surface and leaves a gentle scent.  
  
<h4>What is our secret:</h4>
highly concentrated gel formula = you save 
space, ti me and money.   

<h4>What you can use it for:</h4>
all washable surfaces, metal, MDF, laminated, 
plastic, ceramic, lino, ti les, terracott a tiles, 
milled rock tiles. You’ll appreciate especially 
when you clean big surfaces. <br>
 
<h4>  What assures additional safety:</h4>
schválenie PZH (Národný Hygienický Ústav)

<h4>What is that beautiful scent:</h4>
juicy citrus fruit, French lavender, jasmine, 
and fresh ozone notes.

<h4>Other things we took into account:</h4>
we know very well that 
in many houses there’s 
not enough space to 
store cleaning products. 
We’ve decided to 
address this problem 
and use high-performing 
concentrates based on 
versati le formulae. Now, you 
get one effi  cient product 
that serves four various 
purposes. Clever, isn’t it? 

<h4>SEE HOW SIMPLE IT IS TO USE</h4>
dissolve 35 ml of gel in 
5 l of warm water. Wash 
the surface with a well 
squeezed mop or cloth 
and just leave to it dry (the 
diluted gel does not require 
rinsing). 
						</div>
					</div><!--/product-details-->

				</div>
