
				<div class="col-sm-9 padding-right">
					<div class="product-details"><!--product-details-->
						<div class="col-sm-5">
							<div class="view-product">
								<img src="images/product/504008.jpg" alt="" />
								
							</div>
							

						</div>
						<div class="col-sm-7">
							<div class="product-information"><!--/product-information-->
								<!-- <img src="images/product-details/new.jpg" class="newarrival" alt="" /> -->
								<h2>DIRT BUSTER</h2>
								<p>Product code: 504008</p>
								
								<!-- <span>
									<span>US $59</span>
									<label>Quantity:</label>
									<input type="text" value="3" />
									<button type="button" class="btn btn-fefault cart">
										<i class="fa fa-shopping-cart"></i>
										Add to cart
									</button>
								</span> -->
								<p><b>500 ml</b> In Stock</p>

								
							</div><!--/product-information-->

						</div>
						<div><br><br>
						<h2>How to prepare for major cleaning?</h2>
With our Dirt Buster at hand you’ll put your surroundings in order fast, and cleaning up will 
become easy.
DIRT BUSTER 
It will help you take care of not only interiors, but also spaces around the house. You can 
use it to clean gazebos, balconies, garages, elevations and put workshops in order. You’ll 
look after surfaces and eliminate all stubborn dirt.

<h4>What you will love it for:</h4>
it’s powerful and effi  cient. From now on, you’ll 
be able to transform the surroundings of your 
home in the blink of an eye. With right dosage, 
you can adapt the strength of the liquid to 
your needs. Cleaning will become easier, 
and you’ll eff ortlessly remove: lubricants, 
waxes, oils, dirt and residues from very soiled 
surfaces.   
  
<h4>Other things we took into account: </h4>
additi onal, corrosion-slowing ingredients.   

<h4>What you can clean with it:</h4>
practi cally everything. Clean unprotected 
and hard surfaces: paving stones, terracott a 
tiles, lino, tiles. Wash the residue off  the 
roof, balcony, terrace, and metal surfaces. 
You can also use it to clean dirty clothes and 
upholstery.
 
<h4>What will delight you about it:</h4>
it removes dirt effi ciently, even in cold water.

<h4>What is that beautiful scent:</h4>
resh orange blossom, delicate white fl owers, 
rose, aromatic sandalwood.

<h4>What is our secret:</h4>
the extremely eff ective formula 
combines cleaning and degreasing 
properties. You can use the liquid 
on hard, unprotected, and alkali 
resisting surfaces.

<h4>SEE HOW SIMPLE IT IS TO USE: </h4>
dilute the appropriate 
amount of liquid in 
water (according to 
the instructi ons on the 
packaging). Wash the 
surface and just leave it 
to dry. Use the liquid to 
wash surfaces or for hand 
washing your clothes.
						</div>
					</div><!--/product-details-->

				</div>
