
				
				<div class="col-sm-9 padding-right">
					<div class="features_items"><!--features_items-->
						<h2 class="title text-center">Parfémy Pánske</h2>
						<div class="col-sm-4">
							<div class="product-image-wrapper">
								<div class="single-products">
									<div class="productinfo text-center">
										<img src="images/product/perfumy_02.jpg" alt="" />
										<h2>#02</h2>
										<p>green apple - cinnamon - olive tree oliwne</p>
										<a href="perfumy_101002_xen.html" class="btn btn-default add-to-cart"><i class="fa fa-shopping-cart"></i>More Info</a>
									</div>
									<!-- <div class="product-overlay">
										<div class="overlay-content">
											<h2>$56</h2>
											<p>Easy Polo Black Edition</p>
											<a href="#" class="btn btn-default add-to-cart"><i class="fa fa-shopping-cart"></i>Add to cart</a>
										</div>
									</div> -->
								</div>
							</div>
						</div>
						
						<div class="col-sm-4">
							<div class="product-image-wrapper">
								<div class="single-products">
									<div class="productinfo text-center">
										<img src="images/product/perfumy_04.jpg" alt="" />
										<h2>#04</h2>
										<p>grapefruit - coffee - black pepper </p>
										<a href="perfumy_101004_xen.html" class="btn btn-default add-to-cart"><i class="fa fa-shopping-cart"></i>More Info</a>
									</div>
									<!-- <div class="product-overlay">
										<div class="overlay-content">
											<h2>$56</h2>
											<p>Easy Polo Black Edition</p>
											<a href="#" class="btn btn-default add-to-cart"><i class="fa fa-shopping-cart"></i>Add to cart</a>
										</div>
									</div> -->
								</div>
							</div>
						</div>
						
						<div class="col-sm-4">
							<div class="product-image-wrapper">
								<div class="single-products">
									<div class="productinfo text-center">
										<img src="images/product/perfumy_06.jpg" alt="" />
										<h2>#06</h2>
										<p>lemon - kumquat - juniper </p>
										<a href="perfumy_101006_xen.html" class="btn btn-default add-to-cart"><i class="fa fa-shopping-cart"></i>More Info</a>
									</div>
									<!-- <div class="product-overlay">
										<div class="overlay-content">
											<h2>$56</h2>
											<p>Easy Polo Black Edition</p>
											<a href="#" class="btn btn-default add-to-cart"><i class="fa fa-shopping-cart"></i>Add to cart</a>
										</div>
									</div> -->
								</div>
							</div>
						</div>
						
						<div class="col-sm-4">
							<div class="product-image-wrapper">
								<div class="single-products">
									<div class="productinfo text-center">
										<img src="images/product/perfumy_08.jpg" alt="" />
										<h2>#08</h2>
										<p>marine notes - lime - reseda</p>
										<a href="perfumy_101008_xen.html" class="btn btn-default add-to-cart"><i class="fa fa-shopping-cart"></i>More Info</a>
									</div>
									<!-- <div class="product-overlay">
										<div class="overlay-content">
											<h2>$56</h2>
											<p>Easy Polo Black Edition</p>
											<a href="#" class="btn btn-default add-to-cart"><i class="fa fa-shopping-cart"></i>Add to cart</a>
										</div>
									</div> -->
								</div>
							</div>
						</div>
						
						<div class="col-sm-4">
							<div class="product-image-wrapper">
								<div class="single-products">
									<div class="productinfo text-center">
										<img src="images/product/perfumy_10.jpg" alt="" />
										<h2>#10</h2>
										<p>tangerine - ginger - lavender</p>
										<a href="perfumy_101010_xen.html" class="btn btn-default add-to-cart"><i class="fa fa-shopping-cart"></i>More Info</a>
									</div>
									<!-- <div class="product-overlay">
										<div class="overlay-content">
											<h2>$56</h2>
											<p>Easy Polo Black Edition</p>
											<a href="#" class="btn btn-default add-to-cart"><i class="fa fa-shopping-cart"></i>Add to cart</a>
										</div>
									</div> -->
								</div>
							</div>
						</div>
						

						
						<div class="col-sm-4">
							<div class="product-image-wrapper">
								<div class="single-products">
									<div class="productinfo text-center">
										<img src="images/product/perfumy_14.jpg" alt="" />
										<h2>#14</h2>
										<p>marine notes - orange - cedar</p>
										<a href="perfumy_101014_xen.html" class="btn btn-default add-to-cart"><i class="fa fa-shopping-cart"></i>More Info</a>
									</div>
									<!-- <div class="product-overlay">
										<div class="overlay-content">
											<h2>$56</h2>
											<p>Easy Polo Black Edition</p>
											<a href="#" class="btn btn-default add-to-cart"><i class="fa fa-shopping-cart"></i>Add to cart</a>
										</div>
									</div> -->
								</div>
							</div>
						</div>
						
						<div class="col-sm-4">
							<div class="product-image-wrapper">
								<div class="single-products">
									<div class="productinfo text-center">
										<img src="images/product/perfumy_16.jpg" alt="" />
										<h2>#16</h2>
										<p>pear - mint - basil</p>
										<a href="perfumy_101016_xen.html" class="btn btn-default add-to-cart"><i class="fa fa-shopping-cart"></i>More Info</a>
									</div>
									<!-- <div class="product-overlay">
										<div class="overlay-content">
											<h2>$56</h2>
											<p>Easy Polo Black Edition</p>
											<a href="#" class="btn btn-default add-to-cart"><i class="fa fa-shopping-cart"></i>Add to cart</a>
										</div>
									</div> -->
								</div>
							</div>
						</div>
						
						<div class="col-sm-4">
							<div class="product-image-wrapper">
								<div class="single-products">
									<div class="productinfo text-center">
										<img src="images/product/perfumy_18.jpg" alt="" />
										<h2>#18</h2>
										<p>coffee - rosepepper - tonka beans </p>
										<a href="perfumy_101018_xen.html" class="btn btn-default add-to-cart"><i class="fa fa-shopping-cart"></i>More Info</a>
									</div>
									<!-- <div class="product-overlay">
										<div class="overlay-content">
											<h2>$56</h2>
											<p>Easy Polo Black Edition</p>
											<a href="#" class="btn btn-default add-to-cart"><i class="fa fa-shopping-cart"></i>Add to cart</a>
										</div>
									</div> -->
								</div>
							</div>
						</div>
						
						<div class="col-sm-4">
							<div class="product-image-wrapper">
								<div class="single-products">
									<div class="productinfo text-center">
										<img src="images/product/perfumy_20.jpg" alt="" />
										<h2>#20</h2>
										<p>cinnamon - rose - leather notes</p>
										<a href="perfumy_101020_xen.html" class="btn btn-default add-to-cart"><i class="fa fa-shopping-cart"></i>More Info</a>
									</div>
									<!-- <div class="product-overlay">
										<div class="overlay-content">
											<h2>$56</h2>
											<p>Easy Polo Black Edition</p>
											<a href="#" class="btn btn-default add-to-cart"><i class="fa fa-shopping-cart"></i>Add to cart</a>
										</div>
									</div> -->
								</div>
							</div>
						</div>
						<div class="col-sm-4">
							<div class="product-image-wrapper">
								<div class="single-products">
									<div class="productinfo text-center">
										<img src="images/product/perfumy_22.jpg" alt="" />
										<h2>#22</h2>
										<p>lemon - leather notes - ambergris</p>
										<a href="perfumy_101022_xen.html" class="btn btn-default add-to-cart"><i class="fa fa-shopping-cart"></i>More Info</a>
									</div>
									<!-- <div class="product-overlay">
										<div class="overlay-content">
											<h2>$56</h2>
											<p>Easy Polo Black Edition</p>
											<a href="#" class="btn btn-default add-to-cart"><i class="fa fa-shopping-cart"></i>Add to cart</a>
										</div>
									</div> -->
								</div>
							</div>
						</div>
						
						<div class="col-sm-4">
							<div class="product-image-wrapper">
								<div class="single-products">
									<div class="productinfo text-center">
										<img src="images/product/perfumy_24.jpg" alt="" />
										<h2>#24</h2>
										<p>laurel leaf - sandalwood - ambergris</p>
										<a href="perfumy_101024_xen.html" class="btn btn-default add-to-cart"><i class="fa fa-shopping-cart"></i>More Info</a>
									</div>
									<!-- <div class="product-overlay">
										<div class="overlay-content">
											<h2>$24</h2>
											<p>Easy Polo Black Edition</p>
											<a href="#" class="btn btn-default add-to-cart"><i class="fa fa-shopping-cart"></i>Add to cart</a>
										</div>
									</div> -->
								</div>
							</div>
						</div>
						
						<div class="col-sm-4">
							<div class="product-image-wrapper">
								<div class="single-products">
									<div class="productinfo text-center">
										<img src="images/product/perfumy_26.jpg" alt="" />
										<h2>#26</h2>
										<p>agar - rosewood - vanilla</p>
										<a href="perfumy_101026_xen.html" class="btn btn-default add-to-cart"><i class="fa fa-shopping-cart"></i>More Info</a>
									</div>
									<!-- <div class="product-overlay">
										<div class="overlay-content">
											<h2>$56</h2>
											<p>Easy Polo Black Edition</p>
											<a href="#" class="btn btn-default add-to-cart"><i class="fa fa-shopping-cart"></i>Add to cart</a>
										</div>
									</div> -->
								</div>
							</div>
						</div>
						
						<div class="col-sm-4">
							<div class="product-image-wrapper">
								<div class="single-products">
									<div class="productinfo text-center">
										<img src="images/product/perfumy_28.jpg" alt="" />
										<h2>#28</h2>
										<p>bergamot - papaya - nutmeg </p>
										<a href="perfumy_101028_xen.html" class="btn btn-default add-to-cart"><i class="fa fa-shopping-cart"></i>More Info</a>
									</div>
									<!-- <div class="product-overlay">
										<div class="overlay-content">
											<h2>$56</h2>
											<p>Easy Polo Black Edition</p>
											<a href="#" class="btn btn-default add-to-cart"><i class="fa fa-shopping-cart"></i>Add to cart</a>
										</div>
									</div> -->
								</div>
							</div>
						</div>
						
						<div class="col-sm-4">
							<div class="product-image-wrapper">
								<div class="single-products">
									<div class="productinfo text-center">
										<img src="images/product/perfumy_30.jpg" alt="" />
										<h2>#30</h2>
										<p>green apple - lavender - fir </p>
										<a href="perfumy_101030_xen.html" class="btn btn-default add-to-cart"><i class="fa fa-shopping-cart"></i>More Info</a>
									</div>
									<!-- <div class="product-overlay">
										<div class="overlay-content">
											<h2>$56</h2>
											<p>Easy Polo Black Edition</p>
											<a href="#" class="btn btn-default add-to-cart"><i class="fa fa-shopping-cart"></i>Add to cart</a>
										</div>
									</div> -->
								</div>
							</div>
						</div>
						
						<div class="col-sm-4">
							<div class="product-image-wrapper">
								<div class="single-products">
									<div class="productinfo text-center">
										<img src="images/product/perfumy_32.jpg" alt="" />
										<h2>#32</h2>
										<p>grapefruit - violet - leather notes</p>
										<a href="perfumy_101032_xen.html" class="btn btn-default add-to-cart"><i class="fa fa-shopping-cart"></i>More Info</a>
									</div>
									<!-- <div class="product-overlay">
										<div class="overlay-content">
											<h2>$56</h2>
											<p>Easy Polo Black Edition</p>
											<a href="#" class="btn btn-default add-to-cart"><i class="fa fa-shopping-cart"></i>Add to cart</a>
										</div>
									</div> -->
								</div>
							</div>
						</div>
						
						<div class="col-sm-4">
							<div class="product-image-wrapper">
								<div class="single-products">
									<div class="productinfo text-center">
										<img src="images/product/perfumy_34.jpg" alt="" />
										<h2>#34</h2>
										<p>seaweed - orange - cotton blossom</p>
										<a href="perfumy_101034_xen.html" class="btn btn-default add-to-cart"><i class="fa fa-shopping-cart"></i>More Info</a>
									</div>
									<!-- <div class="product-overlay">
										<div class="overlay-content">
											<h2>$56</h2>
											<p>Easy Polo Black Edition</p>
											<a href="#" class="btn btn-default add-to-cart"><i class="fa fa-shopping-cart"></i>Add to cart</a>
										</div>
									</div> -->
								</div>
							</div>
						</div>
						
						<div class="col-sm-4">
							<div class="product-image-wrapper">
								<div class="single-products">
									<div class="productinfo text-center">
										<img src="images/product/perfumy_36.jpg" alt="" />
										<h2>#36</h2>
										<p>bergamot - tomato leaves - sandalwood</p>
										<a href="perfumy_101036_xen.html" class="btn btn-default add-to-cart"><i class="fa fa-shopping-cart"></i>More Info</a>
									</div>
									<!-- <div class="product-overlay">
										<div class="overlay-content">
											<h2>$56</h2>
											<p>Easy Polo Black Edition</p>
											<a href="#" class="btn btn-default add-to-cart"><i class="fa fa-shopping-cart"></i>Add to cart</a>
										</div>
									</div> -->
								</div>
							</div>
						</div>
						
						<div class="col-sm-4">
							<div class="product-image-wrapper">
								<div class="single-products">
									<div class="productinfo text-center">
										<img src="images/product/perfume_38.jpg" alt="" />
										<h2>#38</h2>
										<p>seawater - laurel leaf - tangerine</p>
										<a href="perfumy_101038_xen.html" class="btn btn-default add-to-cart"><i class="fa fa-shopping-cart"></i>More Info</a>
									</div>
									<!-- <div class="product-overlay">
										<div class="overlay-content">
											<h2>$56</h2>
											<p>Easy Polo Black Edition</p>
											<a href="#" class="btn btn-default add-to-cart"><i class="fa fa-shopping-cart"></i>Add to cart</a>
										</div>
									</div> -->
								</div>
							</div>
						</div>
						
						<div class="col-sm-4">
							<div class="product-image-wrapper">
								<div class="single-products">
									<div class="productinfo text-center">
										<img src="images/product/perfumy_40.jpg" alt="" />
										<h2>#40</h2>
										<p>orange - vetiver - benzoin</p>
										<a href="perfumy_101040_xen.html" class="btn btn-default add-to-cart"><i class="fa fa-shopping-cart"></i>More Info</a>
									</div>
									<!-- <div class="product-overlay">
										<div class="overlay-content">
											<h2>$56</h2>
											<p>Easy Polo Black Edition</p>
											<a href="#" class="btn btn-default add-to-cart"><i class="fa fa-shopping-cart"></i>Add to cart</a>
										</div>
									</div> -->
								</div>
							</div>
						</div>
						
						<div class="col-sm-4">
							<div class="product-image-wrapper">
								<div class="single-products">
									<div class="productinfo text-center">
										<img src="images/product/perfumy_42.jpg" alt="" />
										<h2>#42</h2>
										<p>black pepper - patchouli - wood notes</p>
										<a href="perfumy_101042_xen.html" class="btn btn-default add-to-cart"><i class="fa fa-shopping-cart"></i>More Info</a>
									</div>
									<!-- <div class="product-overlay">
										<div class="overlay-content">
											<h2>$56</h2>
											<p>Easy Polo Black Edition</p>
											<a href="#" class="btn btn-default add-to-cart"><i class="fa fa-shopping-cart"></i>Add to cart</a>
										</div>
									</div> -->
								</div>
							</div>
						</div>
						
						<div class="col-sm-4">
							<div class="product-image-wrapper">
								<div class="single-products">
									<div class="productinfo text-center">
										<img src="images/product/perfumy_44.jpg" alt="" />
										<h2>#44</h2>
										<p>bergamot - incense - ginger</p>
										<a href="perfumy_1010044_xen.html" class="btn btn-default add-to-cart"><i class="fa fa-shopping-cart"></i>More Info</a>
									</div>
									<!-- <div class="product-overlay">
										<div class="overlay-content">
											<h2>$56</h2>
											<p>Easy Polo Black Edition</p>
											<a href="#" class="btn btn-default add-to-cart"><i class="fa fa-shopping-cart"></i>Add to cart</a>
										</div>
									</div> -->
								</div>
							</div>
						</div>
						

						




						
						
<!--						<ul class="pagination">
							<li class="active"><a href="">1</a></li>
							<li><a href="">2</a></li>
							<li><a href="">3</a></li>
							<li><a href="">&raquo;</a></li>
						</ul> -->
					</div><!--features_items-->
							<ul class="pagination">
							<li class="active"><a href="">1</a></li>
							<li><a href="">2</a></li>
							<li><a href="">3</a></li>
							<li><a href="">&raquo;</a></li>
						</ul>
				</div>
