				<div class="col-sm-3">
					<div class="left-sidebar">
						<div class="brands_products"><!--brands_products-->
							<h2>Product categories</h2>
							<div class="brands-name">
								<ul class="nav nav-pills nav-stacked">
									<li><a href="produkty_women_<? echo "$id3"; ?>.html">Perfume Woman</a></li>
									<li><a href="produkty_men_<? echo "$id3"; ?>.html">Man Perfume</a></li>
									<li><a href="produkty_house_<? echo "$id3"; ?>.html">For home</a></li>
									<li><a href="produkty_body_<? echo "$id3"; ?>.html">Make-Up</a></li>
									<li><a href="#"> </a></li>
									<li><a href="#"> </a></li>
									<li><a href="#"> </a></li>
								</ul>
							</div>
						</div><!--/brands_products-->
						
					</div>
				</div>