	<section id="slider"><!--slider-->
		<div class="container">
			<div class="row">
				<div class="col-sm-12">
					<div id="slider-carousel" class="carousel slide" data-ride="carousel">
						<ol class="carousel-indicators">
							<li data-target="#slider-carousel" data-slide-to="0" class="active"></li>
							<li data-target="#slider-carousel" data-slide-to="1"></li>
							<li data-target="#slider-carousel" data-slide-to="2"></li>
						</ol>
						
						<div class="carousel-inner">
							<div class="item active">
								<div class="col-sm-6">
									<h1><span>E</span>-SHOPPER</h1>
									<h2>Proste możliwości </h2>
									<p>Co byś powiedział na możliwość zarobienia dodatkowych kilkuset złotych miesięcznie wykonując kilka prostych czynności?  </p>
									<a href="#sprobuj"><button type="button" class="btn btn-default get">Spróbuj Teraz</button></a>
								</div>
								
								<div class="col-sm-6">
									<img src="images/home/girl1.jpg" class="girl img-responsive" alt="" />
									<img src="images/home/pricing.png"  class="pricing" alt="" />
								</div>
								
							</div>
							<div class="item">
								<div class="col-sm-6">
									<h1><span>E</span>-SHOPPER</h1>
									<h2>Tańsze zakupy o 30%</h2>
									<p>Co byś powiedział na sklep internetowy, w którym Twoje zakupy są 30% tańsze? </p>
									<a href="#sprobuj"><button type="button" class="btn btn-default get">Spróbuj Teraz</button></a>
								</div>
								 
								<div class="col-sm-6">
									<img src="images/home/girl2.jpg" class="girl img-responsive" alt="" />
									<img src="images/home/pricing.png"  class="pricing" alt="" />
								</div>
								
							</div>
							
							<div class="item">
								<div class="col-sm-6">
									<h1><span>E</span>-SHOPPER</h1>
									<h2>Dodatkowe pieniądze </h2>
									<p>Czy byłoby to dla Ciebie opłacalne – zarabiać pieniądze na zakupach?  </p>
									<a href="#sprobuj"><button type="button" class="btn btn-default get">Spróbuj Teraz</button></a>
								</div>
								
								<div class="col-sm-6">
									<img src="images/home/girl3.jpg" class="girl img-responsive" alt="" />
									<img src="images/home/pricing.png" class="pricing" alt="" />
								</div>
								
							</div>
							
						</div>
						
						<a href="#slider-carousel" class="left control-carousel hidden-xs" data-slide="prev">
							<i class="fa fa-angle-left"></i>
						</a>
						<a href="#slider-carousel" class="right control-carousel hidden-xs" data-slide="next">
							<i class="fa fa-angle-right"></i>
						</a>
					</div>
					
				</div>
			</div>
		</div>
	</section><!--/slider-->