
				<div class="col-sm-9 padding-right">
					<div class="product-details"><!--product-details-->
						<div class="col-sm-5">
							<div class="view-product">
								<img src="images/product/perfumy_31.jpg" alt="" />
								
							</div>
							

						</div>
						<div class="col-sm-7">
							<div class="product-information"><!--/product-information-->
								<!-- <img src="images/product-details/new.jpg" class="newarrival" alt="" /> -->
								<h2>PERFUMY DAMSKIE #31</h2><p>piwonia – róża – różowy pieprz</p>
								<p>Kod produktu: 1010031</p>
								<p>Zaperfumowanie: 20%</p>
								<!-- <span>
									<span>US $59</span>
									<label>Quantity:</label>
									<input type="text" value="3" />
									<button type="button" class="btn btn-fefault cart">
										<i class="fa fa-shopping-cart"></i>
										Add to cart
									</button>
								</span> -->
								<p><b>50 ml</b> </p>

								
							</div><!--/product-information-->

						</div>
						<div><br><br>
						<h2>Za co go pokochasz:</h2>
za delikatność i naturalność. Świeży, przyjemny zapach, przepojony słodyczą róż i piwonii, z odrobiną pikantnego różowego pieprzu. 
<br> <br>
<h4>Z jakiej rodziny pochodzi: <i>kwiatowo-owocowej</i></h4> 
<h4>Jak jest odbierany: <i>świeży, różany</i></h4>
<h4>Jaką ma projekcję: <i>subtelną</i></h4>
<h4>Z jakiej jest kategorii: <i>business</i></h4> 
<h4>Architektura zapachu:<br>
<i>Nuta głowy: mandarynka, piwonia</i><br>
<i>Nuta serca: róża, osmantus</i><br>
<i>Nuta głębi: czerwony pieprz, drzewo sandałowe, paczula</i></h4>



						</div>
					</div><!--/product-details-->

				</div>
