
				<div class="col-sm-9 padding-right">
					<div class="product-details"><!--product-details-->
						<div class="col-sm-5">
							<div class="view-product">
								<img src="images/product/perfume_01.jpg" alt="" />
								
							</div>
							

						</div>
						<div class="col-sm-7">
							<div class="product-information"><!--/product-information-->
								<!-- <img src="images/product-details/new.jpg" class="newarrival" alt="" /> -->
								<h2>PERFUMY DAMSKIE #1</h2><p>zielone jabłko – magnolia – ogórek</p>
								<p>Kod produktu: 101001</p>
								<p>Zaperfumowanie: 20%</p>
								<!-- <span>
									<span>US $59</span>
									<label>Quantity:</label>
									<input type="text" value="3" />
									<button type="button" class="btn btn-fefault cart">
										<i class="fa fa-shopping-cart"></i>
										Add to cart
									</button>
								</span> -->
								<p><b>50 ml</b> </p>

								
							</div><!--/product-information-->

						</div>
						<div><br><br>
						<h2>Za co go pokochasz:</h2>
						za naturalność i świeżość. Pamiętasz ten moment, gdy przekrajasz soczyste jabłko? Nagle zalewa cię fala świeżości. Tu dodatkowo towarzyszy jej powiew wiosennych kwiatów: fiołków, konwalii i magnolii.
<br> <br>
<h4>Z jakiej rodziny pochodzi: <i>kwiatowo-owocowej</i></h4> 
<h4>Jak jest odbierany: <i>świeży, zielony</i></h4>
<h4>Jaką ma projekcję: <i>umiarkowaną</i></h4>
<h4>Z jakiej jest kategorii: <i>casual</i></h4> 
<h4>Architektura zapachu:<br><i>Nuta głowy: grejpfrut, zielone jabłko, magnolia</i><br><i>Nuta serca: ogórek, róża, konwalia, fiołek</i><br><i>Nuta głębi: ambra, drzewo sandałowe</i></h4>



						</div>
					</div><!--/product-details-->
					
					
					
					
					
				</div>
