
				<div class="col-sm-9 padding-right">
					<div class="product-details"><!--product-details-->
						<div class="col-sm-5">
							<div class="view-product">
								<img src="images/product/perfumy_67.jpg" alt="" />
								
							</div>
							

						</div>
						<div class="col-sm-7">
							<div class="product-information"><!--/product-information-->
								<!-- <img src="images/product-details/new.jpg" class="newarrival" alt="" /> --> 
								<h2>Perfumy Damskie #67</h2><p>kwiat pomarańczy - bób tonka - wanilia</p>
								<p>Numer produktu: 101067</p>
								<p>Zaperfumowanie: 20%</p>
								<!-- <span>
									<span>US $59</span>
									<label>Quantity:</label>
									<input type="text" value="3" />
									<button type="button" class="btn btn-fefault cart">
										<i class="fa fa-shopping-cart"></i>
										Add to cart
									</button>
								</span> -->
								<p><b>50 ml</b> </p>

								
							</div><!--/product-information-->

						</div>
						<div><br><br>
						<h2>Za co go pokochasz:</h2>
za nieujarzmioną zmysłowość. Intensywne, orientalne nuty kwiatu pomarańczy, wanilii i fasoli tonka w połączeniu z ożywczym jaśminem i różaną bazą są niezwykle kobiece i sensualne.
<br> <br>
<h4>Z jakiej rodziny pochodzi: <i>orientalno-kwiatowej</i></h4> 
<h4>Jak jest odbierany: <i>waniliowy, balsamiczny</i></h4> 
<h4>Jaką ma projekcję: <i>mocną</i></h4> 
<h4>Z jakiej jest kategorii: <i>glamour</i></h4>
<h4>Architektura zapachu: 
<br><i>Nuta głowy: jeżyna, liść mandarynki</i>
<br><i>Nuta serca: kwiat pomarańczy, cereus, jaśmin, róża</i>
<br><i>Nuta głębi: drzewo sandałowe, fasola tonka, wanilia</i></h4>


						</div>
					</div><!--/product-details-->

				</div>
