
				<div class="col-sm-9 padding-right">
					<div class="product-details"><!--product-details-->
						<div class="col-sm-5">
							<div class="view-product">
								<img src="images/product/perfumy_13.jpg" alt="" />
								
							</div>
							

						</div>
						<div class="col-sm-7">
							<div class="product-information"><!--/product-information-->
								<!-- <img src="images/product-details/new.jpg" class="newarrival" alt="" /> -->
								<h2>PERFUMY DAMSKIE #13</h2><p>gorzka pomarańcza – imbir – miód</p>
								<p>Kod produktu: 1010013</p>
								<p>Zaperfumowanie: 20%</p>
								<!-- <span>
									<span>US $59</span>
									<label>Quantity:</label>
									<input type="text" value="3" />
									<button type="button" class="btn btn-fefault cart">
										<i class="fa fa-shopping-cart"></i>
										Add to cart
									</button>
								</span> -->
								<p><b>50 ml</b> </p>

								
							</div><!--/product-information-->

						</div>
						<div><br><br>
						<h2>Za co go pokochasz:</h2>
za wielowymiarowość. Ten zapach jest jak czerwona szminka. Seksowny i uwodzicielski, a jednocześnie elegancki. Podkreśli Twój styl słodyczą miodu i świeżością gorzkiej pomarańczy.
<br> <br>
<h4>Z jakiej rodziny pochodzi: <i>kwiatowo-owocowej</i></h4> 
<h4>Jak jest odbierany: <i>kwiatowy, słodko-gorzki </i></h4>
<h4>Jaką ma projekcję: <i>mocną</i></h4>
<h4>Z jakiej jest kategorii: <i>glamour</i></h4> 
<h4>Architektura zapachu:<br>
<i>Nuta głowy: gorzka pomarańcza, jaśmin</i><br>
<i>Nuta serca: kwiat pomarańczy, imbir</i><br>
<i>Nuta głębi: miód, wanilia, drzewo sandałowe</i></h4>



						</div>
					</div><!--/product-details-->

				</div>
