
				<div class="col-sm-9 padding-right">
					<div class="product-details"><!--product-details-->
						<div class="col-sm-5">
							<div class="view-product">
								<img src="images/product/perfumy_49.jpg" alt="" />
								
							</div>
							

						</div>
						<div class="col-sm-7">
							<div class="product-information"><!--/product-information-->
								<!-- <img src="images/product-details/new.jpg" class="newarrival" alt="" /> -->
								<h2>PERFUMY DAMSKIE #49</h2><p>bergamotka – ylang-ylang – drzewo sandałowe</p>
								<p>Kod produktu: 1010049</p>
								<p>Zaperfumowanie: 20%</p>
								<!-- <span>
									<span>US $59</span>
									<label>Quantity:</label>
									<input type="text" value="3" />
									<button type="button" class="btn btn-fefault cart">
										<i class="fa fa-shopping-cart"></i>
										Add to cart
									</button>
								</span> -->
								<p><b>50 ml</b> </p>

								
							</div><!--/product-information-->

						</div>
						<div><br><br>
						<h2>Za co go pokochasz:</h2>
za łagodną świeżość. Spokojny, wyważony, ale jednocześnie bardzo kobiecy zapach. Subtelności dodają mu białe kwiaty, a zmysłowości – sandałowiec. 
<br> <br>
<h4>Z jakiej rodziny pochodzi: <i>kwiatowo-orientalnej</i></h4> 
<h4>Jak jest odbierany: <i>słodki, świeży</i></h4>
<h4>Jaką ma projekcję: <i>umiarkowaną</i></h4>
<h4>Z jakiej jest kategorii: <i>business</i></h4> 
<h4>Architektura zapachu:<br>
<i>Nuta głowy: bergamotka</i><br>
<i>Nuta serca: ylang-ylang, kwiat pomarańczy, lilia</i><br>
<i>Nuta głębi: drzewo sandałowe, ambra, wanilia</i></h4>



						</div>
					</div><!--/product-details-->

				</div>
