
				<div class="col-sm-9 padding-right">
					<div class="product-details"><!--product-details-->
						<div class="col-sm-5">
							<div class="view-product">
								<img src="images/product/perfumy_53.jpg" alt="" />
								
							</div>
							

						</div>
						<div class="col-sm-7">
							<div class="product-information"><!--/product-information-->
								<!-- <img src="images/product-details/new.jpg" class="newarrival" alt="" /> --> 
								<h2>Perfumy Damskie #53</h2><p>kawa – gruszka – drzewo kaszmirowe</p>
								<p>Numer produktu: 101053</p>
								<p>Zaperfumowanie: 20%</p>
								<!-- <span>
									<span>US $59</span>
									<label>Quantity:</label>
									<input type="text" value="3" />
									<button type="button" class="btn btn-fefault cart">
										<i class="fa fa-shopping-cart"></i>
										Add to cart
									</button>
								</span> -->
								<p><b>50 ml</b> </p>

								
							</div><!--/product-information-->

						</div>
						<div><br><br>
						<h2>Za co go pokochasz:</h2>
za wyjątkową aromatyczność. Kawa, wanilia, migdały – brzmi pysznie. Ale żeby nie było za słodko, mamy tu również bogaty wachlarz nut drzewnych: od sandałowca po luksusowe drzewo kaszmirowe.
<br> <br>
<h4>Z jakiej rodziny pochodzi: <i>orientalno-drzewnej</i></h4> 
<h4>Jak jest odbierany: <i>słodki, kawowy</i></h4> 
<h4>Jaką ma projekcję: <i>mocną</i></h4> 
<h4>Z jakiej jest kategorii: <i>glamour</i></h4>
<h4>Architektura zapachu: 
<br><i>Nuta głowy: gruszka, kwiat pomarańczy, różowy pieprz</i>
<br><i>Nuta serca: migdały, kawa, jaśmin</i>
<br><i>Nuta głębi: drzewo kaszmirowe, drzewo sandałowe, cedr, wanilia</i></h4>


						</div>
					</div><!--/product-details-->

				</div>
