
				<div class="col-sm-9 padding-right">
					<div class="product-details"><!--product-details-->
						<div class="col-sm-5">
							<div class="view-product">
								<img src="images/product/perfumy_09.jpg" alt="" />
								
							</div>
							

						</div>
						<div class="col-sm-7">
							<div class="product-information"><!--/product-information-->
								<!-- <img src="images/product-details/new.jpg" class="newarrival" alt="" /> -->
								<h2>PERFUMY DAMSKIE #9</h2><p>karmel – melon – wata cukrowa</p>
								<p>Kod produktu: 101009</p>
								<p>Zaperfumowanie: 20%</p>
								<!-- <span>
									<span>US $59</span>
									<label>Quantity:</label>
									<input type="text" value="3" />
									<button type="button" class="btn btn-fefault cart">
										<i class="fa fa-shopping-cart"></i>
										Add to cart
									</button>
								</span> -->
								<p><b>50 ml</b> </p>

								
							</div><!--/product-information-->

						</div>
						<div><br><br>
						<h2>Za co go pokochasz:</h2>
za nieziemską słodycz. Karmel, wata cukrowa, czekolada, melon i miód to połączenie  dla kobiet, które mają niepohamowany apetyt na życie.
<br> <br>
<h4>Z jakiej rodziny pochodzi: <i>orientalno-korzennej</i></h4> 
<h4>Jak jest odbierany: <i>słodki, karmelowy</i></h4>
<h4>Jaką ma projekcję: <i>mocną</i></h4>
<h4>Z jakiej jest kategorii: <i>glamour</i></h4> 
<h4>Architektura zapachu:<br>
<i>Nuta głowy: melon, wata cukrowa, liść czarnej porzeczki</i><br>
<i>Nuta serca: miód, śliwka, brzoskwinia</i><br>
<i>Nuta głębi: karmel, czekolada, wanilia, piżmo</i></h4>



						</div>
					</div><!--/product-details-->

				</div>
