
				<div class="col-sm-9 padding-right">
					<div class="product-details"><!--product-details-->
						<div class="col-sm-5">
							<div class="view-product">
								<img src="images/product/perfume_05.jpg" alt="" />
								
							</div>
							

						</div>
						<div class="col-sm-7">
							<div class="product-information"><!--/product-information-->
								<!-- <img src="images/product-details/new.jpg" class="newarrival" alt="" /> -->
								<h2>PERFUMY DAMSKIE #5</h2><p>wanilia – irys – piżmo</p>
								<p>Kod produktu: 101005</p>
								<p>Zaperfumowanie: 20%</p>
								<!-- <span>
									<span>US $59</span>
									<label>Quantity:</label>
									<input type="text" value="3" />
									<button type="button" class="btn btn-fefault cart">
										<i class="fa fa-shopping-cart"></i>
										Add to cart
									</button>
								</span> -->
								<p><b>50 ml</b> </p>

								
							</div><!--/product-information-->

						</div>
						<div><br><br>
						<h2>Za co go pokochasz:</h2>
za radosną lekkość. Za każdym razem, gdy sięgniesz po ten pudrowo-waniliowy zapach, kąciki ust same uniosą Ci się w uśmiechu. Poczujesz się lekko i świeżo.
<br> <br>
<h4>Z jakiej rodziny pochodzi: <i>szyprowo-kwiatowej</i></h4> 
<h4>Jak jest odbierany: <i>słodki, waniliowy</i></h4>
<h4>Jaką ma projekcję: <i>umiarkowaną</i></h4>
<h4>Z jakiej jest kategorii: <i>casual</i></h4> 
<h4>Architektura zapachu:<br>
<i>Nuta głowy: jaśmin, irys</i><br>
<i>Nuta serca: wanilia</i><br>
<i>Nuta głębi: białe piżmo</i></h4>



						</div>
					</div><!--/product-details-->
					
					
					
					
					
				</div>
