
				<div class="col-sm-9 padding-right">
					<div class="product-details"><!--product-details-->
						<div class="col-sm-5">
							<div class="view-product">
								<img src="images/product/perfumy_45.jpg" alt="" />
								
							</div>
							

						</div>
						<div class="col-sm-7">
							<div class="product-information"><!--/product-information-->
								<!-- <img src="images/product-details/new.jpg" class="newarrival" alt="" /> -->
								<h2>PERFUMY DAMSKIE #45</h2><p>brzoskwinia – róża – frezja</p>
								<p>Kod produktu: 1010045</p>
								<p>Zaperfumowanie: 20%</p>
								<!-- <span>
									<span>US $59</span>
									<label>Quantity:</label>
									<input type="text" value="3" />
									<button type="button" class="btn btn-fefault cart">
										<i class="fa fa-shopping-cart"></i>
										Add to cart
									</button>
								</span> -->
								<p><b>50 ml</b> </p>

								
							</div><!--/product-information-->

						</div>
						<div><br><br>
						<h2>Za co go pokochasz:</h2>
za migotliwość. Jeśli poświęcisz mu chwilę, odkryjesz, jak pięknie pulsują w nim nuty słonecznej brzoskwini, słodycz frezji i świeżość kolendry. Jest mocny i intensywny, a jednocześnie zwiewny i delikatny. 
<br> <br>
<h4>Z jakiej rodziny pochodzi: <i>szyprowo-owocowej</i></h4> 
<h4>Jak jest odbierany: <i>kwiatowy, intensywny</i></h4>
<h4>Jaką ma projekcję: <i>mocną</i></h4>
<h4>Z jakiej jest kategorii: <i>romance</i></h4> 
<h4>Architektura zapachu:<br>
<i>Nuta głowy: frezja, brzoskwinia, gardenia</i><br>
<i>Nuta serca: kolendra, róża, jaśmin</i><br>
<i>Nuta głębi: wanilia, paczula, wetyweria</i></h4>



						</div>
					</div><!--/product-details-->

				</div>
