
				<div class="col-sm-9 padding-right">
					<div class="product-details"><!--product-details-->
						<div class="col-sm-5">
							<div class="view-product">
								<img src="images/product/perfumy_34.jpg" alt="" />
								
							</div>
							

						</div>
						<div class="col-sm-7">
							<div class="product-information"><!--/product-information-->
								<!-- <img src="images/product-details/new.jpg" class="newarrival" alt="" /> -->
								<h2>Perfumy Męskie #34</h2><p>wodorosty – pomarańcza – kwiat bawełny</p>
								<p>Kod produktu: 101034</p>
								<p>Zaperfumowanie: 20%</p>
								<!-- <span>
									<span>US $59</span>
									<label>Quantity:</label>
									<input type="text" value="3" />
									<button type="button" class="btn btn-fefault cart">
										<i class="fa fa-shopping-cart"></i>
										Add to cart
									</button>
								</span> -->
								<p><b>50 ml</b></p>

								
							</div><!--/product-information-->

						</div>
						<div><br><br>
<h2>Co Cię w nim uwiedzie:</h2>
oryginalność połączeń. Wyobraź sobie wzburzone fale. Niespokojne morze wyrzuca na brzeg aromatyczne cytrusy, wodorosty i balsamiczną ambrę.  
<br> <br>
<h4>Z jakiej rodziny pochodzi: <i>wodnej</i></h4> 
<h4>Jak jest odbierany: <i>morski, orzeźwiający</i></h4>
<h4>Jaką ma projekcję: <i>mocną</i></h4>
<h4>Z jakiej jest kategorii: <i>sport</i></h4> 
<h4>Architektura zapachu:
<br>Nuta głowy:<i>petitgrain, pomarańcza, mandarynka</i>
<br>Nuta serca:<i>kwiat bawełny, wodorosty, lawenda</i>
<br>Nuta głębi:<i>cedr, paczula, ambra</i></h4>



						</div>
					</div><!--/product-details-->
					
					
					
					
					
				</div>
