
				<div class="col-sm-9 padding-right">
					<div class="product-details"><!--product-details-->
						<div class="col-sm-5">
							<div class="view-product">
								<img src="images/product/perfumy_15.jpg" alt="" />
								
							</div>
							

						</div>
						<div class="col-sm-7">
							<div class="product-information"><!--/product-information-->
								<!-- <img src="images/product-details/new.jpg" class="newarrival" alt="" /> -->
								<h2>PERFUMY DAMSKIE #15</h2><p>truskawka – wiśnia – karmel</p>
								<p>Kod produktu: 1010015</p>
								<p>Zaperfumowanie: 20%</p>
								<!-- <span>
									<span>US $59</span>
									<label>Quantity:</label>
									<input type="text" value="3" />
									<button type="button" class="btn btn-fefault cart">
										<i class="fa fa-shopping-cart"></i>
										Add to cart
									</button>
								</span> -->
								<p><b>50 ml</b> </p>

								
							</div><!--/product-information-->

						</div>
						<div><br><br>
						<h2>Za co go pokochasz:</h2>
za słodkie nuty pełni lata. Soczyste letnie owoce i odważne nuty gourmand sprawiają, że kompozycja jest kusząca i apetyczna.
<br> <br>
<h4>Z jakiej rodziny pochodzi: <i>szyprowo-owocowej </i></h4> 
<h4>Jak jest odbierany: <i>soczysty, owocowy</i></h4>
<h4>Jaką ma projekcję: <i>umiarkowaną</i></h4>
<h4>Z jakiej jest kategorii: <i>romance</i></h4> 
<h4>Architektura zapachu:<br>
<i>Nuta głowy: truskawka, wiśnia, ananas, mandarynka</i><br>
<i>Nuta serca: popcorn, karmel, fiołek</i><br>
<i>Nuta głębi: piżmo, ambra, paczula</i></h4>



						</div>
					</div><!--/product-details-->

				</div>
