
				<div class="col-sm-9 padding-right">
					<div class="product-details"><!--product-details-->
						<div class="col-sm-5">
							<div class="view-product">
								<img src="images/product/perfumy_39.jpg" alt="" />
								
							</div>
							

						</div>
						<div class="col-sm-7">
							<div class="product-information"><!--/product-information-->
								<!-- <img src="images/product-details/new.jpg" class="newarrival" alt="" /> -->
								<h2>PERFUMY DAMSKIE #39</h2><p>cytryna – zielone jabłko – bambus</p>
								<p>Kod produktu: 1010039</p>
								<p>Zaperfumowanie: 20%</p>
								<!-- <span>
									<span>US $59</span>
									<label>Quantity:</label>
									<input type="text" value="3" />
									<button type="button" class="btn btn-fefault cart">
										<i class="fa fa-shopping-cart"></i>
										Add to cart
									</button>
								</span> -->
								<p><b>50 ml</b> </p>

								
							</div><!--/product-information-->

						</div>
						<div><br><br>
						<h2>Za co go pokochasz:</h2>
za subtelność. Delikatny i odprężający jak letni poranek nad Adriatykiem. Morska bryza przynosi orzeźwiające nuty zielonego jabłka, róży, dzwonków i soczystej cytryny. 
<br> <br>
<h4>Z jakiej rodziny pochodzi: <i>cytrusowej</i></h4> 
<h4>Jak jest odbierany: <i>świeży, relaksujący</i></h4>
<h4>Jaką ma projekcję: <i>umiarkowaną</i></h4>
<h4>Z jakiej jest kategorii: <i>casual</i></h4> 
<h4>Architektura zapachu:<br>
<i>Nuta głowy: zielone jabłko, dzwonek, cytryna</i><br>
<i>Nuta serca: biała róża, bambus, jaśmin</i><br>
<i>Nuta głębi: ambra, piżmo, cedr</i></h4>



						</div>
					</div><!--/product-details-->

				</div>
