
				<div class="col-sm-9 padding-right">
					<div class="product-details"><!--product-details-->
						<div class="col-sm-5">
							<div class="view-product">
								<img src="images/product/perfumy_63.jpg" alt="" />
								
							</div>
							

						</div>
						<div class="col-sm-7">
							<div class="product-information"><!--/product-information-->
								<!-- <img src="images/product-details/new.jpg" class="newarrival" alt="" /> --> 
								<h2>Perfumy Damskie #63</h2><p>piwonia - lotos - cytrusy</p>
								<p>Numer produktu: 101063</p>
								<p>Zaperfumowanie: 20%</p>
								<!-- <span>
									<span>US $59</span>
									<label>Quantity:</label>
									<input type="text" value="3" />
									<button type="button" class="btn btn-fefault cart">
										<i class="fa fa-shopping-cart"></i>
										Add to cart
									</button>
								</span> -->
								<p><b>50 ml</b> </p>

								
							</div><!--/product-information-->

						</div>
						<div><br><br>
						<h2>Za co go pokochasz:</h2>
za porywające połączenie egzotycznych owoców z nutami wodnymi. Zrównoważone białym piżmem, drzewem sandałowym i jaśminem rozpościerają przed Tobą nieograniczone możliwości. To będzie piękny dzień!
<br> <br>
<h4>Z jakiej rodziny pochodzi: <i>kwiatowo-wodnej</i></h4> 
<h4>Jak jest odbierany: <i>wodny, owocowy</i></h4> 
<h4>Jaką ma projekcję: <i>umiarkowaną</i></h4> 
<h4>Z jakiej jest kategorii: <i>casual</i></h4>
<h4>Architektura zapachu: 
<br><i>Nuta głowy: różowy pieprz, kiwi , rabarbar</i>
<br><i>Nuta serca: jaśmin, cyklamen, nuty wodne</i>
<br><i>Nuta głębi: piżmo, drzewo sandałowe, drzewo cytrynowe</i></h4>


						</div>
					</div><!--/product-details-->

				</div>
