
				<div class="col-sm-9 padding-right">
					<div class="product-details"><!--product-details-->
						<div class="col-sm-5">
							<div class="view-product">
								<img src="images/product/perfumy_02.jpg" alt="" />
								
							</div>
							

						</div>
						<div class="col-sm-7">
							<div class="product-information"><!--/product-information-->
								<!-- <img src="images/product-details/new.jpg" class="newarrival" alt="" /> -->
								<h2>Perfumy Męskie #02</h2><p>zielone jabłko – cynamon – drzewo oliwne</p>
								<p>Kod produktu: 101002</p>
								<p>Zaperfumowanie: 20%</p>
								<!-- <span>
									<span>US $59</span>
									<label>Quantity:</label>
									<input type="text" value="3" />
									<button type="button" class="btn btn-fefault cart">
										<i class="fa fa-shopping-cart"></i>
										Add to cart
									</button>
								</span> -->
								<p><b>50 ml</b></p>

								
							</div><!--/product-information-->

						</div>
						<div><br><br>
<h2>Co Cię w nim uwiedzie:</h2>
intensywność. To korzenny, otulający zapach słodkiego jabłka i śliwki, z odrobiną cynamonu, na szlachetnym tle drzewa oliwnego. 
<br> <br>
<h4>Z jakiej rodziny pochodzi: <i>drzewno-korzennej</i></h4> 
<h4>Jak jest odbierany: <i>ciepły, korzenny</i></h4>
<h4>Jaką ma projekcję: <i>mocną</i></h4>
<h4>Z jakiej jest kategorii: <i>prestige</i></h4> 
<h4>Architektura zapachu:
<br>Nuta głowy:<i>zielone jabłko, cytryna, bergamotka, śliwka, mech dębowy</i>
<br>Nuta serca:<i>róża, goździk, cynamon</i>
<br>Nuta głębi:<i>drzewo sandałowe, drzewo oliwne, wanilia, wetiwer</i></h4>



						</div>
					</div><!--/product-details-->
					
					
					
					
					
				</div>
