
				<div class="col-sm-9 padding-right">
					<div class="product-details"><!--product-details-->
						<div class="col-sm-5">
							<div class="view-product">
								<img src="images/product/perfumy_24.jpg" alt="" />
								
							</div>
							

						</div>
						<div class="col-sm-7">
							<div class="product-information"><!--/product-information-->
								<!-- <img src="images/product-details/new.jpg" class="newarrival" alt="" /> -->
								<h2>Perfumy Męskie #24</h2><p>liść laurowy – drzewo sandałowe – ambra</p>
								<p>Kod produktu: 101024</p>
								<p>Zaperfumowanie: 20%</p>
								<!-- <span>
									<span>US $59</span>
									<label>Quantity:</label>
									<input type="text" value="3" />
									<button type="button" class="btn btn-fefault cart">
										<i class="fa fa-shopping-cart"></i>
										Add to cart
									</button>
								</span> -->
								<p><b>50 ml</b></p>

								
							</div><!--/product-information-->

						</div>
						<div><br><br>
<h2>Co Cię w nim uwiedzie:</h2>
temperament. Ciepły, balsamiczny zapach otulający kadzidlaną wonią mirry i drzewa sandałowego. Jest niezwykle wyrazisty, słodko-żywiczny.
<br> <br>
<h4>Z jakiej rodziny pochodzi: <i>orientalno-ambrowej</i></h4> 
<h4>Jak jest odbierany: <i>ambrowy, balsamiczny</i></h4>
<h4>Jaką ma projekcję: <i>mocną</i></h4>
<h4>Z jakiej jest kategorii: <i>prestige</i></h4> 
<h4>Architektura zapachu:
<br>Nuta głowy:<i>kolendra, drzewo sandałowe, liść laurowy</i>
<br>Nuta serca:<i>oregano, arcydzięgiel</i>
<br>Nuta głębi:<i>ambra, wanilia, mirra</i></h4>



						</div>
					</div><!--/product-details-->
					
					
					
					
					
				</div>
