
				<div class="col-sm-9 padding-right">
					<div class="product-details"><!--product-details-->
						<div class="col-sm-5">
							<div class="view-product">
								<img src="images/product/perfumy_06.jpg" alt="" />
								
							</div>
							

						</div>
						<div class="col-sm-7">
							<div class="product-information"><!--/product-information-->
								<!-- <img src="images/product-details/new.jpg" class="newarrival" alt="" /> -->
								<h2>Perfumy Męskie #06</h2><p>cytryna – kumkwat – jałowiec</p>
								<p>Kod produktu: 101006</p>
								<p>Zaperfumowanie: 20%</p>
								<!-- <span>
									<span>US $59</span>
									<label>Quantity:</label>
									<input type="text" value="3" />
									<button type="button" class="btn btn-fefault cart">
										<i class="fa fa-shopping-cart"></i>
										Add to cart
									</button>
								</span> -->
								<p><b>50 ml</b></p>

								
							</div><!--/product-information-->

						</div>
						<div><br><br>
<h2>Co Cię w nim uwiedzie:</h2>
niewymuszona elegancja. Bardzo świeże nuty granatu, cytryny i kumkwatu, doprawione owocami jałowca i gałką muszkatołową.
<br> <br>
<h4>Z jakiej rodziny pochodzi: <i>drzewno-owocowej</i></h4> 
<h4>Jak jest odbierany: <i>cytrusowy, pobudzający</i></h4>
<h4>Jaką ma projekcję: <i>umiarkowaną</i></h4>
<h4>Z jakiej jest kategorii: <i>elegance</i></h4> 
<h4>Architektura zapachu:
<br>Nuta głowy:<i>granat, mięta, cytryna, kumkwat</i>
<br>Nuta serca:<i>jałowiec, frezja, gałka muszkatołowa</i>
<br>Nuta głębi:<i>nuty skóry, wanilia, drewno tekowe</i></h4>



						</div>
					</div><!--/product-details-->
					
					
					
					
					
				</div>
