
				<div class="col-sm-9 padding-right">
					<div class="product-details"><!--product-details-->
						<div class="col-sm-5">
							<div class="view-product">
								<img src="images/product/perfumy_42.jpg" alt="" />
								
							</div>
							

						</div>
						<div class="col-sm-7">
							<div class="product-information"><!--/product-information-->
								<!-- <img src="images/product-details/new.jpg" class="newarrival" alt="" /> -->
								<h2>Perfumy Męskie #42</h2><p>czarny pieprz - paczula - nuty drzewne</p>
								<p>Kod produktu: 101042</p>
								<p>Zaperfumowanie: 20%</p>
								<!-- <span>
									<span>US $59</span>
									<label>Quantity:</label>
									<input type="text" value="3" />
									<button type="button" class="btn btn-fefault cart">
										<i class="fa fa-shopping-cart"></i>
										Add to cart
									</button>
								</span> -->
								<p><b>50 ml</b></p>

								
							</div><!--/product-information-->

						</div>
						<div><br><br>
<h2>Co Cię w nim uwiedzie:</h2>
niespotykany charakter. To połączenie świeżego i lekko pikantnego aromatu czarnego pieprzu z orzeźwiającymi cytrusami i ciepłym zapachem nut drzewnych, wnoszących odrobinę egzotyki. Ta odważna kompozycja fascynuje i dostarcza niezwykłych doznań zmysłowych.  
<br> <br>
<h4>Z jakiej rodziny pochodzi: <i>orientalno-drzewne</i></h4> 
<h4>Jak jest odbierany: <i>aromatyczny, energetyzujący</i></h4>
<h4>Jaką ma projekcję: <i>mocną</i></h4>
<h4>Z jakiej jest kategorii: <i>adventure</i></h4> 
<h4>Architektura zapachu:
<br>Nuta głowy:<i>czarny pieprz, nuty cytrusowe</i>
<br>Nuta serca:<i>lawenda, geranium, elemi</i>
<br>Nuta głębi:<i>paczula, wetyweria, nuty drzewne</i></h4>



						</div>
					</div><!--/product-details-->
					
					
					
					
					
				</div>
