
				<div class="col-sm-9 padding-right">
					<div class="product-details"><!--product-details-->
						<div class="col-sm-5">
							<div class="view-product">
								<img src="images/product/perfumy_29.jpg" alt="" />
								
							</div>
							

						</div>
						<div class="col-sm-7">
							<div class="product-information"><!--/product-information-->
								<!-- <img src="images/product-details/new.jpg" class="newarrival" alt="" /> -->
								<h2>PERFUMY DAMSKIE #29</h2><p>liczi – brzoskwinia – piżmo</p>
								<p>Kod produktu: 1010029</p>
								<p>Zaperfumowanie: 20%</p>
								<!-- <span>
									<span>US $59</span>
									<label>Quantity:</label>
									<input type="text" value="3" />
									<button type="button" class="btn btn-fefault cart">
										<i class="fa fa-shopping-cart"></i>
										Add to cart
									</button>
								</span> -->
								<p><b>50 ml</b> </p>

								
							</div><!--/product-information-->

						</div>
						<div><br><br>
						<h2>Za co go pokochasz:</h2>
za uniwersalność. Soczyste liczi i brzoskwinia z lekko pudrowymi nutami lilii i ciepłem piżma sprawdzą się niemal w każdej sytuacji. 
<br> <br>
<h4>Z jakiej rodziny pochodzi: <i>orientalno-kwiatowej</i></h4> 
<h4>Jak jest odbierany: <i>owocowy, pudrowy</i></h4>
<h4>Jaką ma projekcję: <i>umiarkowaną</i></h4>
<h4>Z jakiej jest kategorii: <i>casual</i></h4> 
<h4>Architektura zapachu:<br>
<i>Nuta głowy: liczi, brzoskwinia, bergamotka</i><br>
<i>Nuta serca: lilia, śliwka, konwalia</i><br>
<i>Nuta głębi: wetyweria, wanilia, piżmo</i></h4>



						</div>
					</div><!--/product-details-->

				</div>
