
				<div class="col-sm-9 padding-right">
					<div class="product-details"><!--product-details-->
						<div class="col-sm-5">
							<div class="view-product">
								<img src="images/product/perfumy_36.jpg" alt="" />
								
							</div>
							

						</div>
						<div class="col-sm-7">
							<div class="product-information"><!--/product-information-->
								<!-- <img src="images/product-details/new.jpg" class="newarrival" alt="" /> -->
								<h2>Perfumy Męskie #36</h2><p>bergamotka – liście pomidora – drzewo sandałowe</p>
								<p>Kod produktu: 101036</p>
								<p>Zaperfumowanie: 20%</p>
								<!-- <span>
									<span>US $59</span>
									<label>Quantity:</label>
									<input type="text" value="3" />
									<button type="button" class="btn btn-fefault cart">
										<i class="fa fa-shopping-cart"></i>
										Add to cart
									</button>
								</span> -->
								<p><b>50 ml</b></p>

								
							</div><!--/product-information-->

						</div>
						<div><br><br>
<h2>Co Cię w nim uwiedzie:</h2>
świeżość. Zapach swoją oryginalność zawdzięcza połączeniu liści czarnej porzeczki i liści pomidora. Klasyczna róża i ciepłe drzewo sandałowe dodają mu uroku i elegancji.  
<br> <br>
<h4>Z jakiej rodziny pochodzi: <i>drzewno-owocowej</i></h4> 
<h4>Jak jest odbierany: <i>świeży, zielony</i></h4>
<h4>Jaką ma projekcję: <i>mocną</i></h4>
<h4>Z jakiej jest kategorii: <i>business</i></h4> 
<h4>Architektura zapachu:
<br>Nuta głowy:<i>liście pomidora, liście czarnej porzeczki, bergamotka</i>
<br>Nuta serca:<i>róża, czarny pieprz</i>
<br>Nuta głębi:<i>drzewo sandałowe, paczula</i></h4>



						</div>
					</div><!--/product-details-->
					
					
					
					
					
				</div>
