
				<div class="col-sm-9 padding-right">
					<div class="product-details"><!--product-details-->
						<div class="col-sm-5">
							<div class="view-product">
								<img src="images/product/perfumy_27.jpg" alt="" />
								
							</div>
							

						</div>
						<div class="col-sm-7">
							<div class="product-information"><!--/product-information-->
								<!-- <img src="images/product-details/new.jpg" class="newarrival" alt="" /> -->
								<h2>PERFUMY DAMSKIE #27</h2><p>malina – jaśmin – miód</p>
								<p>Kod produktu: 1010027</p>
								<p>Zaperfumowanie: 20%</p>
								<!-- <span>
									<span>US $59</span>
									<label>Quantity:</label>
									<input type="text" value="3" />
									<button type="button" class="btn btn-fefault cart">
										<i class="fa fa-shopping-cart"></i>
										Add to cart
									</button>
								</span> -->
								<p><b>50 ml</b> </p>

								
							</div><!--/product-information-->

						</div>
						<div><br><br>
						<h2>Za co go pokochasz:</h2>
za dodanie pewności siebie. Soczysta malina z odrobiną aromatycznego miodu to kusząca propozycja. Do tego odrobina ambry, kilka kropel soku z cytryny i słodycz jaśminu. 
<br> <br>
<h4>Z jakiej rodziny pochodzi: <i>kwiatowo-owocowej</i></h4> 
<h4>Jak jest odbierany: <i>kwiatowy, miodowy</i></h4>
<h4>Jaką ma projekcję: <i>umiarkowaną</i></h4>
<h4>Z jakiej jest kategorii: <i>business</i></h4> 
<h4>Architektura zapachu:<br>
<i>Nuta głowy: cytryna, malina, neroli</i><br>
<i>Nuta serca: jaśmin, gardenia, kwiat pomarańczy</i><br>
<i>Nuta głębi: ambra, miód, paczula</i></h4>



						</div>
					</div><!--/product-details-->

				</div>
