
				<div class="col-sm-9 padding-right">
					<div class="product-details"><!--product-details-->
						<div class="col-sm-5">
							<div class="view-product">
								<img src="images/product/perfumy_20.jpg" alt="" />
								
							</div>
							

						</div>
						<div class="col-sm-7">
							<div class="product-information"><!--/product-information-->
								<!-- <img src="images/product-details/new.jpg" class="newarrival" alt="" /> -->
								<h2>Perfumy Męskie #20</h2><p>cynamon – róża – nuty skóry</p>
								<p>Kod produktu: 101020</p>
								<p>Zaperfumowanie: 20%</p>
								<!-- <span>
									<span>US $59</span>
									<label>Quantity:</label>
									<input type="text" value="3" />
									<button type="button" class="btn btn-fefault cart">
										<i class="fa fa-shopping-cart"></i>
										Add to cart
									</button>
								</span> -->
								<p><b>50 ml</b></p>

								
							</div><!--/product-information-->

						</div>
						<div><br><br>
<h2>Co Cię w nim uwiedzie:</h2>
doskonały balans. Ciepły korzenny zapach, z odrobiną balsamicznej ambry i głębokimi nutami skóry. Znakomicie przełamany świeżością cytrusów i mięty.
<br> <br>
<h4>Z jakiej rodziny pochodzi: <i>drzewno-korzennej</i></h4> 
<h4>Jak jest odbierany: <i>ciepły, ambrowy</i></h4>
<h4>Jaką ma projekcję: <i>mocną</i></h4>
<h4>Z jakiej jest kategorii: <i>business</i></h4> 
<h4>Architektura zapachu:
<br>Nuta głowy:<i>grejpfrut, mandarynka, mięta</i>
<br>Nuta serca:<i>róża, przyprawy korzenne, cynamon</i>
<br>Nuta głębi:<i>nuty skóry, cedr, ambra</i></h4>



						</div>
					</div><!--/product-details-->
					
					
					
					
					
				</div>
