
				<div class="col-sm-9 padding-right">
					<div class="product-details"><!--product-details-->
						<div class="col-sm-5">
							<div class="view-product">
								<img src="images/product/perfumy_16.jpg" alt="" />
								
							</div>
							

						</div>
						<div class="col-sm-7">
							<div class="product-information"><!--/product-information-->
								<!-- <img src="images/product-details/new.jpg" class="newarrival" alt="" /> -->
								<h2>Perfumy Męskie #16</h2><p>gruszka – mięta – bazylia</p>
								<p>Kod produktu: 101016</p>
								<p>Zaperfumowanie: 20%</p>
								<!-- <span>
									<span>US $59</span>
									<label>Quantity:</label>
									<input type="text" value="3" />
									<button type="button" class="btn btn-fefault cart">
										<i class="fa fa-shopping-cart"></i>
										Add to cart
									</button>
								</span> -->
								<p><b>50 ml</b></p>

								
							</div><!--/product-information-->

						</div>
						<div><br><br>
<h2>Co Cię w nim uwiedzie:</h2>
prostota i elegancja. Aromatyczny i bardzo elegancki zapach świeżych ziół i owoców. Jeśli ten zapach miałby mieć kolor, to z pewnością byłaby to soczysta zieleń.
<br> <br>
<h4>Z jakiej rodziny pochodzi: <i>drzewno-korzennej</i></h4> 
<h4>Jak jest odbierany: <i>zielony, aromatyczny</i></h4>
<h4>Jaką ma projekcję: <i>mocną</i></h4>
<h4>Z jakiej jest kategorii: <i>elegance</i></h4> 
<h4>Architektura zapachu:
<br>Nuta głowy:<i>cedr, gruszka, bergamotka</i>
<br>Nuta serca:<i>mięta, bazylia</i>
<br>Nuta głębi:<i>paczula, piżmo</i></h4>



						</div>
					</div><!--/product-details-->
					
					
					
					
					
				</div>
