
				<div class="col-sm-9 padding-right">
					<div class="product-details"><!--product-details-->
						<div class="col-sm-5">
							<div class="view-product">
								<img src="images/product/perfumy_23.jpg" alt="" />
								
							</div>
							

						</div>
						<div class="col-sm-7">
							<div class="product-information"><!--/product-information-->
								<!-- <img src="images/product-details/new.jpg" class="newarrival" alt="" /> -->
								<h2>PERFUMY DAMSKIE #23</h2><p>róża – paczula – ambra</p>
								<p>Kod produktu: 1010023</p>
								<p>Zaperfumowanie: 20%</p>
								<!-- <span>
									<span>US $59</span>
									<label>Quantity:</label>
									<input type="text" value="3" />
									<button type="button" class="btn btn-fefault cart">
										<i class="fa fa-shopping-cart"></i>
										Add to cart
									</button>
								</span> -->
								<p><b>50 ml</b> </p>

								
							</div><!--/product-information-->

						</div>
						<div><br><br>
						<h2>Za co go pokochasz:</h2>
za uwodzicielską aurę. Klasyczny, otulający zapach zmysłowych róż i balsamicznej ambry, z odrobiną soczystych cytrusów i ziołowo-ziemnym aromatem paczuli.za zmysłową elegancję. Mocny, kobiecy zapach, w którym dominuje ciepły aromat piżma, kwiatu pomarańczy i drzewa sandałowego.
<br> <br>
<h4>Z jakiej rodziny pochodzi: <i>szyprowo-drzewnej</i></h4> 
<h4>Jak jest odbierany: <i>korzenny, ciepły</i></h4>
<h4>Jaką ma projekcję: <i>mocną</i></h4>
<h4>Z jakiej jest kategorii: <i>glamour</i></h4> 
<h4>Architektura zapachu:<br>
<i>Nuta głowy: bergamotka, mandarynka</i><br>
<i>Nuta serca: róża</i><br>
<i>Nuta głębi: ambra, paczula</i></h4>



						</div>
					</div><!--/product-details-->

				</div>
