
				<div class="col-sm-9 padding-right">
					<div class="product-details"><!--product-details-->
						<div class="col-sm-5">
							<div class="view-product">
								<img src="images/product/perfumy_10.jpg" alt="" />
								
							</div>
							

						</div>
						<div class="col-sm-7">
							<div class="product-information"><!--/product-information-->
								<!-- <img src="images/product-details/new.jpg" class="newarrival" alt="" /> -->
								<h2>Perfumy Męskie #10</h2><p>mandarynka – imbir – lawenda</p>
								<p>Kod produktu: 101010</p>
								<p>Zaperfumowanie: 20%</p>
								<!-- <span>
									<span>US $59</span>
									<label>Quantity:</label>
									<input type="text" value="3" />
									<button type="button" class="btn btn-fefault cart">
										<i class="fa fa-shopping-cart"></i>
										Add to cart
									</button>
								</span> -->
								<p><b>50 ml</b></p>

								
							</div><!--/product-information-->

						</div>
						<div><br><br>
<h2>Co Cię w nim uwiedzie:</h2>
nieoczywiste połączenia. Świeżo wyciśnięte cytrusy, szczypta imbiru i oryginalne nuty drzewne to propozycja dla tych, którzy cenią oryginalność.
<br> <br>
<h4>Z jakiej rodziny pochodzi: <i>cytrusowej</i></h4> 
<h4>Jak jest odbierany: <i>chłodny, korzenny</i></h4>
<h4>Jaką ma projekcję: <i>mocną</i></h4>
<h4>Z jakiej jest kategorii: <i>adventure</i></h4> 
<h4>Architektura zapachu:
<br>Nuta głowy:<i>mandarynka, cytryna, bergamotka</i>
<br>Nuta serca:<i>lawenda, liście fiołka, imbir</i>
<br>Nuta głębi:<i>heban, drewno tekowe</i></h4>



						</div>
					</div><!--/product-details-->
					
					
					
					
					
				</div>
