
				<div class="col-sm-9 padding-right">
					<div class="product-details"><!--product-details-->
						<div class="col-sm-5">
							<div class="view-product">
								<img src="images/product/perfumy_26.jpg" alt="" />
								
							</div>
							

						</div>
						<div class="col-sm-7">
							<div class="product-information"><!--/product-information-->
								<!-- <img src="images/product-details/new.jpg" class="newarrival" alt="" /> -->
								<h2>Perfumy Męskie #26</h2><p>agar – palisander – wanilia</p>
								<p>Kod produktu: 101026</p>
								<p>Zaperfumowanie: 20%</p>
								<!-- <span>
									<span>US $59</span>
									<label>Quantity:</label>
									<input type="text" value="3" />
									<button type="button" class="btn btn-fefault cart">
										<i class="fa fa-shopping-cart"></i>
										Add to cart
									</button>
								</span> -->
								<p><b>50 ml</b></p>

								
							</div><!--/product-information-->

						</div>
						<div><br><br>
<h2>Co Cię w nim uwiedzie:</h2>
głębia oud. Szlachetna, zmysłowa kompozycja z drogocennym drewnem agarowym w roli głównej. Eleganckie tło zapachu wypełniają palisander, wanilia i sandałowiec.
<br> <br>
<h4>Z jakiej rodziny pochodzi: <i>orientalno-drzewnej</i></h4> 
<h4>Jak jest odbierany: <i>ciepły, agarowy</i></h4>
<h4>Jaką ma projekcję: <i>mocną</i></h4>
<h4>Z jakiej jest kategorii: <i>prestige</i></h4> 
<h4>Architektura zapachu:
<br>Nuta głowy:<i>agar, palisander</i>
<br>Nuta serca:<i>wanilia, kardamon, drzewo sandałowe</i>
<br>Nuta głębi:<i>wetyweria, bób tonka</i></h4>



						</div>
					</div><!--/product-details-->
					
					
					
					
					
				</div>
