
				<div class="col-sm-9 padding-right">
					<div class="product-details"><!--product-details-->
						<div class="col-sm-5">
							<div class="view-product">
								<img src="images/product/perfumy_65.jpg" alt="" />
								
							</div>
							

						</div>
						<div class="col-sm-7">
							<div class="product-information"><!--/product-information-->
								<!-- <img src="images/product-details/new.jpg" class="newarrival" alt="" /> --> 
								<h2>Perfumy Damskie #65</h2><p>bergamotka - cytrusy - cedr</p>
								<p>Numer produktu: 101065</p>
								<p>Zaperfumowanie: 20%</p>
								<!-- <span>
									<span>US $59</span>
									<label>Quantity:</label>
									<input type="text" value="3" />
									<button type="button" class="btn btn-fefault cart">
										<i class="fa fa-shopping-cart"></i>
										Add to cart
									</button>
								</span> -->
								<p><b>50 ml</b> </p>

								
							</div><!--/product-information-->

						</div>
						<div><br><br>
						<h2>Za co go pokochasz:</h2>
za natychmiastowy przypływ energii. Doskonale zbalansowany, cytrusowy zapach podbity wyrazistymi nutami drzewa oliwnego i cedru sprawi, że poczujesz się jak na greckiej wyspie.
<br> <br>
<h4>Z jakiej rodziny pochodzi: <i>drzewno-kwiatowej</i></h4> 
<h4>Jak jest odbierany: <i>cytrusowy, drzewny</i></h4> 
<h4>Jaką ma projekcję: <i>umiarkowaną</i></h4> 
<h4>Z jakiej jest kategorii: <i>casual</i></h4>
<h4>Architektura zapachu: 
<br><i>Nuta głowy: bergamotka, figa, zielona mandarynka, cytrusy, gruszka</i>
<br><i>Nuta serca: lilia, jaśmin, kardamon, narcyz</i>
<br><i>Nuta głębi: drzewo sandałowe, cedr, drzewo oliwne, piżmo</i></h4>


						</div>
					</div><!--/product-details-->

				</div>
