
				<div class="col-sm-9 padding-right">
					<div class="product-details"><!--product-details-->
						<div class="col-sm-5">
							<div class="view-product">
								<img src="images/product/perfumy_04.jpg" alt="" />
								
							</div>
							

						</div>
						<div class="col-sm-7">
							<div class="product-information"><!--/product-information-->
								<!-- <img src="images/product-details/new.jpg" class="newarrival" alt="" /> -->
								<h2>Perfumy Męskie #04</h2><p>grejpfrut – kawa – czarny pieprz</p>
								<p>Kod produktu: 101004</p>
								<p>Zaperfumowanie: 20%</p>
								<!-- <span>
									<span>US $59</span>
									<label>Quantity:</label>
									<input type="text" value="3" />
									<button type="button" class="btn btn-fefault cart">
										<i class="fa fa-shopping-cart"></i>
										Add to cart
									</button>
								</span> -->
								<p><b>50 ml</b></p>

								
							</div><!--/product-information-->

						</div>
						<div><br><br>
<h2>Co Cię w nim uwiedzie:</h2>
nieposkromiona świeżość. Ożywczy zapach, pełen nieujarzmionej cytrusowej radości. Odrobina kawy i czarnego pieprzu sprawia, że zawsze jest to dobry sposób na rozpoczęcie nowego dnia. 
<br> <br>
<h4>Z jakiej rodziny pochodzi: <i>cytrusowej</i></h4> 
<h4>Jak jest odbierany: <i>świeży, cytrusowy</i></h4>
<h4>Jaką ma projekcję: <i>umiarkowaną</i></h4>
<h4>Z jakiej jest kategorii: <i>sport</i></h4> 
<h4>Architektura zapachu:
<br>Nuta głowy:<i>grejpfrut, gorzka pomarańcza, mandarynka, bergamotka</i>
<br>Nuta serca:<i>kawa, amyris, czarny pieprz</i>
<br>Nuta głębi:<i>wetyweria, paczula</i></h4>



						</div>
					</div><!--/product-details-->
					
					
					
					
					
				</div>
