
				<div class="col-sm-9 padding-right">
					<div class="product-details"><!--product-details-->
						<div class="col-sm-5">
							<div class="view-product">
								<img src="images/product/perfume_03.jpg" alt="" />
								
							</div>
							

						</div>
						<div class="col-sm-7">
							<div class="product-information"><!--/product-information-->
								<!-- <img src="images/product-details/new.jpg" class="newarrival" alt="" /> -->
								<h2>PERFUMY DAMSKIE #3</h2><p>róża – pomarańcza – paczula</p>
								<p>Kod produktu: 101003</p>
								<p>Zaperfumowanie: 20%</p>
								<!-- <span>
									<span>US $59</span>
									<label>Quantity:</label>
									<input type="text" value="3" />
									<button type="button" class="btn btn-fefault cart">
										<i class="fa fa-shopping-cart"></i>
										Add to cart
									</button>
								</span> -->
								<p><b>50 ml</b> </p>

								
							</div><!--/product-information-->

						</div>
						<div><br><br>
						<h2>Za co go pokochasz:</h2>
za subtelną zmysłowość. To zapach, w którym zawsze będziesz się czuć kobieco i elegancko. Świeże cytrusy, zmysłowe kwiaty i słodycz wanilii dodadzą Ci pewności siebie.
<br> <br>
<h4>Z jakiej rodziny pochodzi: <i>orientalno-drzewnej</i></h4> 
<h4>Jak jest odbierany: <i>słodki, balsamiczny</i></h4>
<h4>Jaką ma projekcję: <i>mocną</i></h4>
<h4>Z jakiej jest kategorii: <i>glamour</i></h4> 
<h4>Architektura zapachu:<br>
<i>Nuta głowy: mandarynka, pomarańcza, kwiat pomarańczy</i><br>
<i>Nuta serca: mimoza, róża, ylang-ylang</i><br>
<i>Nuta głębi: bób tonka, paczula, wanilia</i></h4>



						</div>
					</div><!--/product-details-->
					
					
					
					
					
				</div>
