
				<div class="col-sm-9 padding-right">
					<div class="product-details"><!--product-details-->
						<div class="col-sm-5">
							<div class="view-product">
								<img src="images/product/perfumy_38.jpg" alt="" />
								
							</div>
							

						</div>
						<div class="col-sm-7">
							<div class="product-information"><!--/product-information-->
								<!-- <img src="images/product-details/new.jpg" class="newarrival" alt="" /> -->
								<h2>Perfumy Męskie #38</h2><p>morska woda – liść laurowy – mandarynka</p>
								<p>Kod produktu: 101038</p>
								<p>Zaperfumowanie: 20%</p>
								<!-- <span>
									<span>US $59</span>
									<label>Quantity:</label>
									<input type="text" value="3" />
									<button type="button" class="btn btn-fefault cart">
										<i class="fa fa-shopping-cart"></i>
										Add to cart
									</button>
								</span> -->
								<p><b>50 ml</b></p>

								
							</div><!--/product-information-->

						</div>
						<div><br><br>
<h2>Co Cię w nim uwiedzie:</h2>
przyjemne orzeźwienie. Przypomnij sobie chwilę, gdy zanurzasz się w przyjemnie chłodnej wodzie. Poczuj na skórze słoność morskiej wody, świeżość cytrusów i upojną słodycz kwiatów jaśminu.  
<br> <br>
<h4>Z jakiej rodziny pochodzi: <i>drzewno-owocowej</i></h4> 
<h4>Jak jest odbierany: <i>świeży, zielony</i></h4>
<h4>Jaką ma projekcję: <i>mocną</i></h4>
<h4>Z jakiej jest kategorii: <i>business</i></h4> 
<h4>Architektura zapachu:
<br>Nuta głowy:<i>grapefruit, mandarynka, morska woda</i>
<br>Nuta serca:<i>liść laurowy, jaśmin</i>
<br>Nuta głębi:<i>drzewo gwajakowe, ambra, mech dębowy</i></h4>



						</div>
					</div><!--/product-details-->
					
					
					
					
					
				</div>
