
				<div class="col-sm-9 padding-right">
					<div class="product-details"><!--product-details-->
						<div class="col-sm-5">
							<div class="view-product">
								<img src="images/product/perfumy_08.jpg" alt="" />
								
							</div>
							

						</div>
						<div class="col-sm-7">
							<div class="product-information"><!--/product-information-->
								<!-- <img src="images/product-details/new.jpg" class="newarrival" alt="" /> -->
								<h2>Perfumy Męskie #08</h2><p>nuty morskie – limonka – rezeda</p>
								<p>Kod produktu: 101008</p>
								<p>Zaperfumowanie: 20%</p>
								<!-- <span>
									<span>US $59</span>
									<label>Quantity:</label>
									<input type="text" value="3" />
									<button type="button" class="btn btn-fefault cart">
										<i class="fa fa-shopping-cart"></i>
										Add to cart
									</button>
								</span> -->
								<p><b>50 ml</b></p>

								
							</div><!--/product-information-->

						</div>
						<div><br><br>
<h2>Co Cię w nim uwiedzie:</h2>
mocne orzeźwienie. Świeża morska bryza z ożywczymi nutami cytrusów i słodyczą jaśminu. Oszałamiające nuty rezedy i cyklamenu sprawiają, że nie można mu się oprzeć.
<br> <br>
<h4>Z jakiej rodziny pochodzi: <i>cytrusowej</i></h4> 
<h4>Jak jest odbierany: <i>świeży, morski</i></h4>
<h4>Jaką ma projekcję: <i>umiarkowaną</i></h4>
<h4>Z jakiej jest kategorii: <i>sport</i></h4> 
<h4>Architektura zapachu:
<br>Nuta głowy:<i>limonka, bergamotka, jaśmin, cytryna</i>
<br>Nuta serca:<i>nuty morskie, rezeda, rozmaryn, cyklamen</i>
<br>Nuta głębi:<i>paczula, wetyweria, ambra</i></h4>



						</div>
					</div><!--/product-details-->
					
					
					
					
					
				</div>
