
				<div class="col-sm-9 padding-right">
					<div class="product-details"><!--product-details-->
						<div class="col-sm-5">
							<div class="view-product">
								<img src="images/product/perfumy_44.jpg" alt="" />
								
							</div>
							

						</div>
						<div class="col-sm-7">
							<div class="product-information"><!--/product-information-->
								<!-- <img src="images/product-details/new.jpg" class="newarrival" alt="" /> -->
								<h2>Perfumy Męskie #44</h2><p>bergamotka - kadzidło - imbir</p>
								<p>Kod produktu: 101044</p>
								<p>Zaperfumowanie: 20%</p>
								<!-- <span>
									<span>US $59</span>
									<label>Quantity:</label>
									<input type="text" value="3" />
									<button type="button" class="btn btn-fefault cart">
										<i class="fa fa-shopping-cart"></i>
										Add to cart
									</button>
								</span> -->
								<p><b>50 ml</b></p>

								
							</div><!--/product-information-->

						</div>
						<div><br><br>
<h2>Co Cię w nim uwiedzie:</h2>
fala orzeźwienia. Ten wyrazisty, wielowymiarowy zapach został stworzony dla współczesnego mężczyzny – pewnego siebie, pragnącego wolności i wyzwań. To pobudzające uczucie przyjemnej świeżości otulonej intrygującym aromatem kadzidła.  
<br> <br>
<h4>Z jakiej rodziny pochodzi: <i>drzewno-korzennej</i></h4> 
<h4>Jak jest odbierany: <i>świeży, zielony</i></h4>
<h4>Jaką ma projekcję: <i>umiarkowaną</i></h4>
<h4>Z jakiej jest kategorii: <i>sport</i></h4> 
<h4>Architektura zapachu:
<br>Nuta głowy:<i>bergamotka, kadzidło</i>
<br>Nuta serca:<i>fiołek, lawenda, imbir</i>
<br>Nuta głębi:<i>cedr</i></h4>



						</div>
					</div><!--/product-details-->
					
					
					
					
					
				</div>
