
				<div class="col-sm-9 padding-right">
					<div class="product-details"><!--product-details-->
						<div class="col-sm-5">
							<div class="view-product">
								<img src="images/product/perfumy_19.jpg" alt="" />
								
							</div>
							

						</div>
						<div class="col-sm-7">
							<div class="product-information"><!--/product-information-->
								<!-- <img src="images/product-details/new.jpg" class="newarrival" alt="" /> -->
								<h2>PERFUMY DAMSKIE #19</h2><p>jaśmin – melon – cedr</p>
								<p>Kod produktu: 1010019</p>
								<p>Zaperfumowanie: 20%</p>
								<!-- <span>
									<span>US $59</span>
									<label>Quantity:</label>
									<input type="text" value="3" />
									<button type="button" class="btn btn-fefault cart">
										<i class="fa fa-shopping-cart"></i>
										Add to cart
									</button>
								</span> -->
								<p><b>50 ml</b> </p>

								
							</div><!--/product-information-->

						</div>
						<div><br><br>
						<h2>Za co go pokochasz:</h2>
za wyrazistość. Jeśli lubisz błyszczeć, to połączenie jest dla Ciebie! Zmysłowy jaśmin, orchidea i apetyczne nuty melona, gruszki i jeżyny sprawią, że będziesz w centrum zainteresowania.
<br> <br>
<h4>Z jakiej rodziny pochodzi: <i>kwiatowo-owocowej </i></h4> 
<h4>Jak jest odbierany: <i>kwiatowy, zmysłowy</i></h4>
<h4>Jaką ma projekcję: <i>mocną</i></h4>
<h4>Z jakiej jest kategorii: <i>glamour</i></h4> 
<h4>Architektura zapachu:<br>
<i>Nuta głowy: magnolia, melon, gruszka, bergamotka</i><br>
<i>Nuta serca: śliwka, fiołek, orchidea, konwalia</i><br>
<i>Nuta głębi: jeżyna, wanilia, cedr</i></h4>



						</div>
					</div><!--/product-details-->

				</div>
