
				<div class="col-sm-9 padding-right">
					<div class="product-details"><!--product-details-->
						<div class="col-sm-5">
							<div class="view-product">
								<img src="images/product/perfumy_41.jpg" alt="" />
								
							</div>
							

						</div>
						<div class="col-sm-7">
							<div class="product-information"><!--/product-information-->
								<!-- <img src="images/product-details/new.jpg" class="newarrival" alt="" /> -->
								<h2>PERFUMY DAMSKIE #41</h2><p>zielona herbata – cytryna – mech dębowy</p>
								<p>Kod produktu: 1010041</p>
								<p>Zaperfumowanie: 20%</p>
								<!-- <span>
									<span>US $59</span>
									<label>Quantity:</label>
									<input type="text" value="3" />
									<button type="button" class="btn btn-fefault cart">
										<i class="fa fa-shopping-cart"></i>
										Add to cart
									</button>
								</span> -->
								<p><b>50 ml</b> </p>

								
							</div><!--/product-information-->

						</div>
						<div><br><br>
						<h2>Za co go pokochasz:</h2>
za świeżość. Jest lekki i orzeźwiający niczym łyk mrożonej herbaty w upalne popołudnie. Świeże cytrusy, kwaskowaty rabarbar i moc pikantnych przypraw. 
<br> <br>
<h4>Z jakiej rodziny pochodzi: <i>cytrusowej</i></h4> 
<h4>Jak jest odbierany: <i>lekki, zielony</i></h4>
<h4>Jaką ma projekcję: <i>subtelną</i></h4>
<h4>Z jakiej jest kategorii: <i>casual</i></h4> 
<h4>Architektura zapachu:<br>
<i>Nuta głowy: mięta, zielona herbata, cytryna,  pomarańcza, rabarbar</i><br>
<i>Nuta serca: goździk, koper włoski, jaśmin, mech dębowy</i><br>
<i>Nuta głębi: piżmo, goździk korzenny, amber, kminek</i></h4>



						</div>
					</div><!--/product-details-->

				</div>
