
				<div class="col-sm-9 padding-right">
					<div class="product-details"><!--product-details-->
						<div class="col-sm-5">
							<div class="view-product">
								<img src="images/product/perfumy_30.jpg" alt="" />
								
							</div>
							

						</div>
						<div class="col-sm-7">
							<div class="product-information"><!--/product-information-->
								<!-- <img src="images/product-details/new.jpg" class="newarrival" alt="" /> -->
								<h2>Perfumy Męskie #30</h2><p>zielone jabłko – lawenda – jodła</p>
								<p>Kod produktu: 101030</p>
								<p>Zaperfumowanie: 20%</p>
								<!-- <span>
									<span>US $59</span>
									<label>Quantity:</label>
									<input type="text" value="3" />
									<button type="button" class="btn btn-fefault cart">
										<i class="fa fa-shopping-cart"></i>
										Add to cart
									</button>
								</span> -->
								<p><b>50 ml</b></p>

								
							</div><!--/product-information-->

						</div>
						<div><br><br>
<h2>Co Cię w nim uwiedzie:</h2>
obietnica przygody. Mocny, orzeźwiający zapach, który dotrzyma Ci kroku w każdym, nawet najbardziej gorącym momencie. Pobudza świeżością cytrusów i zielonych ziół.
<br> <br>
<h4>Z jakiej rodziny pochodzi: <i>fougère</i></h4> 
<h4>Jak jest odbierany: <i>świeży, ziołowy</i></h4>
<h4>Jaką ma projekcję: <i>mocną</i></h4>
<h4>Z jakiej jest kategorii: <i>adventure</i></h4> 
<h4>Architektura zapachu:
<br>Nuta głowy:<i>zielone jabłko, bergamotka, lawenda, bazylia, grejpfrut</i>
<br>Nuta serca:<i>goździk, geranium, szałwia</i>
<br>Nuta głębi:<i>paczula, cedr, jodła</i></h4>



						</div>
					</div><!--/product-details-->
					
					
					
					
					
				</div>
