
				<div class="col-sm-9 padding-right">
					<div class="product-details"><!--product-details-->
						<div class="col-sm-5">
							<div class="view-product">
								<img src="images/product/perfumy_33.jpg" alt="" />
								
							</div>
							

						</div>
						<div class="col-sm-7">
							<div class="product-information"><!--/product-information-->
								<!-- <img src="images/product-details/new.jpg" class="newarrival" alt="" /> -->
								<h2>PERFUMY DAMSKIE #33</h2><p>frezja – róża – paczula</p>
								<p>Kod produktu: 1010033</p>
								<p>Zaperfumowanie: 20%</p>
								<!-- <span>
									<span>US $59</span>
									<label>Quantity:</label>
									<input type="text" value="3" />
									<button type="button" class="btn btn-fefault cart">
										<i class="fa fa-shopping-cart"></i>
										Add to cart
									</button>
								</span> -->
								<p><b>50 ml</b> </p>

								
							</div><!--/product-information-->

						</div>
						<div><br><br>
						<h2>Za co go pokochasz:</h2>
za subtelność i kobiecość. Słoneczny, przyjemny zapach słodkich frezji, róż i wanilii, przełamany paczulą i liśćmi czarnej porzeczki. 
<br> <br>
<h4>Z jakiej rodziny pochodzi: <i>szyprowo-kwiatowej</i></h4> 
<h4>Jak jest odbierany: <i>ciepły, zmysłowy</i></h4>
<h4>Jaką ma projekcję: <i>umiarkowaną</i></h4>
<h4>Z jakiej jest kategorii: <i>casual</i></h4> 
<h4>Architektura zapachu:<br>
<i>Nuta głowy: liście czarnej porzeczki</i><br>
<i>Nuta serca: frezja, róża</i><br>
<i>Nuta głębi: wanilia, paczula, ambroksan</i></h4>



						</div>
					</div><!--/product-details-->

				</div>
