
				<div class="col-sm-9 padding-right">
					<div class="product-details"><!--product-details-->
						<div class="col-sm-5">
							<div class="view-product">
								<img src="images/product/perfumy_14.jpg" alt="" />
								
							</div>
							

						</div>
						<div class="col-sm-7">
							<div class="product-information"><!--/product-information-->
								<!-- <img src="images/product-details/new.jpg" class="newarrival" alt="" /> -->
								<h2>Perfumy Męskie #14</h2><p>nuty morskie – pomarańcza – cedr</p>
								<p>Kod produktu: 101014</p>
								<p>Zaperfumowanie: 20%</p>
								<!-- <span>
									<span>US $59</span>
									<label>Quantity:</label>
									<input type="text" value="3" />
									<button type="button" class="btn btn-fefault cart">
										<i class="fa fa-shopping-cart"></i>
										Add to cart
									</button>
								</span> -->
								<p><b>50 ml</b></p>

								
							</div><!--/product-information-->

						</div>
						<div><br><br>
<h2>Co Cię w nim uwiedzie:</h2>
bezkompromisowość. Jest tak ożywczy, jak łyk świeżego, morskiego powietrza. Ani się obejrzysz, a nie będziesz mógł żyć bez tej cytrusowej świeżości, podbitej przyprawami i balsamiczną ambrą.
<br> <br>
<h4>Z jakiej rodziny pochodzi: <i>drzewno-korzennej</i></h4> 
<h4>Jak jest odbierany: <i>morski, korzenny</i></h4>
<h4>Jaką ma projekcję: <i>mocną</i></h4>
<h4>Z jakiej jest kategorii: <i>sport</i></h4> 
<h4>Architektura zapachu:
<br>Nuta głowy:<i>nuty morskie, aldehyd, pomarańcza</i>
<br>Nuta serca:<i>neroli, cedr, czarny pieprz</i>
<br>Nuta głębi:<i>wanilia, ambra, wetyweria</i></h4>



						</div>
					</div><!--/product-details-->
					
					
					
					
					
				</div>
