
				<div class="col-sm-9 padding-right">
					<div class="product-details"><!--product-details-->
						<div class="col-sm-5">
							<div class="view-product">
								<img src="images/product/perfumy_28.jpg" alt="" />
								
							</div>
							

						</div>
						<div class="col-sm-7">
							<div class="product-information"><!--/product-information-->
								<!-- <img src="images/product-details/new.jpg" class="newarrival" alt="" /> -->
								<h2>Perfumy Męskie #28</h2><p>bergamotka – papaja – gałka muszkatołowa</p>
								<p>Kod produktu: 101028</p>
								<p>Zaperfumowanie: 20%</p>
								<!-- <span>
									<span>US $59</span>
									<label>Quantity:</label>
									<input type="text" value="3" />
									<button type="button" class="btn btn-fefault cart">
										<i class="fa fa-shopping-cart"></i>
										Add to cart
									</button>
								</span> -->
								<p><b>50 ml</b></p>

								
							</div><!--/product-information-->

						</div>
						<div><br><br>
<h2>Co Cię w nim uwiedzie:</h2>
czystość i naturalność. Niezwykle świeży, a jednocześnie bardzo zmysłowy zapach. Soczysty ananas i papaja w połączeniu ze szczyptą gałki muszkatołowej i piżma robią niesamowite wrażenie.
<br> <br>
<h4>Z jakiej rodziny pochodzi: <i>cytrusowej</i></h4> 
<h4>Jak jest odbierany: <i>świeży, zielony</i></h4>
<h4>Jaką ma projekcję: <i>umiarkowaną</i></h4>
<h4>Z jakiej jest kategorii: <i>adventure</i></h4> 
<h4>Architektura zapachu:
<br>Nuta głowy:<i>ananas, papaja, bergamotka, cytryna</i>
<br>Nuta serca:<i>konwalia, fiolek, gałka muszkatołowa, róża</i>
<br>Nuta głębi:<i>drzewo sandałowe, piżmo, ambra</i></h4>



						</div>
					</div><!--/product-details-->
					
					
					
					
					
				</div>
