
				<div class="col-sm-9 padding-right">
					<div class="product-details"><!--product-details-->
						<div class="col-sm-5">
							<div class="view-product">
								<img src="images/product/perfume_07.jpg" alt="" />
								
							</div>
							

						</div>
						<div class="col-sm-7">
							<div class="product-information"><!--/product-information-->
								<!-- <img src="images/product-details/new.jpg" class="newarrival" alt="" /> -->
								<h2>PERFUMY DAMSKIE #7</h2><p>wanilia – gruszka – czekoladki</p>
								<p>Kod produktu: 101007</p>
								<p>Zaperfumowanie: 20%</p>
								<!-- <span>
									<span>US $59</span>
									<label>Quantity:</label>
									<input type="text" value="3" />
									<button type="button" class="btn btn-fefault cart">
										<i class="fa fa-shopping-cart"></i>
										Add to cart
									</button>
								</span> -->
								<p><b>50 ml</b> </p>

								
							</div><!--/product-information-->

						</div>
						<div><br><br>
						<h2>Za co go pokochasz:</h2>
za waniliową słodycz. Wyobraź sobie swój idealny dzień. Czujesz się doskonale. Jesteś otulona przez ulubione nuty czekoladowych pralinek, wanilii, gruszki i jaśminu. Widzimy, że się uśmiechasz...
<br> <br>
<h4>Z jakiej rodziny pochodzi: <i>kwiatowo-gourmand</i></h4> 
<h4>Jak jest odbierany: <i>słodki, karmelowy</i></h4>
<h4>Jaką ma projekcję: <i>mocną</i></h4>
<h4>Z jakiej jest kategorii: <i>casual</i></h4> 
<h4>Architektura zapachu:<br>
<i>Nuta głowy: gruszka, czarna porzeczka</i><br>
<i>Nuta serca: kwiat pomarańczy, irys, jaśmin</i><br>
<i>Nuta głębi: wanilia, czekoladowe pralinki, bób tonka, paczula</i></h4>



						</div>
					</div><!--/product-details-->
					
					
					
					
					
				</div>
