
				<div class="col-sm-9 padding-right">
					<div class="product-details"><!--product-details-->
						<div class="col-sm-5">
							<div class="view-product">
								<img src="images/product/perfumy_59.jpg" alt="" />
								
							</div>
							

						</div>
						<div class="col-sm-7">
							<div class="product-information"><!--/product-information-->
								<!-- <img src="images/product-details/new.jpg" class="newarrival" alt="" /> --> 
								<h2>Perfumy Damskie #59</h2><p>pomarańcza – wanilia – czarna porzeczka</p>
								<p>Numer produktu: 101059</p>
								<p>Zaperfumowanie: 20%</p>
								<!-- <span>
									<span>US $59</span>
									<label>Quantity:</label>
									<input type="text" value="3" />
									<button type="button" class="btn btn-fefault cart">
										<i class="fa fa-shopping-cart"></i>
										Add to cart
									</button>
								</span> -->
								<p><b>50 ml</b> </p>

								
							</div><!--/product-information-->

						</div>
						<div><br><br>
						<h2>Za co go pokochasz:</h2>
za naturalną uwodzicielskość. Uważaj, bo to prawdziwy miłosny eliksir. Róża, morela, wanilia i świeże cytrusy skradną serce i Twoje, i jego.
<br> <br>
<h4>Z jakiej rodziny pochodzi: <i>kwiatowo-owocowej</i></h4> 
<h4>Jak jest odbierany: <i>cytrusowy, korzenny</i></h4> 
<h4>Jaką ma projekcję: <i>umiarkowaną</i></h4> 
<h4>Z jakiej jest kategorii: <i>romance</i></h4>
<h4>Architektura zapachu: 
<br><i>Nuta głowy: czarna porzeczka, pomarańcza, mandarynka</i>
<br><i>Nuta serca: morela, róża, konwalia</i>
<br><i>Nuta głębi: ambra, cedr, wanilia</i></h4>


						</div>
					</div><!--/product-details-->

				</div>
