
				<div class="col-sm-9 padding-right">
					<div class="product-details"><!--product-details-->
						<div class="col-sm-5">
							<div class="view-product">
								<img src="images/product/503007.jpg" alt="" />
								
							</div>
							

						</div>
						<div class="col-sm-7">
							<div class="product-information"><!--/product-information-->
								<!-- <img src="images/product-details/new.jpg" class="newarrival" alt="" /> -->
								<h2>Płyn do prania odzieży sportowej</h2>
								<p>Kod produktu: 503007</p>
								
								<!-- <span>
									<span>US $59</span>
									<label>Quantity:</label>
									<input type="text" value="3" />
									<button type="button" class="btn btn-fefault cart">
										<i class="fa fa-shopping-cart"></i>
										Add to cart
									</button>
								</span> -->
								<p><b>1000 ml</b> In Stock</p>

								
							</div><!--/product-information-->

						</div>
						<div><br><br>
						<h2>Jak dbać o ubrania podczas prania?</h2>
						Jeśli regularnie uprawiasz sport i nie wyobrażasz sobie tygodnia bez treningów, to z pewnością używasz odzieży funkcjonalnej. Wiemy, że wymaga ona specjalnego czyszczenia i pielęgnacji, by na długo zachowała swoje właściwości, dlatego stworzyliśmy Płyn do prania odzieży sportowej. Nie tylko skutecznie usuwa z niej zabrudzenia, ale także chroni strukturę tkanin i ich kolor. Zastosowaliśmy w nim innowacyjną technologię neutralizującą przykre zapachy, która zapewni Ci przyjemną świeżość również podczas treningu.

<h4>Za co go pokochasz:</h4>
za to, że nie tylko doskonale czyści, ale też odświeża sportowe ubrania oraz chroni ich właściwości. Jest bezpieczny dla wszystkich rodzajów tkanin funkcjonalnych. Pozwala zachować ich oddychalność.  
  
<h4>Co Cię w nim zachwyci:</h4>
formuła neutralizująca zapachy. Dzięki niej oraz olejkom zapachowym, zamkniętym w specjalnych kapsułkach, zapach potu jest skutecznie neutralizowany nie tylko podczas prania, ale także w trakcie noszenia odzieży, zapewniając długotrwałe uczucie świeżości.   

<h4>Co tak pięknie pachnie:</h4>
kompozycja stworzona z oryginalnych, francuskich olejków zapachowych z orzeźwiającymi nutami cytrusowymi, intensywnie zielonym aromatem liści fiołka, dojrzałą różą i subtelną konwalią. Idealnie dopełnia je balsamiczne drzewo cedrowe, nuty bursztynu oraz zmysłowe piżmo.<br>
 
<h4>Do czego możesz go użyć: </h4>
do czyszczenia i pielęgnacji odzieży termoaktywnej różnego zastosowania - sportowej, membranowej, wiatroszczelnej, wodoodpornej czy bawełnianej. W przypadku gdy czyszczona odzież wymaga zaimpregnowania należy użyć odpowiedniego impregnatu, przeznaczonego do odzieży funkcjonalnej, wlewając go do komory płukania. Stosuj się do zaleceń producenta odzieży.


						</div>
					</div><!--/product-details-->

				</div>
