
				<div class="col-sm-9 padding-right">
					<div class="product-details"><!--product-details-->
						<div class="col-sm-5">
							<div class="view-product">
								<img src="images/product/503008.jpg" alt="" />
								
							</div>
							

						</div>
						<div class="col-sm-7">
							<div class="product-information"><!--/product-information-->
								<!-- <img src="images/product-details/new.jpg" class="newarrival" alt="" /> -->
								<h2>Intensywnie perfumowana odżywka do płukania tkanin</h2>
								<p>Kod produktu: 503008</p>
								
								<!-- <span>
									<span>US $59</span>
									<label>Quantity:</label>
									<input type="text" value="3" />
									<button type="button" class="btn btn-fefault cart">
										<i class="fa fa-shopping-cart"></i>
										Add to cart
									</button>
								</span> -->
								<p><b>1000 ml</b> In Stock</p>

								
							</div><!--/product-information-->

						</div>
						<div><br><br>
						<h2>Jak dbać o ubrania podczas prania?</h2>
						Swoim strojem przekazujemy wiele informacji o sobie, a zadbane i pachnące ubrania wpływają nie tylko na to, jak jesteśmy postrzegani, ale także na nasze samopoczucie. Dlatego jeśli chcesz, by wciąż wyglądały jak nowe i pięknie pachniały przez długi czas, stosuj Intensywnie perfumowaną odżywkę do płukania tkanin, która pielęgnuje włókna i sprawia, że tkaniny są wyjątkowo miękkie, lekkie, elastyczne i puszyste. Zawarte w niej proteiny pszenicy skutecznie chronią kolory przed blaknięciem i biel przed szarzeniem.

<h4>Za co ją pokochasz:</h4>
za formułę stay new, która aktywnie chroni włókna w trakcie prania i suszenia, zapobiega ich uszkadzaniu, deformacjom i mechaceniu, a także pękaniu nadruków na koszulkach. Tkaniny wyglądają tak, jakby były prane o połowę rzadziej.  
  
<h4>Co Cię w niej zachwyci:</h4>
zapach, który utrzymuje się jeszcze dłużej - nawet do 24 tygodni! Olejki zapachowe zamknęliśmy w specjalnych mikrokapsułkach HD Active Life, które uwalniają cudowny aromat - nawet bez pocierania materiału.   

<h4>Co tak pięknie pachnie:</h4>
kwiatowo-drzewna kompozycja stworzona z francuskich olejków zapachowych, w której połączyliśmy delikatny jaśmin, tropikalne ylang-ylang i egzotyczny aromat wody kokosowej ze zmysłowym piżmem, aloesem, palisandrem i żywiczno-korzennymi tonami drzewa sandałowego.<br>
 
<h4>Zobacz, jak prosta jest w użyciu:</h4>
wystarczy, że dodasz odpowiednią ilość odżywki do ostatniego płukania. Możesz stosować ją zarówno podczas prania w pralce, jak i prania ręcznego, do wszystkich rodzajów tkanin i do wszystkich kolorów.

<h4>Co zapewni Ci dodatkowe bezpieczeństwo: </h4>
odżywka przeszła szereg szczegółowych badań, w tym badanie dermatologiczne, potwierdzające tolerancję skórą
						</div>
					</div><!--/product-details-->

				</div>
