
				
				<div class="col-sm-9 padding-right">
					<div class="features_items"><!--features_items-->
						<h2 class="title text-center">Dla Domu</h2>
						<div class="col-sm-4">
							<div class="product-image-wrapper">
								<div class="single-products">
									<div class="productinfo text-center">
										<img src="images/product/503008.jpg" alt="" />
										<h2>#503008</h2>
										<p>Intensywnie perfumowana odżywka do płukania tkanin</p>
										<a href="house_503008_xpl.html" class="btn btn-default add-to-cart"><i class="fa fa-shopping-cart"></i>Więcej</a>
									</div>
									<!-- <div class="product-overlay">
										<div class="overlay-content">
											<h2>$56</h2>
											<p>Easy Polo Black Edition</p>
											<a href="#" class="btn btn-default add-to-cart"><i class="fa fa-shopping-cart"></i>Add to cart</a>
										</div>
									</div> -->
								</div>
							</div>
						</div>
						
						<div class="col-sm-4">
							<div class="product-image-wrapper">
								<div class="single-products">
									<div class="productinfo text-center">
										<img src="images/product/503007.jpg" alt="" />
										<h2>#503007</h2>
										<p>Płyn do prania odzieży sportowej</p>
										<a href="house_503007_xpl.html" class="btn btn-default add-to-cart"><i class="fa fa-shopping-cart"></i>Więcej</a>
									</div>
									<!-- <div class="product-overlay">
										<div class="overlay-content">
											<h2>$56</h2>
											<p>Easy Polo Black Edition</p>
											<a href="#" class="btn btn-default add-to-cart"><i class="fa fa-shopping-cart"></i>Add to cart</a>
										</div>
									</div> -->
								</div>
							</div>
						</div>
						
						<div class="col-sm-4">
							<div class="product-image-wrapper">
								<div class="single-products">
									<div class="productinfo text-center">
										<img src="images/product/501001.jpg" alt="" />
										<h2>#501001</h2>
										<p>Odtłuszczacz</p>
										<a href="house_501001_xpl.html" class="btn btn-default add-to-cart"><i class="fa fa-shopping-cart"></i>Więcej</a>
									</div>
									<!-- <div class="product-overlay">
										<div class="overlay-content">
											<h2>$56</h2>
											<p>Easy Polo Black Edition</p>
											<a href="#" class="btn btn-default add-to-cart"><i class="fa fa-shopping-cart"></i>Add to cart</a>
										</div>
									</div> -->
								</div>
							</div>
						</div>
						
						<div class="col-sm-4">
							<div class="product-image-wrapper">
								<div class="single-products">
									<div class="productinfo text-center">
										<img src="images/product/501002.jpg" alt="" />
										<h2>#501002</h2>
										<p>Pianka neutralizująca przykre zapachy</p>
										<a href="house_501002_xpl.html" class="btn btn-default add-to-cart"><i class="fa fa-shopping-cart"></i>Więcej</a>
									</div>
									<!-- <div class="product-overlay">
										<div class="overlay-content">
											<h2>$56</h2>
											<p>Easy Polo Black Edition</p>
											<a href="#" class="btn btn-default add-to-cart"><i class="fa fa-shopping-cart"></i>Add to cart</a>
										</div>
									</div> -->
								</div>
							</div>
						</div>
						
						<div class="col-sm-4">
							<div class="product-image-wrapper">
								<div class="single-products">
									<div class="productinfo text-center">
										<img src="images/product/501003.jpg" alt="" />
										<h2>#501003</h2>
										<p>Spray do mycia i pielęgnacji powierzchni kuchennych</p>
										<a href="house_501003_xpl.html" class="btn btn-default add-to-cart"><i class="fa fa-shopping-cart"></i>Więcej</a>
									</div>
									<!-- <div class="product-overlay">
										<div class="overlay-content">
											<h2>$56</h2>
											<p>Easy Polo Black Edition</p>
											<a href="#" class="btn btn-default add-to-cart"><i class="fa fa-shopping-cart"></i>Add to cart</a>
										</div>
									</div> -->
								</div>
							</div>
						</div>
						
						<div class="col-sm-4">
							<div class="product-image-wrapper">
								<div class="single-products">
									<div class="productinfo text-center">
										<img src="images/product/501004.jpg" alt="" />
										<h2>#501004</h2>
										<p>Żel do mycia naczyń</p>
										<a href="house_501004_xpl.html" class="btn btn-default add-to-cart"><i class="fa fa-shopping-cart"></i>Więcej</a>
									</div>
									<!-- <div class="product-overlay">
										<div class="overlay-content">
											<h2>$56</h2>
											<p>Easy Polo Black Edition</p>
											<a href="#" class="btn btn-default add-to-cart"><i class="fa fa-shopping-cart"></i>Add to cart</a>
										</div>
									</div> -->
								</div>
							</div>
						</div>
						
						<div class="col-sm-4">
							<div class="product-image-wrapper">
								<div class="single-products">
									<div class="productinfo text-center">
										<img src="images/product/502001.jpg" alt="" />
										<h2>#502001</h2>
										<p>Spray do mycia i pielęgnacji łazienki</p>
										<a href="house_502001_xpl.html" class="btn btn-default add-to-cart"><i class="fa fa-shopping-cart"></i>Więcej</a>
									</div>
									<!-- <div class="product-overlay">
										<div class="overlay-content">
											<h2>$56</h2>
											<p>Easy Polo Black Edition</p>
											<a href="#" class="btn btn-default add-to-cart"><i class="fa fa-shopping-cart"></i>Add to cart</a>
										</div>
									</div> -->
								</div>
							</div>
						</div>
						
						<div class="col-sm-4">
							<div class="product-image-wrapper">
								<div class="single-products">
									<div class="productinfo text-center">
										<img src="images/product/502002.jpg" alt="" />
										<h2>#502002</h2>
										<p>Spray do mycia kabin prysznicowych</p>
										<a href="house_502002_xpl.html" class="btn btn-default add-to-cart"><i class="fa fa-shopping-cart"></i>Więcej</a>
									</div>
									<!-- <div class="product-overlay">
										<div class="overlay-content">
											<h2>$56</h2>
											<p>Easy Polo Black Edition</p>
											<a href="#" class="btn btn-default add-to-cart"><i class="fa fa-shopping-cart"></i>Add to cart</a>
										</div>
									</div> -->
								</div>
							</div>
						</div>
						
						<div class="col-sm-4">
							<div class="product-image-wrapper">
								<div class="single-products">
									<div class="productinfo text-center">
										<img src="images/product/502003.jpg" alt="" />
										<h2>#502003</h2>
										<p>Udrożniacz</p>
										<a href="house_502003_xpl.html" class="btn btn-default add-to-cart"><i class="fa fa-shopping-cart"></i>Więcej</a>
									</div>
									<!-- <div class="product-overlay">
										<div class="overlay-content">
											<h2>$56</h2>
											<p>Easy Polo Black Edition</p>
											<a href="#" class="btn btn-default add-to-cart"><i class="fa fa-shopping-cart"></i>Add to cart</a>
										</div>
									</div> -->
								</div>
							</div>
						</div>
						
						<div class="col-sm-4">
							<div class="product-image-wrapper">
								<div class="single-products">
									<div class="productinfo text-center">
										<img src="images/product/502004.jpg" alt="" />
										<h2>#502004</h2>
										<p>Żel do czyszczenia toalet</p>
										<a href="house_502004_xpl.html" class="btn btn-default add-to-cart"><i class="fa fa-shopping-cart"></i>Więcej</a>
									</div>
									<!-- <div class="product-overlay">
										<div class="overlay-content">
											<h2>$56</h2>
											<p>Easy Polo Black Edition</p>
											<a href="#" class="btn btn-default add-to-cart"><i class="fa fa-shopping-cart"></i>Add to cart</a>
										</div>
									</div> -->
								</div>
							</div>
						</div>
						<div class="col-sm-4">
							<div class="product-image-wrapper">
								<div class="single-products">
									<div class="productinfo text-center">
										<img src="images/product/502005.jpg" alt="" />
										<h2>#502005</h2>
										<p>Żel do usuwania kamienia i rdzy</p>
										<a href="house_502005_xpl.html" class="btn btn-default add-to-cart"><i class="fa fa-shopping-cart"></i>Więcej</a>
									</div>
									<!-- <div class="product-overlay">
										<div class="overlay-content">
											<h2>$56</h2>
											<p>Easy Polo Black Edition</p>
											<a href="#" class="btn btn-default add-to-cart"><i class="fa fa-shopping-cart"></i>Add to cart</a>
										</div>
									</div> -->
								</div>
							</div>
						</div>
						
						<div class="col-sm-4">
							<div class="product-image-wrapper">
								<div class="single-products">
									<div class="productinfo text-center">
										<img src="images/product/502006.jpg" alt="" />
										<h2>#502006</h2>
										<p>Mydło antybakteryjne w piance</p>
										<a href="house_502006_xpl.html" class="btn btn-default add-to-cart"><i class="fa fa-shopping-cart"></i>Więcej</a>
									</div>
									<!-- <div class="product-overlay">
										<div class="overlay-content">
											<h2>$56</h2>
											<p>Easy Polo Black Edition</p>
											<a href="#" class="btn btn-default add-to-cart"><i class="fa fa-shopping-cart"></i>Add to cart</a>
										</div>
									</div> -->
								</div>
							</div>
						</div>
						
						<div class="col-sm-4">
							<div class="product-image-wrapper">
								<div class="single-products">
									<div class="productinfo text-center">
										<img src="images/product/503002.jpg" alt="" />
										<h2>#503002</h2>
										<p>Perfumowana odżywka do tkanin</p>
										<a href="house_503002_xpl.html" class="btn btn-default add-to-cart"><i class="fa fa-shopping-cart"></i>Więcej</a>
									</div>
									<!-- <div class="product-overlay">
										<div class="overlay-content">
											<h2>$56</h2>
											<p>Easy Polo Black Edition</p>
											<a href="#" class="btn btn-default add-to-cart"><i class="fa fa-shopping-cart"></i>Add to cart</a>
										</div>
									</div> -->
								</div>
							</div>
						</div>
						
						<div class="col-sm-4">
							<div class="product-image-wrapper">
								<div class="single-products">
									<div class="productinfo text-center">
										<img src="images/product/503003.jpg" alt="" />
										<h2>#503003</h2>
										<p>Perfumowany żel do zmiękczania tkanin</p>
										<a href="house_503003_xpl.html" class="btn btn-default add-to-cart"><i class="fa fa-shopping-cart"></i>Więcej</a>
									</div>
									<!-- <div class="product-overlay">
										<div class="overlay-content">
											<h2>$56</h2>
											<p>Easy Polo Black Edition</p>
											<a href="#" class="btn btn-default add-to-cart"><i class="fa fa-shopping-cart"></i>Add to cart</a>
										</div>
									</div> -->
								</div>
							</div>
						</div>
						
						<div class="col-sm-4">
							<div class="product-image-wrapper">
								<div class="single-products">
									<div class="productinfo text-center">
										<img src="images/product/503001.jpg" alt="" />
										<h2>#503001</h2>
										<p>Żel do usuwania plam</p>
										<a href="house_503001_xpl.html" class="btn btn-default add-to-cart"><i class="fa fa-shopping-cart"></i>Więcej</a>
									</div>
									<!-- <div class="product-overlay">
										<div class="overlay-content">
											<h2>$56</h2>
											<p>Easy Polo Black Edition</p>
											<a href="#" class="btn btn-default add-to-cart"><i class="fa fa-shopping-cart"></i>Add to cart</a>
										</div>
									</div> -->
								</div>
							</div>
						</div>
						
						<div class="col-sm-4">
							<div class="product-image-wrapper">
								<div class="single-products">
									<div class="productinfo text-center">
										<img src="images/product/503004.jpg" alt="" />
										<h2>#503004</h2>
										<p>Żel do prania tkanin białych</p>
										<a href="house_503004_xpl.html" class="btn btn-default add-to-cart"><i class="fa fa-shopping-cart"></i>Więcej</a>
									</div>
									<!-- <div class="product-overlay">
										<div class="overlay-content">
											<h2>$56</h2>
											<p>Easy Polo Black Edition</p>
											<a href="#" class="btn btn-default add-to-cart"><i class="fa fa-shopping-cart"></i>Add to cart</a>
										</div>
									</div> -->
								</div>
							</div>
						</div>
						
						<div class="col-sm-4">
							<div class="product-image-wrapper">
								<div class="single-products">
									<div class="productinfo text-center">
										<img src="images/product/503005.jpg" alt="" />
										<h2>#503005</h2>
										<p>Żel do prania tkanin ciemnych i czarnych</p>
										<a href="house_503005_xpl.html" class="btn btn-default add-to-cart"><i class="fa fa-shopping-cart"></i>Więcej</a>
									</div>
									<!-- <div class="product-overlay">
										<div class="overlay-content">
											<h2>$56</h2>
											<p>Easy Polo Black Edition</p>
											<a href="#" class="btn btn-default add-to-cart"><i class="fa fa-shopping-cart"></i>Add to cart</a>
										</div>
									</div> -->
								</div>
							</div>
						</div>
						
						<div class="col-sm-4">
							<div class="product-image-wrapper">
								<div class="single-products">
									<div class="productinfo text-center">
										<img src="images/product/503006.jpg" alt="" />
										<h2>#503006</h2>
										<p>Żel do prania tkanin kolorowych</p>
										<a href="house_503006_xpl.html" class="btn btn-default add-to-cart"><i class="fa fa-shopping-cart"></i>Więcej</a>
									</div>
									<!-- <div class="product-overlay">
										<div class="overlay-content">
											<h2>$56</h2>
											<p>Easy Polo Black Edition</p>
											<a href="#" class="btn btn-default add-to-cart"><i class="fa fa-shopping-cart"></i>Add to cart</a>
										</div>
									</div> -->
								</div>
							</div>
						</div>
						
						<div class="col-sm-4">
							<div class="product-image-wrapper">
								<div class="single-products">
									<div class="productinfo text-center">
										<img src="images/product/504001.jpg" alt="" />
										<h2>#504001</h2>
										<p>Aksamitne mleczko do czyszczenia</p>
										<a href="house_504001_xpl.html" class="btn btn-default add-to-cart"><i class="fa fa-shopping-cart"></i>Więcej</a>
									</div>
									<!-- <div class="product-overlay">
										<div class="overlay-content">
											<h2>$56</h2>
											<p>Easy Polo Black Edition</p>
											<a href="#" class="btn btn-default add-to-cart"><i class="fa fa-shopping-cart"></i>Add to cart</a>
										</div>
									</div> -->
								</div>
							</div>
						</div>
						
						<div class="col-sm-4">
							<div class="product-image-wrapper">
								<div class="single-products">
									<div class="productinfo text-center">
										<img src="images/product/504002.jpg" alt="" />
										<h2>#504002</h2>
										<p>Spray do mycia szyb i luster z funkcją antypary</p>
										<a href="house_504002_xpl.html" class="btn btn-default add-to-cart"><i class="fa fa-shopping-cart"></i>Więcej</a>
									</div>
									<!-- <div class="product-overlay">
										<div class="overlay-content">
											<h2>$56</h2>
											<p>Easy Polo Black Edition</p>
											<a href="#" class="btn btn-default add-to-cart"><i class="fa fa-shopping-cart"></i>Add to cart</a>
										</div>
									</div> -->
								</div>
							</div>
						</div>
						
						<div class="col-sm-4">
							<div class="product-image-wrapper">
								<div class="single-products">
									<div class="productinfo text-center">
										<img src="images/product/504003.jpg" alt="" />
										<h2>#504003</h2>
										<p>Płyn do mycia podłóg drewnianych i paneli laminowanych</p>
										<a href="house_504003_xpl.html" class="btn btn-default add-to-cart"><i class="fa fa-shopping-cart"></i>Więcej</a>
									</div>
									<!-- <div class="product-overlay">
										<div class="overlay-content">
											<h2>$56</h2>
											<p>Easy Polo Black Edition</p>
											<a href="#" class="btn btn-default add-to-cart"><i class="fa fa-shopping-cart"></i>Add to cart</a>
										</div>
									</div> -->
								</div>
							</div>
						</div>
						<div class="col-sm-4">
							<div class="product-image-wrapper">
								<div class="single-products">
									<div class="productinfo text-center">
										<img src="images/product/504004.jpg" alt="" />
										<h2>#504004</h2>
										<p>Szampon do dywanów</p>
										<a href="house_504004_xpl.html" class="btn btn-default add-to-cart"><i class="fa fa-shopping-cart"></i>Więcej</a>
									</div>
									<!-- <div class="product-overlay">
										<div class="overlay-content">
											<h2>$56</h2>
											<p>Easy Polo Black Edition</p>
											<a href="#" class="btn btn-default add-to-cart"><i class="fa fa-shopping-cart"></i>Add to cart</a>
										</div>
									</div> -->
								</div>
							</div>
						</div>
						
						<div class="col-sm-4">
							<div class="product-image-wrapper">
								<div class="single-products">
									<div class="productinfo text-center">
										<img src="images/product/504005.jpg" alt="" />
										<h2>#504005</h2>
										<p>Żel do czyszczenia fug</p>
										<a href="house_504005_xpl.html" class="btn btn-default add-to-cart"><i class="fa fa-shopping-cart"></i>Więcej</a>
									</div>
									<!-- <div class="product-overlay">
										<div class="overlay-content">
											<h2>$56</h2>
											<p>Easy Polo Black Edition</p>
											<a href="#" class="btn btn-default add-to-cart"><i class="fa fa-shopping-cart"></i>Add to cart</a>
										</div>
									</div> -->
								</div>
							</div>
						</div>
						
						<div class="col-sm-4">
							<div class="product-image-wrapper">
								<div class="single-products">
									<div class="productinfo text-center">
										<img src="images/product/504006.jpg" alt="" />
										<h2>#504006</h2>
										<p>Żel do czyszczenia grilli i piekarników</p>
										<a href="house_504006_xpl.html" class="btn btn-default add-to-cart"><i class="fa fa-shopping-cart"></i>Więcej</a>
									</div>
									<!-- <div class="product-overlay">
										<div class="overlay-content">
											<h2>$56</h2>
											<p>Easy Polo Black Edition</p>
											<a href="#" class="btn btn-default add-to-cart"><i class="fa fa-shopping-cart"></i>Add to cart</a>
										</div>
									</div> -->
								</div>
							</div>
						</div>
						
						<div class="col-sm-4">
							<div class="product-image-wrapper">
								<div class="single-products">
									<div class="productinfo text-center">
										<img src="images/product/504007.jpg" alt="" />
										<h2>#504007</h2>
										<p>Żel uniwersalny</p>
										<a href="house_504007_xpl.html" class="btn btn-default add-to-cart"><i class="fa fa-shopping-cart"></i>Więcej</a>
									</div>
									<!-- <div class="product-overlay">
										<div class="overlay-content">
											<h2>$56</h2>
											<p>Easy Polo Black Edition</p>
											<a href="#" class="btn btn-default add-to-cart"><i class="fa fa-shopping-cart"></i>Add to cart</a>
										</div>
									</div> -->
								</div>
							</div>
						</div>
						
						<div class="col-sm-4">
							<div class="product-image-wrapper">
								<div class="single-products">
									<div class="productinfo text-center">
										<img src="images/product/504008.jpg" alt="" />
										<h2>#504008</h2>
										<p>Płyn do mocno zabrudzonych powierzchni</p>
										<a href="house_504008_xpl.html" class="btn btn-default add-to-cart"><i class="fa fa-shopping-cart"></i>Więcej</a>
									</div>
									<!-- <div class="product-overlay">
										<div class="overlay-content">
											<h2>$56</h2>
											<p>Easy Polo Black Edition</p>
											<a href="#" class="btn btn-default add-to-cart"><i class="fa fa-shopping-cart"></i>Add to cart</a>
										</div>
									</div> -->
								</div>
							</div>
						</div>
						

						<div class="col-sm-4">
							<div class="product-image-wrapper">
								<div class="single-products">
									<div class="productinfo text-center">
										<img src="images/product/504009.jpg" alt="" />
										<h2>#504009</h2>
										<p>Spray do czyszczenia ekranów i powierzchni ze stali INOX</p>
										<a href="house_504009_xpl.html" class="btn btn-default add-to-cart"><i class="fa fa-shopping-cart"></i>Więcej</a>
									</div>
									<!-- <div class="product-overlay">
										<div class="overlay-content">
											<h2>$56</h2>
											<p>Easy Polo Black Edition</p>
											<a href="#" class="btn btn-default add-to-cart"><i class="fa fa-shopping-cart"></i>Add to cart</a>
										</div>
									</div> -->
								</div>
							</div>
						</div>
						
						<div class="col-sm-4">
							<div class="product-image-wrapper">
								<div class="single-products">
									<div class="productinfo text-center">
										<img src="images/product/504010.jpg" alt="" />
										<h2>#504010</h2>
										<p>Kremowy spray do pielęgnacji mebli</p>
										<a href="house_504010_xpl.html" class="btn btn-default add-to-cart"><i class="fa fa-shopping-cart"></i>Więcej</a>
									</div>
									<!-- <div class="product-overlay">
										<div class="overlay-content">
											<h2>$56</h2>
											<p>Easy Polo Black Edition</p>
											<a href="#" class="btn btn-default add-to-cart"><i class="fa fa-shopping-cart"></i>Add to cart</a>
										</div>
									</div> -->
								</div>
							</div>
						</div>
						
						<div class="col-sm-4">
							<div class="product-image-wrapper">
								<div class="single-products">
									<div class="productinfo text-center">
										<img src="images/product/504011.jpg" alt="" />
										<h2>#504011</h2>
										<p>Spray do mycia szyb i luster</p>
										<a href="house_504011_xpl.html" class="btn btn-default add-to-cart"><i class="fa fa-shopping-cart"></i>Więcej</a>
									</div>
									<!-- <div class="product-overlay">
										<div class="overlay-content">
											<h2>$56</h2>
											<p>Easy Polo Black Edition</p>
											<a href="#" class="btn btn-default add-to-cart"><i class="fa fa-shopping-cart"></i>Add to cart</a>
										</div>
									</div> -->
								</div>
							</div>
						</div>
						




						
						
<!--						<ul class="pagination">
							<li class="active"><a href="">1</a></li>
							<li><a href="">2</a></li>
							<li><a href="">3</a></li>
							<li><a href="">&raquo;</a></li>
						</ul> -->
					</div><!--features_items-->
							<ul class="pagination">
							<li class="active"><a href="">1</a></li>
							<li><a href="">2</a></li>
							<li><a href="">3</a></li>
							<li><a href="">&raquo;</a></li>
						</ul>
				</div>
