
				
				<div class="col-sm-9 padding-right">
					<div class="features_items"><!--features_items-->
						<h2 class="title text-center">Perfumy Męskie</h2>
						<div class="col-sm-4">
							<div class="product-image-wrapper">
								<div class="single-products">
									<div class="productinfo text-center">
										<img src="images/product/perfumy_02.jpg" alt="" />
										<h2>#02</h2>
										<p>zielone jabłko – cynamon – drzewo oliwne</p>
										<a href="perfumy_101002_xpl.html" class="btn btn-default add-to-cart"><i class="fa fa-shopping-cart"></i>Więcej</a>
									</div>
									<!-- <div class="product-overlay">
										<div class="overlay-content">
											<h2>$56</h2>
											<p>Easy Polo Black Edition</p>
											<a href="#" class="btn btn-default add-to-cart"><i class="fa fa-shopping-cart"></i>Add to cart</a>
										</div>
									</div> -->
								</div>
							</div>
						</div>
						
						<div class="col-sm-4">
							<div class="product-image-wrapper">
								<div class="single-products">
									<div class="productinfo text-center">
										<img src="images/product/perfumy_04.jpg" alt="" />
										<h2>#04</h2>
										<p>grejpfrut – kawa – czarny pieprz</p>
										<a href="perfumy_101004_xpl.html" class="btn btn-default add-to-cart"><i class="fa fa-shopping-cart"></i>Więcej</a>
									</div>
									<!-- <div class="product-overlay">
										<div class="overlay-content">
											<h2>$56</h2>
											<p>Easy Polo Black Edition</p>
											<a href="#" class="btn btn-default add-to-cart"><i class="fa fa-shopping-cart"></i>Add to cart</a>
										</div>
									</div> -->
								</div>
							</div>
						</div>
						
						<div class="col-sm-4">
							<div class="product-image-wrapper">
								<div class="single-products">
									<div class="productinfo text-center">
										<img src="images/product/perfumy_06.jpg" alt="" />
										<h2>#06</h2>
										<p>cytryna – kumkwat – jałowiec</p>
										<a href="perfumy_101006_xpl.html" class="btn btn-default add-to-cart"><i class="fa fa-shopping-cart"></i>Więcej</a>
									</div>
									<!-- <div class="product-overlay">
										<div class="overlay-content">
											<h2>$56</h2>
											<p>Easy Polo Black Edition</p>
											<a href="#" class="btn btn-default add-to-cart"><i class="fa fa-shopping-cart"></i>Add to cart</a>
										</div>
									</div> -->
								</div>
							</div>
						</div>
						
						<div class="col-sm-4">
							<div class="product-image-wrapper">
								<div class="single-products">
									<div class="productinfo text-center">
										<img src="images/product/perfumy_08.jpg" alt="" />
										<h2>#08</h2>
										<p>nuty morskie – limonka – rezeda</p>
										<a href="perfumy_101008_xpl.html" class="btn btn-default add-to-cart"><i class="fa fa-shopping-cart"></i>Więcej</a>
									</div>
									<!-- <div class="product-overlay">
										<div class="overlay-content">
											<h2>$56</h2>
											<p>Easy Polo Black Edition</p>
											<a href="#" class="btn btn-default add-to-cart"><i class="fa fa-shopping-cart"></i>Add to cart</a>
										</div>
									</div> -->
								</div>
							</div>
						</div>
						
						<div class="col-sm-4">
							<div class="product-image-wrapper">
								<div class="single-products">
									<div class="productinfo text-center">
										<img src="images/product/perfumy_10.jpg" alt="" />
										<h2>#10</h2>
										<p>mandarynka – imbir – lawenda</p>
										<a href="perfumy_101010_xpl.html" class="btn btn-default add-to-cart"><i class="fa fa-shopping-cart"></i>Więcej</a>
									</div>
									<!-- <div class="product-overlay">
										<div class="overlay-content">
											<h2>$56</h2>
											<p>Easy Polo Black Edition</p>
											<a href="#" class="btn btn-default add-to-cart"><i class="fa fa-shopping-cart"></i>Add to cart</a>
										</div>
									</div> -->
								</div>
							</div>
						</div>
						

						
						<div class="col-sm-4">
							<div class="product-image-wrapper">
								<div class="single-products">
									<div class="productinfo text-center">
										<img src="images/product/perfumy_14.jpg" alt="" />
										<h2>#14</h2>
										<p>nuty morskie – pomarańcza – cedr</p>
										<a href="perfumy_101014_xpl.html" class="btn btn-default add-to-cart"><i class="fa fa-shopping-cart"></i>Więcej</a>
									</div>
									<!-- <div class="product-overlay">
										<div class="overlay-content">
											<h2>$56</h2>
											<p>Easy Polo Black Edition</p>
											<a href="#" class="btn btn-default add-to-cart"><i class="fa fa-shopping-cart"></i>Add to cart</a>
										</div>
									</div> -->
								</div>
							</div>
						</div>
						
						<div class="col-sm-4">
							<div class="product-image-wrapper">
								<div class="single-products">
									<div class="productinfo text-center">
										<img src="images/product/perfumy_16.jpg" alt="" />
										<h2>#16</h2>
										<p>gruszka – mięta – bazylia</p>
										<a href="perfumy_101016_xpl.html" class="btn btn-default add-to-cart"><i class="fa fa-shopping-cart"></i>Więcej</a>
									</div>
									<!-- <div class="product-overlay">
										<div class="overlay-content">
											<h2>$56</h2>
											<p>Easy Polo Black Edition</p>
											<a href="#" class="btn btn-default add-to-cart"><i class="fa fa-shopping-cart"></i>Add to cart</a>
										</div>
									</div> -->
								</div>
							</div>
						</div>
						
						<div class="col-sm-4">
							<div class="product-image-wrapper">
								<div class="single-products">
									<div class="productinfo text-center">
										<img src="images/product/perfumy_18.jpg" alt="" />
										<h2>#18</h2>
										<p>kawa – różowy pieprz – bób tonka</p>
										<a href="perfumy_101018_xpl.html" class="btn btn-default add-to-cart"><i class="fa fa-shopping-cart"></i>Więcej</a>
									</div>
									<!-- <div class="product-overlay">
										<div class="overlay-content">
											<h2>$56</h2>
											<p>Easy Polo Black Edition</p>
											<a href="#" class="btn btn-default add-to-cart"><i class="fa fa-shopping-cart"></i>Add to cart</a>
										</div>
									</div> -->
								</div>
							</div>
						</div>
						
						<div class="col-sm-4">
							<div class="product-image-wrapper">
								<div class="single-products">
									<div class="productinfo text-center">
										<img src="images/product/perfumy_20.jpg" alt="" />
										<h2>#20</h2>
										<p>cynamon – róża – nuty skóry</p>
										<a href="perfumy_101020_xpl.html" class="btn btn-default add-to-cart"><i class="fa fa-shopping-cart"></i>Więcej</a>
									</div>
									<!-- <div class="product-overlay">
										<div class="overlay-content">
											<h2>$56</h2>
											<p>Easy Polo Black Edition</p>
											<a href="#" class="btn btn-default add-to-cart"><i class="fa fa-shopping-cart"></i>Add to cart</a>
										</div>
									</div> -->
								</div>
							</div>
						</div>
						<div class="col-sm-4">
							<div class="product-image-wrapper">
								<div class="single-products">
									<div class="productinfo text-center">
										<img src="images/product/perfumy_22.jpg" alt="" />
										<h2>#22</h2>
										<p>cytryna – nuty skóry – ambra</p>
										<a href="perfumy_101022_xpl.html" class="btn btn-default add-to-cart"><i class="fa fa-shopping-cart"></i>Więcej</a>
									</div>
									<!-- <div class="product-overlay">
										<div class="overlay-content">
											<h2>$56</h2>
											<p>Easy Polo Black Edition</p>
											<a href="#" class="btn btn-default add-to-cart"><i class="fa fa-shopping-cart"></i>Add to cart</a>
										</div>
									</div> -->
								</div>
							</div>
						</div>
						
						<div class="col-sm-4">
							<div class="product-image-wrapper">
								<div class="single-products">
									<div class="productinfo text-center">
										<img src="images/product/perfumy_24.jpg" alt="" />
										<h2>#24</h2>
										<p>liść laurowy – drzewo sandałowe – ambra</p>
										<a href="perfumy_101024_xpl.html" class="btn btn-default add-to-cart"><i class="fa fa-shopping-cart"></i>Więcej</a>
									</div>
									<!-- <div class="product-overlay">
										<div class="overlay-content">
											<h2>$24</h2>
											<p>Easy Polo Black Edition</p>
											<a href="#" class="btn btn-default add-to-cart"><i class="fa fa-shopping-cart"></i>Add to cart</a>
										</div>
									</div> -->
								</div>
							</div>
						</div>
						
						<div class="col-sm-4">
							<div class="product-image-wrapper">
								<div class="single-products">
									<div class="productinfo text-center">
										<img src="images/product/perfumy_26.jpg" alt="" />
										<h2>#26</h2>
										<p>agar – palisander – wanilia</p>
										<a href="perfumy_101026_xpl.html" class="btn btn-default add-to-cart"><i class="fa fa-shopping-cart"></i>Więcej</a>
									</div>
									<!-- <div class="product-overlay">
										<div class="overlay-content">
											<h2>$56</h2>
											<p>Easy Polo Black Edition</p>
											<a href="#" class="btn btn-default add-to-cart"><i class="fa fa-shopping-cart"></i>Add to cart</a>
										</div>
									</div> -->
								</div>
							</div>
						</div>
						
						<div class="col-sm-4">
							<div class="product-image-wrapper">
								<div class="single-products">
									<div class="productinfo text-center">
										<img src="images/product/perfumy_28.jpg" alt="" />
										<h2>#28</h2>
										<p>bergamotka – papaja – gałka muszkatołowa</p>
										<a href="perfumy_101028_xpl.html" class="btn btn-default add-to-cart"><i class="fa fa-shopping-cart"></i>Więcej</a>
									</div>
									<!-- <div class="product-overlay">
										<div class="overlay-content">
											<h2>$56</h2>
											<p>Easy Polo Black Edition</p>
											<a href="#" class="btn btn-default add-to-cart"><i class="fa fa-shopping-cart"></i>Add to cart</a>
										</div>
									</div> -->
								</div>
							</div>
						</div>
						
						<div class="col-sm-4">
							<div class="product-image-wrapper">
								<div class="single-products">
									<div class="productinfo text-center">
										<img src="images/product/perfumy_30.jpg" alt="" />
										<h2>#30</h2>
										<p>zielone jabłko – lawenda – jodła</p>
										<a href="perfumy_101030_xpl.html" class="btn btn-default add-to-cart"><i class="fa fa-shopping-cart"></i>Więcej</a>
									</div>
									<!-- <div class="product-overlay">
										<div class="overlay-content">
											<h2>$56</h2>
											<p>Easy Polo Black Edition</p>
											<a href="#" class="btn btn-default add-to-cart"><i class="fa fa-shopping-cart"></i>Add to cart</a>
										</div>
									</div> -->
								</div>
							</div>
						</div>
						
						<div class="col-sm-4">
							<div class="product-image-wrapper">
								<div class="single-products">
									<div class="productinfo text-center">
										<img src="images/product/perfumy_32.jpg" alt="" />
										<h2>#32</h2>
										<p>grejpfrut – ﬁołek – nuty skóry</p>
										<a href="perfumy_101032_xpl.html" class="btn btn-default add-to-cart"><i class="fa fa-shopping-cart"></i>Więcej</a>
									</div>
									<!-- <div class="product-overlay">
										<div class="overlay-content">
											<h2>$56</h2>
											<p>Easy Polo Black Edition</p>
											<a href="#" class="btn btn-default add-to-cart"><i class="fa fa-shopping-cart"></i>Add to cart</a>
										</div>
									</div> -->
								</div>
							</div>
						</div>
						
						<div class="col-sm-4">
							<div class="product-image-wrapper">
								<div class="single-products">
									<div class="productinfo text-center">
										<img src="images/product/perfumy_34.jpg" alt="" />
										<h2>#34</h2>
										<p>wodorosty – pomarańcza – kwiat bawełny</p>
										<a href="perfumy_101034_xpl.html" class="btn btn-default add-to-cart"><i class="fa fa-shopping-cart"></i>Więcej</a>
									</div>
									<!-- <div class="product-overlay">
										<div class="overlay-content">
											<h2>$56</h2>
											<p>Easy Polo Black Edition</p>
											<a href="#" class="btn btn-default add-to-cart"><i class="fa fa-shopping-cart"></i>Add to cart</a>
										</div>
									</div> -->
								</div>
							</div>
						</div>
						
						<div class="col-sm-4">
							<div class="product-image-wrapper">
								<div class="single-products">
									<div class="productinfo text-center">
										<img src="images/product/perfumy_36.jpg" alt="" />
										<h2>#36</h2>
										<p>bergamotka – liście pomidora – drzewo sandałowe</p>
										<a href="perfumy_101036_xpl.html" class="btn btn-default add-to-cart"><i class="fa fa-shopping-cart"></i>Więcej</a>
									</div>
									<!-- <div class="product-overlay">
										<div class="overlay-content">
											<h2>$56</h2>
											<p>Easy Polo Black Edition</p>
											<a href="#" class="btn btn-default add-to-cart"><i class="fa fa-shopping-cart"></i>Add to cart</a>
										</div>
									</div> -->
								</div>
							</div>
						</div>
						
						<div class="col-sm-4">
							<div class="product-image-wrapper">
								<div class="single-products">
									<div class="productinfo text-center">
										<img src="images/product/perfume_38.jpg" alt="" />
										<h2>#38</h2>
										<p>morska woda – liść laurowy – mandarynka</p>
										<a href="perfumy_101038_xpl.html" class="btn btn-default add-to-cart"><i class="fa fa-shopping-cart"></i>Więcej</a>
									</div>
									<!-- <div class="product-overlay">
										<div class="overlay-content">
											<h2>$56</h2>
											<p>Easy Polo Black Edition</p>
											<a href="#" class="btn btn-default add-to-cart"><i class="fa fa-shopping-cart"></i>Add to cart</a>
										</div>
									</div> -->
								</div>
							</div>
						</div>
						
						<div class="col-sm-4">
							<div class="product-image-wrapper">
								<div class="single-products">
									<div class="productinfo text-center">
										<img src="images/product/perfumy_40.jpg" alt="" />
										<h2>#40</h2>
										<p>pomarańcza – wetyweria – benzoes</p>
										<a href="perfumy_101040_xpl.html" class="btn btn-default add-to-cart"><i class="fa fa-shopping-cart"></i>Więcej</a>
									</div>
									<!-- <div class="product-overlay">
										<div class="overlay-content">
											<h2>$56</h2>
											<p>Easy Polo Black Edition</p>
											<a href="#" class="btn btn-default add-to-cart"><i class="fa fa-shopping-cart"></i>Add to cart</a>
										</div>
									</div> -->
								</div>
							</div>
						</div>
						
						<div class="col-sm-4">
							<div class="product-image-wrapper">
								<div class="single-products">
									<div class="productinfo text-center">
										<img src="images/product/perfumy_42.jpg" alt="" />
										<h2>#42</h2>
										<p>czarny pieprz - paczula - nuty drzewne</p>
										<a href="perfumy_101042_xpl.html" class="btn btn-default add-to-cart"><i class="fa fa-shopping-cart"></i>Więcej</a>
									</div>
									<!-- <div class="product-overlay">
										<div class="overlay-content">
											<h2>$56</h2>
											<p>Easy Polo Black Edition</p>
											<a href="#" class="btn btn-default add-to-cart"><i class="fa fa-shopping-cart"></i>Add to cart</a>
										</div>
									</div> -->
								</div>
							</div>
						</div>
						
						<div class="col-sm-4">
							<div class="product-image-wrapper">
								<div class="single-products">
									<div class="productinfo text-center">
										<img src="images/product/perfumy_44.jpg" alt="" />
										<h2>#44</h2>
										<p>bergamotka - kadzidło - imbir</p>
										<a href="perfumy_101044_xpl.html" class="btn btn-default add-to-cart"><i class="fa fa-shopping-cart"></i>Więcej</a>
									</div>
									<!-- <div class="product-overlay">
										<div class="overlay-content">
											<h2>$56</h2>
											<p>Easy Polo Black Edition</p>
											<a href="#" class="btn btn-default add-to-cart"><i class="fa fa-shopping-cart"></i>Add to cart</a>
										</div>
									</div> -->
								</div>
							</div>
						</div>
						

						




						
						
<!--						<ul class="pagination">
							<li class="active"><a href="">1</a></li>
							<li><a href="">2</a></li>
							<li><a href="">3</a></li>
							<li><a href="">&raquo;</a></li>
						</ul> -->
					</div><!--features_items-->
							<ul class="pagination">
							<li class="active"><a href="">1</a></li>
							<li><a href="">2</a></li>
							<li><a href="">3</a></li>
							<li><a href="">&raquo;</a></li>
						</ul>
				</div>
