
				
				<div class="col-sm-9 padding-right">
					<div class="features_items"><!--features_items-->
						<h2 class="title text-center">Perfumy Damskie</h2>
						<div class="col-sm-4">
							<div class="product-image-wrapper">
								<div class="single-products">
									<div class="productinfo text-center">
										<img src="images/product/perfume_01.jpg" alt="" />
										<h2>#01</h2>
										<p>zielone jabłko – magnolia – ogórek</p>
										<a href="perfumy_101001_xpl.html" class="btn btn-default add-to-cart"><i class="fa fa-shopping-cart"></i>Więcej</a>
									</div>
									<!-- <div class="product-overlay">
										<div class="overlay-content">
											<h2>$56</h2>
											<p>Easy Polo Black Edition</p>
											<a href="#" class="btn btn-default add-to-cart"><i class="fa fa-shopping-cart"></i>Add to cart</a>
										</div>
									</div> -->
								</div>
							</div>
						</div>
						
						<div class="col-sm-4">
							<div class="product-image-wrapper">
								<div class="single-products">
									<div class="productinfo text-center">
										<img src="images/product/perfume_03.jpg" alt="" />
										<h2>#03</h2>
										<p>róża – pomarańcza – paczula</p>
										<a href="perfumy_101003_xpl.html" class="btn btn-default add-to-cart"><i class="fa fa-shopping-cart"></i>Więcej</a>
									</div>
									<!-- <div class="product-overlay">
										<div class="overlay-content">
											<h2>$56</h2>
											<p>Easy Polo Black Edition</p>
											<a href="#" class="btn btn-default add-to-cart"><i class="fa fa-shopping-cart"></i>Add to cart</a>
										</div>
									</div> -->
								</div>
							</div>
						</div>
						
						<div class="col-sm-4">
							<div class="product-image-wrapper">
								<div class="single-products">
									<div class="productinfo text-center">
										<img src="images/product/perfume_05.jpg" alt="" />
										<h2>#05</h2>
										<p>wanilia – irys – piżmo</p>
										<a href="perfumy_101005_xpl.html" class="btn btn-default add-to-cart"><i class="fa fa-shopping-cart"></i>Więcej</a>
									</div>
									<!-- <div class="product-overlay">
										<div class="overlay-content">
											<h2>$56</h2>
											<p>Easy Polo Black Edition</p>
											<a href="#" class="btn btn-default add-to-cart"><i class="fa fa-shopping-cart"></i>Add to cart</a>
										</div>
									</div> -->
								</div>
							</div>
						</div>
						
						<div class="col-sm-4">
							<div class="product-image-wrapper">
								<div class="single-products">
									<div class="productinfo text-center">
										<img src="images/product/perfume_07.jpg" alt="" />
										<h2>#07</h2>
										<p>wanilia – gruszka – czekoladki</p>
										<a href="perfumy_101007_xpl.html" class="btn btn-default add-to-cart"><i class="fa fa-shopping-cart"></i>Więcej</a>
									</div>
									<!-- <div class="product-overlay">
										<div class="overlay-content">
											<h2>$56</h2>
											<p>Easy Polo Black Edition</p>
											<a href="#" class="btn btn-default add-to-cart"><i class="fa fa-shopping-cart"></i>Add to cart</a>
										</div>
									</div> -->
								</div>
							</div>
						</div>
						
						<div class="col-sm-4">
							<div class="product-image-wrapper">
								<div class="single-products">
									<div class="productinfo text-center">
										<img src="images/product/perfumy_09.jpg" alt="" />
										<h2>#9</h2>
										<p>karmel – melon – wata cukrowa</p>
										<a href="perfumy_101009_xpl.html" class="btn btn-default add-to-cart"><i class="fa fa-shopping-cart"></i>Więcej</a>
									</div>
									<!-- <div class="product-overlay">
										<div class="overlay-content">
											<h2>$56</h2>
											<p>Easy Polo Black Edition</p>
											<a href="#" class="btn btn-default add-to-cart"><i class="fa fa-shopping-cart"></i>Add to cart</a>
										</div>
									</div> -->
								</div>
							</div>
						</div>
						
						<div class="col-sm-4">
							<div class="product-image-wrapper">
								<div class="single-products">
									<div class="productinfo text-center">
										<img src="images/product/perfume_11.jpg" alt="" />
										<h2>#11</h2>
										<p>orchidea – liście herbaty – bergamotka</p>
										<a href="perfumy_101011_xpl.html" class="btn btn-default add-to-cart"><i class="fa fa-shopping-cart"></i>Więcej</a>
									</div>
									<!-- <div class="product-overlay">
										<div class="overlay-content">
											<h2>$56</h2>
											<p>Easy Polo Black Edition</p>
											<a href="#" class="btn btn-default add-to-cart"><i class="fa fa-shopping-cart"></i>Add to cart</a>
										</div>
									</div> -->
								</div>
							</div>
						</div>
						
						<div class="col-sm-4">
							<div class="product-image-wrapper">
								<div class="single-products">
									<div class="productinfo text-center">
										<img src="images/product/perfumy_13.jpg" alt="" />
										<h2>#13</h2>
										<p>gorzka pomarańcza – imbir – miód</p>
										<a href="perfumy_101013_xpl.html" class="btn btn-default add-to-cart"><i class="fa fa-shopping-cart"></i>Więcej</a>
									</div>
									<!-- <div class="product-overlay">
										<div class="overlay-content">
											<h2>$56</h2>
											<p>Easy Polo Black Edition</p>
											<a href="#" class="btn btn-default add-to-cart"><i class="fa fa-shopping-cart"></i>Add to cart</a>
										</div>
									</div> -->
								</div>
							</div>
						</div>
						
						<div class="col-sm-4">
							<div class="product-image-wrapper">
								<div class="single-products">
									<div class="productinfo text-center">
										<img src="images/product/perfumy_15.jpg" alt="" />
										<h2>#15</h2>
										<p>truskawka – wiśnia – karmel</p>
										<a href="perfumy_101015_xpl.html" class="btn btn-default add-to-cart"><i class="fa fa-shopping-cart"></i>Więcej</a>
									</div>
									<!-- <div class="product-overlay">
										<div class="overlay-content">
											<h2>$56</h2>
											<p>Easy Polo Black Edition</p>
											<a href="#" class="btn btn-default add-to-cart"><i class="fa fa-shopping-cart"></i>Add to cart</a>
										</div>
									</div> -->
								</div>
							</div>
						</div>
						
						<div class="col-sm-4">
							<div class="product-image-wrapper">
								<div class="single-products">
									<div class="productinfo text-center">
										<img src="images/product/perfumy_17.jpg" alt="" />
										<h2>#17</h2>
										<p>jaśmin – passiﬂora – wanilia</p>
										<a href="perfumy_101017_xpl.html" class="btn btn-default add-to-cart"><i class="fa fa-shopping-cart"></i>Więcej</a>
									</div>
									<!-- <div class="product-overlay">
										<div class="overlay-content">
											<h2>$56</h2>
											<p>Easy Polo Black Edition</p>
											<a href="#" class="btn btn-default add-to-cart"><i class="fa fa-shopping-cart"></i>Add to cart</a>
										</div>
									</div> -->
								</div>
							</div>
						</div>
						
						<div class="col-sm-4">
							<div class="product-image-wrapper">
								<div class="single-products">
									<div class="productinfo text-center">
										<img src="images/product/perfumy_19.jpg" alt="" />
										<h2>#19</h2>
										<p>jaśmin – melon – cedr</p>
										<a href="perfumy_101019_xpl.html" class="btn btn-default add-to-cart"><i class="fa fa-shopping-cart"></i>Więcej</a>
									</div>
									<!-- <div class="product-overlay">
										<div class="overlay-content">
											<h2>$56</h2>
											<p>Easy Polo Black Edition</p>
											<a href="#" class="btn btn-default add-to-cart"><i class="fa fa-shopping-cart"></i>Add to cart</a>
										</div>
									</div> -->
								</div>
							</div>
						</div>
						<div class="col-sm-4">
							<div class="product-image-wrapper">
								<div class="single-products">
									<div class="productinfo text-center">
										<img src="images/product/perfumy_21.jpg" alt="" />
										<h2>#21</h2>
										<p>kwiat pomarańczy – drzewo sandałowe – piżmo</p>
										<a href="perfumy_101021_xpl.html" class="btn btn-default add-to-cart"><i class="fa fa-shopping-cart"></i>Więcej</a>
									</div>
									<!-- <div class="product-overlay">
										<div class="overlay-content">
											<h2>$56</h2>
											<p>Easy Polo Black Edition</p>
											<a href="#" class="btn btn-default add-to-cart"><i class="fa fa-shopping-cart"></i>Add to cart</a>
										</div>
									</div> -->
								</div>
							</div>
						</div>
						
						<div class="col-sm-4">
							<div class="product-image-wrapper">
								<div class="single-products">
									<div class="productinfo text-center">
										<img src="images/product/perfumy_23.jpg" alt="" />
										<h2>#23</h2>
										<p>róża – paczula – ambra</p>
										<a href="perfumy_101023_xpl.html" class="btn btn-default add-to-cart"><i class="fa fa-shopping-cart"></i>Więcej</a>
									</div>
									<!-- <div class="product-overlay">
										<div class="overlay-content">
											<h2>$56</h2>
											<p>Easy Polo Black Edition</p>
											<a href="#" class="btn btn-default add-to-cart"><i class="fa fa-shopping-cart"></i>Add to cart</a>
										</div>
									</div> -->
								</div>
							</div>
						</div>
						
						<div class="col-sm-4">
							<div class="product-image-wrapper">
								<div class="single-products">
									<div class="productinfo text-center">
										<img src="images/product/perfumy_25.jpg" alt="" />
										<h2>#25</h2>
										<p>róża – szałwia – bergamotka</p>
										<a href="perfumy_101025_xpl.html" class="btn btn-default add-to-cart"><i class="fa fa-shopping-cart"></i>Więcej</a>
									</div>
									<!-- <div class="product-overlay">
										<div class="overlay-content">
											<h2>$56</h2>
											<p>Easy Polo Black Edition</p>
											<a href="#" class="btn btn-default add-to-cart"><i class="fa fa-shopping-cart"></i>Add to cart</a>
										</div>
									</div> -->
								</div>
							</div>
						</div>
						
						<div class="col-sm-4">
							<div class="product-image-wrapper">
								<div class="single-products">
									<div class="productinfo text-center">
										<img src="images/product/perfumy_27.jpg" alt="" />
										<h2>#27</h2>
										<p>malina – jaśmin – miód</p>
										<a href="perfumy_101027_xpl.html" class="btn btn-default add-to-cart"><i class="fa fa-shopping-cart"></i>Więcej</a>
									</div>
									<!-- <div class="product-overlay">
										<div class="overlay-content">
											<h2>$56</h2>
											<p>Easy Polo Black Edition</p>
											<a href="#" class="btn btn-default add-to-cart"><i class="fa fa-shopping-cart"></i>Add to cart</a>
										</div>
									</div> -->
								</div>
							</div>
						</div>
						
						<div class="col-sm-4">
							<div class="product-image-wrapper">
								<div class="single-products">
									<div class="productinfo text-center">
										<img src="images/product/perfumy_29.jpg" alt="" />
										<h2>#29</h2>
										<p>liczi – brzoskwinia – piżmo</p>
										<a href="perfumy_101029_xpl.html" class="btn btn-default add-to-cart"><i class="fa fa-shopping-cart"></i>Więcej</a>
									</div>
									<!-- <div class="product-overlay">
										<div class="overlay-content">
											<h2>$56</h2>
											<p>Easy Polo Black Edition</p>
											<a href="#" class="btn btn-default add-to-cart"><i class="fa fa-shopping-cart"></i>Add to cart</a>
										</div>
									</div> -->
								</div>
							</div>
						</div>
						
						<div class="col-sm-4">
							<div class="product-image-wrapper">
								<div class="single-products">
									<div class="productinfo text-center">
										<img src="images/product/perfumy_31.jpg" alt="" />
										<h2>#31</h2>
										<p>piwonia – róża – różowy pieprz</p>
										<a href="perfumy_101031_xpl.html" class="btn btn-default add-to-cart"><i class="fa fa-shopping-cart"></i>Więcej</a>
									</div>
									<!-- <div class="product-overlay">
										<div class="overlay-content">
											<h2>$56</h2>
											<p>Easy Polo Black Edition</p>
											<a href="#" class="btn btn-default add-to-cart"><i class="fa fa-shopping-cart"></i>Add to cart</a>
										</div>
									</div> -->
								</div>
							</div>
						</div>
						
						<div class="col-sm-4">
							<div class="product-image-wrapper">
								<div class="single-products">
									<div class="productinfo text-center">
										<img src="images/product/perfumy_33.jpg" alt="" />
										<h2>#33</h2>
										<p>frezja – róża – paczula</p>
										<a href="perfumy_101033_xpl.html" class="btn btn-default add-to-cart"><i class="fa fa-shopping-cart"></i>Więcej</a>
									</div>
									<!-- <div class="product-overlay">
										<div class="overlay-content">
											<h2>$56</h2>
											<p>Easy Polo Black Edition</p>
											<a href="#" class="btn btn-default add-to-cart"><i class="fa fa-shopping-cart"></i>Add to cart</a>
										</div>
									</div> -->
								</div>
							</div>
						</div>
						
						<div class="col-sm-4">
							<div class="product-image-wrapper">
								<div class="single-products">
									<div class="productinfo text-center">
										<img src="images/product/perfumy_35.jpg" alt="" />
										<h2>#35</h2>
										<p>frezja – drzewo sandałowe – zamsz</p>
										<a href="perfumy_101035_xpl.html" class="btn btn-default add-to-cart"><i class="fa fa-shopping-cart"></i>Więcej</a>
									</div>
									<!-- <div class="product-overlay">
										<div class="overlay-content">
											<h2>$56</h2>
											<p>Easy Polo Black Edition</p>
											<a href="#" class="btn btn-default add-to-cart"><i class="fa fa-shopping-cart"></i>Add to cart</a>
										</div>
									</div> -->
								</div>
							</div>
						</div>
						
						<div class="col-sm-4">
							<div class="product-image-wrapper">
								<div class="single-products">
									<div class="productinfo text-center">
										<img src="images/product/perfumy_37.jpg" alt="" />
										<h2>#37</h2>
										<p>granat – orchidea – mahoń</p>
										<a href="perfumy_101037_xpl.html" class="btn btn-default add-to-cart"><i class="fa fa-shopping-cart"></i>Więcej</a>
									</div>
									<!-- <div class="product-overlay">
										<div class="overlay-content">
											<h2>$56</h2>
											<p>Easy Polo Black Edition</p>
											<a href="#" class="btn btn-default add-to-cart"><i class="fa fa-shopping-cart"></i>Add to cart</a>
										</div>
									</div> -->
								</div>
							</div>
						</div>
						
						<div class="col-sm-4">
							<div class="product-image-wrapper">
								<div class="single-products">
									<div class="productinfo text-center">
										<img src="images/product/perfumy_39.jpg" alt="" />
										<h2>#39</h2>
										<p>cytryna – zielone jabłko – bambus</p>
										<a href="perfumy_101039_xpl.html" class="btn btn-default add-to-cart"><i class="fa fa-shopping-cart"></i>Więcej</a>
									</div>
									<!-- <div class="product-overlay">
										<div class="overlay-content">
											<h2>$56</h2>
											<p>Easy Polo Black Edition</p>
											<a href="#" class="btn btn-default add-to-cart"><i class="fa fa-shopping-cart"></i>Add to cart</a>
										</div>
									</div> -->
								</div>
							</div>
						</div>
						
						<div class="col-sm-4">
							<div class="product-image-wrapper">
								<div class="single-products">
									<div class="productinfo text-center">
										<img src="images/product/perfumy_41.jpg" alt="" />
										<h2>#41</h2>
										<p>zielona herbata – cytryna – mech dębowy</p>
										<a href="perfumy_101041_xpl.html" class="btn btn-default add-to-cart"><i class="fa fa-shopping-cart"></i>Więcej</a>
									</div>
									<!-- <div class="product-overlay">
										<div class="overlay-content">
											<h2>$56</h2>
											<p>Easy Polo Black Edition</p>
											<a href="#" class="btn btn-default add-to-cart"><i class="fa fa-shopping-cart"></i>Add to cart</a>
										</div>
									</div> -->
								</div>
							</div>
						</div>
						

						
						<div class="col-sm-4">
							<div class="product-image-wrapper">
								<div class="single-products">
									<div class="productinfo text-center">
										<img src="images/product/perfumy_45.jpg" alt="" />
										<h2>#45</h2>
										<p>brzoskwinia – róża – frezja</p>
										<a href="perfumy_101045_xpl.html" class="btn btn-default add-to-cart"><i class="fa fa-shopping-cart"></i>Więcej</a>
									</div>
									<!-- <div class="product-overlay">
										<div class="overlay-content">
											<h2>$56</h2>
											<p>Easy Polo Black Edition</p>
											<a href="#" class="btn btn-default add-to-cart"><i class="fa fa-shopping-cart"></i>Add to cart</a>
										</div>
									</div> -->
								</div>
							</div>
						</div>
						

						
						<div class="col-sm-4">
							<div class="product-image-wrapper">
								<div class="single-products">
									<div class="productinfo text-center">
										<img src="images/product/perfumy_49.jpg" alt="" />
										<h2>#49</h2>
										<p>bergamotka – ylang-ylang – drzewo sandałowe</p>
										<a href="perfumy_101049_xpl.html" class="btn btn-default add-to-cart"><i class="fa fa-shopping-cart"></i>Więcej</a>
									</div>
									<!-- <div class="product-overlay">
										<div class="overlay-content">
											<h2>$56</h2>
											<p>Easy Polo Black Edition</p>
											<a href="#" class="btn btn-default add-to-cart"><i class="fa fa-shopping-cart"></i>Add to cart</a>
										</div>
									</div> -->
								</div>
							</div>
						</div>

						
						<div class="col-sm-4">
							<div class="product-image-wrapper">
								<div class="single-products">
									<div class="productinfo text-center">
										<img src="images/product/perfumy_51.jpg" alt="" />
										<h2>#51</h2>
										<p>konwalia – czarna porzeczka – wanilia</p>
										<a href="perfumy_101051_xpl.html" class="btn btn-default add-to-cart"><i class="fa fa-shopping-cart"></i>Więcej</a>
									</div>
									<!-- <div class="product-overlay">
										<div class="overlay-content">
											<h2>$56</h2>
											<p>Easy Polo Black Edition</p>
											<a href="#" class="btn btn-default add-to-cart"><i class="fa fa-shopping-cart"></i>Add to cart</a>
										</div>
									</div> -->
								</div>
							</div>
						</div>
						
						<div class="col-sm-4">
							<div class="product-image-wrapper">
								<div class="single-products">
									<div class="productinfo text-center">
										<img src="images/product/perfumy_53.jpg" alt="" />
										<h2>#53</h2>
										<p>kawa – gruszka – drzewo kaszmirowe</p>
										<a href="perfumy_101053_xpl.html" class="btn btn-default add-to-cart"><i class="fa fa-shopping-cart"></i>Więcej</a>
									</div>
									<!-- <div class="product-overlay">
										<div class="overlay-content">
											<h2>$56</h2>
											<p>Easy Polo Black Edition</p>
											<a href="#" class="btn btn-default add-to-cart"><i class="fa fa-shopping-cart"></i>Add to cart</a>
										</div>
									</div> -->
								</div>
							</div>
						</div>

						
						<div class="col-sm-4">
							<div class="product-image-wrapper">
								<div class="single-products">
									<div class="productinfo text-center">
										<img src="images/product/perfumy_55.jpg" alt="" />
										<h2>#55</h2>
										<p>orchidea – czekolada – truﬂa</p>
										<a href="perfumy_101055_xpl.html" class="btn btn-default add-to-cart"><i class="fa fa-shopping-cart"></i>Więcej</a>
									</div>
									<!-- <div class="product-overlay">
										<div class="overlay-content">
											<h2>$56</h2>
											<p>Easy Polo Black Edition</p>
											<a href="#" class="btn btn-default add-to-cart"><i class="fa fa-shopping-cart"></i>Add to cart</a>
										</div>
									</div> -->
								</div>
							</div>
						</div>

						
						<div class="col-sm-4">
							<div class="product-image-wrapper">
								<div class="single-products">
									<div class="productinfo text-center">
										<img src="images/product/perfumy_57.jpg" alt="" />
										<h2>#57</h2>
										<p>bób tonka – kakao – tuberoza</p>
										<a href="perfumy_101057_xpl.html" class="btn btn-default add-to-cart"><i class="fa fa-shopping-cart"></i>Więcej</a>
									</div>
									<!-- <div class="product-overlay">
										<div class="overlay-content">
											<h2>$56</h2>
											<p>Easy Polo Black Edition</p>
											<a href="#" class="btn btn-default add-to-cart"><i class="fa fa-shopping-cart"></i>Add to cart</a>
										</div>
									</div> -->
								</div>
							</div>
						</div>

						
						<div class="col-sm-4">
							<div class="product-image-wrapper">
								<div class="single-products">
									<div class="productinfo text-center">
										<img src="images/product/perfumy_59.jpg" alt="" />
										<h2>#59</h2>
										<p>pomarańcza – wanilia – czarna porzeczka</p>
										<a href="perfumy_101059_xpl.html" class="btn btn-default add-to-cart"><i class="fa fa-shopping-cart"></i>Więcej</a>
									</div>
									<!-- <div class="product-overlay">
										<div class="overlay-content">
											<h2>$56</h2>
											<p>Easy Polo Black Edition</p>
											<a href="#" class="btn btn-default add-to-cart"><i class="fa fa-shopping-cart"></i>Add to cart</a>
										</div>
									</div> -->
								</div>
							</div>
						</div>

						
						<div class="col-sm-4">
							<div class="product-image-wrapper">
								<div class="single-products">
									<div class="productinfo text-center">
										<img src="images/product/perfumy_61.jpg" alt="" />
										<h2>#61</h2>
										<p>piwonia - lotos - cytrusy</p>
										<a href="perfumy_101061_xpl.html" class="btn btn-default add-to-cart"><i class="fa fa-shopping-cart"></i>Więcej</a>
									</div>
									<!-- <div class="product-overlay">
										<div class="overlay-content">
											<h2>$56</h2>
											<p>Easy Polo Black Edition</p>
											<a href="#" class="btn btn-default add-to-cart"><i class="fa fa-shopping-cart"></i>Add to cart</a>
										</div>
									</div> -->
								</div>
							</div>
						</div>


						
						<div class="col-sm-4">
							<div class="product-image-wrapper">
								<div class="single-products">
									<div class="productinfo text-center">
										<img src="images/product/perfumy_63.jpg" alt="" />
										<h2>#63</h2>
										<p>jaśmin - nuty wodne - drzewo sandałowe</p>
										<a href="perfumy_101063_xpl.html" class="btn btn-default add-to-cart"><i class="fa fa-shopping-cart"></i>Więcej</a>
									</div>
									<!-- <div class="product-overlay">
										<div class="overlay-content">
											<h2>$56</h2>
											<p>Easy Polo Black Edition</p>
											<a href="#" class="btn btn-default add-to-cart"><i class="fa fa-shopping-cart"></i>Add to cart</a>
										</div>
									</div> -->
								</div>
							</div>
						</div>

						
						<div class="col-sm-4">
							<div class="product-image-wrapper">
								<div class="single-products">
									<div class="productinfo text-center">
										<img src="images/product/perfumy_65.jpg" alt="" />
										<h2>#65</h2>
										<p>bergamotka - cytrusy - cedr</p>
										<a href="perfumy_101065_xpl.html" class="btn btn-default add-to-cart"><i class="fa fa-shopping-cart"></i>Więcej</a>
									</div>
									<!-- <div class="product-overlay">
										<div class="overlay-content">
											<h2>$56</h2>
											<p>Easy Polo Black Edition</p>
											<a href="#" class="btn btn-default add-to-cart"><i class="fa fa-shopping-cart"></i>Add to cart</a>
										</div>
									</div> -->
								</div>
							</div>
						</div>


						
						<div class="col-sm-4">
							<div class="product-image-wrapper">
								<div class="single-products">
									<div class="productinfo text-center">
										<img src="images/product/perfumy_67.jpg" alt="" />
										<h2>#67</h2>
										<p>kwiat pomarańczy - bób tonka - wanilia</p>
										<a href="perfumy_101067_xpl.html" class="btn btn-default add-to-cart"><i class="fa fa-shopping-cart"></i>Więcej</a>
									</div>
									<!-- <div class="product-overlay">
										<div class="overlay-content">
											<h2>$56</h2>
											<p>Easy Polo Black Edition</p>
											<a href="#" class="btn btn-default add-to-cart"><i class="fa fa-shopping-cart"></i>Add to cart</a>
										</div>
									</div> -->
								</div>
							</div>
						</div>

						
						
						
<!--						<ul class="pagination">
							<li class="active"><a href="">1</a></li>
							<li><a href="">2</a></li>
							<li><a href="">3</a></li>
							<li><a href="">&raquo;</a></li>
						</ul> -->
					</div><!--features_items-->
							<ul class="pagination">
							<li class="active"><a href="">1</a></li>
							<li><a href="">2</a></li>
							<li><a href="">3</a></li>
							<li><a href="">&raquo;</a></li>
						</ul>
				</div>
